### ISSUE TITLE
PowerShell Core 6.2.3/7.0.0 failing to install AzureAD module on macOS 10.15

### ISSUE THREAD

**Issue by chrsdrhm** [Azure/azure-powershell#10326]
# Steps to reproduce

Run command install-module azureadpreview or install-module azuread in Terminal after starting PowerShell

# Expected behavior

Module installs...

# Actual behavior

Module fails to install with the following error:

PackageManagement\Install-Package : Unable to load shared library 'api-ms-win-core-sysinfo-l1-1-0.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libapi-ms-win-core-sysinfo-l1-1-0.dll, 1): image not found                At /usr/local/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9508 char:21                                                                           
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

# Environment data

PowerShell 6.2.3 or 7.0.0-preview.4 installed via Homebrew on macOS 10.15 Catalina

Attempting to install latest stable and preview versions of AzureAD module

"Az" PowerShell module installs on macOS

**Comment by wyunchi-ms** [comment]
Hi @chrsdrhm , thanks for your report. We have receive your report and will investigate this issue soon.

**Comment by peppekerstens** [comment]
@chrsdrhm a few questions
1. Has Install-Module been working correct on your system so far?
2. Have you recently updated the nuget and/or packagemanagement module ?
3. could you please check your packageprovider versions?

I had all kinds of strange behaviour for a while too: https://github.com/OneGet/oneget/issues/462
re-install machine helped in my case ... :|

**Comment by jschwanz** [comment]
As far as I know the "stable" version of that module is not Core compatible. I've been successfully using this one (https://www.poshtestgallery.com/packages/AzureAD.Standard.Preview/0.0.0.10) for a while now.

**Comment by oscarmelo2** [comment]
Hi there

I'm having problems installing Azure AD, someone who's been through something like this?

PS /Users/XXXXXXXX> Install-Module AzureADPreview

Untrusted repository You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'? [Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "N"): A PackageManagement\Install-Package : Unable to load shared library 'api-ms-win-core-sysinfo-l1-1-0.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libapi-ms-win-core-sysinfo-l1-1-0.dll, 1): image not found At /usr/local/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9508 char:21 + ... $null = PackageManagement\Install-Package @PSBoundParameters + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
+ CategoryInfo : NotSpecified: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception + FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS /Users/XXXXXXXX > Install-Module -Name AzureAD.Standard.Preview -RequiredVersion 0.0.0.10 PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'AzureAD.Standard.Preview'. Try Get-PSRepository to see all available registered module repositories. At /usr/local/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9508 char:21 + ... $null = PackageManagement\Install-Package @PSBoundParameters + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS /Users/XXXXXXXX > Install-Module -Name AzureADPreview -RequiredVersion 2.0.2.5

Untrusted repository You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'? [Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "N"): A PackageManagement\Install-Package : Unable to load shared library 'api-ms-win-core-sysinfo-l1-1-0.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libapi-ms-win-core-sysinfo-l1-1-0.dll, 1): image not found At /usr/local/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9508 char:21 + ... $null = PackageManagement\Install-Package @PSBoundParameters + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
+ CategoryInfo : NotSpecified: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception + FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS /Users/XXXXXXXX > Install-Module -Name AzureADPreview -RequiredVersion 1.1.147.0

Untrusted repository You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'? [Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "N"): A PackageManagement\Install-Package : Unable to load shared library 'api-ms-win-core-sysinfo-l1-1-0.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libapi-ms-win-core-sysinfo-l1-1-0.dll, 1): image not found At /usr/local/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9508 char:21 + ... $null = PackageManagement\Install-Package @PSBoundParameters + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
+ CategoryInfo : NotSpecified: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception + FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by peppekerstens** [comment]
In my experience, PS7 works fine. PS6 is FUBAR with this module (both on my system)

**Comment by dingmeng-xue** [comment]
AzureAD module is not owned by Az PowerShell or installed with Az PowerShell. Needs ADD team's further check.

**Comment by archmangler** [comment]
This issue has been running since 2017. Has Azure made any progress on it? Our use-case requires this module as follows:

- We deploy SQL-MI server instances using an automated pipeline which uses pwsh hosted on Linux.
- The SQL-MI server needs integration with AD which is to be done using a script which requires AzureAD module.
- Without the AzureAD module, the AD configuration of Azure SQL MI cannot be fully automated.
- This is a serious blocker for us in a cloud  environment since we require the automation of SQL MI deployments for customer service delivery.

**Comment by darrelmiller** [comment]
@archmangler The goal is to provide all the necessary Azure AD functionality via the Microsoft Graph PowerShell modules which are currently in preview https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-powershell-preview-now-on-powershell-gallery/  These modules install on PS5.1, PS6 and PS7.

**Comment by daviscyd** [comment]
> @archmangler The goal is to provide all the necessary Azure AD functionality via the Microsoft Graph PowerShell modules which are currently in preview https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-powershell-preview-now-on-powershell-gallery/ These modules install on PS5.1, PS6 and PS7.

Is there any documentation on the permissions needed in AAD for this module?  Currently getting `Insufficient permissions to complete this operation` for the cmdlets I'm trying to run.

**Comment by adam230594** [comment]
@daviscyd I'm getting a similar error `Insufficient privileges to complete the operation.`

**Comment by lelloz0** [comment]
Same Issue here. Apparently neither the AzureAD and AzureADPreview module can get installed on PowerShell Core (tried on PS7 for Mac). And this is the only module that allows to grant a user assigned managed identity permissions to Microsoft Graph ([info here](https://blog.bredvid.no/accessing-apis-using-azure-managed-service-identity-ff7802b887d)) - this is a serious blocker!

**Comment by dingmeng-xue** [comment]
I have to close this issue now because Azure PowerShell team has no channel to log or transfer issue to  AzureAD team. Please contact Microsoft CSS if it is serious blocker. Sorry for inconvenience.

**Comment by joepaulk** [comment]
You could instead try to use the az rest invoking the graph api.

Until the time az-cli is in par with the AzureAD powershell module you can instead use the graph api

I have put some samples to use this via az rest,

https://github.com/joepaulk/utilities/blob/master/manage-azuread-applicationregistrations.ps1

Example code: Please use the above link for more references, and you could also make your own.
You may also refer to: https://damienbod.com/2020/06/22/using-azure-cli-to-create-azure-app-registrations/ from where i picked up inspiration 👍 

$uri = "https://graph.microsoft.com/v1.0/applications"

$allApplications = az rest `
   --method GET `
   --uri $uri `
   --headers 'Content-Type=application/json' | convertfrom-json

$allApplications.value |% {"{0}-{1}" -f $_.appid, $_.displayname}

**Comment by jschwanz** [comment]
The Microsoft.Graph modules are now GA, so you might give them a look.
