### ISSUE TITLE
No more Resource Group Name for Service Vault Containers?

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-powershell#10457]
## Description

I've been using a self made script to recollect information about VM Backups and last week I started to get $null errors for the containers of the Backups.

When I debugged my code this was the part that was getting $null values:

`$container = (Get-AzRecoveryServicesBackupContainer -ContainerType "AzureVM" -Status "Registered" -VaultId $VaultID | where-object {$_.FriendlyName -eq $vmname -and $_.ResourceGroupName -eq $rg}) `

Going step by step I found that the Backup Containers no longer have a Resource Group or at least not a Resource Group Name output...

Is this intended behavior? 
Am I missing something?
How can this be possible, having in mind all Azure Resources are logically placed in RGs?

**Comment by sambitratha** [comment]
Hi @DanteNahuel There was a bug within the service that changed the case of the RG being returned. That basically broke the pattern matching and extraction and hence the columns are returning null. This will be fixed in the next release i.e. 26th november. 

However as a workaround, you can also use 
**$regex = "*;" + $rg + ";*"
$container = (Get-AzRecoveryServicesBackupContainer -ContainerType "AzureVM" -status "Registered" -VaultId $vaultID | where {$_.Name -like $regex ) 
**
This will fetch the containers in the given resourceGroup. 
Hope this helps.

**Comment by pvrk** [comment]
Also, we have fixed in the bug in the service and the fix is scheduled to be completed by Nov 29th. With that fix, even if you are not updating to latest PS version, this error should be fixed.

P.S: We generally recommend you to update with latest PS version, always.

**Comment by pvrk** [comment]
Closing this issue since this was verified to be fixed.
