### ISSUE TITLE
Request query contains more than one $expand

### ISSUE THREAD

**Issue by drewkg** [Azure/azure-powershell#10635]
## Description

Running Get-AzBlueprint and then Get-AzManagementGroup results in an error of Request query contains more than one $expand.  The issue is Get-AzBlueprint as this is reproducible with storage modules as well.

## Steps to reproduce

```
Get-AzBlueprint -Name <Blueprint Name> -ManagementGroupId <management Group>
Get-AzManagementGroup -ManagementGroupId <Management Group>
```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by VeryEarly** [comment]
Hi @drewkg ,

Can you provide the required information?

Environment data/MOdule versions/Debug output/Error output

**Comment by dingmeng-xue** [comment]
@drewkg , is there any update. If no, this issue will be closed soon due to inactivity.

**Comment by dingmeng-xue** [comment]
@drewkg, thanks for your report. This issue is closed due to inactivity. If there is the same issue in the latest version, please raise issue with debug output message.

**Comment by noopman** [comment]
I just ran into this issue as well! Very weird! I execute one statement. It works. I execute the next one. That works too. Now I execute the first one - it now does not work.

What "Environment data" do you seek? I provided "Get-Childitem env:" below!

C:\code> Get-Module -Name 'Az.Blueprint'
Get-Module -Name 'Az.Resources'
Get-AzManagementGroup -GroupName '8f1e1564-6469-4e97-9d3b-06db1003b1d2' -Expand -Recurse # Works
Get-AzManagementGroup -GroupName '8f1e1564-6469-4e97-9d3b-06db1003b1d2' -Expand -Recurse # Works again
Get-AzBlueprint -ManagementGroupId '8f1e1564-6469-4e97-9d3b-06db1003b1d2' -Name 'PlayGroundRules' # Works All the time
Get-AzManagementGroup -GroupName '8f1e1564-6469-4e97-9d3b-06db1003b1d2' -Expand -Recurse # No longer works because of the line above

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.2.10     Az.Blueprint                        {Export-AzBlueprintWithArtifact, Get-AzBlueprint, Get-AzBlueprintArtifact, Get-AzBlueprintAssignment...}

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.11.0     Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Get-AzADAppCredential, Get-AzADApplication...}

Id                : /providers/Microsoft.Management/managementGroups/8f1e1564-6469-4e97-9d3b-06db1003b1d2
Type              : /providers/Microsoft.Management/managementGroups
Name              : 8f1e1564-6469-4e97-9d3b-06db1003b1d2
TenantId          : c95a25de-f20a-4216-bc84-99694442c1b5
DisplayName       : nd Operation Playgrounds
UpdatedTime       : 0001-01-01 00:00:00
UpdatedBy         :
ParentId          : /providers/Microsoft.Management/managementGroups/c95a25de-f20a-4216-bc84-99694442c1b5
ParentName        : c95a25de-f20a-4216-bc84-99694442c1b5
ParentDisplayName : Tenant Root Group
Children          : {nd-playground, tm-playground}

Id                : /providers/Microsoft.Management/managementGroups/8f1e1564-6469-4e97-9d3b-06db1003b1d2
Type              : /providers/Microsoft.Management/managementGroups
Name              : 8f1e1564-6469-4e97-9d3b-06db1003b1d2
TenantId          : c95a25de-f20a-4216-bc84-99694442c1b5
DisplayName       : nd Operation Playgrounds
UpdatedTime       : 0001-01-01 00:00:00
UpdatedBy         :
ParentId          : /providers/Microsoft.Management/managementGroups/c95a25de-f20a-4216-bc84-99694442c1b5
ParentName        : c95a25de-f20a-4216-bc84-99694442c1b5
ParentDisplayName : Tenant Root Group
Children          : {nd-playground, tm-playground}


Versions          : {1.0.0.0, 2.0.0.0, 2.0.1.0, 202001081544...}
Scope             : /providers/Microsoft.Management/managementGroups/8f1e1564-6469-4e97-9d3b-06db1003b1d2
SubscriptionId    :
ManagementGroupId : 8f1e1564-6469-4e97-9d3b-06db1003b1d2
DisplayName       :
Description       : Rules to play by. Play nice! Rules that apply to a Playground subscription.
Location          :
Status            : Microsoft.Azure.Commands.Blueprint.Models.PSBlueprintStatus
TargetScope       : Subscription
Parameters        : {}
ResourceGroups    : {[ResourceGroup, Microsoft.Azure.Commands.Blueprint.Models.PSResourceGroupDefinition]}
Id                : /providers/Microsoft.Management/managementGroups/8f1e1564-6469-4e97-9d3b-06db1003b1d2/providers/Microsoft.Blueprint/blueprints/PlaygroundRules
Type              :
Name              : PlaygroundRules

Get-AzManagementGroup : Request query contains more than one $expand.
At line:6 char:1
+ Get-AzManagementGroup -GroupName '8f1e1564-6469-4e97-9d3b-06db1003b1d ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzManagementGroup], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.ManagementGroups.GetAzureRmManagementGroup

C:\code> Get-Childitem env:

Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
APPDATA                        C:\Users\MagnusMårtensson\AppData\Roaming
COLORTERM                      truecolor
CommonProgramFiles             C:\Program Files\Common Files
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
CommonProgramW6432             C:\Program Files\Common Files
COMPUTERNAME                   MAGNUSPRO6
ComSpec                        C:\WINDOWS\system32\cmd.exe
DriverData                     C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING Internet Explorer
FPS_BROWSER_USER_PROFILE_ST... Default
HOME                           C:\Users\MagnusMårtensson
HOMEDRIVE                      C:
HOMEPATH                       \Users\MagnusMårtensson
LANG                           en_GB.UTF-8
LOCALAPPDATA                   C:\Users\MagnusMårtensson\AppData\Local
LOGONSERVER                    \\MAGNUSPRO6
MOZ_PLUGIN_PATH                C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
NUMBER_OF_PROCESSORS           8
OneDrive                       C:\OneDrive - Loftysoft
OneDriveCommercial             C:\OneDrive - Loftysoft
OneDriveConsumer               C:\OneDrive
OS                             Windows_NT
Path                           C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;... 
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE         AMD64
PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
PROCESSOR_LEVEL                6
PROCESSOR_REVISION             8e0a
ProgramData                    C:\ProgramData
ProgramFiles                   C:\Program Files
ProgramFiles(x86)              C:\Program Files (x86)
ProgramW6432                   C:\Program Files
PSExecutionPolicyPreference    RemoteSigned
PSModulePath                   C:\Magnus\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;c:\Users\Magnu... 
PUBLIC                         C:\Users\Public
SESSIONNAME                    Console
SystemDrive                    C:
SystemRoot                     C:\WINDOWS
TEMP                           C:\Users\MAGNUS~1\AppData\Local\Temp
TERM_PROGRAM                   vscode
TERM_PROGRAM_VERSION           1.42.1
TMP                            C:\Users\MAGNUS~1\AppData\Local\Temp
USERDOMAIN                     AzureAD
USERDOMAIN_ROAMINGPROFILE      AzureAD
USERNAME                       MagnusMårtensson
USERPROFILE                    C:\Users\MagnusMårtensson
windir                         C:\WINDOWS

**Comment by dingmeng-xue** [comment]
@noopman, could you create a new issue and we will follow up.

**Comment by noopman** [comment]
Wooow! That is a LOT of data you require! I am surprised anyone submits any errors at all! [Here is the issue](https://github.com/Azure/azure-powershell/issues/11251).
