### ISSUE TITLE
Remove-AzBlueprintAssignment in DevOps Pipelines - Azure PowerShell task

### ISSUE THREAD

**Issue by dzemp** [Azure/azure-powershell#10648]
## Description
When using the Remove-AzBlueprintAssignment in an Azure PowerShell task in DevOps Pipelines, the assignment cannot be deleted, although the task succeeded. Or the task returns a PowerShell error. 
- With the parameter -Confirm - task returns "PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."
- With the parameter -Confirm:$false - task succeeds but assignment is still there.
- With the parameter -Confirm:$true - task succeeds but assignment is still there.

## Steps to reproduce

```powershell
Remove-AzBlueprintAssignment -Name $blueprintName -Subscription $subscriptionId -Confirm
```

## Environment data

```

```

## Module versions

```powershell
2019-12-02T17:40:57.0034730Z Task         : Azure PowerShell
2019-12-02T17:40:57.0034821Z Description  : Run a PowerShell script within an Azure environment
2019-12-02T17:40:57.0034886Z Version      : 4.159.3
2019-12-02T17:40:57.0034964Z Author       : Microsoft Corporation
```

## Debug output

```

```

## Error output

```
2019-12-02T17:50:00.9247706Z ##[error]Remove-AzBlueprintAssignment : PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.
```

**Comment by VeryEarly** [comment]
Thanks for the feedback, forwarded to Blueprint team.

**Comment by dzempms** [comment]
Hi, any update on this issue?

**Comment by alex-frankel** [comment]
Hi @dzemp,

-Confirm is not the right flag here because, as you note, it's for interactive sessions, which a pipeline execution is not :)

You can try the -PassThru which has the following behavior:
* if the blueprint assignment exists, and is deleted, we will return the blueprint assignment object that we removed
* if the blueprint assignment *does not* exist, we will return nothing

With that behavior you should be able to identify the blueprint assignment was successfully removed.

If there is an error (4xx or 5xx), that will be returned by the cmdlet as well and will fail the pipeline.

The fact that the assignment is not being removed in any of the above cases makes me think you may not be referencing the assignment correctly. Have you been able to get that part resolved?

**Comment by alex-frankel** [comment]
@dzemp - I'm going to close this tomorrow if I don't hear back
