### ISSUE TITLE
Az.KeyVault Get-AzKeyVault return object always includes VaultUri

### ISSUE THREAD

**Issue by ajpatterson7** [Azure/azure-powershell#10657]
## Description of the new feature
Currently, there is some logic which creates two different possible returns when calling Get-AzKeyVault. The only way to get a complete object is to call the command providing a full 'VaultName' parameter, and not using wildcards in the 'ResourceGroupName' parameter, if you choose to provide it. A call which does not meet this criteria returns a lesser object which does not contain many of the properties. Perhaps most crucial is the 'VaultUri' property.

New Feature can be implemented one of two ways:
1. Object always returns the same, regardless of input parameter specificity. This allows consistency at the cost of a larger return and more processing time.
2. Lesser version of object includes VaultUri property. This allows the lesser object to be used for cases such as Customer Managed Key encryption of storage accounts.

**Comment by VeryEarly** [comment]
Hi @ajpatterson7 ,

Thanks for your feedback, we are investigating on this request.

**Comment by dingmeng-xue** [comment]
@ajpatterson7 it is by design according to current API of Keyvault service. If there is no vault name, Keyvault service returns the list of vaults with limited properties. If Azure PowerShell iterates list and populates full result, it may have performance concern to current other customers.

One workaround is using pipeline, such as
```powershell
Get-AzKeyVault | foreach {Get-AzKeyVault -VaultName $_.VaultName}
```
