### ISSUE TITLE
enable autorefresh of creds that use a token

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#1068]
Add-AzureAccount and Login-AzureRMAccount will automatically refresh the access token if creds are provided.  If a token is used for authn the refresh doesn't happen since PS doesn't have the refresh token.

We need a way to have the cmdlets do the auto refresh of token based auth, maybe by sharing a cache or providing a refresh token (if that's even possible).

**Comment by devigned** [comment]
I'm sure that a refresh token could be used, but I can't help but feel it would be much simpler to provide the credentials. Azure PowerShell will take care of all cases where the token needs to be refreshed if credentials are provided.

**Comment by markcowl** [comment]
@devigned This would work for org id or spn, but not for live id credentials

**Comment by markcowl** [comment]
@bmoore-msft Per today's discussion, this is no longer in plan

**Comment by jahmai** [comment]
Is there any workaround for this? I've got ARM templates that take longer than an hour to deploy (looking at you Gateway and Redis). When I want to put them all together into a combined deployment script, any part of the script can fail from a timeout of credentials. This can be hard to recover from without trying to manually execute the missed parts of my script. How can I just get a really long auth token?

**Comment by subramp** [comment]
Did you find any answers to get auth tokens for long running services?

**Comment by jahmai** [comment]
I ended up using a Service Principle account instead for operations that take a long time, and a User Account for operations that require it (AzureRmAD operations seem to require a user account since service principles can't be assigned domain admin permissions in the AD).

Add-AzureRmAccount -ServicePrincipal -TenantId $TenantId -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint

I had to set up the service principle first with the commands:

New-AzureRmADApplication / New-AzureRmADServicePrincipal / New-AzureRmRoleAssignment

You also need to create a certificate outside that process. Bit of a pain but it works well now.

**Comment by subramp** [comment]
I did create an SPA to start my operations in Azure.

However, the authentication token I receive via C# is valid just for an
hour. After that, I have to create new token, otherwise my deployments fail
in Azure with the below exception



DEBUG SAT.AutoFLEX.Platform.Azure.AzureRunner - NetworkInterface creation
for VM <> error Microsoft.Rest.Azure.CloudException: The access token
expiry UTC time '3/17/2017 11:30:10 PM' is earlier than current UTC time
'3/18/2017 12:02:55 AM'.
at
Microsoft.Azure.Management.Network.NetworkInterfacesOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at
Microsoft.Azure.Management.Network.NetworkInterfacesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at
Microsoft.Azure.Management.Network.NetworkInterfacesOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at
SAT.AutoFLEX.Platform.Azure.AzureRunner.<CreateNetworkAsync>d__44.MoveNext()


I was wondering, if there is a way to refresh the token programatically.

Based on the article

https://docs.microsoft.com/en-us/azure/active-directory/active-directory-configurable-token-lifetimes

unfortunately an access token cannot be extended for more than an hour.
Looking forward to any pointers.

**Comment by jahmai** [comment]
Sorry I am not sure. I used the creds with Powershell commands and it seems to auto refresh principle tokens so it must be possible.

**Comment by bmoore-msft** [comment]
Tokens are good for an hour - the refresh token (which can be used to refresh that hourly token) has a longer lifetime.  When PowerShell does authn with creds, it gets the refresh token and automatically refreshes the auth token when needed.  Visual Studio does the same thing, portal, etc.  And client doing auth, could follow the same pattern.

This issue is about when PowerShell does authn without creds (i.e. with a token) - it doesn't auto refresh in that case because it doesn't have the refresh token so it can't - would could take a change to the cmdlets to accept the refresh token as well, but need to work through that...

As long as you authn with creds (via PowerShell) you're fine with long running tasks (account type doesn't matter).  It's only when you authn PowerShell with a token that this issues appears...

**Comment by jahmai** [comment]
Actually this is not what I've observed.

If I use Add-AzureRmAccount and enter credentials at a prompt (I assume this is what you are referring to when you 'authn with creds'), and then execute some very long running task, like deploying a Redis cache, after 1 hour of polling the status of that command it will timeout.
If I use Add-AzureRmAccount -ServicePrincipal which doesn't prompt and uses a certificate to authenticate, then this issue does not occur.

Unless something has changed in the past 3 months, which is when I last did 4 very large deployments across multiple data centers and encountered this issue.

While this might be slightly different to what you originally reported, I think the solutions should be the same.

**Comment by subramp** [comment]
I am trying to deploy VMs on demand-> Run some activity -> Tear down the
VMs on activity completion.

This happens over and over, within and beyond an hour. All on Azure .net!

After an hour my access tokens expire :(
This requires me to reauthenticate before I proceed.

Any pointers for my scenario would be appreciated.

**Comment by bmoore-msft** [comment]
@subramp - if you're acquiring the token yourself (via C#) then that code is responsible for refreshing the token or getting a new one - you can take a look at how the cmdlets do it here: https://github.com/Azure/azure-powershell/tree/dev/src/Common/Commands.Common.Authentication/Authentication

**Comment by subramp** [comment]
Just to make sure I am looking at the right file. Are we talking about

https://github.com/Azure/azure-powershell/blob/dev/src/Common/Commands.Common.Authentication/Authentication/ServicePrincipalTokenProvider.cs ?
