### ISSUE TITLE
Cmdlet to quickly resize Azure Virtual Machine

### ISSUE THREAD

**Issue by KohaiMomomiya** [Azure/azure-powershell#11047]
## Description of the new feature
Implement a dedicated cmdlet to resize an Azure Virtual Machine without needing to update all of its model data. In Azure CLI, this is already implemented in the command [**az vm resize** ](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-resize)

## Proposed implementation details (optional)
Example of the cmdlet:
`Set-AzVMSize -VMSize "Standard_B2ms" -VMName "VirtualMachine" -ResourceGroupName "ResourceGroup"`

**Comment by dingmeng-xue** [comment]
Compute team, please look into this feature request.

**Comment by Drewm3** [comment]
I have opened an idea in User Voice to track this request. Please upvote the following item: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/39671230-powershell-cmdlet-to-quickly-resize-azure-virtual

I will close this issue here so that we can track the request in one location with vote counting.
