### ISSUE TITLE
Az commands to configure Notification Hub (not just creating only the Hub)

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#11119]
## Description of the new feature

Commands should be available to add GCM, Apple, Baidu connectivity properties in the notification Hub, 

## Proposed implementation details (optional)

Command may look like,

Set-AzNotificationHubGCMCredential
Set-AzNotificationHubMpnsCredential
Set-AzNotificationHubBaiduCredential

**Comment by wyunchi-ms** [comment]
Hi @rajaprad , thanks a lot for your feedback! We will contact with Notification Hub team with this issue. We will consider this issue seriously.

**Comment by navba-MSFT** [comment]
@rajaprad Apologies for the late reply. Refer [this](https://docs.microsoft.com/en-us/cli/azure/notification-hub/credential?view=azure-cli-latest) article for managing the Notification HUB credentials of GCM, Baidu, APNS and MPNS. This issue is open for quite sometime, please let us know if you have any further questions. Awaiting your reply.
