### ISSUE TITLE
need cmdlet in Az.PolicyInsights to trigger evaluation

### ISSUE THREAD

**Issue by pmozbert** [Azure/azure-powershell#11365]
## Description of the new feature
Add a new Az.PolicyInsights cmdlet to trigger policy evaluation.

## Proposed implementation details (optional)
The cmdlet should implement the triggerEvaluation REST API
(https://docs.microsoft.com/en-us/rest/api/policy-insights/policystates/triggersubscriptionevaluation)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Involve PolicyInsights team.

**Comment by kenieva** [comment]
Hi pmozbert, we don't have this in the upcoming plans due to other features in the pipeline. One of those is an improvement in the time for compliance evaluation to surface. With this exciting change, there will be little need to trigger an evaluation. However, I would recommend adding a feature request to our UserVoice on this request: https://feedback.azure.com/forums/915958-azure-governance. You can add this and any other feature request in that channel so it can be properly backlog. Thanks!

**Comment by pmozbert** [comment]
I tried logging in to post a comment in user voice and got this error.


Request Id: c8c43765-0aa5-43da-a5f0-ae833ea64a00
Correlation Id: 8b45e4f0-a567-40cc-88e2-f711cbc84f1e
Timestamp: 2020-03-20T00:12:09Z
Message: AADSTS50020: User account 'pmolzer@gmail.com' from identity
provider 'live.com' does not exist in tenant 'UserVoice, Inc.' and cannot
access the application '91a42e81-999b-4cf1-aa36-bb33f25ff53b'(
windowsazure.uservoice.com) in that tenant. The account needs to be added
as an external user in the tenant first. Sign out and sign in again with a
different Azure Active Directory user account.
