### ISSUE TITLE
How to filter SKUs API from PowerShell to a specific region?

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-powershell#11460]
## Description of the new feature
Get-AzVMSize return the max NICs that for VM can attach. If we already have this, could you please share it with me?  Thanks.

**Comment by dingmeng-xue** [comment]
Compute team, please help to look into this question.

**Comment by Drewm3** [comment]
The number of NICs allowed for a specific VM size is available in the API [Resource Skus - List](https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list) under the property **MaxNetworkInterfaces**.

Let me know if this answers your question.

**Comment by LiliDeng** [comment]
Thanks @Drewm3 , my request is not based on the created VM, but based on the size, like add another property for the return of get-azvmsize.

MaxDataDiskCount     : 64
MemoryInMB           : 2199023
Name                 : Standard_M192s_v2
NumberOfCores        : 192
OSDiskSizeInMB       : 1047552
ResourceDiskSizeInMB : 15393163
**MaxNicCount: XX**

**Comment by Drewm3** [comment]
@LiliDeng, you can get the number of NICs allowed for any VM Size (aka SKU) in the Resource SKUs API. If you want to get the count of NICs available for an existing VM you would need to get the size of the existing VM, and then lookup the max NIC count in the SKUs API.

We have tried to move to one location that provides all information for SKUs instead of having multiple APIs that provide details on the Max size of component X.

**Comment by LiliDeng** [comment]
Thanks @Drewm3 , I found it. But Get-AzComputeResourceSku command cost 15 seconds to return, is it expected?

```
$re = Get-AzComputeResourceSku | where {$_.Name -icontains "standard_nc6" -and $_.Locations.Contains("westus2")} 
$re.Capabilities
Name                         Value  
----                         -----  
MaxResourceVolumeMB          389120 
OSVhdSizeMB                  1047552
vCPUs                        6      
HyperVGenerations            V1     
MemoryGB                     56     
MaxDataDiskCount             24     
LowPriorityCapable           True   
PremiumIO                    False  
VMDeploymentTypes            IaaS   
vCPUsAvailable               6      
GPUs                         1      
vCPUsPerCore                 1      
EphemeralOSDiskSupported     False  
AcceleratedNetworkingEnabled False  
RdmaEnabled                  False  
MaxNetworkInterfaces         2      
```

**Comment by Drewm3** [comment]
Yes that is the correct cmdlet, and yes, it does take a bit of time to complete. The actual API for GetREsourceSku allows for a filter that filters to a specific region that enables a much faster run time when looking at only a single region. 

Let me look into the possibility of exposing the region filter into the Get-AzComputeResourceSKU in order to make the cmdlet faster when looking up a SKU in a specific region.

**Comment by Drewm3** [comment]
I have updated the title to this issue. The original question has been answered, and we are now working to see if we can offer regional filtering in the SKUs API to enable it to return faster than the ~15 seconds required today (and growing as Azure adds new regions)

**Comment by Drewm3** [comment]
We will be updating the cmdlet to accept a region filter which should provide a significant performance improvement. I'll update this issue once the new cmdlet is available.

**Comment by Drewm3** [comment]
The current version of the PowerShell cmdlets now support location filtering for Get-AzComputeResourceSku. 

`SYNTAX
    Get-AzComputeResourceSku [[-Location] <System.String>]`

**Comment by LiliDeng** [comment]
@Drewm3 Thank you!
