### ISSUE TITLE
Get-AzureRmAutomationJobOutput does not return full string

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#1158]
Get-AzureRmAutomationJobOutput only returns the first 83 characters of the job output. Please return the full output of the job

**Comment by jodoglevy** [comment]
Looking into it...ASM cmdlets should still be not truncating though, right? So you can continue to use those for now?

**Comment by trondhindenes** [comment]
Absolutely, it's a blocking bug (and these are preview bits after all). But between this and the way a lot of these cmdlets ignore erroractionpreference, I think it's safe to say that test coverage seems to be way too low.

**Comment by jodoglevy** [comment]
This is by design in ARM cmdlets, not a bug. We are planning to expose a new cmdlet that gives you the output of a job as the full complex objects that were output, rather than as just a string. The field you are trying to use is meant to just be a summary field for the output stream record, not the full stream item itself. Please see https://social.msdn.microsoft.com/Forums/en-US/c15ebcd1-bb71-4f15-be71-ea9e31923581/getazureautomationjoboutput-doesnt-return-all-data-in-its-output-streams?forum=azureautomation&prof=required for more info on the background on this.

**Comment by trondhindenes** [comment]
Gotcha. As long as it's documented in the cmdlet help that the field does _not_ represent the full output I'm happy. I wouldn't mind having the field indicate that it is a summary field tho.

**Comment by trondhindenes** [comment]
Joe, I just read thru the discussion link you sent. I can't see how they are related. I get that there are suggestions on returning objects instead of strings, but imho that's a non-issue - we've always serialized to json and then just picked up the json string when needing to get the output in a objectized way. My issue is that there is simply no way (in AzureRM) to get full outputs. The "stream any" does not help. 

I cannot see how this limitation is by design. If you're providing part of the string, the only sensible thing is to provide the full string. 

Think of all the failure situations this may cause as poeple are testing their runbooks with outputs that only return a little text, and then experience trouble when the return string is longer than 83 characters.  This kind of stuff will take lots of time (even for a skilled scripter) to track down. 

Think about the user - please reconsider this.

I would rather not have any output at all (simply remove the "text" attribute) than having it return just a portion of the output.

**Comment by trondhindenes** [comment]
btw @jodoglevy The bug is the same when trying from asm using the 0.9.11 version of the azure module. Making this a blocking/high-pri bug.

**Comment by trondhindenes** [comment]
As far as I can see the ASM rest api returns this in a field called "summary". IMHO that would be a much better attribute name for the cmdlet returned object as well, as it indicates that the returned value might not be the full output.

**Comment by jodoglevy** [comment]
Agree with a lot of what you're saying, Trond. I just alerted the team that we have a high-pri issue here, thanks for letting me know. We weren't aware we had accidentally changed the behavior in ASM cmdlets / API. It was meant for only ARM. We will likely rollback the truncation.

**Comment by trondhindenes** [comment]
Great! Thanks for following up so quickly!

**Comment by JakobGSvendsen** [comment]
an idea would be to have a parameter to define that we want full string instead of truncated. :) and great news about the other cmdlet

**Comment by jodoglevy** [comment]
This should now be fixed. Get-AzureRmAutomationJobOutput returns a Summary field instead of a Text field, to better alert that it may not contain the whole output item. And we have a new cmdlet Get-AzureRmAutomationJobOutputRecord which returns the entire item written to the output stream, as an object rather than only supporting strings.
