### ISSUE TITLE
Invoke-AzureRemoteAppSessionLogoff cmdlet has a bug

### ISSUE THREAD

**Issue by ozbeanz** [Azure/azure-powershell#1176]
The Confirm parameter seems to be active whether it is selected or not. Need to be able to run this cmdlet without a Confirm

**Comment by relmer** [comment]
Logging off a user is a high-impact operation and is very likely to lead to user data loss, so we've marked this cmdlet as being high-impact.  You're seeing the confirmation prompt because your ConfirmPreference environment variable in PS is set to High or lower.  

If you'd like to suppress the prompt, simply add "-Confirm:$false" to the cmdline.
