### ISSUE TITLE
Should update Powershell doc to make clear that it applies onlyt to Data Lake Storage Gen1

### ISSUE THREAD

**Issue by normesta** [Azure/azure-powershell#11797]
## Description
Hello - the doc https://docs.microsoft.com/en-us/powershell/module/azurerm.datalakestore/?view=azurermps-6.13.0 should make clear that this documentation applies only to Data Lake Storage Gen1 so that folks don't get confused. I'm an author with the Data Lake Storage Gen2 team and I received this request from Brian Roder. I can't edit these docs so I'm filing this request via this channel. Thx!

## Cost
Seems pretty low cost.

**Comment by blueww** [comment]
@normesta 
This doc is for [very old module ](https://github.com/Azure/azure-powershell/releases/tag/v6.13.0-November2018) which released on 2018/11. 

Tha lastest version has specify this is only for datalake gen1, see https://docs.microsoft.com/en-us/powershell/module/Az.DataLakeStore/?view=azps-3.8.0

@dingmeng-xue , @markcowl , any idea in it? Should we change the old PSH doc, since new feature changes?

**Comment by dingmeng-xue** [comment]
@mikefrobbins, @dcaro, can we update old version of doc?

**Comment by dcaro** [comment]
This is an update of the reference doc of AzureRM.  @mikefrobbins could we consider consider making a single edit on the docs repo and on the source code without rebuilding the AzureRM reference docs?

**Comment by normesta** [comment]
@mikefrobbins  - thank you!
