### ISSUE TITLE
provision to add query parameters while creating api operation using Set-AzApiManagementOperation

### ISSUE THREAD

**Issue by nareshbonagiri** [Azure/azure-powershell#11811]
## Description of the new feature
At present there is no provision to add query parameters using Set-AzApiManagementOperation command, only template parameters can be added.
## Proposed implementation details (optional)
Provision to add query parameters using Set-AzApiManagementOperation, while creating operation.

**Comment by dingmeng-xue** [comment]
Involve API Management team to look into it.

**Comment by lilyjma** [comment]
@miaojiang could you take a look at this issue.

**Comment by navba-MSFT** [comment]
@nareshbonagiri Apologies for the late reply. Could you please refer [this](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagementoperation?view=azps-7.2.0#example-2--create-an-api-management-operation-with-request-and-response-details) article for using the QueryParameters for the APIM operation and see if that helps ? Also this issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.
