### ISSUE TITLE
Is there any way to get currently logged in user account?

### ISSUE THREAD

**Issue by jongio** [Azure/azure-powershell#11928]
We have this in CLI, to get currently logged in user info.

az ad signed-in-user show

What is equivalent in PSH?

Jon

**Comment by dingmeng-xue** [comment]
Please try to use all context information using `Get-AzContext`. If account specifically, `(Get-AzContext).Account` shows login user information.

**Comment by jongio** [comment]
I actually need the objectId of the currently logged in user.  I don't see that with that command.

**Comment by dingmeng-xue** [comment]
Hi Jongio, what's the attribute of objectid? Id of account in ccontext of powershell is user's email account. If you need AD id, you can use `Get-AzADUser -UserPrincipalName (Get-AzContext).Account`

**Comment by jongio** [comment]
Thanks, this is what I needed

(Get-AzADUser -UserPrincipalName (Get-AzContext).Account).Id

**Comment by Akshat59** [comment]
@jongio (Get-AzADUser -UserPrincipalName (Get-AzContext).Account).Id
this is not working for me

**Comment by dingmeng-xue** [comment]
@Akshat59 , please create a new Github issue for your question. We need more information from your side for further analysis.

**Comment by lesterw1** [comment]
The challenge to solve is to simply do a: ```Connect-AzureAD``` and then determine the logged in AzureAD username. You can catch the **Connect-AzureAD** response but (for the purposes of this challenge) you cannot use **Get-AzContext** as that requires a *separate* **Connect-AzAccount** login.

So... does anyone know how to solve this?

**Comment by dingmeng-xue** [comment]
@lesterw1, could you tell us more why you cannot call Connect-AzAccount?

**Comment by sdg002** [comment]
This did not work for me
```
Get-AzADUser -UserPrincipalName (Get-AzContext).Account.Id
```
I thought it would. But, upon digginit, I understood the reason.

`(Get-AzContext).Account.Id` gives me  `john.doe@hotmail.com`

However, `Get-AzADUser` shows the same user to have a more complex `UserPrincipalName`, something like this `john_doe@hotmail.com#EXT#johndoehotmail.onmicrosoft.com`

## Summary
The account name returned by `Get-AzContext` does not fully match the `UserPrincipalName`. 


CC @jongio  @Akshat59 .  Were you able to make this work?

**Comment by sdg002** [comment]
> @lesterw1, could you tell us more why you cannot call Connect-AzAccount?

Allow me to explain my position.

I have already done a `Connect-AzAccount` and connected to my Azure account via MFA.
Now, in a separate requirement, I want to know what is the `UserPrincipalName` of the account that I used for doing `Connect-AzAccount`

I do not want to do an interactive login at all - because it is all done.

The user information returned  by `Get-AzContext` does not match the `UserPrincipalName` returned by  `Get-AzADUser`.
See my response https://github.com/Azure/azure-powershell/issues/11928#issuecomment-912959342

**Comment by lesterw1** [comment]
> @lesterw1, could you tell us more why you cannot call Connect-AzAccount?
> The user information returned by `Get-AzContext` does not match the `UserPrincipalName` returned by `Get-AzADUser`.
> See my response [#11928 (comment)](https://github.com/Azure/azure-powershell/issues/11928#issuecomment-912959342)

@sdg002 The issue is that the PowerShell session is likely logged in using your default Windows credentials, so the `Get-AzContext` is returning that `UserPrincipalName`. In other cases, you may not be logged in at all until you do a `Connect-AzureAd`. Note that you can be logged into _multiple_ Azure tenants concurrently (this is what I didn't realize when I wrote the message).  So `Get-AzADUser -UserPrincipalName (Get-AzContext).Account.Id` will only return the _currently selected_ subscription/tenant. 

There is a way to get the list of all accounts that you are currently logged into along with tokens, etc.:

```
$azProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile
# $azProfile.contexts lists the various context

$currentAzureContext = Get-AzContext
# $currentAzureContext has the currently selected tenant/subscription

$profileClient = New-Object Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient($azProfile)
$token = $profileClient.AcquireAccessToken($currentAzureContext.Tenant.TenantId)
# $token.ExpiresOn basically indicates if the token is still valid
```

Hopefully, the above helps.

**Comment by nelt-ken** [comment]
I know this issue is old, but i've got some input which i believe is valuable for any future googlers.

"get-azcontext" will not always work if you are looking for the logged on user in AzureAD because Azure and AzureAd are separate. You could be logged on to azuread as one user while being logged on to azure as another use, they are different modules.

to connect to azure you use "connect-azureaccount" from the AZ module(s), while azuread is another module where you connect with "connect-azuread"

The way i found to save the azure-ad account username is to get it at login, for instance like such:

`[string]$username = (connect-azuread).account.id`

$username will now return your logged on account id like "michael@contoso.com"
