### ISSUE TITLE
Set-AzureRmResource -Tag replaces existing tags.

### ISSUE THREAD

**Issue by DreamRivulet** [Azure/azure-powershell#12003]
Currently Set-AzureRmResource -Tag will replace existing tags instead of merging,  this may Azure managed tags overwritten, and it will be difficult to restore them.

Could we can change the default behavior to merge new tags into existing ones?

**Comment by dingmeng-xue** [comment]
@DreamRivulet , thanks for your feedback. Azure PowerShell cmdlet honors API of services. The set (update) operation partially updates object and the granularity is on attribute level such as Tag. If we allow merging Tag, we need to introduce additional parameter set to avoid breaking change to other customer and we need to figure out another way to support removing tag via update operation. 

Involve @dcaro for the awareness.

**Comment by dcaro** [comment]
@DreamRivulet thanks for this feature request, we want to have consistency across the different cmdlet in Azure PowerShell. Such a change would imply to update all the currently released Az module. We will evaluate the possibility of this change based on its impact and the need from other customers.

In the meantime, you can use the following workaround: 
```
$vm = Get-AzResource -ResourceId /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MYRG/providers/Microsoft.Compute/virtualMachines/MYVM
$vm.Tags.Add( "owner", "myvm")
Set-AzResource -ResourceId /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MYRG/providers/Microsoft.Compute/virtualMachines/MYVM  -Tag $vm.Tags
```

**Comment by markcowl** [comment]
@dcaro @DreamRivulet  So, you can use ```Set-AzResource -UsePatchSemantics``` rather than trying to represent the entire resource.  This is actually the prefferred method, as it does not attempt to replace the rest of the resource configuration.

I am wondering if we instead had a command ```Update-AzResource``` that automatically used Patch semantics, if this would be more discoverable?

**Comment by hamidtirmizi** [comment]
Patch on a resource will not patch the tags applied to the resource. It will be taken as an update to a single property, and replace all the tags. This is unlikely to change.

The solution to your problem is here in a different cmdlet:
https://docs.microsoft.com/en-us/powershell/module/az.resources/update-aztag?view=azps-4.6.0
