### ISSUE TITLE
New-AzDatalakeGen2FileSystem is undocumented

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-powershell#12038]
This example is given in the Data Lake docs.
```
$filesystemName = "my-file-system"
New-AzDatalakeGen2FileSystem -Context $ctx -Name $filesystemName
```
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-powershell

But this command is not listed in the reference docs.
https://docs.microsoft.com/en-us/powershell/module/az.storage/?view=azps-4.1.0

Please add documentation when possible.

**Comment by dcbrown16** [comment]
For that matter, it looks like there are Get-AzDatalakeGen2FileSystem and Remove-AzDatalakeGen2FileSystem commands at least as well. Please add all related commands.

**Comment by dingmeng-xue** [comment]
@dcbrown16 , thanks for your feedback. `New-AzDatalakeGen2FileSystem` is an alias and formal name is `New-AzStorageContainer`. You can find their mapping via `Get-Command new-AzDatalakeGen2FileSystem | fl` or `Get-Help New-AzDatalakeGen2FileSystem`. Online doc only use formal name.

Online doc should use formal name instead of alias. I have raised issue to msdoc. https://github.com/MicrosoftDocs/azure-docs/issues/56249

**Comment by dcbrown16** [comment]
I see, thanks for the info!
