### ISSUE TITLE
Remove-AzStorageShare : Cannot bind parameter 'Share' on Az.Storge 2.1

### ISSUE THREAD

**Issue by yashi-cloud** [Azure/azure-powershell#12247]
Does Az.Storage 2.1 have any problem on Remove-AzStorageShareat command?
Remove-AzStorageShareat -Share <FileShareSnapshot> got bind error on Az.Storage 2.1.
The error did not happen Az.Storage 1.4.0.

## Steps to reproduce

```powershell

Below commands got error.
-> Remove-AzStorageShare -Share <snapshot for Azure File>
-> Get-AzStorageFile -Share <snapshot for Azure File>

https://docs.microsoft.com/ja-jp/azure/storage/files/storage-how-to-use-files-powershell#delete-a-share-snapshot
https://docs.microsoft.com/ja-jp/azure/storage/files/storage-how-to-use-files-powershell#delete-a-share-snapshot

# Error message
Remove-AzStorageShare: Cannot bind parameter 'Share'. Cannot convert the 
"Microsoft.WinowsAzure.Commands.Common.Storage.resourceModel.AzureStorageFileShare" value of type
"Microsoft.WinowsAzure.Commands.Common.Storage.ResourceModel.AzureStorageFileShare" to type
"Microsoft.Azure.Storage.File.CloudFileShare".

## Environment data
$PSVersionTable N/A

**Comment by blueww** [comment]
@yashi-cloud
Thanks for raise the issue!

We have  changed the way to pipeline File object in Az.Storage 2.0.0 (Az 4.1.0)
You can find the migration guild [here](https://github.com/Azure/azure-powershell/blob/master/documentation/migration-guides/Az.4.1.0-migration-guide.md#get-azstorageshare-new-azstorageshare-remove-azstorageshare).

Would you please share how you get the share snapshot object, do you get it by `$share.CloudFileShare.Snapshot()` , or by `Get-AzStorageShare`?
If you get it in the first way, the `Remove-AzStorageShare -Share <snapshot for Azure File>` should work.
If you get in the 2nd way, you should use "Remove-AzStorageShare -Share $sharesnapshot.CloudFileShare"

This because currently:
- SDK API `$share.CloudFileShare.Snapshot()` will output object with type "CloudFileShare" . 
- cmdlet `Get-AzStorageShare` will output object with type "AzureStorageFileShare", and "AzureStorageFileShare" has a child object with type "CloudFileShare".
(The 2 ways both output "CloudFileShare" before).

I will contact doc team to update https://docs.microsoft.com/ja-jp/azure/storage/files/storage-how-to-use-files-powershell

**Comment by yashi-cloud** [comment]
Thank you very much for your answer. Remove-AzStorageShare -Share $sharesnapshot.CloudFileShare" solved the issue. I appreciate you contact doc team to update https://docs.microsoft.com/ja-jp/azure/storage/files/storage-how-to-use-files-powershell.

**Comment by blueww** [comment]
@yashi-cloud
I will close this issue as your problem is solved.
Feel free to contact us again if you need further assistance on Azure PowerShell.
