### ISSUE TITLE
Start-AzStorageBlobCopy: Ability to use URI?SAS for the destination

### ISSUE THREAD

**Issue by Lumute** [Azure/azure-powershell#12265]
## Description of the new feature

I am able to use -AbsoluteURI parameter to specify the URI?SAS of a source blob without specifying the context and works well but I could  not figure out a way to do this for the destination, would it be possible to add this?

## Proposed implementation details (optional)

Add a -DestAbsoluteURI that allows the use of a URI?SAS to specify the destination blob without the need of -DestContext

**Comment by blueww** [comment]
@Lumute

For CopyBlob, the [Rest API](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) support parameter "x-ms-copy-source" as Uri, so we can support it in the copy blob cmdlet.
For destination, the credential input is same as other cmdlets per rest API (And SAS not supported in all copy blob scenario), so please use -DestContext to input the credential, we support create storage context with SAS.
If you have any scenarios, that can only use SAS Uri instead of -DestContext, please clarify.

**Comment by Lumute** [comment]
Thanks for looking into this, I have a requirement to be able to copy (clone) a page blob snapshot inside a storage account with a single command (no scripts). I ended embedding the New-AzStorageContext in the Start-AzStorageBlobCopy command in a single line, not ideal and quite long but works...

The support for URI:SAS for destination would had simplified that command and made it cleaner but I guess if it is a restriction of the API then that's ok...

**Comment by blueww** [comment]
@Lumute
Thanks for the comment!
Good to know your scenario works now.

I will close this issue.
Feel free to contact us if you need any further assistance.
