### ISSUE TITLE
add page for `Invoke-Rest`

### ISSUE THREAD

**Issue by skmkzyk** [Azure/azure-powershell#12510]
## Description of the new feature

The `Invoke-Rest` cmdlet seems implemented as alias for the `Invoke-RestMethod`.
If it's true, is it good to add page for `Invoke-Rest` to become more clear documentation?
(Or either of cmdlet will be deprecated?)

```
> Get-Help Invoke-Rest

NAME
    Invoke-RestMethod
```

**Comment by dingmeng-xue** [comment]
@skmkzyk , Azure PowerShell just released new cmdlet `Invoke-AzRestMethod` (alias is `Invoke-AzRest`). Its online help is https://docs.microsoft.com/en-us/powershell/module/az.accounts/invoke-azrestmethod?view=azps-4.4.0

 `Invoke-RestMethod` is PowerShell native cmdlet. https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7

Please let me know if you need further clarification.

**Comment by skmkzyk** [comment]
I'm sorry for mistake what I want to propose you...

I want some description/page for `Invoke-AzRest` for more clarification.
If could, please add that "`Invoke-AzRest` is an alias for `Invoke-AzRestMethod`"?
It's just a little request..

**Comment by dcaro** [comment]
@skmkzyk the aliases are implemented to facilitate the use of a cmdlet or ensure backward compatibility. It is preferable to use the cmdlets rather than the aliases.

We are working on having a documentation page with more details on the use of the cmdlet that should be published in few weeks. Before it gets published, you can refer to this article: https://techcommunity.microsoft.com/t5/azure-tools/how-to-manage-azure-resources-with-the-new-powershell-invoke/ba-p/1540306

**Comment by skmkzyk** [comment]
Thanks for info!
