### ISSUE TITLE
Alpine Docker Image for azure Powershell

### ISSUE THREAD

**Issue by SunnyOswal** [Azure/azure-powershell#12555]
## Description of the new feature
Our organization has approved only alpine based docker images to be used. Can we have alpine image also part of Microsoft official docker image with Azure Powershell Pre-Installed ? Any particular reason it is not already provided ?

I have raised this issue on docs as well. Not sure which is the right place to open up this issue.
https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1503

**Comment by dingmeng-xue** [comment]
@SunnyOswal , thanks for your feedback. We haven't covered all because of the priority and team resource. We will address this gap soon. Which Alpine version do you want to use? Current PowerShell supports Alpine 3.10, 3.9 and 3.8. If we have no bandwidth to test all, we can focus on your need at the first.

**Comment by SunnyOswal** [comment]
Thanks for superfast response. We would appreciate if we can get powershell core 7 , alpine 3.10 and latest azure powershell pre-installed in the docker image.
