### ISSUE TITLE
Unable to execute win app driver and launch it through powershell

### ISSUE THREAD

**Issue by samkhayal** [Azure/azure-powershell#12579]
## Description
created powershell to run it on my azure vm from my local. I am doing this to run several tests at the same time from my machine without the need to connect to vm and run it manually. so create power shell script . connected to vm.

## Steps to reproduce
```
connect-AzAccount
then execute line
Invoke-AzVMRunCommand -ResourceGroupName 'vmresouregroup' -Name 'vmname' -CommandId 'RunPowerShellScript' -ScriptPath 'c:\SmokeTesting.ps1'
ps1file content:
$ProjectDir = "."
$PackagesDir = "\packages"
$OutDir = "\WinAppDriverProject\bin\Debug"

# Set nunit path test runner
$nunit = "C:\Nunit\nunit-console\nunit3-console.exe"
 
#Find tests in OutDir
$tests = (Get-ChildItem $OutDir -Recurse -Include WinAppDriverProject.dll)
```

# Run NUnit3 tests
```powershell
& $nunit $tests   --work=$OutDir --where="cat==SmokeTesting"
```

## Environment data

```

```

## Module versions

```

## Debug output

<!-- Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block -->

```

```

## Error output
failed cause was unable to launch the desktop application
<!-- Please run Resolve-AzError and paste the output in the below code block -->

```

```

**Comment by dingmeng-xue** [comment]
@samkhayal , we guess it is due to `Invoke-AzVMRunCommand` cannot launch application with GUI. Please try some approaches to narrow down the issue. Firstly, you can remove logic of launching nunit3-console.exe from the script and ensure Invoke-AzVMRunCommand can work. Then, try to launching other tools such as `dotnet --info` and check if script works. If first step works, you also can check if there is way to launch nunit3-console.exe without GUI.

If you still meet the issue, please share debug information via setting `$DebugPreference="Continue"`
