### ISSUE TITLE
Missing parameters from new-azurermresourcegroup?

### ISSUE THREAD

**Issue by mortenlerudjordet** [Azure/azure-powershell#1269]
Hi, after migrating to the new AzureRM modules there seems to be some parameters missing on new-azureRMresourcegroup? Might be a bug, or are these deprecated? 

Running (v. 1.0.0):
(Get-Command -Name new-azurermresourcegroup).Parameters.Keys

Shows:
Name
Location
Tag
Force
++

On 0.9.8 running:
(Get-Command -Name new-azureresourcegroup).Parameters.Keys

Shows:
Name
Location
DeploymentName
Tag
Force
TemplateParameterObject
TemplateParameterFile
TemplateParameterUri
GalleryTemplateIdentity
TemplateFile
TemplateUri
StorageAccountName
TemplateVersion
Profile 
++

**Comment by Nepomuceno** [comment]
This is by design before you could create a resource group and deploy it on the same command what was causing confusion because you actually has always a command to deploy resource groups. So now if you wan to create a resource group you run this command. if you need to actually deploy you use the deploy command

**Comment by mortenlerudjordet** [comment]
Thanks for clearing that up for me.

**Comment by mortenlerudjordet** [comment]
Should update the help text on the function and remove the information about supporting the parameters on the new RM function.
