### ISSUE TITLE
New-azresourcegroupdeployment: Array parameters

### ISSUE THREAD

**Issue by jethrovaneetvelde** [Azure/azure-powershell#12835]
Noticed a big issue with the 2.5.0 version of az.resources. This is not an issue on 2.3.0 (didnt test on other versions).
The array parameter does not get handled as it should
This is the (partial) params file:
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "dnsservers": {
      "value": [
        "10.8.0.5",
        "10.8.0.4"
      ]
    }
  }
}
This deployment works fine on 2.3.0 but fails on 2.5.0. When I check the parameters on the (failed) deployment in the portal, I see this as input parameters:
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "dnsservers": {
            "value": [
                [],
                []
            ]
        }
    }
}

**Comment by jngibert** [comment]
I am seeing this same issue with v2.5.0 as well.

**Comment by dingmeng-xue** [comment]
Hi team, please help to look into it.

**Comment by jan-delaet** [comment]
Noticed the same issue as well with v2.5.0 of Az.Resources. Version 2.4.0 of Az.Resources does not have this issue. This ends up showing up like this in the portal after the failed deployment:

![image](https://user-images.githubusercontent.com/60466246/92248084-6eeb3680-eec8-11ea-98cf-f39feaea2b27.png)

This only happens when an array parameter value is specified through a ARM template parameter file. If the parameter is provided at runtime through Powershell's dynamic parameter processing, this problem does not occur. So it's likely to do with how to ARM template parameter file is being processed.

**Comment by kwiecek** [comment]
This problem also affected me during deployment by Azure pipelines.

If:
- you implement ARM Template Powershell
- you are using a hosted agent
- parameters are passed through the file
- you pass the value of the parameter of type array

Then use the following workaround:
- indicate the specific version of Azure Powershell:

```
azurePowerShellVersion: OtherVersion
preferredAzurePowerShellVersion: 4.4.0
```

**Comment by anthony-c-martin** [comment]
This looks like the same issue as #12773. @shenglol please could you confirm?

**Comment by shenglol** [comment]
Yes, this is already fixed in [Az.Resources 2.5.1](https://www.powershellgallery.com/packages/Az.Resources/2.5.1). Closing the issue.
