### ISSUE TITLE
Specify BlobType within Start-AzStorageBlobCopy -- Similar to AzCopy 

### ISSUE THREAD

**Issue by deontaepharr** [Azure/azure-powershell#12907]
azcopy copy command allows for one to specify the type of blob that the destination blob will be. So, if I am copying over an AppendBlob, I can specify --blob-type=BlockBlob to have it converted as such once it lands in the new location.

This functionality doesn't exist (at least from my research) in Start-AzStorageBlobCopy, unless I am mistaken.

**Comment by blueww** [comment]
@deontaepharr 
Start-AzStorageFileCopy means to copy an Azure blob/file to an Azure file.
If you want to copy an Azure file to Azure blob, you should use Start-AzStorageBlobCopy, but it also only allows copy File to a block blob, since the [Copy-Blob rest API ](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) only allows copy Azure file to block blob.
> If the source is a file, the destination must be a block blob.

As I know, AzCopy should use other ways to copy an Azure file to append blob, like download the blob content to local memory and upload to an append blob; or copy blob from Uri.

We will evaluate this feature request for Powershell per the customer request count and our bandwith.

As a workaround, you can call AzCopy in Powershell console.

**Comment by deontaepharr** [comment]
@blueww This is my mistake, but I meant Start-**_AzStorageBlobCopy_**, which I have updated now. I really wish I caught this before posting on the forum. My apologies.
To clarify, I do not want to copy a file. I would like to copy an AppendBlob to BlockBlob, by specifying the type within the Start-AzStorageBlobCopy command.

**Comment by blueww** [comment]
@deontaepharr 
Since the [Copy-Blob rest API ](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) only allows copy blob to same blob type, Powershell currently only support copy blob to same type.

AzCopy should use other ways to copy an Azure file to append blob, like download the blob content to local memory and upload to an append blob; or copy blob from Uri.

We will evaluate this feature request for Powershell per the customer request count and our bandwith.

**Comment by blueww** [comment]
@deontaepharr
Could you share why do you want to copy an append blob to block blob? It can help us to evaluate requirement, and see if it's a common request.
BTW, as a workaround, you might can download the append blob to local, and upload as a block blob, then delete the local file.

**Comment by deontaepharr** [comment]
@blueww The reason why I want this is due to having separate storage accounts, one with hierarchical namespace enabled and another without. The non-hierarchical storage account is needed as it allows append blobs. However, I need to perform copying/moving of these AppendBlobs to the hierarchical namespace enabled storage account. 

The workaround would be sufficient, but unfortunately, downloading gigabytes of data takes a very long time for the work I am trying to accomplish. Being able to use the MS backend, service-to-service transfer would be much faster, simpler, and beneficial.

**Comment by blueww** [comment]
@deontaepharr
Thanks for sharing the scenario!
Let's see if this is a common scenario that also needed by other customers.

BTW, for how to run AzCopy in Azure Function, you might can ask Azure Function team for help.

**Comment by deontaepharr** [comment]
@blueww thank you for pointing me to the functions team. I will pose that question there about azcopy
