### ISSUE TITLE
Resource management commandlets not loaded in v1.0.1

### ISSUE THREAD

**Issue by paulmey** [Azure/azure-powershell#1300]
Installed v1.0.1 (November 2015) via Web PI.
The `C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureResourceManager.psd1` file is missing, hence none of the ARM commandlets are being loaded.

**Comment by mortenlerudjordet** [comment]
There is no AzureResourceManager.psd1 in 1.0.1, they have changed how modules load in AzureRM.
AzureResourceManager was deprecated after 0.9.8.1.

The easiest way to get this working is checking:
C:\Program Files\WindowsPowerShell\Modules and delete AzureResourceManager folder. Just to clean up old versions.

If you have WMF 5 (or win 10) installed do:
````
Install-Module -Name AzureRM
Import-Module -Name AzureRM

Install-AzureRM or Update-AzureRM
````

You will now see a lot of new folders in C:\Program Files\WindowsPowerShell\Modules called AzureRM.xxxx

In : C:\Program Files\WindowsPowerShell\Modules\AzureRM\<version>\AzureRM.psm1
there is now a function called Import-AzureRM that imports all the new AzureRM.xxx modules.

**Comment by jeffpatton1971** [comment]
Ya, so I have windows 10 installed and those cmdlets listed above don't work/exist?
install-module -name azurerm
install-module : The term 'install-module' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ install-module -name azurerm
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install-module:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
Import-Module -Name AzureRM
Import-Module : The specified module 'AzureRM' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module -Name AzureRM
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (AzureRM:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
install-azurerm
install-azurerm : The term 'install-azurerm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ install-azurerm
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install-azurerm:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
update-azurerm
update-azurerm : The term 'update-azurerm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ update-azurerm
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (update-azurerm:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mortenlerudjordet** [comment]
Do : $PSVersionTable.PSVersion from a PS window and check that you are on version 5.

Try : Import-Module -Name PowerShellGet (this has the install-module function)
Check if you have the folder: C:\Program Files\WindowsPowerShell\Modules\PowerShellGet

If not check out the instructions here: https://www.powershellgallery.com/

**Comment by jeffpatton1971** [comment]
Ya, looks like I needed to run powershell in admin mode in order to use install-module?? seems wrong...but it's currently installing now...

**Comment by mortenlerudjordet** [comment]
That's powershell for you, always do everything i admin mode :)

**Comment by jeffpatton1971** [comment]
That's bad joo joo yo! ;-)

**Comment by paulmey** [comment]
@mortenlerudjordet That's kind of confusing, because the `ShortcutStartup.ps1` still mentions `AzureResourceManager.psd1`. Also, there is no way to install the RM modules using Web PI and I never got the PS gallery cmdlets to work on this Win 8.1 machine, but that maybe because I didn't try as an admin...

**Comment by paulmey** [comment]
Tried with admin just now, I can install the PS gallery package. I'll go with that route in the future. Thanks for the help! :+1: 

I'd strongly reconsider distributing through Web PI if that's only going to give you the service management cmdlets without a simple way to load the ARM ones even on pre-wmf5 machines...

**Comment by mortenlerudjordet** [comment]
Sure, that happens with all change. Though it will be clean up eventually. 

You should be able to get everything through webPI and MSI, though I have not tried personally. Therefore I can only advice with what I know :)

**Comment by jeffpatton1971** [comment]
So i'm only able to run the ARM modules from an admin console....that feels wrong. is there a permissions thing I need to fix? My user account is in local admins, but I launch powershell in not admin mode.

**Comment by jeffpatton1971** [comment]
so, the following allowed me to run import-azurerm from a non-admin console
# Jeff Patton@C02PX3KSG8WL | 17:29:02 | 11-17-2015 | F:\projects\mod-posh\powershell\production $  [master ≡]
Import-Module 'C:\Program Files\WindowsPowerShell\Modules\PackageManagement'
# Jeff Patton@C02PX3KSG8WL | 17:29:13 | 11-17-2015 | F:\projects\mod-posh\powershell\production $  [master ≡]
Import-Module 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet'
# Jeff Patton@C02PX3KSG8WL | 17:29:22 | 11-17-2015 | F:\projects\mod-posh\powershell\production $  [master ≡]
Import-Module 'C:\Program Files\WindowsPowerShell\Modules\AzureRM'
# Jeff Patton@C02PX3KSG8WL | 17:29:33 | 11-17-2015 | F:\projects\mod-posh\powershell\production $  [master ≡]
Import-AzureRM
Importing AzureRM modules.
# Jeff Patton@C02PX3KSG8WL | 17:30:04 | 11-17-2015 | F:\projects\mod-posh\powershell\production $  [master ≡]

**Comment by devigned** [comment]
@jeffpatton1971 sounds like your $env:PSModulePath was messed up. If you restart, you should see that corrected. I've run into this and I think it's actually a PowerShell bug

**Comment by devigned** [comment]
@paulmey if there is a pending install, the $env:PSModulePath can get messed up. See the restart comment above (stinks... i know).

After that, you can use the cmdlets straight away (as long as they are in your path). You should only need admin to install from Gallery.

**Comment by devigned** [comment]
@paulmey and @jeffpatton1971 please confirm this corrects your issue.

**Comment by paulmey** [comment]
@devigned I'll test that when my machine is in a rebootable state again. :-) Feel free to close this issue in the mean time.

**Comment by AzimUddin** [comment]
I was able to repro this issue with the following steps -
1. Install Azure PowerShell 1.0.1 (November release) via Web Platform installer 5.x
I can see all Azure RM modules
2. Uninstall Azure PowerShell
3. Restart machine
4. Install Azure PowerShell
At this point, no RM modules are loaded.

I didn't have any pending update. But once I rebooted the machine, everything works fine. The question is - why did I need this reboot? If reboot is indeed a necessary part of this install, let's please ensure to document this. Since a few of us were able to repro this, I envision others will run into this as well.

**Comment by dotdot2** [comment]
Same, here. Even ARM deployment is failing
22:46:31 - Build started.
22:46:31 - Project "AzureResourceGroup2.deployproj" (StageArtifacts target(s)):
22:46:31 - Project "AzureResourceGroup2.deployproj" (ContentFilesProjectOutputGroup target(s)):
22:46:31 - Done building project "AzureResourceGroup2.deployproj".
22:46:31 - Done building project "AzureResourceGroup2.deployproj".
22:46:31 - Build succeeded.
22:46:31 - The following parameter values will be used for this deployment:
22:46:31 -     hostingPlanName: basic
22:46:31 -     sku: Free
22:46:31 -     workerSize: 0
22:46:31 -     administratorLogin: freetest
22:46:31 -     administratorLoginPassword: <securestring>
22:46:31 -     databaseName: foog
22:46:31 -     collation: SQL_Latin1_General_CP1_CI_AS
22:46:31 -     edition: Basic
22:46:31 -     maxSizeBytes: 1073741824
22:46:31 -     requestedServiceObjectiveId: dd6d99bb-f193-4ec1-86f2-43d3bccbc49c
22:46:31 - Launching deployment PowerShell script with the following command:
22:46:31 - 'c:\users\user1\documents\visual studio 2015\projects\azureresourcegroup2\Scripts\Deploy-AzureResourceGroup.ps1' -StorageAccountName '' -ResourceGroupName 'beatestarm' -ResourceGroupLocation 'westus' -TemplateFile 'c:\users\user1\documents\visual studio 2015\projects\azureresourcegroup2\templates\websitesqldatabase.json' -TemplateParametersFile 'c:\users\user1\documents\visual studio 2015\projects\azureresourcegroup2\templates\websitesqldatabase.parameters.json' -ArtifactStagingDirectory '..\bin\Debug\staging'
22:46:31 - [ERROR] Add-AzureRMAccount : The term 'Add-AzureRMAccount' is not recognized as the 
22:46:31 - [ERROR] name of a cmdlet, function, script file, or operable program. Check the 
22:46:31 - [ERROR] spelling of the name, or if a path was included, verify that the path is 
22:46:31 - [ERROR] correct and try again.
22:46:31 - [ERROR] At line:1 char:596
22:46:31 - [ERROR] + ... ndpoint 'https://graph.windows.net/'  }; ((Add-AzureRMAccount -Subscr ...
22:46:31 - [ERROR] +                                                ~~~~~~~~~~~~~~~~~~
22:46:31 - [ERROR]     + CategoryInfo          : ObjectNotFound: (Add-AzureRMAccount:String) [],  
22:46:31 - [ERROR]    CommandNotFoundException
22:46:31 - [ERROR]     + FullyQualifiedErrorId : CommandNotFoundException
22:46:31 - [ERROR]  
22:46:31 - [ERROR] & : The script 'Deploy-AzureResourceGroup.ps1' cannot be run because the 
22:46:31 - [ERROR] following modules that are specified by the "#requires" statements of the 
22:46:31 - [ERROR] script are missing: AzureRM.Resources.
22:46:31 - [ERROR] At line:1 char:2499
22:46:31 - [ERROR] + ... eCloud')));&'c:\users\user1\documents\visual studio 2015\projects\ ...
22:46:31 - [ERROR] +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
22:46:31 - [ERROR]     + CategoryInfo          : ResourceUnavailable: (Deploy-AzureResourceGroup. 
22:46:31 - [ERROR]    ps1:String) [], ScriptRequiresException
22:46:31 - [ERROR]     + FullyQualifiedErrorId : ScriptRequiresMissingModules
22:46:31 - [ERROR]  
22:46:31 - 
22:46:31 - Deploying template using PowerShell script failed.
22:46:31 - Tell us about your experience at http://go.microsoft.com/fwlink/?LinkId=691202

**Comment by dstandish** [comment]
This happened to me too.  

I had PowerShell 3.0.  sqlps module was not working, so I installed Windows Management Framework 4.0 to get Powershell 4.0, and then installed Microsoft® Windows PowerShell Extensions for Microsoft® SQL Server® 2012.

After adding the sql server module directory to the environment variable, sqlps worked.

But then I went back to work on some azure scripts, and found that the cmdlets were not accessible.  Thankfully I found AzimUddin's post, and I restarted.  Now everything is fine.

**Comment by chriswelles** [comment]
There is a long standing issue with the Azure-Powershell added PSModulePath entries.  They get added without the trailing backslash, and it breaks several things in non-admin powershell instances.  I can't see any of my customizations outside of admin mode.  Once I go in and fix the PSModulePath to include a final backslash for all the added entries, everything works perfectly.

**Comment by mani0070** [comment]
This happened to me as well. Cannot figure out how to fix this. Install via web platform installer

**Comment by chriswelles** [comment]
It seems the trailing backslash issue has been fixed for the 1.2 installer.  That fix might resolve this particular issue as well.

**Comment by devigned** [comment]
Please let us know if the issue still persists. We are hoping the latest release corrected this issue.

**Comment by jeffpatton1971** [comment]
Sorry for the late reply, I did not see that issue crop up this go round.

Thanks for the hard work!

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Fri, Feb 5, 2016 at 12:33 PM -0800, "David Justice" <notifications@github.com<mailto:notifications@github.com>> wrote:


Please let us know if the issue still persists. We are hoping the latest release corrected this issue.

-

**Comment by markcowl** [comment]
Closing, as I believe this issue is resolved.  Please open a new issue if this perists for you

**Comment by Michael-DST** [comment]
OMG I have been getting pwnz0red (yeah, bringing that back... it's THAT bad!) this entire day with this.  I have Windows 10, but I do NOT have C:\Program Files\WindowsPowerShell\Modules\PowerShellGet on my system.  It has been a longgggg day, but this thread is the most valuable that I have seen in my very difficult journey thus far. :stuck_out_tongue:

**Comment by Michael-DST** [comment]
I also do not have Modules/AzureRM which is the whole reason for my angst to begin with, I believe.  I have not been able to run any default AzRM methods like New-AzureADApplication but can run New-AzureRmADApplication.

**Comment by devigned** [comment]
@Michael-DST did you run `install-module azure` or install via MSI? If you have installed only the AzureRM.* modules, then you only have the {Verb}-AzureRm{Noun} cmdlets.

**Comment by Michael-DST** [comment]
Hi @devigned thank you for playing support to my personal hell. :smile:  I did install via MSI, or rather the WebPI.  Also, I did just realize that I have a "C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet" (x86). Is this expected/part of the problem?  I do not have an Azure* in either x86 or plain Program Files.

**Comment by devigned** [comment]
@Michael-DST, WebPI install is completely separate from anything PowerShellGet related. WebPI installs the modules to program files and adds the path to your psmodulepath.

If the psmodulepath is messed up, you will not see this issue if you open PS in admin mode.

We are going to fix this in a near future release. @mayurid or @markcowl can provide more detail here.

**Comment by Michael-DST** [comment]
WOW!!!  I just totally figured it out.  In my case I was running 64-bit ("regular") PowerShell, and all the action is over in x86!  That is obviously totally unexpected.  Does everyone work in x86?  That would be good to know in the documentation somewhere. :stuck_out_tongue: 

Also, it is saying that PSGallery is an untrusted repository, which also seems completely inaccurate.

Goodness gracious.

**Comment by AaronLS** [comment]
Tried x86 and 64-bit, both ISE and non-ISE prompts, same problem. Probably something I am missing that was left out of the documentation.  This would be fine if this were just a game or a toy, but projects hinge on this.  There's alot of things, such as setting up deployment from VS Online to Azure, which require PowerShell to assign permissions to the service principal. I have no choice in the matter.

PS C:\Users\usernamehere> Import-Module AzureRM
Import-Module : The specified module 'AzureRM' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module AzureRM
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (AzureRM:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by MarcoMol** [comment]
For the past day I've been trying to run Set-AzureRmDiagnosticSetting wit hthe -workspaceid parameter from ISE x64.
However, PS doesn't recognize the parameter as being valid. Which is correct, it only recognizes storageaccountid and servcebusruleid as parameters.
So I figure I am missing the proper modules in powershell:
```
ModuleType

 Name                      ExportedCommands                                                           
---------- ----                      ----------------                                                           
Script     ISE                       {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                        
Manifest   Microsoft.PowerShell.M... {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}         
Manifest   Microsoft.PowerShell.U... {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                  
Binary     PackageManagement         {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}  
Script     PowerShellGet             {Find-DscResource, Find-Module, Find-Script, Get-InstalledModule...}`
```

I think I do, I should have the AzureRM modules loaded.
So I have powershell 5:
```
Name                           Value                                                                                                                                                                   
----                           -----                                                                                                                                                                   
PSVersion                      5.0.10586.117                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                 
BuildVersion                   10.0.10586.117                                                                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                                                                         
WSManStackVersion              3.0                                                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                                                     
SerializationVersion           1.1.0.1
```

I run install-module -name AzureRM, but it is unable to resolve the location?
```
Install-Module -Name AzureRM
WARNING: Unable to resolve package source 'http://www.powershellgallery.com/packages'.
WARNING: Unable to resolve package source 'http://www.powershellgallery.com/packages'.
Install-Package : No match was found for the specified search criteria and module name 'AzureRM'.At C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

I've been fighting with this module for the past day now. First I was on Powershell 4. I got the newest nuGet, I installed the packagemanagement for powershell from the microsoft website. The same thing as above. so I figured, whatever, I'll do the upgrade to powershell 5. But I'm still having the same challenge. I'm at a loss for what could be the solution to being able to get the module loaded. 
I've looked at so many sites now, and none of them have a working solution. 

Hoping this is the spot someone might have an answer.

Other info:
```
Name                      PackageManagementProvider InstallationPolicy   SourceLocation                                                                                                                
----                      ------------------------- ------------------   --------------                                                                                                                
PSGallery                 NuGet                     Trusted              http://www.powershellgallery.com/packages 
```
