### ISSUE TITLE
New-AzVM is unable to create VM without public IP address

### ISSUE THREAD

**Issue by glenncarr** [Azure/azure-powershell#13026]
## Description

This is a follow-up issue to the issue reported (and closed) here:
https://github.com/Azure/azure-cli/issues/8296

There does not appear to be a way to create a VM without a public IP address using New-AzVM.

**Comment by VeryEarly** [comment]
Hi @glenncarr ,

I'm able to create VM using New-AzVM without providing '-PublicIpAddressName' parameter, can you provide the exact command you executed?

**Comment by glenncarr** [comment]
@VeryEarly thanks for the response.  

When I create a new VM using New-AzVM without specifying `-PublicIPAddressName`, a public IP address is created by default.  I want to create the VM _without_ a public IP address.

I've tried passing in `""` and `'""'` as you can do with with `az vm create` using `'""'` as @tjprescott [states here](https://github.com/Azure/azure-cli/issues/8296#issuecomment-455609415).

He also describes the problem with New-AzVM: _"In this case, Powershell eats the empty string as if it weren't sent"_.

The only way I've seen to do this with PowerShell is to use `New-AzVMConfig` with additional commands.

**Comment by dcaro** [comment]
@glenncarr you are right, currently, you will have to use `New-AzVMConfig` to build the VM configuration and use `New-AzVM` to deploy it. Yiu can use this example: 
https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azvm?view=azps-4.7.0#example-3--create-a-vm-from-a-marketplace-image-without-a-public-ip

**Comment by glenncarr** [comment]
Thanks @dcaro, that's what I'll use.  Will there be a way in the future to use `New-AzVM` without creating a public IP address?  Or will this just be a documented limitation for `New-AzVM` vs `az vm create`?  I would expect them both to accept an empty string and have the same behavior.

**Comment by dcaro** [comment]
Our goal is to give a similar experience across the tools, this is one delta that we would need to address.

**Comment by glenncarr** [comment]
@dcaro Good to hear.  Thanks for the response.  We're also glad to have a workaround until this is implemented.

**Comment by Pistle** [comment]
If we need to access an Azure VM using RDP or SSH, most commonly we use public IP method. In this way, the virtual machine will have a public IP address (static or dynamic) assigned to it. Also, RDP or SSH service ports will open to the public via NSG. This is easy but not a very secure method. 
If we have VPN or Express Route connectivity to Azure, we can connect to virtual machines using private IP addresses. It is secure than the public IP address method. However, it required additional configuration in-network level. 
Azure Bastion is a solution that we can use to access Azure VM securely without the use of public IP addresses or VPN connectivity. This is similar to using a jump-server to connect to resources in the remote network but instead of the traditional RDP method, it is using browser-based secure HTTP connectivity. Let's go ahead and explore a bit more about the Azure bastion solution. 
I hope this will be helpful. To know more: [Windows Virtual Desktop](https://www.apps4rent.com/windows-virtual-desktop-azure), [Azure Managed Services](https://www.apps4rent.com/managed-azure.html)
Best Regards

**Comment by Drewm3** [comment]
In general there are two forms for "New-AzVM" there is a model that allows full functionality which effectively allows any configuration that you want, but it requires more commands to be executed to do this "quick create" form. For the "quick create" form, the number of options available are limited. Currently the "quick create" form always creates a public IP address.

The team is looking to extend the "quick create" support into a wider selection of options including creating a VM without a public IP address. Once the plan for improvements has locked down, then we will provide more details on if this specific request will be in the near term (~6 months) plan or not.

**Comment by jaylabell** [comment]
Apologies for the delay here due to the holiday season. We are looking into this issue, and will provide feedback shortly.

**Comment by jaylabell** [comment]
Update: This item has been added to our backlog. Development will begin soon.

**Comment by albertoRamon** [comment]
Some workaround or progress?

**Comment by Sandido** [comment]
This bug has been fixed and released in the PS module Az.Compute version 4.22.0 on 1/4/2022.
