### ISSUE TITLE
Convert azure cli script to azure powershell

### ISSUE THREAD

**Issue by shps951023** [Azure/azure-powershell#13257]
Because `Azure-CLI doesn't support runbook, function, logics`, only azure powershell can do it.  
So if I'd like to upload my Azure CLI script to azure, I only have to convert azure cli to azure powershell..  

Is there any tool can convert azure cli script to azure powershell? e.g :  
input `az group list`    
oupout : `Get-AzManagementGroup`  

input : `az group show --resource-group system`  
oupout : `Get-AzManagementGroup -GroupName system`  

It's a heavy job when script is large..

**What I've tried :**  
Right now, I convert cli to powershell with my hands one by one.

**Comment by dingmeng-xue** [comment]
Thanks for reporting.

Currently, there is no tool to do this conversion automatically. The challenging is Azure CLI and PowerShell cannot map one-to-one. The syntax of Azure CLI and PowerShell are different.

**Comment by shps951023** [comment]
@dingmeng-xue  thanks!

**Comment by dcaro** [comment]
@shps951023 we are working on allowing customers to manage any Azure resources with any of the following: Az PowerShell, Az CLI or Terraform. For example, we have added support for [Functions](https://www.powershellgallery.com/packages/Az.Functions) in PowerShell and still updating it.

I have seen some initiatives from community member to create PowerShell modules calling az cli commands if you are wiling to try out but from the Azure PowerShell team we do not have such plans.
If you ask for support for a specific service, we would be able to prioritize the development of  the associated module.

I am closing this issue since we will not implement the feature request but feel free to open a new issue or put additional comments.

**Comment by shps951023** [comment]
@dcaro thanks
