### ISSUE TITLE
Az PowerShell Module: Configuration of Azure AD Application (App Registration)

### ISSUE THREAD

**Issue by gerrylaenen** [Azure/azure-powershell#13360]
## Description of the new feature
Hi,

I would like to configure the following parameters for App Registration through the Az PowerShell module:
- API Permissions
- Implicit grants (ID Tokens & Access Tokens)

Thanks in advance

**Comment by gerrylaenen** [comment]
Hi @dingmeng-xue , yes currently I sideload the AzureAD module. I am using the Set-AzureADApplication cmdlet to set the resource access and the cmdlet New-AzureADServiceAppRoleAssignment to grant the resource access.

Unfortunately, sideloading in compatibility mode gives some extra troubles... So I have extracted all AzureAD functions in a separate module which I then load in compatiblity mode. Some workarounds needed to get the job done now :).

**Comment by michaelmaillot** [comment]
Hi,

Like @gerrylaenen, I would like to use the Az PowerShell module to manipulate AAD Applications, but it looks like many features are missing, so I have to use AzureAD PowerShell module in addition.

@dingmeng-xue are you planning to update the Az PowerShell module in the future or will the AzureAD be the persistent one to work with AAD ?

**Comment by dingmeng-xue** [comment]
@michaelmaillot , Azure PowerShell just provides very basic functions on authorization and AzureAD is correct one which contains more features and the latest API version. It's the agreement at the beginning. If possible, we recommend you to use AzureAD module.

**Comment by gerrylaenen** [comment]
Unfortunately both Az and AzureAD are incompatible as Az is Powershell Core
while AzureAD is still on PowerShell .NET. We would like to foresee a
script that rolls out everything at once, but it seems that this is only
possible when going back to AzureRm. It is a pity that AzureAD is not yet
available in Powershell Core. I hope it will be soon :).

Op ma 9 nov. 2020 om 16:50 schreef Dingmeng Xue <notifications@github.com>:

**Comment by dingmeng-xue** [comment]
@gerrylaenen , could you share me more about why you have to go back to AzureRM? My understanding is AzureRM shouldn't have more features than Az. It seems you just need to use to Windows PowerShell in your case. Am I correct?

**Comment by gerrylaenen** [comment]
Hi, sorry for the late reply. AzureRm and AzureAD are compatible, both
running on Windows Powershell 5.1. The Az module did not run in Windows
Powershell, I had to import AzureAD in compatibility mode to use it. Which
in fact is a different PowerShell session that does not have access to
certain types etc...

When AzureAD is available in Powershell 7, I'll switch back to Az but for
the moment sticking to AzureRm.

Op di 10 nov. 2020 om 15:57 schreef Dingmeng Xue <notifications@github.com>:

**Comment by michaelmaillot** [comment]
@gerrylaenen I'm currently using both Az and AzureAD modules in PowerShell 5 (currently 5.1.18362.752). Below a screen for example.

![image](https://user-images.githubusercontent.com/44271458/99871805-a4f1aa00-2bdd-11eb-868c-03d1998c88f9.png)

**Comment by dingmeng-xue** [comment]
Az supports Windows PowerShell. Please double check. If you meet any issue, please let us know.

**Comment by pwouavre** [comment]
@dingmeng-xue  Hi, i'm using Powershell Core 7.1 in order tu use new parallelization feature.
`
Name                                    Value
----                                        -----
PSVersion                              7.1.0
PSEdition                               Core
GitCommitId                          7.1.0
OS                                          Microsoft Windows 10.0.18363
Platform                                 Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion  2.3
SerializationVersion                1.1.0.1
WSManStackVersion               3.0
`

However, because of the need to use the -UseWindowsPowershell when importing AzureAd module 
`
try {
  Write-Host "Importing module AzureAD if exist ... "
  Import-Module AzureAD -UseWindowsPowerShell -ErrorAction 'Stop'
} catch {
  try {
    Write-Host "No AzureAD module in present context : Installing module AzureAD ... "
    Install-Module AzureAD -Force -ErrorAction 'Stop'
    Write-Host "Importing module AzureAD ... "
    Import-Module AzureAD -UseWindowsPowerShell -ErrorAction 'Stop'
  } catch {
    Write-Error $_
  }
}
`

Im unable to run it using an AzureDevops Agent 
`
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az659-292'
Current agent version: '2.179.0'
##[group]Operating System
Microsoft Windows Server 2019
10.0.17763
Datacenter
##[endgroup]
##[group]Virtual Environment
Environment: windows-2019
Version: 20201210.0) 
##[endgroup]
`

`
Importing module AzureAD if exist ... 
No AzureAD module in present context : Installing module AzureAD ... 
Importing module AzureAD ... 
##[error]Failure from remote command: Import-Module -Name 'AzureAD': The specified module 'AzureAD' was not loaded because no valid module file was found in any module directory.
##[error]PowerShell exited with code '1'.
`

I also tryied with the AzureAD.Standard.Preview Module in the Posh Test Gallery source repository and the behavior is kind of different : Module is well importing 
`
Importing module AzureAD if exist ... 
No AzureAD module in present context : Installing and Importing module AzureAD ... 
Installing module AzureAD.Standard.Preview ...
Module installed
WARNING: C:\Users\VssAdministrator\Documents\PowerShell\Modules\AzureAD.Standard.Preview\0.1.599.7
WARNING: AzureAD.Standard.Preview
WARNING: C:\Users\VssAdministrator\Documents\PowerShell\Modules\AzureAD.Standard.Preview\0.1.599.7\net471
WARNING: Loading module in coreclr folder: 'netstandard2.0' ...
`

but once i'm using Get-AzureAdUser i have an error : 
`
##[error]Unhandled exception [Microsoft.PowerShell.Commands.WriteErrorException]: Unhandled exception [System.IO.FileNotFoundException]: Could not load file or assembly 'Microsoft.Data.Services.Client, Version=5.8.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
##[error]PowerShell exited with code '1'.
`

So i understand @gerrylaenen, who like me maybe tryied different way to use AzureAd Module in a Powershell Core context without any success, so maybe his solution is to use AzureRm, wich i will not do because of the time I need to do the migration (and honestly who wants to do that --> Oh right maybe to enjoy Parallelization feature).

Do you have any advise or update for me ?

Thanks for your help,

BR,

/Simon

**Comment by dingmeng-xue** [comment]
Thanks @pwouavre . We know AzureAD limitation but it's our of our scope. We are thinking to improve AzAD features once we have bandwidth. Hopefully, this issue can be resolved in the upcoming couple months.

**Comment by pwouavre** [comment]
HI @dingmeng-xue ,

Thanks for the update, looking forward for a resolution is there any place to track it ?

BR,

/Simon
