### ISSUE TITLE
Object of Get-AzCosmosDbAccount should also contain the ResourcegroupName

### ISSUE THREAD

**Issue by Paxilein** [Azure/azure-powershell#13597]
## Description of the new feature

The Object "Microsoft.Azure.Commands.CosmosDB.Models.PSDatabaseAccountGetResults" that's returned by Get-AzCosmosDbAccount should also contain the ResourcegroupName-Property. Especially as the other commands rely on the ResourcegroupName to be supplied - for example Get-AzCosmosDbSqlDatabase

**Comment by MehaKaushik** [comment]
The ResourceId is a property which contains the information of the resource group as well as the object. Instead of using the Name parameter set which requires both the name of account and resource group, consider using the ParentObject parameter set. In there you would just need to pass in the parent object and resource-group would be automatically extracted from it. 

Refer this: https://github.com/Azure/azure-powershell/blob/536d04c40ce5ab1f1c1243adbe1a37a94838e0a3/src/CosmosDB/CosmosDB/SQL/GetAzCosmosDBSqlContainer.cs#L46

Let me know if you have trouble using this parameter set.

**Comment by Paxilein** [comment]
I was using the Resourcegroupname to add them to logs and having the ResourcegroupName in the Object returned by Get-AzCosmosDbAccount would make it much easier than having to figure the ResourcegroupName out from the ResourceId...

**Comment by MehaKaushik** [comment]
ResourceGroup is not a property of Database Account, it would be wrong to include it in the same. 

You can read more about resource-group here https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal#what-is-a-resource-group

**Comment by MehaKaushik** [comment]
Please open this issue again if you have any further questions
