### ISSUE TITLE
New-AzSupportTicket Quota Change Requests error

### ISSUE THREAD

**Issue by motim6026** [Azure/azure-powershell#14035]
## Description

Get error when try open new ticket using  New-AzSupportTicket.

## Steps to reproduce

```powershell
New-AzSupportTicket -Name "test1" `
                    -Title "Test" `
                    -Description "Test" `
                    -Severity "minimal" `
                    -ProblemClassificationId "/providers/Microsoft.Support/services/6f16735c-b0ae-b275-ad3a-03479cfa1396/problemClassifications/4d78b174-3203-a3ac-9e08-41fb35de6354" `
                    -QuotaTicketDetail @{`
                                         QuotaChangeRequestVersion = "1.0"; `
                                         QuotaChangeRequests = ( `
                                          @{ `
                                            Region = "westus"; `
                                            Payload = "{`"VMFamily`":`"Dv2 Series`",`"NewLimit`":350}"})} `
                    -CustomerContactDetail @{ `
                                             FirstName = "moti"; `
                                             LastName = "malks"; `
                                             PreferredTimeZone = "pacific standard time"; `
                                             PreferredSupportLanguage = "en-us"; `
                                             Country = "USA"; `
                                             PreferredContactMethod = "Email"; `
                                             PrimaryEmailAddress = "email@domain.com"}

```

## Environment data

```
Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
PSVersion                      5.1.19041.1                                                                                                                                                   
PSEdition                      Desktop                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                       
BuildVersion                   10.0.19041.1                                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                           
SerializationVersion           1.1.0.1    
```

## Module versions

```powershell

ModuleType Version    Name  
Script     1.9.1      Az.Accounts 
```

## Debug output

```

```

## Error output

```
New-AzSupportTicket : Error response received. Error Message: '{"error":{"code":"InvalidParameterValue","message":"Thecallingclientsentabadrequesttothe
service","details":[{"code":"JsonDeserializationError","message":"Quota ticket details cannot be specified for non-subscription and service limits (quota) tickets"}]}}'
At line:1 char:1
+ New-AzSupportTicket -Name "test1" `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzSupportTicket], PSArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Support.SupportTickets.NewAzSupportTicket
```

**Comment by dingmeng-xue** [comment]
@motim6026 , please share debug log here. You can turn on it via `$DebugPreference="Continue"`

**Comment by pkrasnousov** [comment]
Have the same issue. Is there any updates on it?
**Debug Output**
`**********************
Transcript started, output file is C:\localtest.log
DEBUG: 11:19:43 AM - NewAzSupportTicket begin processing with ParameterSet 'CreateQuotaSupportTicketWithContactObjectParameterSet'.
DEBUG: 11:19:43 AM - using account id 'pavel@d.equa.se'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'pavel@d.equa.se', environment: 'AzureCloud', tenant: 'e2ce1cd3-f9bb-4161-bffb-57274421f5dc'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-04-05T09:19:34.0000000+00:00
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-04-05T09:19:34.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'e2ce1cd3-f9bb-4161-bffb-57274421f5dc', UserId: 'pavel@d.equa.se'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/b084f095-50da-4957-80c1-388bce450987/providers/Microsoft.Support/checkNameAvailability?api-version=2020-04-01

Headers:
x-ms-client-request-id        : 9f6d653b-5a03-4bdb-81e3-2d26bb648f81
accept-language               : en-US

Body:
{
  "name": "Aseries",
  "type": "Microsoft.Support/supportTickets"
}
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : 9195a9af-0937-4e4b-adc6-ea79e9ed3df1
x-ms-correlation-request-id   : 9195a9af-0937-4e4b-adc6-ea79e9ed3df1
x-ms-routing-request-id       : GERMANYNORTH:20210405T081944Z:9195a9af-0937-4e4b-adc6-ea79e9ed3df1
Cache-Control                 : no-cache
Date                          : Mon, 05 Apr 2021 08:19:44 GMT
Server                        : Kestrel

Body:
{
  "nameAvailable": true
}
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/b084f095-50da-4957-80c1-388bce450987/providers/Microsoft.Support/supportTickets/Aseries?api-version=2020-04-01

Headers:
x-ms-client-request-id        : 9f6d653b-5a03-4bdb-81e3-2d26bb648f81
accept-language               : en-US

Body:
{
  "properties": {
    "description": "Aseries",
    "problemClassificationId": "/providers/Microsoft.Support/services/3f33d852-e61f-d835-8217-a9a677d96914/problemClassifications/8109d6e2-f8e8-51e2-7b63-1f0f52620cb2}",
    "severity": "Minimal",
    "contactDetails": {
      "firstName": "FirstName",
      "lastName": "LastName",
      "preferredContactMethod": "Email",
      "primaryEmailAddress": "pavel@d.equa.se",
      "preferredTimeZone": "UTC",
      "country": "SWE",
      "preferredSupportLanguage": "en-us"
    },
    "title": "Aseries",
    "serviceId": "/providers/Microsoft.Support/services/3f33d852-e61f-d835-8217-a9a677d96914",
    "quotaTicketDetails": {
      "quotaChangeRequestSubType": "Account",
      "quotaChangeRequestVersion": "1.0",
      "quotaChangeRequests": [
        {
          "region": "westus",
          "payload": "{\"AccountName\":\"rdsa6fz6xcmszyx5q\",\"VMFamily\":\"Av2 Series\",\"NewLimit\":200,\"Type\":\"Dedicated\"}"
        }
      ]
    }
  }
}
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : bd130fb2-add3-4bf0-baf6-31d88c8484ee
x-ms-correlation-request-id   : bd130fb2-add3-4bf0-baf6-31d88c8484ee
x-ms-routing-request-id       : GERMANYNORTH:20210405T081946Z:bd130fb2-add3-4bf0-baf6-31d88c8484ee
Cache-Control                 : no-cache
Date                          : Mon, 05 Apr 2021 08:19:46 GMT
Server                        : Kestrel

Body:
{
  "error": {
    "code": "InvalidParameterValue",
    "message": "The calling client sent a bad request to the service",
    "details": [
      {
        "code": "JsonDeserializationError",
        "message": "Quota ticket details cannot be specified for non-subscription and service limits (quota) tickets"
      }
    ]
  }
}
>> TerminatingError(New-AzSupportTicket): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Error response received. Error Message: '{"error":{"code":"InvalidParameterValue","message":"The calling client sent a bad request to the service","details":[{"code":"JsonDeserializationError","message":"Quota ticket details cannot be specified for non-subscription and service limits (quota) tickets"}]}}'"
>> TerminatingError(New-AzSupportTicket): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Error response received. Error Message: '{"error":{"code":"InvalidParameterValue","message":"The calling client sent a bad request to the service","details":[{"code":"JsonDeserializationError","message":"Quota ticket details cannot be specified for non-subscription and service limits (quota) tickets"}]}}'"
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Error response received. Error Message: '{"error":{"code":"InvalidParameterValue","message":"The calling client sent a bad request to the service","details":[{"code":"JsonDeserializationError","message":"Quota ticket details cannot be specified for non-subscription and service limits (quota) tickets"}]}}'
>> @{ 'computerName' = if ([Environment]::MachineName) {[Environment]::MachineName}  else {'localhost'}; 'processId' = $PID; 'instanceId' = $host.InstanceId }

Name                           Value
----                           -----
processId                      23692
computerName                   PAVEL-PC
instanceId                     1c4918f9-4d6c-478f-8399-0ac7e8daa76d


New-AzSupportTicket : Error response received. Error Message: '{"error":{"code":"InvalidParameterValue","message":"Thecallingclientsentabadrequesttotheservice","details":[{"code":"JsonDeserializationError","message":"Quota
ticket details cannot be specified for non-subscription and service limits (quota) tickets"}]}}'
At D:\EQUA\DevOps\scripts\trash\localtest.ps1:36 char:1
+ New-AzSupportTicket -Name "Aseries" `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzSupportTicket], PSArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Support.SupportTickets.NewAzSupportTicket

`

**Comment by ganganarayanan** [comment]
+@Bhavin ***@***.***> @Nilay ***@***.***> and @Saket ***@***.***>

**Comment by saket** [comment]
Wrong @saket

**Comment by ganganarayanan** [comment]
@shahbj79, @mit2nil to comment

**Comment by mit2nil** [comment]
Hi @motim6026,

Problem Classification Id value is not valid for quota increase support ticket. Could you please try below value instead? We will look into how we can update the documentation and validation messages to correctly point out the issue.

/providers/Microsoft.Support/services/06bfd9d3-516b-d5c6-5802-169c800dec89/problemClassifications/e12e3d1d-7fa0-af33-c6d0-3c50df9658a3

**Comment by SteveNewa** [comment]
The documentation here: https://docs.microsoft.com/en-us/powershell/module/az.support/new-azsupportticket?view=azps-7.2.0

Is still very vague on this point.

> Hi @motim6026,
> 
> Problem Classification Id value is not valid for quota increase support ticket. Could you please try below value instead? We will look into how we can update the documentation and validation messages to correctly point out the issue.
> 
> /providers/Microsoft.Support/services/06bfd9d3-516b-d5c6-5802-169c800dec89/problemClassifications/e12e3d1d-7fa0-af33-c6d0-3c50df9658a3
