### ISSUE TITLE
Update Databricks PowerShell Module documentation related to enableNoPublicIP Property

### ISSUE THREAD

**Issue by msaranga** [Azure/azure-powershell#14381]
## Proposed implementation details (optional)
Please navigate to Az Databricks workspace creation [documentation](https://docs.microsoft.com/en-us/powershell/module/az.databricks/new-azdatabricksworkspace?view=azps-5.5.0) , search for property "-EnableNoPublicIP" property. This has generic documentation information. Please update document as per Swagger. 
Here is the Swagger description
"enableNoPublicIp":   
                  {
                          "$ref": "#/definitions/WorkspaceCustomBooleanParameter",
                          "description": "Should the Public IP be Disabled?"
                }

**Comment by isra-fel** [comment]
Thanks @msaranga for reporting!

This issue is because swagger defines a boolen parameter with a nested object, and our code generator chose the description of the inner property instead of the outer one.

```json
    "WorkspaceCustomObjectParameter": {
      "properties": {
        "type": {
          "$ref": "#/definitions/WorkspaceCustomParameterType",
          "description": "The type of variable that this is"
        },
        "value": {
          "type": "object",
          "description": "The value which should be used for this field."     <---------- here
        }
      },
      "required": [
        "value"
      ],
      "description": "The value which should be used for this field."
    },
```

So as the code was generated, we might need to revisit the logic of autorest.powershell

BTW do you happen to know why wasn't the parameter be designed as a simple boolean parameter, for example
```json
"enableNoPublicIp":
{
  "type": "boolean",
  "description": "Should the Public IP be Disabled?"
}
```

**Comment by LucasYao93** [comment]
> @LucasYao93 , can we fix it in this release?

Yes, we can.
