### ISSUE TITLE
New-AzRoleAssignment is not idempotent

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-powershell#14424]
I am using 3.2.0 version of Az.Resources module.

![image](https://user-images.githubusercontent.com/11664898/109884939-9b42fe00-7c32-11eb-87fc-bd266a250096.png)

_Originally posted by @pruthviuvss in https://github.com/Azure/azure-cli/issues/8568#issuecomment-790138937_

**Comment by dingmeng-xue** [comment]
Please provide the summary about the expected behavior on `New-AzRoleAssigment`.

**Comment by pruthviuvss** [comment]
@dingmeng-xue  My assumption from [this post](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types) is New-AzRoleAssignment should not throw an error if we apply a role to a principal that is already existing in a subscription. 

1. Since it is throwing an error, do you have any suggestions for a work around?
2. Or is this the expected behavior?

**Comment by dingmeng-xue** [comment]
Got your point. In Azure PowerShell, the exception is suggested when user want to create a new object using the same name of an existing one. I believe it's expected behavior.

PowerShell scripts allow try-catch. Please reference https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-7.1

**Comment by dingmeng-xue** [comment]
Close this issue now. Feel free to contact us for further question.

**Comment by cveld** [comment]
@dingmeng-xue What is the easiest way to do this in an idempotent way?
