### ISSUE TITLE
The Az module's implementation of the Get-AzADuser does not return all attributes

### ISSUE THREAD

**Issue by cobdev** [Azure/azure-powershell#14568]
The following issue should not have been closed as the feature wasn't fully implemented:
https://github.com/Azure/azure-powershell/pull/12032

**Comment by dingmeng-xue** [comment]
@cobdev , thanks for reporting. #12032 is not issue. It is PR and was closed when code was merged to master. Closed PR cannot be opened again. 

Please explain further about your requirements. If it is not specific, the priority will become lower because of the lack of engineering resource. 

FYI, Azure AD Graph used by AzAD or AzureAD cmdlets will be shut down at the middle of 2022 https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-or-azure-ad-graph/. According to that blog, user is recommended to use Microsoft Graph. You can get those modules (Microsoft.Graph.*) from PSGallery.

**Comment by cobdev** [comment]
The Az module's implementation of the Get-AzADuser does not return all attributes.  There are multiple people commenting on the closed PR to this effect.
________________________________
