### ISSUE TITLE
Add ScriptBlock parameter to Invoke-AzVMRunCommand

### ISSUE THREAD

**Issue by stevenjudd** [Azure/azure-powershell#14658]
## Description of the new feature
Add a new parameter to Invoke-AzVMRunCommand named "ScriptBlock" that would accept a PowerShell ScriptBlock object and execute that code on the remote VM specified. This would allow for more ad-hoc script running remotely against an Azure VM without the requirement of saving the code as a PS1 file that is locally accessible to the Invoke-AzVMRunCommand process.

**Comment by Drewm3** [comment]
Assigning this to @axayjo to consider this in a future release of Run Command

**Comment by axayjo** [comment]
@stevenjudd We track all feature requests centrally at feedback.azure.com. I've opened a feedback item there: https://feedback.azure.com/forums/216665-scripting-and-command-line-tools/suggestions/43262568-add-scriptblock-parameter-to-invoke-azvmruncommand

Now that we have a tracking item on feedback.azure.com, we may not need to keep this issue open. Please do go to the above link to upvote it. 

I'll be closing this issue within 7 days, unless you think otherwise. Let me know.

**Comment by axayjo** [comment]
Closing this issue now. Please head over to [Azure Feedback](https://feedback.azure.com/forums/216665-scripting-and-command-line-tools/suggestions/43262568-add-scriptblock-parameter-to-invoke-azvmruncommand) to upvote the feature.
