### ISSUE TITLE
Get-AzContext doesn't list all the available azure subscription

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-powershell#14736]
## Description

I am trying to understand after connecting my account with Connect-AzAccount then Get-AzContext it doesn't list all the Azure Subscription available to me, it only listed one subscription that attached to my account though I don't have any contributor level of permission.  It worked for my personal account ( which is a separate tenant from my company ), and didn't work out the same when I was trying with my company account. One available subscription that available to me was only associate to my company account but no permissions attached. 

Here's the doc link : 
https://docs.microsoft.com/en-us/powershell/module/az.accounts/get-azcontext?view=azps-5.7.0

**Comment by dingmeng-xue** [comment]
@cloudmelon , Azure context is the used for Azure cmdlet execution. The default one showing on console means the current account, tenant and subscription. You can list all available context via `Get-AzContext -ListAvailable`. Due to performance consideration, Azure PowerShell only fetches the first 25 subscriptions. You can change it in `Connect-AzAccount`

If you just want to list all available subscription, you can use `Get-AzSubscription` https://docs.microsoft.com/en-us/powershell/module/az.accounts/get-azsubscription?view=azps-5.7.0
