### ISSUE TITLE
How to avoid API-Throttling with Get-AzConsumptionUsageDetail?

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#14798]
When I query cost items with `Get-AzConsumptionUsageDetail`, I regularly run into throttling of the API. Inside my Azure Ecosystem I generate over 11,000 cost itmes per day, so you can imagine I stress the API alot!

It gets even worse when I use the `ForEach-Object -Parallel` function from Powershell Core 7 for performance reasons.

`Operation returned an invalid status code 'TooManyRequests'`

Is there a recommendation to design the queries so that I don't run into throttling?

**Comment by dingmeng-xue** [comment]
Service team, we believe this question should be mitigate on service side. It's great that API allows user to query multiple items in one REST call which can reduce the total number of REST call.

**Comment by octalimon** [comment]
Reduce the degree of parallelism also use exponential backoff for retries.  

If possible avoid duplicated calls and implement caching on the client side. 

Not sure if this applies but you may want to increase your date range in order to reduce the number of calls in order to get the usage details.

**Comment by octalimon** [comment]
Closing this issue,  let us know if you have any more questions.
