### ISSUE TITLE
Wrong version 1.10.0 released for Az module

### ISSUE THREAD

**Issue by kevin808** [Azure/azure-powershell#15314]
Hi Team,

Az module with version 1.10.0 was released 18 days ago and seems to be a wrong version in its branch.
https://www.powershellgallery.com/packages/Az/1.10.0.

Compared to previous version 1.8.0, it has removed nearly all the dependencies. Which caused a lot of problems when using commands in its sub-modules.
![image](https://user-images.githubusercontent.com/7627859/122712963-8187fe00-d297-11eb-9759-740dc3f8cd5f.png)

Compared to version 0.10.0-preview, it seems to be the right branch it should belong to.
![image](https://user-images.githubusercontent.com/7627859/122713227-f3f8de00-d297-11eb-8420-845a828e9a97.png)

Can you have a check?
BR,
Kevin

**Comment by dingmeng-xue** [comment]
Hi @kevin808 , thanks for your reporting. Az.1.10.0 is a very special version for Azure Stack environment which supports 2020-09-01 profile and only limited services. Do you need to use this version? If you environment is not Azure stack, please ignore this version.

**Comment by kevin808** [comment]
Thanks @dingmeng-xue , we were using Az module in Azure Function App and automatically use the latest version of 1.*, the latest update caused it broken down, and I think it should be released to 0.11.0 or something like that, rather in the branch of 1.*.

**Comment by dcaro** [comment]
@kevin808 we made some changes on the gallery that should now solve your issue and you should not download version 1.10.0 anymore. 
I wanted to mention that we are now in version 6 of the Azure PowerShell modules and I highly recommend that you consider upgrading to this version rather than staying with version 1.
Some of the changes include support for new capabilities of the Azure services, bug fixes and several security related improvements by upgrading to the MSAL library with Az version 5.

**Comment by kevin808** [comment]
Thank you @dcaro , that resolved our issue and thanks for the suggestion!
