### ISSUE TITLE
Get-AzureRmWebApp - unable to pipe into select-object

### ISSUE THREAD

**Issue by mjyeaney** [Azure/azure-powershell#1544]
Using `AzureRM.Websites`, v.1.0.2, I am unable to execute the following command:

`Get-AzureRmWebApp | select Name`

This returns an empty set of results. However, if we drill down one additional level in the object structure, the following command works:

`Get-AzureRmWebApp | foreach { $_.Name }`

Expectation is for this to work as other similar cmdlets do. For example:

`Get-AzureRmVM | select Name`

**Comment by jonsabo** [comment]
I can reproduce this on AzureRM.Websites v2.2.0. 

Looks like it's because `Get-AzureRmWebApp` outputs a list to the pipeline:
```
PS > Get-AzureRmWebApp | gm
   TypeName: System.Collections.Generic.List`1[[Microsoft.Azure.Management.WebSites.Models.Site, Microsoft.Azure.Management.Websites, Version=1.0.0.2, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35]]
```

where `Get-AzureRmVm` outputs a VM
```
PS > get-azurermvm | gm
   TypeName: Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine
```


Took a look at the differences
https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Websites/Commands.Websites/Cmdlets/WebApps/GetAzureWebApp.cs#L148-L172

https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/GetAzureVMCommand.cs#L154

Looks like `WriteObject` can take a `bool enumerateCollection` arg, so I think this line in `GetAzureWebApp`:
```
            WriteObject(list);
```
just needs to be changed to
```
            WriteObject(list, true);
```

to fix this.

**Comment by Falconwmua** [comment]
As a work around you can use: 

    PS > $list = Get-AzureRMWebApp
    PS > $list | Select Name

I agree though the Cmdlet needs to be fixed to output the collection rather than the list.

**Comment by cormacpayne** [comment]
@Nking92 @LukaszStem would you mind taking a look at this issue? I believe the solution @jonsabo has provided will fix this problem.

**Comment by Nking92** [comment]
I'll patch this bug with the provided fix in the next update. Thanks everyone for finding the bug and a fix for it.

**Comment by wangting66** [comment]
hi 
has this been patched seems to still be occuring?
![image](https://user-images.githubusercontent.com/36086041/35824165-ae0ccdaa-0aba-11e8-9c43-46833648a332.png)

**Comment by panchagnula** [comment]
Please websites-preview for this https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites 

![image](https://user-images.githubusercontent.com/13839372/37234765-9545348a-23ae-11e8-93cb-e24d49cd537d.png)
