### ISSUE TITLE
[AKS] Enable managed identity features for AKS cluster in AKS cmdlets

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#15656]
## Description of the new feature
We need to enable the managed identity features for AKS clusters in Az.AKS PowerShell module. 
Supported operations should be:
- Create AKS cluster with managed identity
- Update AKS cluster to managed identity
- Obtain the managed identity of a cluster 

More information: https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#create-an-aks-cluster-with-managed-identities

**Comment by vrapolinario** [comment]
Has this been worked on? I'm seeing different behavior for Managed Identities when using PowerShell versus Azure Portal and CLI.
Here's the scenario:
If I create a new cluster on the Azure Portal or Azure CLI, the default behavior is to set up with Managed Identities. The CLI even has an option to especially flag `--enable-managed-identity`. The implementation of the preview feature gMSA works fine after that.

If I create a new cluster using the PowerShell module, the documentation says it uses Managed Identity by default. However, the configuration of gMSA fails with the following error:
(BadRequest) Windows GMSA requires managed identity.
Code: BadRequest
Message: Windows GMSA requires managed identity.

When checking the configuration (via CLI, because the PowerShell module doesn't provide way to check that) I can see that the cluster is using a Service Principal rather than Managed Identity:
```
PS C:\GitHub\gMSA on AKS trial> az account set --subscription bd0b675c-02c7-49b2-8e49-ae963925fa6c
PS C:\GitHub\gMSA on AKS trial> az aks show -g GMSA -n ContosoCluster --query "servicePrincipalProfile"
{
  "clientId": "2ec4105c-3d66-43ff-b53d-23214a81c89e"
}
PS C:\GitHub\gMSA on AKS trial> az aks show -g GMSA2 -n ContosoCluster --query "servicePrincipalProfile"
{
  "clientId": "msi"
}
```
The cluster on the GMSA RG above was created using the AzAKS PowerShell module. The one of the GMSA2 RG was created using the Azure Portal.

This inconsistency between Azure Portal/CLI and PowerShell is not ideal for Windows admins that would prefer to use the PS module.

@justindavies and @palma21 any ideas on this?
