### ISSUE TITLE
New-AzStorageAccountSASToken Missing Parameter for Signing Key

### ISSUE THREAD

**Issue by mark7five7** [Azure/azure-powershell#15661]
## Description of the new feature

When creating a SAS token from the Azure Portal, you have the ability to select either key1 or key2 from the UI.  Currently, New-AzStorageAccountSASToken does not have that functionality.  Please add the ability to select the signing key from the cmdlet

**Comment by blueww** [comment]
@mark7five7 

Actually New-AzStorageAccountSASToken has the ability to create sas token with the chosen key.
Since to create sas token , you need first create a storage context with "New-AzStorageContext", and with this cmdlet, you need to input the key to sign the SAS token.

Like in following script, `$key` can be key1 or key2 of the account.

```powershell
$ctx = New-AzStorageContext -StorageAccountName $accountName -StorageAccountKey $key
New-AzStorageBlobSASToken -Container $containerName -Blob $blobname -Permission rw -Context $ctx
```

**Comment by mark7five7** [comment]
Thank you for the quick reply!
