### ISSUE TITLE
Missing error message in Get-AzMetric when RBAC permission is missing.

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#15829]
If the cmdlet `Get-AzMetric` is executed and the user has missing RBAC permissions to read this information, there is no error message but only an empty result.

It would be extremely helpful if an error message was issued instead.

```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.0                 Az.Monitor
```

**Comment by dingmeng-xue** [comment]
Hi @Gill-Bates , This is expected result. Conventionally, Get-Az{} cmdlet should throw existing when resourcegroup is invalid but won't throw error when resource is not existing. Due to security consideration, service normally tells client 404 error even if user cannot access resource due to permission. 

Some cmdlets or service may not follow above guideline.
