### ISSUE TITLE
Cannot execute Connect-AzAccount (in C# method) in IIS 10 Website

### ISSUE THREAD

**Issue by oka-bi-dave** [Azure/azure-powershell#15906]
Hi. I've created a Blazor Server app that needs to execute azure powershell cmdlets through a c# class, see method below..

public void ConnectAzAccount()
{

         InitialSessionState initialState = InitialSessionState.CreateDefault();
         initialState.ExecutionPolicy = Microsoft.PowerShell.ExecutionPolicy.Bypass;
         initialState.LanguageMode = PSLanguageMode.FullLanguage;
         initialState.ImportPSModule(new string[] { "Az.Accounts" });
         Runspace runspace = RunspaceFactory.CreateRunspace(initialState);
         runspace.Open();
         Pipeline pipeline = runspace.CreatePipeline();
         string sScriptCommand = "Connect-AzAccount";
         pipeline.Commands.AddScript(sScriptCommand); 
         var outputCollection = pipeline.Invoke();
     }

When i execute on my dev VM, using VS2019 & IIS express, the code above when executed will open an authentication page, which i select the azure account to login with and then I can run other cmdlets in my project without an issue.

However., when deploying the project to IIS (using folder based deployment, and setting IIS application pool (".Net CLR Version" = "No managed code") The login window never appears so cannot authenticate to azure powershell.

Any ideas would be greatly appreciated, i have even added the ApplicationPoolIdentity account to the server admin group incase this was permissions related.

additional Info - i examined an Event View application log, see output below. 

"Application: w3wp.exe CoreCLR Version: 4.700.21.35901 .NET Core Version: 3.1.18 
Description: The process was terminated due to an unhandled exception. Exception 
Info: System.OperationCanceledException: The operation was canceled. at 
System.Threading.CancellationToken.ThrowOperationCanceledException() at 
Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken 
cancellationToken) at 
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost 
host, CancellationToken token) at 
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost 
host, CancellationToken token) at 
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost 
host, CancellationToken token) at 
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host) 
at StakGenAzure.Program.Main(String[] args) in 
\Program.cs:line 
19 

Thanks

**Comment by dingmeng-xue** [comment]
Hi @oka-bi-dave , thanks for raising question to us. I don't remember others reports the issue in IIS. We have no idea about the root cause. 

You can compare your local environment and IIS environment. The issue may be narrowed down.
* Message "operation was cancelled" is vague. Please check which line it is hanging and cancelled at. If it is due to `Connect-AzAccount` execution, you can try other scripts, such as `Get-AzContext`. In addition, is there any error from PowerShell around `Connect-AzAccount`?
* The different behavior may be due to PowerShell version. You can check the version info via `$PSVersionTable` 
* Loaded assemblies is another factor. Executing `Get-AzContext` and then check loaded assemblies via PowerShell script `[System.AppDomain]::CurrentDomain.GetAssemblies()`, you will see all loaded assemblies. Comparing the result from 2 environments may give you hint.
