### ISSUE TITLE
How to improve copy file performance

### ISSUE THREAD

**Issue by Shawn-Yuen** [Azure/azure-powershell#16332]
Hi, I have met a problem about copying file in ADLS gen2 using Start-AzStorageBlobCopy. I need to copy 20000 files from one folder to another folder in same container in ADLS gen2 and it could use about more than one hour to finish.  Is there any command or code demo could do the copy file in batch or pipeline or multithread to shorten the time it used? My expectation is that it could copy 20000 files in twenty minutes.

Version: PowerShell 7.1.5
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Code I use:
foreach( $Blob in $File_list )
    {
      $Target_Blob_Name=$Path_Param + ($Blob.Name -replace $Src_Path)
      Start-AzStorageBlobCopy -SrcContainer $Src_Container_Nm -SrcBlob $Blob.Name -DestContainer $Dest_Container_Nm -DestBlob $Target_Blob_Name -Context $Storage_Context -Force
    }

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by blueww** [comment]
@Shawn-Yuen
Start-AzStorageBlobCopy  will do server side async copy. It doesn't aim for performance.
If you would like to copy the blobs faster, you can try to use [AzCopy ](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10)(by call it in PSH script), AzCopy is designed for performance.

**Comment by Shawn-Yuen** [comment]
We used Azcopy before, but I need to copy some files between different containers at the same time. Azcopy seems can't do that so we use powershell instead of azcopy. Should I use both methods depends on different situations？But honestly, I prefer use powershell cos it is much more flexible. Could you provide some suggestions on powershell coding, for example, use runspace pool to improve powershell performance. Many thanks ！！

**Comment by blueww** [comment]
@Shawn-Yuen

Could you please share more details for you scenarios?

- Does the copy inside same storage account, but in different containers? Or between different account?
- Will you copy all files in the container, or part of the files?
- The normal file size, file count in a copy?

For "I need to copy some files between different containers at the same time. Azcopy seems can't do that ", would you please share how you use AzCopy and what's the failure you meet?

Besides that, for you information `Start-AzStorageBlobCopy`  will just start copy, user normally can wait for copy finish by `Get-AzStorageBlobCopyState -Container $containerName -Blob $destBlobName -Context $ctx -WaitForComplete`.

**Comment by Shawn-Yuen** [comment]
Yeah sure.
- Does the copy inside same storage account? Or between different accounts?
   A: Same storage account.
- Will you copy all files in the container, or part of the files? Any pattern?
   A: part of them, 
   FROM: halley-etl-sl-parallel-th  202101/PAS/EGTD    TO: halley-etl-sl-p01-land	  WRK/TH/PAS/EGTD
- The normal file size, file count in a copy?
   A: The file size is diverse, the total batch of files that needed to copy are about 25000 files.

For "I need to copy some files between different containers at the same time. Azcopy seems can't do that ", would you please share how you use AzCopy and what's the failure you meet?
A: azcopy login --service-principal XXXXXXXX --application-id XXXXXXXX --tenant-id=XXXXXXXXXXX
    azcopy cp "halley-etl-sl-sit/LAND/SAP/20201229/*" "halley-etl-sl-sit/LANK/yit/Shawn_Test/"  --recursive=true

**error meesage**:INFO: The parameters you supplied were Source: 'halley-etl-sl-sit/LAND/SAP/20201229/*' of type Local, and Destination: 'halley-etl-sl-sit/LANK/yit/Shawn_Test/' of type Local
INFO: Based on the parameters supplied, a valid source-destination combination could not automatically be found. Please check the parameters you supplied.  If they are correct, please specify an exact source and destination type using the --from-to switch. Valid values are two-word phases of the form BlobLocal, LocalBlob etc.  Use the word 'Blob' for Blob Storage, 'Local' for the local file system, 'File' for Azure Files, and 'BlobFS' for ADLS Gen2. If you need a combination that is not supported yet, please log an issue on the AzCopy GitHub issues list.

**Comment by blueww** [comment]
@Shawn-Yuen 

From the [Azcopy doc](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs-copy#copy-a-directory), it looks you should set the source as a Uri of source blob Dir with SAS token, and destination should also be a Uri of dest Blob Dir. So it looks your  usage of Azcopy above is not correct. Would you like to change the source and dest to Uri and try again? (If you can't use SAS, another way is to set the source container as public and you don't need use SAS to access source Uri, but this will make the source container can be read by everyone.)

BTW, why can't user SAS? Is that OK to generate a SAS with script in the running time, and only use in copy blob, then the SAS not be record anywhere?

Besides that, since the copy is inside storage account, so the copy will finish with Start-AzStorageBlobCopy, you don't need wait for the copy finish.
And in Powershell, even you input key/Oauth credential, Powershell will genearate SAS token internally and invoke copy with the SAStoken (Since Server need sas to read source).

**Comment by Shawn-Yuen** [comment]
@blueww 
As you suggested, I generate a SAS token using SP in my code, but it raise some error. It looks like the value of the $sas_token variable have been changed when I pass to azcopy command.

Code:
$storage_context = New-AzStorageContext -StorageAccountName $storage_account_name -UseConnectedAccount
$sas_token=New-AzStorageContainerSASToken -Name "halley-etl-sl-sit" -Permission rwdl -context $storage_context
write-host $sas_token
output:
?sv=2019-07-07&sr=c&sig=lrrnLg%2BohF....................

Error:
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:d1ae26be-401e-006e-1c76-d4c60e000000
Time:2021-11-08T07:56:14.6627070Z, Details:
   Code: AuthorizationFailure
   GET https://XXXXXXXXXXX.blob.core.windows.net/halley-etl-sl-sit/LANK/yit/Shawn_Test/XXXXXXXXX_TYPE_CODE.TXT?comp=properties&restype=account&se=2021-11-08t08%3A56%3A13z&sig=-REDACTED-&ske=2021-11-08t0%3A13z&skoid=-9354-43fd1a67381b&sks=b&skt=2021-11-08t07%3A56%3A13z&sktid=7f2c1900-9fd4-4b89-91d3-79a&skv=2019-07-07&sp=rwdl&sr=c&sv=2019-07-07&timeout=901
   User-Agent: [AzCopy/10.11.0 Azure-Storage/0.13 (go1.15; linux)]
   X-Ms-Client-Request-Id: [66c7551f-1c86-483b-6a65-a3e706a5fb2a]
   X-Ms-Version: [2020-04-08]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Mon, 08 Nov 2021 07:56:14 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [66c7551f-1c86-483b-6a65-a3e706a5fb2a]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [d1ae26be-401e-006e-1c76-d4c60e000000]
   X-Ms-Version: [2020-04-08]

**Comment by blueww** [comment]
@Shawn-Yuen 

For AzCopy failures, my team doesn't own AzCopy so we might not be the best person to answer it.
Would you like to raise an issue for AzCopy in https://github.com/Azure/azure-storage-azcopy/issues?
Please indicate how the SAS is generated, and how you run AzCopy, and the failure.

Besides that, from the above error, it looks fail since try to GetAccountInformation on dest with Oauth based SAS. Per [rest API](https://docs.microsoft.com/en-us/rest/api/storageservices/get-account-information#authorization), "OAuth-based authorization via an Access Token from AAD/MSI or a User Delegation SAS is not supported with this API" So this will definately fail in server. Not sure why AzCopy call this API.

**Comment by Shawn-Yuen** [comment]
Thanks WEIWEI, I  will raise a ticket to AzCopy team then and will update this issue when I receive feedback.

**Comment by amishra-dev** [comment]
closing this issue here. Please file a new issue if you need further assistance.
