### ISSUE TITLE
[Functions] Add support to  create dotnet-isolated apps

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-powershell#16349]
### Description of the new feature

https://github.com/Azure/azure-powershell/blob/main/src/Functions/custom/FunctionsStack/WindowsFunctionsStacks.json and  https://github.com/Azure/azure-powershell/blob/main/src/Functions/custom/FunctionsStack/LinuxFunctionsStacks.json are missing options to create `dotnet-isolated` apps.

Please see https://github.com/Azure/azure-functions-ux/blob/dev/server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts#L59

cc @AnatoliB @Francisco-Gamino @anthonychu @fabiocav

**Comment by nicolashemery** [comment]
Hello,

I see that despite promoting donet-isolated, and it seemingly being supported on the CLI, it is not supported yet on powershell. 
Do you have a roadmap for it? And better an estimation of when we can expect having it ?

If not any workaround?

Thanks.

**Comment by Francisco-Gamino** [comment]
> Hello,
> 
> I see that despite promoting donet-isolated, and it seemingly being supported on the CLI, it is not supported yet on powershell. Do you have a roadmap for it? And better an estimation of when we can expect having it ?
> 
> If not any workaround?
> 
> Thanks.

Hello @nicolashemery -- I am working on enabling the New-AzFunctionApp to pull down the function app definitions for our Stacks API. When this work is completed, the user will be able to create same type of apps as the Az CLI, the VSCode Extension (vscode-azurefunctions), and the Azure Portal. For this work, we have to reimplement how the function app is created, so the schedule to release this fix will depend on whether there will be breaking changes. 

The tentative release schedule is as follows:
- If not breaking changes are introduced, the release will be in April 2023.
- Otherwise, this change will be included in the next breaking change or new Az major version release, which will be sometime in May or June 2023.

**Comment by nicolashemery** [comment]
Thanks @Francisco-Gamino  for the quick answer, any advice for a workaround in the meantime?

**Comment by Francisco-Gamino** [comment]
> Thanks @Francisco-Gamino for the quick answer, any advice for a workaround in the meantime?

@nicolashemery -- In the meantime, please use the Az CLI which supports the functionally I will enable in the `New-AzFunctionApp` cmldet.

**Comment by nicolashemery** [comment]
Thanks, in the meatime i managed the following powershell workaround if it helps other with same issue as me, after creating a DotNet application on Windows  OS  i execute the following before Publishing:

    Update-AzFunctionAppSetting -ResourceGroupName $ResourceGroup.ResourceGroupName -Name $FunctionApp.Name -AppSetting @{"FUNCTIONS_WORKER_RUNTIME" = "donet-isolated"}

**Comment by Francisco-Gamino** [comment]
> Thanks, in the meatime i managed the following powershell workaround if it helps other with same issue as me, after creating a DotNet application on Windows OS i execute the following before Publishing:
> 
> ```
> Update-AzFunctionAppSetting -ResourceGroupName $ResourceGroup.ResourceGroupName -Name $FunctionApp.Name -AppSetting @{"FUNCTIONS_WORKER_RUNTIME" = "donet-isolated"} -Force -Verbose
> ```

@nicolashemery --  Yes, that works. If your app is targeting .Net 7, please update this `netFrameworkVersion` property to `'v7.0'` in the site config as well. To do so, run the following:

```powershell
$SubId = "<your sub id>"
$ResourceGroupName = "<your resource group name>"
$AppName = "<your app name>"

Set-AzContext -Subscription $Subscription | Out-Null

Set-AzResource -ResourceId "/subscriptions/$SubId/resourceGroups/$ResourceGroupName/providers/Microsoft.Web/sites/$AppName/config/web" -UsePatchSemantics -Properties @{ netFrameworkVersion = 'v7.0' } -Force

# Restart your app for the version changes to take effect
Restart-AzFunctionApp -Name $AppName -ResourceGroupName $ResourceGroupName -Force

# Verify that version was updated
$app = Get-AzFunctionApp -Name $AppName -ResourceGroupName $ResourceGroupName 
$app.SiteConfig.NetFrameworkVersion 
```

**Comment by davidpeden3** [comment]
>If not breaking changes are introduced, the release will be in April 2023.
Otherwise, this change will be included in the next breaking change or new Az major version release, which will be sometime in May or June 2023.

hey @Francisco-Gamino, i just ran into this issue and am running the [latest version](https://www.powershellgallery.com/packages/Az/10.1.0) of `Az` (`10.1.0`) which was released just a couple of days ago.

<img width="672" alt="image" src="https://github.com/Azure/azure-powershell/assets/1190710/1eab7308-7d2a-4939-831c-e97316d34f9f">

The error is:

`Runtime 'dotnet-isolated' is not supported. Currently supported runtimes: 'DotNet', 'Java', 'Node', 'PowerShell', 'Python'. For supported languages, please visit
     | 'https://docs.microsoft.com/azure/azure-functions/functions-versions#languages'.`

it's now July 2023. can we get an update on the release schedule?

thanks.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest release.
