### ISSUE TITLE
The Get-AzVM doesn't have consistent output

### ISSUE THREAD

**Issue by NickDorak** [Azure/azure-powershell#16346]
### Description

The Get-AzVM returns different results depending if the ResourceGroupName parameter is included. This is undocumented and confusing to users. The command should return at least same column names for predictable results. 
i.e.
Get-AzVM -Name "VMName1" -ResourceGroupName "NGName2" -Status | FL
Get-AzVM -Name "VMName1" -Status | FL

### Issue script & Debug output

```PowerShell
n/a
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.65
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.65
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.2.1      Az
```

### Error output

```PowerShell
No errors
```

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by PramodValavala-MSFT** [comment]
@NickDorak Without the resource group name, you can't really pinpoint a particular VM (since they are not required to be unique across resource groups). The docs cover [this scenario which allows to filter through all available VMs in a subscription](https://docs.microsoft.com/en-us/powershell/module/az.compute/get-azvm?view=azps-6.6.0#example-6--get-all-virtual-machines-using-filtering).

**Comment by PramodValavala-MSFT** [comment]
@NickDorak Just following up here... Hope my previous comment clears things up.

**Comment by NickDorak** [comment]
@PramodValavala-MSFT, your response doesn't explain why **totally** different results are returned.
I understand that you may not be able to pinpoint a single resource, but in the cause where there is a unique resource and the one item is returned, the information is not consistent.

**Comment by PramodValavala-MSFT** [comment]
@NickDorak Looks like this is [by design](https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs#L106). The `-Status` flag includes extra information when able to pinpoint a particular VM otherwise it just fetches the `PowerState` for the VMs return in the list (so just the `PowerState` for the one VM returned)

**Comment by NickDorak** [comment]
> @NickDorak Looks like this is [by design](https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs#L106). The `-Status` flag includes extra information when able to pinpoint a particular VM otherwise it just fetches the `PowerState` for the VMs returned in the list (so just the `PowerState` for the one VM returned)

Event with the `-Status` flag, both commands still return completely different fields. It's like as if two different PS commands are being used. 
In all scenarios tested, only a particular VM is returned as we are using a unique VM name.

**Comment by PramodValavala-MSFT** [comment]
@NickDorak Apologies for the long delay here! I was taking another look at this and here are my findings.

1. These two commands return the same for me

```ps1
Get-AzVM -Name <VM_NAME> -ResourceGroupName <RG_NAME> | FL
Get-AzVM -Name <VM_NAME> | FL
```

2. The `-Status` flag causes the cmdlet to return [the instance view of a VM](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.compute.models.psvirtualmachineinstanceview) as mentioned in [the reference doc for the cmdlet](https://docs.microsoft.com/en-us/powershell/module/az.compute/get-azvm?view=azps-7.4.0) when using both the resource group and name of the VM but just adds the power state when using just the name since its a list operation (even if in your case there is just one VM in the list)

Hope this clears things up
