### ISSUE TITLE
[Doc]: Import-AzureRMApiManagementApi

### ISSUE THREAD

**Issue by parkybyang** [Azure/azure-powershell#16372]
### Description

-SpecificationFormat   parameter,
acceptable value should include "OpenApi" and "OpenApiJson".

**Comment by dcaro** [comment]
@parkybyang thanks for reporting this issue, the accepted values for the `-SpecificationFormat` parameter are up to date in the reference documentation of the [Az.ApiManagement module](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/import-azapimanagementapi?view=azps-6.6.0). 

Since the [AzureRM modules will retire by February 2024](https://azure.microsoft.com/en-us/updates/update-your-scripts-to-use-az-powershell-modules-by-29-february-2024/) we are limiting our effort on those modules to critical fixes.
