### ISSUE TITLE
[Doc]: Status of Update-AzCosmosDBAccount

### ISSUE THREAD

**Issue by BMichaelJ** [Azure/azure-powershell#16507]
### Description

Doing the migration in PowerShell, it would be nice to see the status with Powershell also, the documentation includes the az commands under the PowerShell chapter.
If there is no PowerShell support to check the status this could be clarified to avoid confusion,

https://docs.microsoft.com/en-us/azure/cosmos-db/migrate-continuous-backup#powershell

Also opened here

https://github.com/MicrosoftDocs/azure-docs/issues/84451

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by Karishma-Tiwari-MSFT** [comment]
The [doc](https://docs.microsoft.com/en-us/azure/cosmos-db/migrate-continuous-backup#check-the-migration-status) mentions - 

![image](https://user-images.githubusercontent.com/20851144/144025849-0d5c472f-ec61-45fe-9635-fdddaaadeceb.png)

Please let me know if you are looking for something else.

**Comment by BMichaelJ** [comment]
Well, that is the az command and I was looking for the PowerShell one.
I have PSVersion 7.1.3 installed on intended build machine and I get this error.

"az: The term 'az' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again"

So instead of trying to fix my build machine I was hoping there would be a PowerShell version of the command.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for sharing the details. 

Can you please confirm the version of Azure CLI you have?
-If you don’t have CLI, [install](https://docs.microsoft.com/en-us/cli/azure/) the latest version of Azure CLI or version higher than 2.26.0.
-If you already have Azure CLI installed, use az upgrade command to upgrade to the latest version.
-Alternatively, user can also use Cloud Shell from Azure portal.

**Comment by Karishma-Tiwari-MSFT** [comment]
Since this is resolved here : https://github.com/MicrosoftDocs/azure-docs/issues/84451
I will now close this issue. Thanks for bringing this to our attention.

Solution for reference for others :
The "BackupPolicy" object from the "Get-AzCosmosDBAccount -ResourceGroupName {resourceGroupName} -Name {databaseAccountName}" command shows the type of backup mode supported by the account. However, this command currently doesn't expose the Migration state as CLI does. It will be released with the next version of PowerShell that could happen in late Jan or Feb.

I noticed an issue with the doc, the migration status check section should be in CLI and not PS. I moved the content in the above PR. we will close this issue now.
