### ISSUE TITLE
[Feature]: Add a parameter to allow changing API version for Az powershell commands

### ISSUE THREAD

**Issue by yurych** [Azure/azure-powershell#16573]
### Description of the new feature

It seems not all Azure environments support API versions that are internally used by Az powershell commands.  
It would be helpful to have a command line parameter to override the default API version.
Please see [this stack overflow question](https://stackoverflow.microsoft.com/questions/285048) for more details.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. API version cannot be changed because the input and output vary across API versions. It makes deserialization and serialization impossible. The workaround is user can use Invoke-AzRestMethod to manage resource using expected API version.  

Regarding question asked on Stackoverflow, it should be a bug in service module. It should not expose unsupported API version. Please create a bug if it is till not work.
