### ISSUE TITLE
disable send-azpredictorrating in results az.tools.predictor

### ISSUE THREAD

**Issue by brwilkinson** [Azure/azure-powershell#16586]
### Description

I was wondering what is the setting to disable this?

![image](https://user-images.githubusercontent.com/3605266/144942941-8f08f251-6a08-4c77-96f1-173032c25d3e.png)

**Comment by dcaro** [comment]
@brwilkinson we introduced this in the preview but there is no setting to remove the message.  We will remove this in the upcoming preview.

**Comment by brwilkinson** [comment]
Thank you @dcaro

**Comment by craiglandis** [comment]
This broke all prediction for me, not just Az prediction. With Az.Tools.Predictor loaded I only ever see a single prediction - for **Send-AzPredictorRating**. Adding a feedback mechanism that breaks the module is not a great way to solicit feedback. :-)

I've uninstalled it for now. Since it's typically in use, I close all PS sessions and run this from CMD - 

pwsh -noprofile -nologo -command Uninstall-Module -Name Az.Tools.Predictor

**Comment by brwilkinson** [comment]
@craiglandis what pwsh version are you on and which version of psreadline do you have installed?

**Comment by craiglandis** [comment]
> @craiglandis what pwsh version are you on and which version of psreadline do you have installed?

PS 7.2.1,  Az.Tools.Predictor 0.5.0

**Comment by brwilkinson** [comment]
Script     2.2.0      beta4      PSReadLine     ?

```powershell
    if ( $PSVersionTable.psversion.Major -ge 7  -and $PSVersionTable.PSVersion.Minor -ge 2)
    {
        Enable-AzPredictor
        Set-PSReadLineOption -PredictionViewStyle ListView
        Set-PSReadLineOption -PredictionSource HistoryAndPlugin
    }
```

Is this what you have?

**Comment by kceiw** [comment]
@craiglandis Can you please help us to improve the qualify by giving us some examples like what you types when you see it's broken?

Az Predictor only shows the suggestions based on the command history and the command you're typing (The commands are Az commands). If there are no suggestions, it doesn't show anything. It gets the suggestions from our server. So it also requires Internet connection. "Send-AzPredictorRating" doesn't require Internet connection and is always shown as the last item in the suggestion list. So even if there are no suggestions for what you types or there is no Internet connection, we still show this cmdlet.

I ask for your input because I would like to try it at my side and also trying to see if we have any gaps in the model we use for the suggestions.

**Comment by brwilkinson** [comment]
Hi @dcaro It seems the survey prompt is having more impact that I initially thought.

There has been an issue over on PowerShell/vscode-powershell#3701 that relates to the survey functionality.

It seems the eventsubscriber as below is causing exceptions within PsReadline and powershell editor services within VSCode.

```powershell
Get-EventSubscriber -Force  | foreach action | foreach command

                if ([Microsoft.Azure.PowerShell.Tools.AzPredictor.AzPredictorData]::ShowSurveyOnIdle) {
                    [Microsoft.Azure.PowerShell.Tools.AzPredictor.AzPredictorData]::ShowSurveyOnIdle = $False
                    Write-Host ''
                    Write-Host ''; Write-Host `Survey: -ForegroundColor $Host.PrivateData.VerboseBackgroundColor -BackgroundColor $host.PrivateData.VerboseForegroundColor -NoNewLine; Write-Host ' How was your experience using the Az Predictor module?'
                    Write-Host ''
                    Write-Host 'Run ' -NoNewline; Write-Host Open-AzPredictorSurvey -ForegroundColor $Host.PrivateData.VerboseBackgroundColor -BackgroundColor $host.PrivateData.VerboseForegroundColor -NoNewline; Write-Host ' to give us your feedback.'
                    Write-Host ''
                    Write-Host '(Use "Ctrl + C" to return to the prompt)'
                }
```

**Comment by brwilkinson** [comment]
for a workaround I am deleting the event subscriber directly after the AzPredictor is loaded.

```powershell
    if ( $PSVersionTable.psversion.Major -ge 7 -and $PSVersionTable.PSVersion.Minor -ge 2)
    {
        Enable-AzPredictor
        Set-PSReadLineOption -PredictionViewStyle ListView
        Set-PSReadLineOption -PredictionSource HistoryAndPlugin
        Get-EventSubscriber -Force -SourceIdentifier PowerShell.OnIdle | Unregister-Event -Force
    }
```

**Comment by brwilkinson** [comment]
Please ... please ... please ... please... please... please... please... 

please can we remove this feature ?

How many people have sent a ratings request ?

![image](https://user-images.githubusercontent.com/3605266/160700483-eb0c62c5-d439-4335-9152-2ee4508af1cc.png)

This is EXTREMELY frustrating.

_I can only say that if I walked into your Office and put a quite distracting object on your clean office desk that takes up quite a large amount of space "of your workspace" so that you had to constantly look at it, how frustrating would that be?_

or at least make it configurable or time based?

I gave a rating and it still shows up ?

![image](https://user-images.githubusercontent.com/3605266/160701053-afc2816c-015f-4560-9edf-b82fa30e3c8d.png)

**Comment by dcaro** [comment]
@brwilkinson this additional line was an experiment that we did to understand better how to prompt users for feedback in a command line tool.
We will remove this in the upcoming release of Az.Tools.Predictor.

**Comment by brwilkinson** [comment]
Thank you @dcaro 🙏🏼

**Comment by brwilkinson** [comment]
great news

![image](https://user-images.githubusercontent.com/3605266/164091472-c11434cb-1c8a-4272-b465-72dc81b185b8.png)

![image](https://user-images.githubusercontent.com/3605266/164091412-d653cf35-8da6-4653-85a1-f09cd1b5d632.png)

Thanks all.
