### ISSUE TITLE
Mark New-AzWebAppContainerPSSession as obsolete

### ISSUE THREAD

**Issue by jvano** [Azure/azure-powershell#16646]
### Description

We are no longer recommending customers to use the Win-RM capability as we added a Web Console in the portal and in the advanced Web Console in the “Advanced Tools” section of the portal which is better and more secure option. We are planning on stop supporting the Win-RM capability in the future.

For more information on the Web Console:
https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-windows#from-the-kudu-console

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
N/A
```

### Error output

```PowerShell
N/A
```

**Comment by panchagnula** [comment]
@dingmeng-xue looks like we need to deprecate this command with no replacement - what is the recommended process for this? Should we just wait for the next breaking change milestone?

**Comment by dingmeng-xue** [comment]
@panchagnula , if the deprecation is not due to bug, we should introduce the breaking change till next major release . You team can add custom attribute on that cmdlet and user will see warning message about upcoming change. https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-definition.md#cmdlets

**Comment by Kotasudhakarreddy** [comment]
@dingmeng-xue Thanks for your suggestion. For now we will be introducing a `[CmdletDeprecation()]` attribute untill next breaking change release.

**Comment by jvano** [comment]
👍
