### ISSUE TITLE
Clear Run Command state in VM

### ISSUE THREAD

**Issue by SirMrDexter** [Azure/azure-powershell#16936]
### Description

After provisioning VM from a custom Image, we noticed that the output from Run Commands were in correct. On closer inspection, we noticed that the version of RunCommand plugin inside the Image was 1.1.8 and it got updated to 1.1.9. Looks like update operation happens on its own after the VM is created and it resets the index.

But this doesn't clear the previous run/status data. So any command we run after the plugin update, returns the output for corresponding command that ran before the plugin update.

Is there any way to clear the plugin state to ensure that the output is consistent?

**Comment by SirMrDexter** [comment]
Temporary workaround we managed to figure out is to delete the contents of `C:\Packages\Plugins\Microsoft.CPlat.Core.RunCommandWindows\1.1.*\Status` folders right after the VM create command is complete.

**Comment by avirishuv** [comment]
hi @amjads1 would you please take a look at this?

**Comment by Drewm3** [comment]
Moving this one over to @nikhilpatel909.

**Comment by nikhilpatel909** [comment]
This issue happened because customer haven’t removed the extension prior to creating a custom image . Customers need to remove all the extensions prior to creating a custom image. Listed below are the command to remove RunCommand extension:

For Windows PowerShell command:
•	Invoke-AzVMRunCommand -ResourceGroupName '<myResourceGroup>' -Name '<myVMName>' -CommandId 'RemoveRunCommandWindowsExtension'

For Linux command
•	"RemoveRunCommandLinuxExtension"

I am also reviewing a custom image create documentation, If the guidance is in the documentation.

**Comment by nikhilpatel909** [comment]
@SirMrDexter , Were you able to resolve the issue using above commands provided?

**Comment by nikhilpatel909** [comment]
Closing issue fix has been provided, See May 19 Comments
