### ISSUE TITLE
Connect-AzAccount uses Warning stream to convey Sign-In URL and token

### ISSUE THREAD

**Issue by nyanhp** [Azure/azure-powershell#16963]
### Description

Connect-AzAccount uses Warning stream to convey Sign-In URL and token. In sessions that choose to set the WarningActionPreference to SilentlyContinue or Ignore, this means that their script will hang indefinitely without any indication.

To me this is not the ideal behavior. The login information should not be a warning. The cmdlet should either attempt to detect if the Warning stream is ignored or silenced and display the message, or another, more appropriate way of conveying this information should be used.

### Issue script & Debug output

```PowerShell
Connect-AzAccount -UseDeviceAuthentication -WarningAction SilentlyContinue
Write-Host "I am never to be seen"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Script     2.7.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...
```

### Error output

```PowerShell
No error, just no output at all. Console hangs indefinitely, until CTRL-C is pressed to cancel the login.
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It is good question. I believe the original design of using warning instead of information helps user to pay more attention on message with URL. I don't think it's good idea to downgrade message level from warning to information. But we should check warning preference and show message as information if user ignore/skip the warning.

@dcaro what's your thought?

**Comment by davidsandbrand** [comment]
To add some details from a different perspective, this is an even more obvious problem when one set of credentials is connected to multiple tenants.  In this case, after the Connect-AzAccount command runs, it can output a large number of warning such as:

- WARNING: TenantId '[REDACTED TENANT ID]' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.

- WARNING: Unable to acquire token for tenant '[REDACTED TENANT ID]' with error 'You must use multi-factor authentication to access tenant [REDACTED TENANT ID], please rerun 'Connect-AzAccount' with additional parameter '-TenantId [REDACTED TENANT ID]'.'

- WARNING: Unable to acquire token for tenant '[REDACTED TENANT ID]' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user [REDACTED LOGIN EMAIL ADDRESS]. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'

It is a legitimate need to be able to hide these types of messages, but the only way of doing so also hides the code requested to authenticate.


Or put another way, the device login code is obviously NOT an unexpected warning, given the presence of the 'UseDeviceAuthentication' switch.  This output should not be output as an information, warning, or error.  It should simply be output.

**Comment by dingmeng-xue** [comment]
@davidsandbrand , those warning message were added due to various reasons. Some Azure PowerShell user are not familiar to default behavior and it made user fault when they were unaware of what happened. 

You know PowerShell is object-oriented scripting language. It's not good to make login message as output, because it will interfere with pipeline operation.

**Comment by davidsandbrand** [comment]
@dingmeng-xue,

Yes, I know that PowerShell is object-oriented, and yes I do understand how output could interfere with a pipeline operation, but what I don't understand **and I would like you to explain to me**, is how using a command-line switch (-UseDeviceAuthentication) that is specifically documented as not accepting pipeline input could possibly interfere with a pipeline operation?

To put it another way, the -UseDeviceAuthentication switch **requires** human interaction, and the specifically requested code that is generated as part of the process is meant for a human to use.  So then why are you pointing at a pipeline operation as being the reason you cannot make this command work in the way that everyone expects it to work?

It seems like the answer to this question is because this poorly planned implementation of using an error code to write output is because you don't want the few people who are inexperienced in PowerShell and uninformed on this specific command to not get upset.

What sense does that make?  How about you make this command work the way it should, for the people who **are** experienced and knowledgeable?

The authentication code is **NOT** a warning, and silencing warnings should **NOT** eliminate this command-line switch from being usable - which is functionally what you have implemented and are defending as a good design decision.

I await your explanation.

**Comment by dingmeng-xue** [comment]
HI @davidsandbrand ,

You can see the current output of `Connect-AzAccount` is `PSAzureProfile`. If message is printed out as output as you mentioned, it means this cmdlet will have 2 types of output, `String` and `PSAzureProfile`. PowerShell is strong type language.  That ambiguity makes user cannot predict its output. Another problem is output becomes array like below example. 

Pipeline operation I mentioned meant output. User can use output of `Connect-AzAccount` as the input of other cmdlets or their custom functions. So, we seldom change the output type of high usage cmdlet.

```
function Test-MyCode {

    Write-Output "To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code 123 to authenticate."
    # use it as a dummy. The output type is different from Connect-AzAccount
    Write-Output Get-AzContext
}
```

**Comment by davidsandbrand** [comment]
@dingmeng-xue,

I see what you're saying, and perhaps you misunderstood me.  I wasn't suggesting that the displayed code be an output **_object_**; I was suggesting it be written to screen, for the human that requested it, needs it, and is expecting it.

The device auth code is not part of the PSAzureProfile class, regardless of how this code gets written to screen. The device auth code continues to be irrelevant to the final output (since it's not relevant to the context, is it?). By the very nature that this authentication method must involve a human, the object-oriented aspect of the language is irrelevant to the code itself.

It's not an error, and it's not a warning.  Potentially it could be considered an information output, but since it was requested by the user, this output is expected and **should not be able to be silenced** - that's the point here. Writing it to screen using an info output could also be silenced, which should not be possible.

Wrapping the device auth code in a warning message offers no benefit and simultaneously creates functional problems.

**Comment by nyanhp** [comment]
@dingmeng-xue do you know if there is an update to this issue? The current module versions still show this behaviour.

A change from Warning to Host would already be very helpful for this message, even if Host messages could potentially be suppressed with an InformationAction Ignore.

**Comment by isra-fel** [comment]
Two approaches that I'll evaluate:
1. A config that disables warning messages of `Connect-AzAccount`.
    - Selected warning types or all of them?
    - Can the config be applied to other cmdlet? Other module?
2. Change the device auth message from warning to informational. 
    - Technical challenges - WriteInformational isn't available in authenticator.

**Comment by davidsandbrand** [comment]
@isra-fel , 

I maintain that an information output is inappropriate because the displaying of this code is not a **_result of_** the command, but rather an expected **_part of_** the command.

Do any other commands interact with a user through an informational alert as part of its normal operation?

Put another way: When shown, this code was requested for the immediate use of a human. It never needs to be captured in code.  It's being displayed now just in the wrong method, so why would simply displaying it be a problem?

**Comment by o-l-a-v** [comment]
@davidsandbrand 

Microsoft Graph module sends it to the output, but then people will complain about that too:

* https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1403

I think information makes sense here.

But consistency between Microsoft modules I'd place even higher.
