### ISSUE TITLE
Get-AzKeyVault should not use List API twice when only vault name is specified

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#17186]
### Description

When vault name is specified, Get-AzKeyVault doesn't call Keyvault API but ARM API `https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resources?$filter=resourceType eq 'Microsoft.KeyVault%2Fvaults'&api-version=2016-09-01`

The shortage is client filtering is not accurate when query result is big and it increases additional burden to ARM.

In addition, it calls ARM API twice. It seems once should be sufficient.

### Issue script & Debug output

```PowerShell
NA
```

### Environment data

```PowerShell
NA
```

### Module versions

```PowerShell
The latest
```

### Error output

```PowerShell
NA
```

**Comment by BethanyZhou** [comment]
Correct, `Get-AzKeyVault` should not call ARM API twice. But once is necessary when only vault name is specified.

- Vaults_Get operation requires parameter resourceGroupName and vaultName both. 
- When only vault name is specified, `Get-AzKeyVault` call ARM API to query the resource group for specified vault. 
- If successes, `Get-AzKeyVault` will call Vaults_Get to get key vault's further information. Otherwise, it call ARM API to get general information. I think this time is unnecessary. First call for ARM API is enough.

Will fix it.

**Comment by FabianGonzalez-MSFT** [comment]
> Correct, `Get-AzKeyVault` should not call ARM API twice. But once is necessary when only vault name is specified.
> 
> * Vaults_Get operation requires parameter resourceGroupName and vaultName both.
> * When only vault name is specified, `Get-AzKeyVault` call ARM API to query the resource group for specified vault.
> * If successes, `Get-AzKeyVault` will call Vaults_Get to get key vault's further information. Otherwise, it call ARM API to get general information. I think this time is unnecessary. First call for ARM API is enough.
> 
> Will fix it.

@BethanyZhou I think there's another issue apart from the API being called twice. It looks like when **Get-AzKeyVault** is run without the ResourceGroupName it executes a Vaults_Get request (which according to your explanation is expected), however, it looks like PS is not able to handle paging... If the customer has too many KVs in the subscription, API response will contain a limited number of Key Vaults on the 1st page with a NextLinkURL to continue to the rest of pages, PS should be able to navigate among the pages and find the cutomer's inputted KV.
Current behavior is that if you run the command with only the KeyVault's name and not the ResourceGroupName, if the KV inputted by cthe customer was not listed on the first page of the Service's response, the command will directly return nothing/empty as the result just because the requested KV wasn't on the first page and PS doesn't seem to keep looking the NextLinkURL.

**Comment by BethanyZhou** [comment]
Thanks for reminding me. I'm fixing the paging issue. We have identified its root cause. will provide a engineer build FOR.

**Comment by BethanyZhou** [comment]
Thanks for reminding me. I'm fixing the paging issue. We have identified its root cause. 

There are our internal engineer builds for fixing this issue. Could you access these packages and let customer to try these new packages whether fix the paging issue?
https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.7.2.nupkg
https://azposhpreview.blob.core.windows.net/public/Az.KeyVault.4.2.1.nupkg

Followings are the way to install module by packages.

## Registering the Repository

To install your module from the .nupkg file provided in the pkgs folder, you will need to create a local PowerShell repository that points at the pkgs folder.

You can create a new repository by running the following command:

```powershell
Register-PSRepository -Name LocalRepository -SourceLocation {{pathToPkgsFolder}} -PackageManagementProvider NuGet -InstallationPolicy Trusted
```

After registering your repository, you can ensure that it was created by running `Get-PSRepository` and verifying that your repository appears and points at the appropriate folder containing the .nupkg files.

## Installing the Module

To install the module, you will need to run the following command:

```powershell
Install-Module -Name {{moduleName}} -Repository LocalRepository 
```

**Comment by BethanyZhou** [comment]
Close as resolved.
