### ISSUE TITLE
Get-AzResource doesn't show all resources

### ISSUE THREAD

**Issue by florinangelescu** [Azure/azure-powershell#17336]
### Description

Get-AzResource doesn't show all resources in a given resource group.
No filters were added on the cmdlet. When going to Azure portal GUI, we can see all resources, but the cmdlet doesn't show everything.
We noticed especially what web apps are missing.

### Issue script & Debug output

```PowerShell
Get-AzResource -ResourceGroupName $ResourceGroupName
```

### Environment data

```PowerShell
Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.19041.1320                                  
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.19041.1320                                 
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     2.7.2      Az.Accounts                         {Add-AzEnvironment...
Script     5.3.1      Az.Resources                        {Export-AzReso
```

**Comment by dingmeng-xue** [comment]
@florinangelescu , how many resources are under that resource group?  Could you share the request to us? You can get it from console after setting $DebugPreference = "Continue"

**Comment by brianstringfellow** [comment]
I have been seeing a similar problems with various other resources, such as storage accounts and virtual networks. The problem typically occurs for a few hours after the resources have been created. I have a support ticket open with Microsoft and the support engineer told me that the problem that I am seeing is due to replication delays between ARM regions.

In the following screen capture, I query for resources using two different cmdlets. The call with `Get-AzResource` does not show the recently created storage account `zzbrian` whereas the call with `Get-AzStorageAccount` does.
![image](https://user-images.githubusercontent.com/22823524/158181907-78cba45e-e90a-473f-b89c-a1534255b980.png)

The Azure engineer explained that the reason the call to to `Get-AzStorageAccount` works in this case is because it is querying the resource provider directly instead of the ARM. The part that really confused me was when I limited the query to search by resource group name, then the call to `Get-AzStorageAccount` no longer worked.
