### ISSUE TITLE
[Feature]: Get-AzRecoveryServicesBackupContainer does not currently support container type sqlagworkloadcontainer

### ISSUE THREAD

**Issue by SQLCanuck** [Azure/azure-powershell#17720]
### Description of the new feature

SQL Server Availability Group backups when configured utilize a container type named **sqlagworkloadcontainer**, however the module currently does not allow specifying this type of container.

### Proposed implementation details (optional)

In the module's Container parameter, add **sqlagworkloadcontainer** as a valid container type.

**Comment by adityabalaji-msft** [comment]
Thanks for reaching out. Looking into this

**Comment by SQLCanuck** [comment]
Thanks @adityabalaji-msft !

**Comment by adityabalaji-msft** [comment]
Hi @SQLCanuck - just to make sure that I understood the issue correctly - is there currently a SQL AG backup scenario which is getting blocked/throwing errors due to the sqlAGworkloadcontainer value not present? 
Or is it more of a suggestion to make the command experience better? 

If it is the latter, could you also share an example of how the updated command would look like?

**Comment by SQLCanuck** [comment]
Hi @adityabalaji-msft,
Currently if I try to specify a container type of sqlAGworkloadcontainer the following error is given:

![image](https://user-images.githubusercontent.com/38919668/162765045-c0d95b03-893d-4047-b054-9fd91724d0b8.png)

However, this does seem to be the container type used for SQL AG groups as it can be viewed in the container Id information.

![image](https://user-images.githubusercontent.com/38919668/162765408-7a29f638-45e5-4588-bb0d-067d4c39392f.png)

**Comment by SQLCanuck** [comment]
@adityabalaji-msft 

If this feature request is completed, the following command would be possible:

Get-AzRecoveryServicesBackupContainer -ContainerType sqlagworkloadcontainer -Status Registered -FriendlyName $AgName -VaultId $vault.ID

**Comment by hiaga** [comment]
@SQLCanuck, this is by design as we currently do not include SQLAGs as part of the Get-AzRecoveryServicesBackupContainer command and we currently do it via Get-AzRecoveryServicesBackupprotectableItem command. This is in accordance with the backup REST APIs where we do not get SQL AG containers in Get containers API. @Daya-Patil can take a call if we need to change this design.

**Comment by Daya-Patil** [comment]
no @hiaga For now we will keep it as is. Will look forward for more customer requirement on this and consider based on that

**Comment by Daya-Patil** [comment]
Will evaluate based on feedback.
