### ISSUE TITLE
Azure PowerShell 1.2.0 - Missing Shortcuts

### ISSUE THREAD

**Issue by AErmie** [Azure/azure-powershell#1773]
After installing version 1.2.0, the Azure PowerShell entry is missing from the Search results, and no longer appears in the All Apps list.

The only work-around is to use the normal PowerShell and use Import-Module Azure. 

<img width="511" alt="capture" src="https://cloud.githubusercontent.com/assets/10376796/12828625/ed6823f8-cb53-11e5-9b3d-daeb69a549b1.PNG">

**Comment by timoschwarte** [comment]
As far as I know, you should not need to run `Import-Module Azure`, modules are loaded automatically. I can run all Azure cmdlets directly from the "normal" PowerShell after this latest update. I can confirm though, that the Azure PowerShell start menu entry disappears with 1.2.0, and this was confusing at first, but I believe it is "by design".

**Comment by AErmie** [comment]
Thanks Tim.
If there is some way we can get confirmation that this is "by design" and that the Azure modules are loaded automatically in the "normal" PowerShell, then I'll make an update on my post about this.

Thanks for the info.

**Comment by markcowl** [comment]
@AErmie @timoschwarte This is, indeed by design.  Since both azure and azurerm modules are in the PSModulePath, so that they are automatically loaded in any PowerShell or PowerShell ISE session,  and since we are ensuring the global ExecutionPolicy, there is no longer any real reason for the AzurePowerShell shortcut, so it was removed.

**Comment by kuangweizhang** [comment]
Please update document for this change:
https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/
