### ISSUE TITLE
Set-AzAlertProcessingRule doesn't support 24-hour clock

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#17762]
### Description

Due to below code, the input data time format doesn't support 24-hour clock.

https://github.com/Azure/azure-powershell/blob/3535d15724a49d7ab908cc4d321608b3c2281e0c/src/AlertsManagement/AlertsManagement/ActionRuleCommands/SetAzureAlertProcessingRule.cs#L663

### Issue script & Debug output

```PowerShell
PS C:\Dev >  Set-AzAlertProcessingRule -ResourceGroupName "dixue" -Name "dixuealertprocrule" -Scope /subscriptions/xxxxxxxx-3399-4e19-88eb-0975f02ac87f/resourceGroups/dixue -Enabled "True" -AlertProcessingRuleType "RemoveAllActionGroups" -ScheduleStartDateTime "2022-05-01 14:51:59" -ScheduleEndDateTime "2022-05-02 16:51:59"
```

### Environment data

```PowerShell
All environments
```

### Module versions

```PowerShell
0.4.0                 Az.AlertsManagement
```

### Error output

```PowerShell
Set-AzAlertProcessingRule: Invalid ScheduleStartDateTime Format
```

**Comment by dolauli** [comment]
According to [CSDN](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings?redirectedfrom=MSDN), we should use "HH" instead of "hh" in the format string. And besides, Following code in [here ](https://github.com/Azure/azure-powershell/blob/main/src/AlertsManagement/AlertsManagement/ActionRuleCommands/SetAzureAlertProcessingRule.cs#L676-L682)looks another bug. Shall we check ScheduleEndDateTime here instead of ScheduleStartDateTime ?
```
            if (ScheduleEndDateTime != null)
            {
                if (System.DateTime.TryParseExact(ScheduleStartDateTime, format, CultureInfo.InvariantCulture, DateTimeStyles.None, out outDateTime) == false)
                {
                    throw new PSInvalidOperationException("Invalid ScheduleStartDateTime Format");
                }
            }
```

**Comment by dingmeng-xue** [comment]
Thanks. Checking ScheduleEndDateTime should be better.

**Comment by dingmeng-xue** [comment]
It will be available on April 26. Close it now.
