### ISSUE TITLE
New-AzureRmResourceGroupDeployment errors on successful deployment

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#1801]
New-AzureRmResourceGroupDeployment errors on successful deployment
If you deploy templates
https://github.com/Azure/azure-quickstart-templates/tree/master/301-multi-vmss-linux
or 
https://github.com/Azure/azure-quickstart-templates/tree/master/301-multi-vmss-windows
like this
PS C:\WINDOWS\system32> $p=New-AzureRmResourceGroupDeployment -Name stan -ResourceGroupName TestRG -TemplateFile "D:\ARM
TEST11\BadError\301-multi-vmss-linux\azuredeploy-modified.json" -TemplateParameterFile "D:\ARMTEST11\BadError\301-multi-
vmss-linux\azuredeploy.parameters-modified.json" -Force -ErrorAction SilentlyContinue -ErrorVariable DeploymentError

An error occurs. On the portal the deployment says it succeeded. 
PS C:\WINDOWS\system32> $DeploymentError
New-AzureRmResourceGroupDeployment : Object reference not set to an instance of an object.
At line:1 char:4
+ $p=New-AzureRmResourceGroupDeployment -Name stan -ResourceGroupName T ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

**Comment by markcowl** [comment]
@slavish  Ow, a null ref.  Adding in the product team to evaluate.

**Comment by vsilgalis-rise** [comment]
Getting a similar problem with a test script deploying 3 VMs, the main thing in common is the nested deployment templates for creating the VMs, wondering if something happens when a successful run of the nested template returns

VERBOSE: 9:21:26 AM - Resource Microsoft.Compute/virtualMachines/extensions 'rstestdev1/scripts' provisioning status is succeeded
New-AzureRmResourceGroupDeployment : Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -Name testdeploy -ResourceGroupNam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand
 
DEBUG: 9:21:31 AM - NewAzureResourceGroupDeploymentCommand end processing.

**Comment by ravbhatnagar** [comment]
Thanks for reporting this. We will investigate this further.

**Comment by vsilgalis-rise** [comment]
Changing the API version for the Microsoft.Resources/Deployments node fixed this issue for me.  I was using 2015-11-01, and switched to the 2015-01-01 and had no issues. 
eg:
 {
      "type": "Microsoft.Resources/deployments",
      "name": "[concat('vmcreate', copyindex())]",
      "apiVersion": "2015-01-01",


Also when running in debug mode it looks like it is hitting the 2014-01-01-preview api version instead of what I specify.
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<subscription id>/resourcegroups/rg/deployments/vmcreate0/operations?api-version=2014-04-01-preview

**Comment by vivsriaus** [comment]
Thanks for reporting this issue. It will be fixed in the upcoming Azure powershell release

**Comment by ravbhatnagar** [comment]
Fixed - 3/3 PS release
