### ISSUE TITLE
[Doc]: Get-AzRoleManagementPolicy returns 339 policies for a scope

### ISSUE THREAD

**Issue by eosho** [Azure/azure-powershell#18111]
### Description

After reviewing the [Az.Resources](https://docs.microsoft.com/en-us/powershell/module/az.resources/?view=azps-7.5.0#policy) module, I have some questions regarding modifying a PIM role setting for a scope/role definition.
- Before granting a role eligibility to a user/group, I would like to modify the max duration, approvers (2x or more) and enable mfa but only scope these to a specific role and scope.

Ideally, I should be able to run:
```
$scope = "/subscriptions/38ab2ccc-3747-4567-b36b-9478f5602f0d/"
Get-AzRoleManagementPolicy -Scope $scope
```
but with a `-Filter` flag on the roledefinition, modify the settings, and pipe it back to `Update-AzRoleManagementPolicy`

```
$scope = "/subscriptions/38ab2ccc-3747-4567-b36b-9478f5602f0d/"
$policy = Get-AzRoleManagementPolicy -Scope $scope -Filter "roleDefinitionId eq 'xxxx'"
$expirationRule = @{
    isExpirationRequired = $false
    maximumDuration = "P180D"   # does this take day in the format "7" for 7 days?
    id = "Expiration_Admin_Eligibility"
    ruleType =("RoleManagementPolicyExpirationRule")
    targetCaller = "Admin"
    targetOperation = @('All')
    targetLevel = "Eligibility"
    targetObject = $null
    targetInheritableSetting = $null
    targetEnforcedSetting = $null
}

$policy | Update-AzRoleManagementPolicy -Rule $expirationRule
```

In concept, this should do the trick. Would appreciate any examples you can share on the use cases I described.

**Comment by tobvil** [comment]
Same issue. We have no way of finding the policy for a specific role or roleDefinitionId.

**Comment by teckmark** [comment]
I am also having this same issue.

**Comment by svwie** [comment]
I was also trying to figure this one out and found this discussion without any solution. Documentation has some room for improvement. There are no proper examples on how the cmdlets work together and the structure of Az PowerShell documentation is not helping at all. You might want to put all the PIM related cmdlets in a PIM category instead of spreading them across categories. 🤷🏻‍♂️

Either way, here is my sample code which helps you get to the actual role on the specified resource. With 'name' from Get-AzRoleMangementPolicy you can use Update-AzRoleManagementPolicy to change notification settings etc.

Here we go:

```PowerShell
Connect-AzAccount

$scope = '/subscriptions/xxxxx-xxxx-xxxx-xxxx-xxxxxx'
$role = 'Reader'

$roleDefinition = Get-AzRoleDefinition -Scope $scope -Name $role
$roleDefinitionId = $scope + '/providers/Microsoft.Authorization/roleDefinitions/' + $roleDefinition.Id

$managementPolicyAssignment = Get-AzRoleManagementPolicyAssignment -Scope $scope | Where-Object { $_.roleDefinitionId -EQ $roleDefinitionId }
$roleManagementPolicyName = $managementPolicyAssignment.Name.Split('_')[0]

Get-AzRoleManagementPolicy -scope $scope -Name $roleManagementPolicyName
```
