### ISSUE TITLE
Azure Bastion Deployment fails in westeurope region: Compute allocation failed. Please retry later

### ISSUE THREAD

**Issue by TahaBenseddik** [Azure/azure-powershell#18155]
### Description

The deployment of azure bastion fails in the westeurope region. I have tried to create Azure Bastion through powershell commands and the portal, but it keeps failing. The error is: Long running operation failed with status 'Failed'. Additional Info:'Compute allocation failed. Please retry later.'

The command is being run within a runbook from an automation account
Runbook type = Powershell
Runtime version = 5.1

### Issue script & Debug output

```PowerShell
New-AzBastion : Long running operation failed with status 'Failed'. Additional Info:'Compute allocation failed. Please retry later.' StatusCode: 200 ReasonPhrase: OK Status: Failed ErrorCode: GatewayAllocationFailed ErrorMessage: Compute allocation failed. Please retry later. At line:107 char:20 + $bastion = New-AzBastion -ResourceGroupName $bastionrg ` + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [New-AzBastion], NetworkCloudException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.Bastion.NewAzBastionCommand
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Az.Accounts
Az.Automation
Az.Monitor
Az.Network
Az.OperationalInsights
Az.Resources
```

**Comment by TahaBenseddik** [comment]
Seems to be working again! Thank you.

**Comment by navba-MSFT** [comment]
@TahaBenseddik Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. 
You will see such issue when there is a resource crunch in that datacenter. In such scenario, you could try to quickly create the resource in some other region as a workaround. 

**[Here](https://github.com/Azure/azure-cli/issues/21678#issuecomment-1127403970)** is the update on the same issue being reported on another thread. 

>Update to issue:
We opened supports request to Microsoft about this Azure bastion deployment problem to West europe Region. Reply was following:
As it turns out, we currently have a capacity issue in region West Europe, and PG is working to increase the capacity in this region. As of right now, there is no ETA on when the capacity will be increased.
So MS had capacity issue at West Europe region and now it seems to be resolved. I managed to deploy Azure Bastion to West Europe just few minutes ago.

Similar issue Azure/azure-cli#21678

Hope this helps. We will now proceed with the closure of this issue. If you see similar issue in future feel free to reopen this github thread.
