### ISSUE TITLE
[Doc]: New-AzSqlInstanceServerTrustCertificate Issue

### ISSUE THREAD

**Issue by bdschaap** [Azure/azure-powershell#18182]
### Description

I'm having difficulty using New-AzSqlInstanceServerTrustCertificate.  The commands in [this article](https://docs.microsoft.com/en-us/powershell/module/az.sql/new-azsqlinstanceservertrustcertificate?view=azps-7.5.0) return an error when I supply my public key.  I'm using an X509Certificate2 object to obtain the key similar to this [article](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.publickey.encodedkeyvalue?view=net-6.0).

PS C:\> $publicKey = "0x3082..."
PS C:\> $instance = Get-AzSqlInstance -ResourceGroupName "ResourceGroup01" -Name "ManagedInstance01"
PS C:\> New-AzSqlInstanceServerTrustCertificate -InstanceObject $instance -Name "Certificate01" -PublicKey $publicKey 

`New-AzSqlInstanceServerTrustCertificate: Invalid public blob specified, reason: 'Cannot find the requested object.
'.`

**Comment by RakeshMohanMSFT** [comment]
@bdschaap Thank you for reaching out, we are looking into it.

**Comment by navba-MSFT** [comment]
@bdschaap Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@bdschaap Apologies for the late reply. This Azure powershell command does is that it imports (creates) a cert on Azure SQL Managed Instance for the purpose of using two functinalities - MI link and MI service broker.

Could you please provide the answers to my below questions ?

•	Could you please let me know what is your use case ? what are you trying to accomplish ?
•	For which feature/functionality you are trying to use this for?

I believe you are using this for SQL managed instances. Could you please confirm ?
•	If you are logged in to Azure, and has selected subscription where MI is located?
•	Could we please get the screenshot of this managed instance from Azure portal to confirm the MI and RG name?
•	In addition, how did you create your certificate ?
•	What happens when not using $publicKey variable and copy-pasting the string directly into the command line?

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@bdschaap Could you please look into the above questions and get back to me with the answers ? That will help us in assisting you better. Awaiting your reply.

**Comment by bdschaap** [comment]
Sorry for the delay.  I suspect my use case is different than the intended use case of this feature.  I was trying to get a SQL CLR function hosted on MI to access a https endpoint on our private network but receiving an error message stating that it didn't trust the certificate.

**Comment by bdschaap** [comment]
Probably not unless you think there is a way to cover my use case as well using this feature.  Otherwise, the issue can be closed.

**Comment by navba-MSFT** [comment]
@bdschaap Could you paste that error message in this GitHub thread ? That will help us to assist you better.

**Comment by navba-MSFT** [comment]
@bdschaap Please let us know if you had a chance to look at my above comment. Please share the certificate related error message here. Awaiting your reply.

**Comment by bdschaap** [comment]
Unfortunately I won't have time to revisit for a few weeks.  Can close this and will reopen if it's still an issue at that time.
