### ISSUE TITLE
*-AzureAutomationVariable commands have a boolean parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#183]
The New-AzureAutomationVariable command has a Boolean parameter named `-Encrypted`. From a PowerShell perspective, it seems more user friendly to change the `-Encrypted` parameter from a Boolean type to a switch parameter, which is effectively the same thing.

Switch parameters can still be explicitly set to `$true` or `$false` using the following syntax:

```
New-AzureAutomationVariable -Encrypted:$false
```

Or
```
New-AzureAutomationVariable -Encrypted:$true
```

In cases where users prefer to use PowerShell’s simplified switch parameter syntax, they can either omit the parameter, or specify it with no value passed in.

```
New-AzureAutomationVariable -Encrypted; # Create an encrypted variable
```

Or
```
New-AzureAutomationVariable; # Create an unencrypted variable
```

**Recommendation**: Change the `-Encrypted` parameter from a boolean to a switch parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
@jodoglevy do you have any thoughts on this issue?

**Comment by jodoglevy** [comment]
We specifically made it a boolean instead of a switch because choosing to encrypt the variable value or not is a decision we want the user to consciously make. If -Encrypted were a switch parameter, a user could easily shoot themselves in the foot by forgetting to specify the optional switch parameter, and end up giving us some secret value which we would store in plain text and expose in the portal, API, and cmdlets in a visible format. An optional boolean param prevents this from happening.

My opinion is to close this as 'wont fix'

**Comment by devigned** [comment]
@jodoglevy thank you for the background. @pcgeek86 if you feel strongly about this, reopen or post to user voice to see if it can get some traction.

**Comment by pcgeek86** [comment]
Hello David, Joe,

I don't feel particularly strongly about this specific instance, but rather the overarching idea that boolean parameters in PowerShell don't really make much sense. Switch parameters implement the exact same functionality, but require less typing for users. If you ask pretty much anyone in the community, if 

To resolve what Joe commented above, I would suggest adding a `-NoEncrypt` parameter. The default should always be to encrypt, but if the user explicitly wants to store a value in plain text, then they would specify the `-NoEncrypt` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
