### ISSUE TITLE
[Doc]: AzFrontDoorCdn module 8.0 documentation is incomplete

### ISSUE THREAD

**Issue by mikenri** [Azure/azure-powershell#18328]
### Description

This page has no examples and it seems to be incomplete:

https://docs.microsoft.com/en-us/powershell/module/az.cdn/new-azfrontdoorcdnsecuritypolicy?view=azps-8.0.0

This is the situation with all of the AzFrontDoorCdn cmdlet documentation

**Comment by dingmeng-xue** [comment]
@jessie-jyy , please invite team to look into them

**Comment by mikenri** [comment]
Is there any update on this?

I also opened a severity B premier support case with Azure support and have gotten no response.

**Comment by navba-MSFT** [comment]
@mikenri Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. We are looking into this issue. We will provide an update once we have more details.

In the meantime, Could you please share the support ticket # here so that we can check its status in the background. Awaiting your reply.

**Comment by dingmeng-xue** [comment]
Service team is working on reference docs. I route this issue to engineering owner.

**Comment by VeryEarly** [comment]
available now: https://review.docs.microsoft.com/en-us/powershell/module/az.cdn/new-azfrontdoorcdnsecuritypolicy?view=azps-8.1.0&branch=CI
