### ISSUE TITLE
New-AzureRmADApplication: Allow ID as Parameter

### ISSUE THREAD

**Issue by Mike-EEE** [Azure/azure-powershell#1839]
I am looking at this cmdlet, and it would be useful to be able to pass in the guid for the application.  Let's say that the ID is generated in a process that is also used elsewhere.  If the ID is not provided, then it gets generated as it does now.

In my case, I would like to create a self-signed certificate for Azure Key Vault with the application's ID stored in the certificate, that way I only need the thumbprint to load the certificate from the machine's store and get the application ID from the cert (rather than from app/web.config, where this could be checked into source control, etc).

Thank you for any consideration!

(BTW, your link to http://windowsazure.github.com/guidelines.html on your [Guidelines Page](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md) is broken)

**Comment by Michael-DST** [comment]
According to this article it appears that you can edit the application's key credentials after the fact: https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential

So, this might be a good workaround until this issue is solved.  I will give this a shot and update accordingly.

**Comment by Michael-DST** [comment]
Further discussion here: https://social.msdn.microsoft.com/Forums/azure/en-US/15cbac12-9911-4867-8389-828eeb63fcb8/guidance-creating-a-nontest-production-certificate?forum=AzureKeyVault&prof=required

**Comment by rahulpnath** [comment]
Hi Mike,
I am not quite sure on why there is a problem in having the application Id in the web.config and checked into the source control. It is just an identifier number and does not have any significance or sensitive information by itself. Even along with the thumbprint value, as you can connect to it only if you have the certificate.

(Anyways would wait for some one from the key vault team to reply)

**Comment by Michael-DST** [comment]
Well... it is the GUID to an application that resides within your cloud-connected Active Directory, correct?  To me that seems like something I wouldn't want the world to know.  Please let me know if I have that wrong. I'm still learning here. :)

**Comment by rahulpnath** [comment]
Thats why we have authentication in place. At least that's how I see it. (_If not we would not even be sharng our email addresses_)

**Comment by Michael-DST** [comment]
Haha... yes, I am learning this right along with you. :) To summarize my understanding so far: currently in order to access the AVK, we need the following information (when going with the certificate route):
 1. Thumbprint (the key/id, or "The How")
 1. Rest URL of secret ("The Where")
 1. Client ID ("The Who")

In my view, 2 and 3 are extraneous articles of surface area for a malicious party.  If those items are checked into source control and viewable via GitHub, they now know a target's "where" and "who".  Again, really not valuable unless they have the certificate which is truly the key here. 

However, being security-minded here (and because of the very nature of what we are dealing with -- a cloud-hosted key vault _that holds all of my application's secrets_) I would prefer to have a system where I am using 1 artifact (less surface area) rather than 3 (greater surface area).

I should also qualify that preference with an EASY and ELEGANT system. :)

**Comment by maddieclayton** [comment]
Please check out this document for an in-depth explanation of service principal creation: https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azurermps-5.4.0. Closing this issue, please reopen if you still have issues in the current version.
