### ISSUE TITLE
[Doc]: How to list monitoring categories without the resource being present

### ISSUE THREAD

**Issue by cveld** [Azure/azure-powershell#18423]
### Description

It seems that `Get-AzDiagnosticSettingCategory` can only operate when the resource is already there. 
Is there a way to get the available monitoring categories without the resource being present?
I believe I have seen somewhere that it is possible to pull the service description document of a service provider. How can I do that? Maybe it is part of this?

**Comment by dingmeng-xue** [comment]
Hi @cveld , thanks for contacting us.

Have you seen this feature available or documented somewhere? It's great that you can share more information. Azure PowerShell implementation bases on API provided by service. We have no idea which one can support your requirement yet.

**Comment by cveld** [comment]
The lead of this is the following page:
https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings-policy

It refers to the following PowerShell gallery script: [Create-AzDiagPolicy](https://www.powershellgallery.com/packages/Create-AzDiagPolicy)
This script in turn utilizes the assumption that the resources already exist.

**Comment by JimGBritt** [comment]
@cveld Unfortunately, there currently isn’t any way to actually pull the available categories (logs) for a ResourceType unless it already exists in the environment somewhere.  Diagnostic settings are a proxy resource (internal term I don’t think is documented anywhere externally for customers but that is what we call it) and they are not tracked by ARM.  We track the ResourceType itself but not the proxy ResourceType that would be deployed once the resource exists.  Because of this, there is no way for a customer to do this today.  My script exists to help customers (at a very large scale) navigate this challenge with a bit less friction given discoverability on what resourceTypes support Azure Diagnostics is not obvious or easy to get (scripted or otherwise) in a programmatic way without leveraging az modules / cli and just beating on the service.  My script generates the Azure Policy content that will allow a customer to query “once” for what a ResourceType that exists supports (if it does) and generate a policy for that ResourceType or wrap say a hundred policies in a policy initiative wrapped with an ARM template so you can deploy it.  I also have a pipeline example that will layer this into an Azure DevOps approach where you can schedule daily to catch up if new resourceTypes enter into the picture.  https://aka.ms/AzPolicyPipeline which could help helpful.  Mileage may vary and I'd recommend testing in your environment if this is something that you think may be helpful.

CategoryGroups help (referenced in that doc you mentioned https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings-policy).  There are two types of category groups today (AllLogs and Audit).  AllLogs would satisfy the selection of every category if used.  And in fact I have a PR in my script that is mentioned that will help a customer configure AllLogs in policies at scale but it is on hold as I am doing some more regression testing and looking  for a proper way to support a good customer experience.  If the goal is to ensure all logs will be selected all the time, this is the approach, method I would recommend (categoryGroups) and you can review that in the portal, under diagnostic settings, and you can see it when you create a configuration.  Audit is only avaiable for some resourceTypes where AllLogs should show up for all as a baseline.  Hope this helps.
