### ISSUE TITLE
[Doc]: Start-AzPolicyComplianceScan; Management Group Scope?

### ISSUE THREAD

**Issue by jberry777** [Azure/azure-powershell#18696]
### Description

This question/feedback is related to the Azure PowerShell cmdlet [Start-AzPolicyComplianceScan](https://docs.microsoft.com/en-us/powershell/module/az.policyinsights/start-azpolicycompliancescan?view=azps-8.0.0). The documentation mentions that calling the cmdlet with no parameters will only evaluate the compliance of the current subscription as the scope. The only scope parameter options described in the documentation are for subscription or resource group. 

The issue:
There's a policy that is assigned at the Root management group level. Is it possible to call the Start-AzPolicyComplianceScan cmdlet and have it execute a compliance check for the policy at the management group level?

**Comment by navba-MSFT** [comment]
@jberry777 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@jberry777 It is not possible to trigger the policy compliance scan at a management group level through PS/CLI/API. This is **by design** due to the amount of time it takes for a management group scan to kick off and complete. Hope this answers. Please feel free to reopen this thread if you need any further assistance on this.

**Comment by jberry777** [comment]
Thanks for the response @navba-MSFT! That makes sense for limiting from PS/CLI/API. Does that imply that it is possible through the Azure Portal?

My use case is that I've defined a policy in a customer tenant and assigned it at the root management group level. The policy registers subscriptions to our Azure Lighthouse offering and is configured with "deployIfNotExists" as well as a remediation task. What I'm trying to do is trigger a compliance scan at the management group level through the Azure Portal in order to have the policy onboard all of the subscriptions for me. (In addition to onboarding any new subscriptions that may be created in the future.)

**Comment by navba-MSFT** [comment]
@jberry777 Apologies for the late reply. I somehow missed replying to this. To answer your question:
No, it not possible to trigger a compliance scan through the portal (since we do not have the capability through API). 
The engine will run a delta scan when it gets triggered on a change along with the daily scan (every 24 hours).
