### ISSUE TITLE
[Cdn] Parameter OptimizationType for New-AzCdnEndpoint mandatory

### ISSUE THREAD

**Issue by VeryEarly** [Azure/azure-powershell#18749]
### Description

Thanks @jack-cloud-platform catching this bug, parameter OptimizationType for New-AzCdnEndpoint is actually mandatory, please plan to fix this in next major release.
@ChenglongLiu 

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
N/A
```

**Comment by isra-fel** [comment]
If it's a bug, we don't have to wait until next major release to fix it, we can do it in any release.
@ChenglongLiu  Hi Chenglong, can you prioritize this? Thanks

**Comment by TracyYaoYao** [comment]
Hi, @VeryEarly, parameter _OptimizationType_ cannot be set as mandatory. 
Because for some providers, it is not accepted. Like you could see, the _ProviderType_ of _classicCDNtest_ is **AzureFrontdoorStandard**, SKU is **Standard_Microsoft**. If we use the parameter _OptimizationType_, it will throw exception.

`PS C:\Users> New-AzCdnEndpoint -Name cdntestcert01 -ProfileName classicCDNtest -ResourceGroupName yaoshitest  -Location Global -Origin $origin -OptimizationType LargeFileDownload
New-AzCdnEndpoint : Optimization Type is not applicable for this profile.
At line:1 char:1
+ New-AzCdnEndpoint -Name cdntestcert01 -ProfileName classicCDNtest -Re ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ResourceGroup...    ]
  }
} }:<>f__AnonymousType29`5) [New-AzCdnEndpoint_CreateExpanded1], Exception
    + FullyQualifiedErrorId : BadRequest,Microsoft.Azure.PowerShell.Cmdlets.Cdn.Cmdlets.NewAzCdnEndpoint_CreateExpanded1
`
If you do not use this parameter, then will use the default value when create a new endpoint.

**Comment by TracyYaoYao** [comment]
For some providers, like EdgeCastCdn, it allows to use this parameter. But if you don't use it, then the default value will be used.
```Powershell
PS C:\Users\> New-AzCdnEndpoint -Name endpointTest01 -ProfileName certtest01 -ResourceGroupName yaoshitest  -Location Global -Origin $origin -OptimizationType DynamicSiteAcceleration -ProbePath /path/test.txt

Location Name           ResourceGroupName
-------- ----           -----------------
Global   endpointTest01 yaoshitest
```
