### ISSUE TITLE
Az.Account and Az.Resources Heavy writes when using on Azure functions/Azure Durable Functions

### ISSUE THREAD

**Issue by KelvinTegelaar** [Azure/azure-powershell#18758]
### Description

When using Az.Account and Az.Resources on Azure functions, the writes go explosive; a single import-module generates over 500 writes. Azure file shares which Azure functions run have quite expensive writes.

The writes seem to not make any sense as each import it tries to create folders or files that already exist. Included is a screenshot as an example:
![image](https://user-images.githubusercontent.com/49186168/175967773-1cc50778-a640-497e-8186-25d6e860aa7d.png)

Running an Azure Durable function that launches 100 scripts with the follwing contents every 15 minutes(a pretty normal schedule) does over 280k file transactions:
![image](https://user-images.githubusercontent.com/49186168/175967928-72133111-349f-44ab-bf9a-79975f95da52.png)

Complete script:
```powershell
param($Timer)
$AzSession = Connect-AzAccount -Identity
```

The same behaviors' is observed with both the Managed Dependencies & manually imported modules.

### Issue script & Debug output

```PowerShell
None
```

### Environment data

```PowerShell
Azure Functions on function runtime 4.0
```

### Module versions

```PowerShell
2.8.0
```

### Error output

```PowerShell
None.
```

**Comment by dingmeng-xue** [comment]
@isra-fel , does it relate to configuration? If yes, can user disable it?

**Comment by isra-fel** [comment]
Hi @KelvinTegelaar , have you been experiencing the same issue on previous versions of Azure PowerShell (Az.Accounts)?

**Comment by dcaro** [comment]
@KelvinTegelaar there is a chance that this issue is related to https://github.com/Azure/Azure-Functions/issues/1307 and https://github.com/Azure/Azure-Functions/issues/2231
We are monitoring this with the functions team and please provide the information asked in the previous comment.

**Comment by KelvinTegelaar** [comment]
Working with the azure functikn dev team to resolve this.

**Comment by nzthiago** [comment]
I investigated with Kelvin and our team. The key mitigation was to use the legacy v1 general purpose storage accounts. Standard general purpose Azure Storage accounts are required when using the Azure Storage provider for Durable Functions. All other storage account types are not supported. We highly recommend using legacy v1 general purpose storage accounts because the newer v2 storage accounts can be significantly more expensive for Durable Functions workloads. For more information on Azure Storage account types, see the [Storage account overview](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview) documentation.

In summary:
1)	The mitigation to avoid expensive billing is to use V1 general purpose for the Storage Account
2)	We’ll follow up with the storage account as to why the SMB transactions translated to Write transactions
3)	We’ll look at updating other areas of documentation with [the same note we have in the Durable Functions Storage Provider page](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-storage-providers#azure-storage)

if you run into similar issues of high storage billing related to Azure Functions please:

* Open a support ticket if this is impacting a production app that needs immediate attention or
* Follow these steps to [share your function app name privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) in a new issue together with the region your app is deployed to for us to investigate
