### ISSUE TITLE
Implicit calls to AAD/Graph APIs in multiple modules 

### ISSUE THREAD

**Issue by cutecycle** [Azure/azure-powershell#18858]
### Description

There seem to be a few modules involving Azure Resources-based role assignments that end up implicitly making calls to AAD/graph to read/validate the display name of a Principal. 

But this isn't necessary in many cases: specifically, when there is a service principal or identity that hasn't been given "Read.All" on a directory,but does have the objectId. It seems somewhat common:

`
https://github.com/Azure/azure-powershell/issues/12195
https://github.com/Azure/azure-powershell/issues/13573

It's even an issue, historically, in azure CLI: 
https://github.com/Azure/azure-cli/issues/1496
https://github.com/Azure/azure-powershell/issues/16414

I'm not sure if this is because it's considered an anti-pattern to have a resource deployment principal that doesn't also have the ability to read all principal DisplayNames, but typically users end up scratching their heads, running `$DebugPreference`, seeing an API call they can't ignore, and working around this by making direct REST API calls or deploying ARM templates... 

The SQL API requires a DisplayName, but it doesn't require the account invoking the request to know it. In both of these cases, the actual API doesn't need a second call to graph or a caller that retrieves a full principal object.

Does it make sense to instead catch-warn implicit API calls, or provide an option similar to `az role assignment`'s `--assignee-object-id`?

**Comment by dingmeng-xue** [comment]
Hi @cutecycle , thanks for raising the questions.

Cmdlets have been implemented by multiple teams. Developer hope to provide convenience to end user but may not consider all scenarios. For instance, creation of dummy object requires a service principal. Its cmdlet design contains below scenarios:

* New-AzDummy -name <> -sp <GUID>
  * MSGraph call is not required if client doesn't want to validate it. Otherwise, cmdlet needs to call MSGraph to fetch directory object by id. 
* New-AzDummy -name <> -spName <string>
  * If service creation needs object id rather than sp name, it needs to call MSGraph search API to find object by name. If service creation needs name, MSGraph call is not required.
* New-AzDummy -name <>
  * Cmdlet needs to call MSGraph creation API to create sp. It requires higher privilege permission than Read.

You can see behavior depends on service requirement and expectation to client. It needs to be discussed case by case. If you found one cmdlet doesn't follow this guideline or doesn't make sense from your perspective, please share to us. We will look into and ask team to make them better.

**Comment by cutecycle** [comment]
@dingmeng-xue yeah, that makes sense; different services have different priorities for convenience and different implementations. 

It may make sense to use a shared facade for GraphClient calls across Az, and force cmdlets that make graph calls to use it, then build fallbacks into that, though it may be more trouble than it's worth.

Right now we're just onboarding our service principal for directory read permission, and we're somehwat lucky that we're starting this after the AD admin consent processes improved dramatically.

**Comment by dingmeng-xue** [comment]
Sure. We have shared GraphClient across Az modules. Your team can reference https://github.com/Azure/azure-powershell/blob/76b66604c112ce193e46ed4952e998bda99d7610/src/KeyVault/KeyVault/Models/KeyVaultManagementCmdletBase.cs#L63. Keyvault module creates GraphClient internally and fetch information for keyvault purpose.

FYI, Azure PowerShell is the first party app. The consent grant flow is different from 3rd party app. Let us know if you meet the problem.

**Comment by bgawale** [comment]
Is there any workaround for the issue apart from onboarding the SPN with directory readers permission? This still is an issue and becomes more visible while running commands from DevOps where it expects DevOps SPN to have the directory users reader permission which I find is too wide.

**Comment by dingmeng-xue** [comment]
@bgawale , ideally, cmdlet should provide one parameter set which doesn't require MSGraph call when SPN has limited permission. Could you let us know which cmdlet may have the problem?

**Comment by bgawale** [comment]
It is while using Set-AzSqlServerActiveDirectoryAdministrator
