### ISSUE TITLE
[Az Compute] Include Trusted Launch related flags to Simple Parameter Set for New-AzVm and New-AzVmss

### ISSUE THREAD

**Issue by sirfamelin** [Azure/azure-powershell#19094]
### Description of the new feature

We would like to include Trusted Launch related flags be included into the Simple Parameter Set for the following reasons:

- Parity with Az Cli, configuring Trusted Launch features is available through the Az Cli simple parameter set.

- Lower bar of entry for Az Ps, today customers have to use the Default Parameter Set which requires a whole script to set up several resources in order to deploy a Trusted Launch VM. We want to simplify the process for customers

### Proposed implementation details (optional)

Details of the request can be found here: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1232

**Comment by Drewm3** [comment]
Travis, could you please work with Jayla to get this added. Part of the goal for the simple parameter set is to be close to the functionality of the portal for creating a single VM, and supporting Trusted Launch is in the portal. The default should not yet be to create a trusted launch VM, but it should be easy to get a trusted launch VM with the simple parameter set.

This may also mean changing the simple parameter set to creating Gen2 VMs as compared to Gen1 VMs, but this change should be done and made default if it is not already since Gen2 is the default in the portal when the image supports Gen2.

**Comment by TravisCragg-MSFT** [comment]
@Drewm3 ack, starting an Email thread.

**Comment by TravisCragg-MSFT** [comment]
@sirfamelin  I am working with our PowerShell teams to get this added. I will reach out if any more information is needed.

**Comment by TravisCragg-MSFT** [comment]
@sirfamelin The parameters have been added!
