### ISSUE TITLE
Publish-AzureWebsiteProject fails in Azure-Powershell 1.2.2

### ISSUE THREAD

**Issue by GasiorowskiPiotr** [Azure/azure-powershell#1911]
Publish-AzureWebsiteProject -Name "website-name" -Package "WebDeployPackage.zip" -Slot "production" -Verbose fails with:

Publish-AzureWebsiteProject : Value cannot be null.
Parameter name: path2
At line:1 char:1

**Comment by markcowl** [comment]
@naveedaz @akurmi Can you take a look?

**Comment by kmkumaran** [comment]
I am noticing similar issue with Azure SDK 1.2.2.

**Comment by eocrawford** [comment]
Appears that optional parameter SetParametersFile has become mandatory, likely due to a missing String.IsNullOrEmpty() check on line 90:

https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Services/Commands/Websites/PublishAzureWebsiteProject.cs:

            if (!File.Exists(fullSetParametersFile)) <============ may need a check here
            {
                if (File.Exists(Path.Combine(Path.GetDirectoryName(fullPackage), fullSetParametersFile))) <================ crashes here, line 92

Stack trace:

System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject.ExecuteCmdlet() in d:\workspace\powershell-publish\src\ServiceManagement\Services\Commands\Websites\PublishAzureWebsiteProject.cs:line 92
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in d:\workspace\powershell-publish\src\Common\Commands.Common\AzurePSCmdlet.cs:line 545

**Comment by eocrawford** [comment]
For the time being, I've worked around this by passing an empty parameters file:

`function Publish-WebsitePackage
{
	param(
		[parameter(Mandatory = $true)]
		[string] $packageName,
		[parameter(Mandatory = $true)]
		[string] $websiteName
	)

	$tempFile = $env:TEMP + "\" + [guid]::NewGuid().ToString() + ".xml"
	"<?xml version=`"1.0`"?><parameters />" | Out-File $tempFile

	Publish-AzureWebsiteProject -Package $packageName -Name $websiteName -SetParametersFile $tempFile -Verbose | Out-Null

	del $tempFile
}
`

**Comment by CloudyOne** [comment]
I was having this problem after Azure Web App Deploy to my Build / Release definitions (i tried both).

After downloading the build agent and hosting it on-premise, i was able to customize the Publish-AzureWebDeployment.ps1 file located in the build agent using @eocrawford's recommendation. 

Now my deploy is successful! :)

**Comment by eocrawford** [comment]
Submitted pull request https://github.com/Azure/azure-powershell/pull/1917 to fix this.

**Comment by ChocoMachine** [comment]
I'm using build vNext and have this problem manifesting in the "Azure Web App Deployment" task. I will apply @eocrawford fix to local .ps1 file till update available. 

Cheers...

**Comment by paul-daly** [comment]
Are there plans to replace **Publish-AzureWebsiteProject** with something like **Publish-AzureRMWebAppProject**?

**Comment by berzns** [comment]
Make sure you have installed the latest Azure PowerShell Command-line tools.
https://azure.microsoft.com/en-us/downloads/

**Comment by cormacpayne** [comment]
Closing as this issue has been resolved.
