### ISSUE TITLE
Inconsistent error handling on Get-AzADUser

### ISSUE THREAD

**Issue by Hindy-UK** [Azure/azure-powershell#19276]
### Description

Depending on the property you use to search for an account, accounts that are not found respond differently:

- ObjectID - ObjectNotFound error.
- DisplayName - no error.
- UserPrincipalName - no error.

### Issue script & Debug output

```PowerShell
N/a
```

### Environment data

```PowerShell
5.1.17763.2931
```

### Module versions

```PowerShell
2.9.1
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Ideally, fetching object by its identity or property should not return error. So the first case should be corrected. However, we don't want to make too many breaking change from previous version. Let's check original behavior. @VeryEarly

**Comment by Hindy-UK** [comment]
No problem. 

I disagree that it shouldn’t return an error. This is when searching for objects that don’t exist. The behaviour of other cmdlets (Get-ADUser, Get-AzureADUser) is to return an error if something doesn’t exist. For Get-AzADUser, I can use it in a Try-Catch block and with ErrorAction common parameter only when using the ObjectID parameter. If I do that using DisplayName or UPN, the Catch block never triggers.

So, I’d suggest the first case is fine and it’s the other two that should be fixed.

**Comment by dingmeng-xue** [comment]
@hindy-UK ,  Latter 2 cases are consistent with Azure PowerShell guideline. The behavior of the first one is special case due to historical reason. If we want to make them consistent, the only option is to correct the first case and return null rather than throwing error. We are fine to keep current behavior there because of the consideration of breaking change. Some existing cmdlets have the same case.
