### ISSUE TITLE
[Doc]: Get-AzStorageAccountKey Example2 is wrong

### ISSUE THREAD

**Issue by mrdenny** [Azure/azure-powershell#19282]
### Description

Example 2 should end in"[0].value". The .Key1 syntax was for the older cmdlets.

**Comment by dingmeng-xue** [comment]
@mrdenny , thanks for reporting. Could you share which cmdlet contains incorrect example?

**Comment by mrdenny** [comment]
Get-AzStorageAccountKey is the cmdlet with the problem. Example 2, second line.

**Comment by blueww** [comment]
@mrdenny 

For the [example #2 of Get-AzStorageAccountKey](https://docs.microsoft.com/en-us/powershell/module/az.storage/get-azstorageaccountkey?view=azps-8.2.0#example-2-get-a-specific-access-key-for-a-storage-account), it's added before for a breaking change of "Get-AzureRmStorageAccountKey".
The command description should already indicate this is for old cmdlet: " This command works for Azure PowerShell version 1.3.2, and previous versions."

However, since the breaking happens long before, and cmdlet name changes after that, this example should update.
We will decide how to update it and update this issue later.

**Comment by blueww** [comment]
Close this issue as the help already updated.
