### ISSUE TITLE
Get-AzStorageBlob -IncludeDeleted does not return any soft-deleted blobs (Az.Storage 4.8.0)

### ISSUE THREAD

**Issue by dariusonsched** [Azure/azure-powershell#19287]
### Description

When calling `Get-AzStorageBlob` using the `-IncludeDeleted` argument, no previously soft-deleted blobs are returned, on StorageV2 Azure Storage account, _with_ Blob Soft Delete _and_ Versioning **Enabled.**

This was happening with `Az.Storage 3.1.2` **and continues to happen with** `Az.Storage 4.8.0`.

Note:  We even tried using the `-Blob *` parameter with the asterisk wildcard _and_ using `-ContinuationToken`.  Nothing, even on a container with 10,000's of recently soft-deleted blobs, shows up.

### Issue script & Debug output

```PowerShell
DEBUG: 11:37:55 PM - NewAzureStorageContext begin processing with ParameterSet 'AccountNameAndKey'.
DEBUG: AzureQoSEvent: Module: Az.Storage:4.8.0; CommandName: New-AzStorageContext; PSVersion: 7.2.4; IsSuccess: True; Duration: 00:00:00.0241053
DEBUG: Finish sending metric.
DEBUG: 11:37:55 PM - NewAzureStorageContext end processing.
DEBUG: 11:37:55 PM - Init Operation Context for 'GetAzureStorageBlobCommand' with client request id  Azure-Storage-PowerShell-694005c9-df93-4f41-91bc-90532535a6f8. If you want to get more details, please add "-Debug" 
to your command.
DEBUG: 11:37:55 PM - GetAzureStorageBlobCommand begin processing with ParameterSet 'BlobName'.
DEBUG: 11:37:55 PM - Use storage account '*******' from storage context.
DEBUG: 11:37:55 PM - Start 4th remote call, method: , destination: https://********.blob.core.windows.net/data?restype=container.
DEBUG: 11:37:56 PM - GetAzureStorageBlobCommand end processing, Start 6 remote calls. Finish 6 remote calls. Elapsed time 238270.53 ms. Client operation id: Azure-Storage-PowerShell-694005c9-df93-4f41-91bc-90532535a6f8.
DEBUG: AzureQoSEvent: Module: Az.Storage:4.8.0; CommandName: Get-AzStorageBlob; PSVersion: 7.2.4; IsSuccess: True; Duration: 00:00:00.5237678
DEBUG: Finish sending metric.
DEBUG: 11:37:56 PM - GetAzureStorageBlobCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name       
---------- -------    ---------- ----       
Script     2.9.1                 Az.Accounts
Script     4.8.0                 Az.Storage
```

### Error output

```PowerShell
NO Errors are presented.
```

**Comment by dariusonsched** [comment]
Note - tried again with `-Debug` at the end of `Get-AzStorageBlob` but did not reveal any further information.

**Comment by blueww** [comment]
@dariusonsched 

As you have both blob version and blob soft delete enabled on the storage account, the soft delete behavior will work like https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview#versioning-on-delete-operations

Please note, when you delete a current version, the current version becomes a previous version (not deleted), and there is no longer a current version. 
Then when you run Get-AzStorageBlob with only "-IncludeDeleted" won't see the previous blob version created by delete the current version (since the created previous blob version is not in deleted status). Please run Get-AzStorageBlob with "-IncludeVersion" to see the blob version created with delete the blob current version. 

And if you delete a previous blob version (not current version), the blob version will be in Deleted status, and you can run Get-AzStorageBlob with both  "-IncludeDeleted" to "-IncludeVersion" to see the deleted blob version.

So this is server behavior, not a PSH issue.

**Comment by dariusonsched** [comment]
@blueww Wei - Thank you.  This was helpful and we were able to get past this.  Closing.
