### ISSUE TITLE
Get-AzSupportTicket with datetime filter is not working

### ISSUE THREAD

**Issue by junpark12** [Azure/azure-powershell#19484]
### Description

Based on the following sample, I tried to run Get-AzSupportTicket with datetime (createdDate) filter.
https://github.com/Azure/azure-powershell/blob/main/src/Support/Support/help/Get-AzSupportTicket.md
But it does not work.

### Issue script & Debug output

```PowerShell
PS>  Get-AzSupportTicket -Filter "Status eq 'Open' and CreatedDate gt 2019-12-20"
output> Get-AzSupportTicket: Error response received. Error Message: '{"error":{"code":"InvalidQueryParameter","message":"OData query param(s) contains invalid value for property 'CreatedDate'. Allowed values are: DateTime <= 540 days","details":[]}}'

PS> Get-AzSupportTicket -Filter "CreatedDate ge '2014-06-23T03:30:00.000Z'" 
Get-AzSupportTicket: Error response received. Error Message: '{"error":{"code":"InvalidQueryParameter","message":"OData query param(s) contains invalid value for one or more properties","details":[]}}'
```

### Environment data

```PowerShell
Azure cloud Shell.
```

### Module versions

```PowerShell
Azure cloud Shell.
```

**Comment by raghumunukutla** [comment]
@junpark12, if you read through the entire error message "output> Get-AzSupportTicket: Error response received. Error Message: '{"error":{"code":"InvalidQueryParameter","message":"OData query param(s) contains invalid value for property 'CreatedDate'. **Allowed values are: DateTime <= 540 days**","details":[]}}'"

It says allowed values are DateTime <= 540 days. Since you are providing input for date as "2019-12-20" which is greater than 540 days, its throwing the error. Please use the date filter with date <=540 days and you should be able to retrieve the tickets. 

Please let us know if that helps.
