### ISSUE TITLE
New-AzureRMNetworkSecurityGroup has no examples

### ISSUE THREAD

**Issue by philmea** [Azure/azure-powershell#1948]
The cmdlets New-AzureRMNetworkSecurityGroup has no examples, just a "1:" with not text.

**Comment by markcowl** [comment]
@DeepakRajendranMsft Can you take a look?

**Comment by craiglandis** [comment]
It's worse than that. Out of the 23 *Azure*NetworkSecurity* cmdlets (get-command *azure*networksecurity*) only the 3 *-AzureNetworkSecurityGroupAssociation cmdlets have even a single example populated. The other 20 have no examples at all.

These 3 have 1 example each:

get-help Get-AzureNetworkSecurityGroupAssociation -examples
get-help Remove-AzureNetworkSecurityGroupAssociation -examples
get-help Set-AzureNetworkSecurityGroupAssociation -examples

None of these 20 have even a single example:

get-help Add-AzureRmNetworkSecurityRuleConfig -examples
get-help Get-AzureNetworkSecurityGroup -examples
get-help Get-AzureNetworkSecurityGroupConfig -examples
get-help Get-AzureNetworkSecurityGroupForSubnet -examples
get-help Get-AzureRmNetworkSecurityGroup -examples
get-help Get-AzureRmNetworkSecurityRuleConfig -examples
get-help New-AzureNetworkSecurityGroup -examples
get-help New-AzureRmNetworkSecurityGroup -examples
get-help New-AzureRmNetworkSecurityRuleConfig -examples
get-help Remove-AzureNetworkSecurityGroup -examples
get-help Remove-AzureNetworkSecurityGroupConfig -examples
get-help Remove-AzureNetworkSecurityGroupFromSubnet -examples
get-help Remove-AzureNetworkSecurityRule -examples
get-help Remove-AzureRmNetworkSecurityGroup -examples
get-help Remove-AzureRmNetworkSecurityRuleConfig -examples
get-help Set-AzureNetworkSecurityGroupConfig -examples
get-help Set-AzureNetworkSecurityGroupToSubnet -examples
get-help Set-AzureNetworkSecurityRule -examples
get-help Set-AzureRmNetworkSecurityGroup -examples
get-help Set-AzureRmNetworkSecurityRuleConfig -examples

**Comment by markjbrown** [comment]
Yes, it's actually much worse than even that. There are very few examples for Network in PS across all of it. This is a backlog issue which we hope to start addressing but no dates. I will leave this open for now and update after we get through vNext planning.

**Comment by ward0** [comment]
Still working on it it seems...

**Comment by markjbrown** [comment]
We recently updated our docs for many of our cmdlets but we still need to add examples in many places.

Myself and @DeepakRajendranMsft will work to get these updated as well.

Thanks for your continued patience.

**Comment by anavinahar** [comment]
Hi @ward0, what version of PowerShell are you using? Please make sure you have the updated version. Info here: https://github.com/Azure/azure-powershell/releases

All the Rm cmdlets have examples for a while now.  Is there a specific cmdlet you are referring to?

**Comment by jeffpatton1971** [comment]
@anavinahar and @markjbrown we need to fix the documentation online, agreed the examples are in PowerShell with get-help, but the original ticket was created because of a lack of documentation on the website. It would be helpful if we could get some clarification on exactly HOW the documentation that is obviously there in PowerShell, either does or doesn't make it to the online version of said help.

It really feels that the Azure PowerShell team routinely marches to their own drum with regards to writing their cmdlets, in terms of outputs, help and so on. You all are welcome to reach out to me if you want to talk about this more, but it's incredibly frustrating that this disconnect exists.

**Comment by markjbrown** [comment]
Yes, we are aware the online docs are missing as well. We are actively investigating this right now. Will update here when we have this resolved or with an ETA.

thanks.

**Comment by jeffpatton1971** [comment]
Additionally check the get-help for Set-AzureRmLocalNetworkGateway it's missing a lot in PowerShell and apparently errors out

Get-Help Set-AzureRmLocalNetworkGateway -Online
Get-Help : The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
At line:1 char:1
+ Get-Help Set-AzureRmLocalNetworkGateway -Online
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-Help], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.GetHelpCommand

**Comment by markjbrown** [comment]
Hi folks. We just recently published updates to our online help for PS to include the examples.

Apologize for the delay in this. We had some hiccups in our publishing process. Thanks for your patience and thank you for raising this with us.
