### ISSUE TITLE
Disconnect-AzAccount can't clear an active context when multiple sessions are running

### ISSUE THREAD

**Issue by mr-oliva** [Azure/azure-powershell#19778]
### Description

Disconnect-AzAccount can logout but can't clear an active context.

How to reproduce is below:

1. Run a PowerShell Session (pwsh 1)
2. Connect-AzAccount in pwsh 1
3. Get-AzContext in pwsh 1 => return the context (not null)
4. Run a PowerShell Session (pwsh 2)
5. Get-AzContext in pwsh 2 => return the context (not null)
6. Get-AzVM in pwsh 2 => success
7. Disconnect-AzAcccount in pwsh 1
8. Get-AzContext in pwsh 1 => not return the context (null)
9. **Get-AzContext in pwsh 2 => return the context (not null)**
10. **Get-AzVM in pwsh 2 => failed**
11. Run a PowerShell Session (pwsh 3)
12. Get-AzContext in pwsh 3 => not return the context (null)

Please focus on 9 and 10.
In 9, the login state appears to be maintained because the context remains.
In 10, however, Get-AzVM failed.

Since it is after logging out, it seems correct that the command execution fails.
Is it a bug that the context remains despite a successful logout?

The expected behavior is to not return the context in step 9.

### Issue script & Debug output

```PowerShell
No error occurs.
```

### Environment data

```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
```

**Comment by dingmeng-xue** [comment]
@mr-oliva , it is by design. Context in Azure PowerShell indicates which user account, tenant and subscription are being used by current script. It is related to login but not equal to login status and token cache. By default, once PowerShell process is started, context is loaded into memory of current process. It is only updated when context in current process is changed. Login status is stored to central place and shared across processes. It is the reason why script in the 2nd process was failed when you log out in the first process, but context is not updated.

If you hope process is isolated, you need to use `Disable-AzContextAutosave`. Then, all information is kept in current process. The side effect of it is that you have to login when you start PowerShell each time.

**Comment by mr-oliva** [comment]
@dingmeng-xue 

Thank you for your answer.

I understood below:

>  It is related to login but not equal to login status and token cache.

> Login status is stored to central place and shared across processes. It is the reason why script in the 2nd process was failed when you log out in the first process, but context is not updated.

In my scenario, I'm gonna consider using `Disable-AzContextAutosave`
