### ISSUE TITLE
Az.Quota module is missing from PS Gallery

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-powershell#20093]
### Description

![image](https://user-images.githubusercontent.com/13176884/201414126-9bdac07f-1d78-4f74-9d93-914fce04f763.png)

**Comment by dingmeng-xue** [comment]
@artisticcheese , thanks for reporting. Az.Quota is existing in Azure PowerShell repo. It had been published but hidden because this service is under private preview and limited user can access its feature. The module will be shown up again once it is public preview or GA.

If you want to try this module, you can install hidden module using its name and version directly
```
Install-Module -Name Az.Quota -RequiredVersion 0.1.0
```
