### ISSUE TITLE
[Doc]: Az.Storage summary page general usage instructions

### ISSUE THREAD

**Issue by paulaustin-automutatio** [Azure/azure-powershell#20208]
### Description

On the summary page for the Az.Storage module could you provide general instructions on creating a context that is then used for the other commands.

The documentation Get-AzStorageBlob page doesn't show the fact that you need to create a context at all. If you put the general instructions on the main page then in the Get-AzStorageBlob just include -Context $ctx in the examples

**Comment by blueww** [comment]
@paulaustin-automutatio 

Thanks for the request!

What do you mean by "summary page for the Az.Storage module"? Would you please give a page link?

And for "instructions on creating a context", you can find in : https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azstoragecontext?view=azps-9.1.0#examples

BTW, there are several way to set storage context, like with set-azcurrentstorageaccount cmdlet, there will be a default storage context in the powershell console, so user don't need to input "-context" parameter when run Storage dataplane cmdlets. So normally we don't add "-Context" parameter to storage dataplane cmdlet help since this is a not required common parameter. And when user not input it and no default context , there will be error message to remind user input the Storage Context.

**Comment by paulaustin-automutatio** [comment]
At the top of each module is a summary page which currently only includes a list of all the commands., It would be useful if that page gave an overview of using the module.

https://learn.microsoft.com/en-us/powershell/module/az.storage/?view=azps-9.1.0#storage

Here is an example from the https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstorageblob?view=azps-9.1.0 page

PS C:\>Get-AzStorageBlob -Container "ContainerName" -Blob blob*

It doesn't indicate that you need to either have a default context in the poweshell console (or bash environment) or specify the context using the -Context parameter.

Also the https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azstoragecontext?view=azps-9.1.0#examples doesn't give any description of what contexts are and how they should be used.

I only knew about contexts as I had used other apis that used them.

Currently the only way for a new user to figure this out from the documentation of a specific command would be a combination of trial and error and web searches for example.

**Comment by blueww** [comment]
@paulaustin-automutatio 
Thanks for the suggestion!

How about we change the error message when the cmdlet misses "-Context" to make it more actionable, so user don't need web search how to use it:

- Current error message:
"Could not get the storage context.  Please pass in a storage context or set the current storage context."
- Changed Error message:
"Could not get the storage context. Please pass in a storage context with "-Context" parameter (can be created with *New-AzStorageContext* cmdlet), or set the current storage context with *Set-AzCurrentStorageAccount* cmdlet."

For the change in the summary page, I will need to check with Powershell team to see if that's applicable. 
However, although there are many cmdlets in Az.Storage need "-Context", there are also a lot of other cmdlets in Az.Storage doesn't need "-Context". So we need think how to not mislead customer that all Az.Strorage need Storage Context.

**Comment by yifanz7** [comment]
The error message has been updated in the latest release.  Closing the issue.
