### ISSUE TITLE
Get-AzStorageShare for Public network access disabled

### ISSUE THREAD

**Issue by shekaryenagandula** [Azure/azure-powershell#20763]
### Description

I'm trying to list the file share of storage accounts for which public network access disabled. 
Is there any way to list the file share using PowerShell in automation runbook? 
I tried using different methods but it's throwing denied error. 
I tried using Private endpoint but it's not working either

**Comment by shekaryenagandula** [comment]
I didn't find any relevant documentation for that. 
Basically I'm trying to automate the back up of all the storage accounts to recovery service vault for which public network access disabled.

**Comment by blueww** [comment]
@shekaryenagandula 

Thanks for raising the request!

However, this looks more like a private link feature question, instead of Powershell question. 

For a Storage account disabled Public network access, you can only access it from private link currently, you can see more details in https://learn.microsoft.com/en-us/azure/storage/common/storage-private-endpoints

If you can give more details of the script you use (include how to create storage context), and the detail error when you run it from private link, we might can get more clue to investigate this issue.

If you also failed to send request to Storage account with any other storage tools (Storage Explorer, storage SDK, CLI...), you might can file a ticket to ask help from the feature team:
![image](https://user-images.githubusercontent.com/6926193/215372373-152ea034-2766-4ef4-a4d1-ffe5e83c79a3.png)

**Comment by shekaryenagandula** [comment]
Thanks for sharing input. 
I'm trying to list the file share names to enable the backup of file share using PowerShell. Due to public access disabled, it's not allowing to fetch the fs names. 
Is it feasible solution to use private link for just fetching the names of FS name? 
Any other suggestion?

**Comment by blueww** [comment]
@shekaryenagandula

As the Storage account disabled Public network access, to use the rest API to list file share names, you must run it from private link.

For the following backup steps, if you use Powershell (based on rest API), you still need run it from private link. 
If you use other ways, this is out of Powershell scope, we might not be the best person to answer it. Would you please file a ticket to ask help from the feature team?

**Comment by shekaryenagandula** [comment]
Appreciate your response. 
I'm closing this chain
