### ISSUE TITLE
[Doc]: get-azcosmosdbaccount needs to link to a page defining Microsoft.Azure.Commands.CosmosDB.Models.PSDatabaseAccount

### ISSUE THREAD

**Issue by caroysMSFT** [Azure/azure-powershell#20884]
### Description

How do I know what methods and members exist within the return type of Microsoft.Azure.Commands.CosmosDB.Models.PSDatabaseAccount?

I am able to of course inspect these if I run the cmdlet like:

get-azcosmosdbaccount | get-member

However - this is inferior to actually having a page which lists methods and members and explains them.  Please create a documentation page for the return object type PSDatabaseAccount, and link it to any cmdlet's page which is referencing this type.

This is useful for the type of programmer who plans things out before they write a single line of code (ostensibly the kind of programmers we strive to employ).

**Comment by Alex-wdy** [comment]
Doc  improvement

**Comment by isra-fel** [comment]
Docs link: https://learn.microsoft.com/en-us/powershell/module/az.cosmosdb/get-azcosmosdbaccount?view=azps-9.4.0
The C# type PSDatabaseAccount did not appear in the C# docs.

**Comment by caroysMSFT** [comment]
*Powershell, not C#.

**Comment by BethanyZhou** [comment]
- PSDatabaseAccount doesn't exist in source code. That's why we can't link PSDatabaseAccount.

- From source code, we can find that the output of Get-AzCosmosDBAccount is PSDatabaseAccountGetResults, see 
https://github.com/Azure/azure-powershell/blob/ebe90379e1220f6250baf4388a1250c1f6aeb807/src/CosmosDB/CosmosDB/CosmosDBAccount/GetAzCosmosDBAccount.cs#L26

- Will update the help doc for Get-AzCosmosDBAccount. And its related doc should be checked as well.

- @caroysMSFT For the time being, please visit https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.cosmosdb.models.psdatabaseaccountgetresults?view=az-ps-latest to get the output definition of Get-AzCosmosDBAccount directly. The link issue is supposed to go on March 7.
