### ISSUE TITLE
[Doc]: Cmdlet docs do not provide distinction between `AzStorage` and `AzRmStorage`

### ISSUE THREAD

**Issue by aelij** [Azure/azure-powershell#21214]
### Description

Cmdlets such as `Remove-AzStorageContainer` use the storage account's data plane, while cmdlets such as `Remove-AzRmStorageContainer` use the control plane (ARM).

I think it's worth adding a note on the top of these pages explaining the difference, as different roles are used for those operations.

For example:

> Note: `AzStorage` commands use data plane permissions while `AzRmStorage` use control plane (ARM) permissions. They require different roles and network access. See [Authorize data operations](https://learn.microsoft.com/en-us/azure/storage/common/authorize-data-access) and [Authorizing management operations](https://learn.microsoft.com/en-us/azure/storage/common/authorization-resource-provider).

**Comment by blueww** [comment]
@aelij 

Thanks for the suggestion!

However, the statement "`AzStorage` commands use data plane permissions " is not correct. We also have many control plane `AzStorage` cmdlets like "New-AzStorageAccount".
Actually user can find how to use the cmdlets (include which credentail to prepare) from the parameters / examples of the cmdlet help.

For those cmdlets with "AzRmStorage", we add "Rm" since both dataplane and control plane have cmdlets to handle same object (like container), to differ the 2 kind cmdlets on same object, we add "Rm" which means resource manager to the related control plane cmdlets. 

For "adding a note on the top of these pages", which page do you mean?

**Comment by aelij** [comment]
OK, I over-generalized the statement. I would add the note to all pages that have cmdlets for both control and data plane, such as the example above. Thanks!
