### ISSUE TITLE
[Feature]: Add parameter -NoWait for Set-AzResource 

### ISSUE THREAD

**Issue by WiseK** [Azure/azure-powershell#21286]
### Description of the new feature

Add parameter -NoWait for Set-AzResource 

Set-AzResource
Reference
Module:
[Az.Resources](https://learn.microsoft.com/en-us/powershell/module/az.resources/?view=azps-9.5.0)

**Comment by isra-fel** [comment]
Hi @WiseK , if you do not want `Set-AzResource` to block your script, you can use `-AsJob` to make it a background job.

**Comment by shellby1** [comment]
> Hi @WiseK , if you do not want `Set-AzResource` to block your script, you can use `-AsJob` to make it a background job.

it is not an option if case exit pwsh process (job will die with the process with unknow state)
"-NoWait" option will make a deployment in azure but won't wait for it completion

**Comment by isra-fel** [comment]
> > Hi @WiseK , if you do not want `Set-AzResource` to block your script, you can use `-AsJob` to make it a background job.
> 
> it is not an option if case exit pwsh process (job will die with the process with unknow state) "-NoWait" option will make a deployment in azure but won't wait for it completion

Job will die yes, but the deployment will continue in the cloud, just like '-NoWait'. Am I missing something here?

**Comment by shellby1** [comment]
> Hi @WiseK , if you do not want `Set-AzResource` to block your script, you can use `-AsJob` to make it a background job.

Hi,
-AsJob uses compute resources and need running VM

-NoWait will create deployment process in Azure and won't wait for completion
so running process/VM can be terminated

**Comment by isra-fel** [comment]
`-AsJob` uses compute resources. That's true. But it doesn't require the VM to run until the job is finished. You can cut the job early. Let me explain.

The difference between them is `-AsJob` starts the deployment then constantly pulls the status until finished, while `-NoWait` only starts it.

So normally if you cut `-AsJob` in the middle, since the deployment has already begun on the cloud, you are just stop polling the status. It doesn't affect the deployment. This behavior is similar to `-NoWait`.

**Comment by shellby1** [comment]
this method returns [PSResourceGroupDeployment](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.resourcemanager.cmdlets.sdkmodels.psresourcegroupdeployment?view=az-ps-latest)
how i can figure out that "job" can be terminated without impact on deployment?
