### ISSUE TITLE
Do not close running PowerShell processes when installing

### ISSUE THREAD

**Issue by jberezanski** [Azure/azure-powershell#2130]
What is the reason for the installer to close the running PowerShell processes?

We have an automated workstation setup solution based on PowerShell. When the Azure Tools are installed (using webpicmd), the Azure PowerShell installer kills all running PowerShell processes, which breaks our configuration workflow and even terminates the Azure Tools installation itself (because the owner of the console window is powershell). This happens even though this is a clean machine (no existing older Azure bits).

Is there a way to prevent this undesired behavior?

**Comment by markcowl** [comment]
@jberezanski Sorry for the bad experience.  The reason is that we are deleting modules and updating the PSModulePath.  Open PowerShell sessions could have dlls loaded that would prevent the deletion, and would be in an inconsistent state after install, because they would not have the PSModulePath change.

This is planned for a fix in one of the next two releases, when we change the installation location for the installer.

**Comment by jberezanski** [comment]
Thanks for the explanation.

I'd much prefer if the installer acted like a lot of other installers do:
1) detect if the files being replaced are actually in use; if not - there is no problem, so do nothing
2) if some files are in use and the installation is interactive, warn the user and present a choice: either the user closes the specified applications or the installer schedules the files to be replaced upon reboot
3) if some files are in use and the installation is unattended (/passive or /quiet), schedule the files to be replaced upon reboot

Automatically killing powershell processes basically causes user data loss: the user might have a long command history, or some important info shown on screen, or a remoting session open to a server with remote commands running... Lots of valuable state could be lost. On the other hand, having to open a new powershell instance (or manually adjusting PSModulePath in the current instance, or importing the module using the full path) to use a newly installed module is only a tiny bit inconvenient.

Another point: there are lots of other PowerShell hosts apart from powershell.exe and powershell_ise.exe (Server Manager, Active Directory Administrative Center, Visual Studio, Chocolatey, PowerShell DSC...), many of which can import modules and invoke arbitrary cmdlets, so targeting those two specific applications does not solve the problem.

Fortunately, I was able to work around the current installer behavior by simply renaming powershell.exe to something else. I'm eager to see how you will solve it in the future.

**Comment by markcowl** [comment]
@jberezanski Unfortunately, it is difficult due to sharing installation between an msi installer and the PowerShell Gallery modules to use the standard installer mechanisms that can require a reboot when removed files are in use.  This is because the file names and paths installed by Install-Module are not predictable, and the msi attempts to clean them up.

This will be resolved in the installer rewrite, as a different mechanism for installing and removing files will be used.

**Comment by markcowl** [comment]
This will be fixed by the newer installer referenced here #2220  .  Closing in favor of the issue tracking the solution.

**Comment by jberezanski** [comment]
FWIW, the problem still exists, at least in version 5.0.0, which is installed by the Azure workload for Visual Studio 2017. It is reallly inconvenient for people using scripts to automate developer workstation configuration.

**Comment by MaurGi** [comment]
@markcowl this reproes on VS2017 installation - see above and see https://github.com/jberezanski/ChocolateyPackages/issues/35#issuecomment-370054633
