### ISSUE TITLE
[Doc]: the hashtable format for ConnectionStrings should be specified in the document

### ISSUE THREAD

**Issue by engineer45** [Azure/azure-powershell#21373]
### Description

I do not see if the issue is now linked to the document 
the document with the issue is : 
https://learn.microsoft.com/en-us/powershell/module/az.websites/set-azwebappslot?view=azps-9.5.0#-connectionstrings 

Please update the connection string parameter with this info: It is NOT a standard HASHTABLE, it has to be specific format. The format details are specified in this issue: 

https://learn.microsoft.com/en-us/powershell/module/az.websites/set-azwebappslot?view=azps-9.5.0#parameters 
[The details are in this issue](https://learn.microsoft.com/en-us/powershell/module/az.websites/set-azwebappslot?view=azps-9.5.0#parameters )

**Comment by navba-MSFT** [comment]
@engineer45 Thanks for reaching out to us and reporting this issue. The connectionString format is the same for `set-azwebappslot `and `Set-AzWebApp`. This is because of the Hash Table formation. It should be formed as below.

> **$connStrings = @{ConnectionStringName = @{ Type = "MySql"; Value = "TestValue"}}**

**Note**: I will also create a PR to update [this ](https://learn.microsoft.com/en-us/powershell/module/az.websites/set-azwebappslot?view=azps-9.5.0#-connectionstrings)documentation as per your feedback and try to make the description more clear.
