### ISSUE TITLE
Get-AzureRmSubscription outputs the same information twice

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-powershell#2209]
Here is my output:
```
PS C:\WINDOWS\system32> Get-AzureRmSubscription
WARNING: Unable to acquire token for tenant 'Common'


SubscriptionName : AzureSDKADGraph2
SubscriptionId   : 0b1f6471-1bf0-4dda-aec3-cb9272f09590
TenantId         : 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
State            : Enabled

SubscriptionName : AzureSDKADGraph2
SubscriptionId   : 0b1f6471-1bf0-4dda-aec3-cb9272f09590
TenantId         : 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
State            : Enabled
```

Repro steps:
1. Login-AzureRmAccount SubscriptionId 0b1f6471-1bf0-4dda-aec3-cb9272f09590 -TenantId AzureSDKTeam.onmicrosoft.com
2. use corp credentials
3. Get-AzureRmSubscription

**Comment by markcowl** [comment]
Analysis:  This is caused because the tenant list contains both 'AzureSDKTeam.onmicrosoft.com' and the corresponding tenantId after login.  If we resolve tenantId using the tenatId value in the returned token, then this issue would be resolved.

Proposal:

Populate Account.Tenants only after obtaining tokens.  Use the tenantId from the token to populate this value, and never the value passed in from the command line.

**Comment by markcowl** [comment]
Investigation complete.  Closing
