### ISSUE TITLE
Remove-AzStorageContainer can't remove container with expired immutabilityPolicy

### ISSUE THREAD

**Issue by ChengleiYuan** [Azure/azure-powershell#22564]
### Description

Hello team,

I found that I can't remove a container with expired immutability policy with command `Remove-AzStorageContainer`. But it works with `Remove-AzRmStorageContainer`. Is this by design?

![image](https://github.com/Azure/azure-powershell/assets/29225536/2ca995c8-c954-4396-9b32-1c51cf1cbec8)
![image](https://github.com/Azure/azure-powershell/assets/29225536/d4592a6e-b53f-4540-8b25-53b4393f4577)

### Issue script & Debug output

```PowerShell
PS D:\DevTools\AIB> remove-azstoragecontainer -Name vhds -Context $storageaccount.Context -Confirm:$false -Force
Remove-AzStorageContainer: The requested operation is not allowed as the container has a locked immutability policy. HTTP Status Code: 409 - HTTP Error Message: The requested operation is not allowed as the container has a locked immutability policy.
ErrorCode: ContainerImmutabilityPolicyLocked
ErrorMessage: The requested operation is not allowed as the container has a locked immutability policy.
RequestId:30b2ac22-e01e-00b1-07ac-ce02ab000000
Time:2023-08-14T12:43:58.6240697Z
```

### Environment data

```PowerShell
PS D:\DevTools\AIB> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.25926
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS D:\DevTools\AIB> Get-Module az*

ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     2.10.4                Az.Accounts
Script     6.5.0                 Az.Resources
Script     5.2.0                 Az.Storage
```

**Comment by blueww** [comment]
@ChengleiYuan 
The error is from Azure storage server, not from Powershell code.
So this looks a server side issue/question, instead of Powershell side.

Besides that, Remove-AzStorageContainer and Remove-AzRmStorageContainer are based on different rest API with different credentials.
•	Remove-AzStorageContainer: based on dataplane API Delete Container (REST API) - Azure Storage | Microsoft Learn
•	Remove-AzRmStorageContainer: based on management plane API: Blob Containers - Delete - REST API (Azure Storage Resource Provider) | Microsoft Learn


Would you please open an ICM and include Xstore team to investigate the server side failure?

The error is from Azure storage server, not from Powershell code.
So this looks a server side issue/question, instead of Powershell side.

Besides that, Remove-AzStorageContainer and Remove-AzRmStorageContainer are based on different rest API with different credentials.
•	Remove-AzStorageContainer: based on dataplane API [Delete Container (REST API) - Azure Storage | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/storageservices/delete-container?tabs=azure-ad)
•	Remove-AzRmStorageContainer: based on management plane API: [Blob Containers - Delete - REST API (Azure Storage Resource Provider) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/storagerp/blob-containers/delete?tabs=HTTP)

As the immutabilityPolicy is expired, it looks more like a dataplane API issue instead of management plane API issue.
@ChengleiYuan Would you please open an ICM and include Xstore team to investigate the server side failure?

**Comment by blueww** [comment]
@ChengleiYuan

I will close this issue as this is not an Azure Powershell side issue (but server side). 

Feel free to contact us again if need any further assistance on Azure Powershell.
