### ISSUE TITLE
FIDO 2 security key entry doesn't work when sign in

### ISSUE THREAD

**Issue by tithiraw** [Azure/azure-powershell#22738]
### Description

I encountered this issue while attempting to sign in to the Azure Portal using Azure az-connect with my FIDO 2 Security Key.

The problem I'm facing is that when I reach the sign-in window, the FIDO 2 Security Key doesn't seem to detect properly. Instead of progressing to a successful sign-in, the sign-in window keeps looping without completing the authentication process.

I have tried the following troubleshooting steps but have not been able to resolve the issue:

Hardware Verification: Ensured that the FIDO 2 Security Key is properly inserted and recognized by my device.

Browser Testing: Attempted the sign-in using different web browsers to rule out any browser-specific issues.

Device and Driver Updates: Verified that my device and the FIDO 2 Security Key have the latest firmware and driver updates.

Alternative Authentication Methods: Successfully signed in using password sign in method after excluding my account from FIDO2 passwordless entry CA policy to confirm that my Azure account is functional. 

Despite these efforts, the problem persists, and I'm unable to access the Azure Portal using my FIDO 2 Security Key.

**Comment by isra-fel** [comment]
Hi @tithiraw since your question isn't related to Azure PowerShell, I may need to close the issue. I suggest you [Contact Microsoft Azure Support](https://support.microsoft.com/en-us/topic/contact-microsoft-azure-support-2315e669-8b1f-493b-5fb1-d88a8736ffe4#:~:text=Get%20answers%20in%20Azure%20forums.%201%20Connect%20with,3%20Check%20the%20status%C2%A0of%20Azure.%20Search%20Azure%20documentation.) instead.
