### ISSUE TITLE
[Feature]: When getting Key Vaults per resource group allow an expandproperties to get all the properties of the keyvault 

### ISSUE THREAD

**Issue by cblomart** [Azure/azure-powershell#23806]
### Description of the new feature

When getting a keyvault per name many properties are returned.
When getting keyvaults per resourcegroup, only a few of them are returned.

In my case this means that i need to call the get-azkeyvault once per resourcegroup and then itterate per keyvault to get all the details.

It would be a lot more convenient to have the option to ask to gather all the properties when getting all keyvaults in a resourcegroup (ExpandProperties).

**Comment by isra-fel** [comment]
Fair point. Let's talk to key vault service team to get their ideas. @BethanyZhou

**Comment by BethanyZhou** [comment]
we use Odata query instead of Get "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.KeyVault/vaults" to list all key vaults. That's the reason why we don't have additional properties for each vault. It's an implementation from long time ago. I'm not sure if it's by design for efficiency. @jlichwa, any thoughts for this feature request?

**Comment by jlichwa** [comment]
No plan, the list is mostly to list with common information for finding right key vault and is optimized for performance, then get of individual key vault is to get all information about specific key vault.

**Comment by BethanyZhou** [comment]
thanks for your opinions @jlichwa .

@cblomart, To obtain all properties per resource group, please use `Get-AzKeyVault -ResourceGroupName test-rg | ForEach-Object {Get-AzKeyVault -VaultName $_.VaultName -ResourceGroupName $_.ResourceGroupName}` as workaround.

**Comment by BethanyZhou** [comment]
Close as no plan for this feature request.
