### ISSUE TITLE
"Select-AzureRmSubscription -SubscriptionId" will give you an error after Azure PS 1.5.0

### ISSUE THREAD

**Issue by TeppeiIshii** [Azure/azure-powershell#2388]
PS C:\Users\teppei> Select-AzureRmSubscription -SubscriptionId "XXXXX-YYYY-ZZZZ"
Set-AzureRmContext : パラメーター 'SubscriptionId の引数を確認できません。引数 "XXXXX-YYYY-ZZZZ"
は、ValidateSet 属性で指定されたセット "52c748bc-65e5-44aa-8d64-97abff022b4e" に属していません。このセットの引数を指定
して、コマンドを再度実行してください。
発生場所 行:1 文字:44
+ ... RmSubscription -SubscriptionId "aee69007-7b6d-465e-9df7-ae8b05fb2e94"
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureRmContext]、ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Profile.SetAzureRMContextComma
   nd

// It's odd.
// The following goes successful. <Workaround>

PS C:\Users\teppei> $sub = get-azurermsubscription
PS C:\Users\teppei> Select-AzureRmSubscription -SubscriptionId $sub[0].SubscriptionId

// But the following will fail in the same error.

PS C:\Users\teppei> $subid =  "XXXXX-YYYY-ZZZZ"
PS C:\Users\teppei> Select-AzureRmSubscription -SubscriptionId $subid
Set-AzureRmContext : パラメーター 'SubscriptionId の引数を確認できません。引数 "aee69007-7b6d-465e-9df7-ae8b05fb2e94"
は、ValidateSet 属性で指定されたセット "52c748bc-65e5-44aa-8d64-97abff022b4e" に属していません。このセットの引数を指定
して、コマンドを再度実行してください。
発生場所 行:1 文字:44
+ Select-AzureRmSubscription -SubscriptionId $subid
+                                            ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureRmContext]、ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Profile.SetAzureRMContextComma
   nd

**Comment by markcowl** [comment]
@TeppeiIshii I'm not sure what's different between these two invocations, can you elaborate?

**Comment by TeppeiIshii** [comment]
@markcowl 
Not really. The type is both String, but the second one is allowed.  Also, the below will fail.

$subID = "XXXXX-YYYY-ZZZZ"
Select-AzureRmSubscription -SubscriptionId $subID

It's reproducible for subscriptions of some of my team (Azure tech support) members.  Can you check if it repros on your subscription?

**Comment by njwilloughby** [comment]
I am experiencing the same issue after updating to azure powershell 1.5.0

It appears that when you have more than 2 subscriptions you may not be able to select a subscription with 

`Select-AzureRmSubscription -SubscriptionId xyz `

since the update

Example error as I have lots of subscriptions

![image](https://cloud.githubusercontent.com/assets/2200580/15915290/8025a0d2-2e2b-11e6-97d3-e22c91293cbb.png)

Example working with a user that only has one subscription (selecting same subscription as above)

![image](https://cloud.githubusercontent.com/assets/2200580/15915284/6bd0e448-2e2b-11e6-892b-78700a5ab1d7.png)

I have experienced the same issue on a local development machine, azure VM being used as a VSTS build agent and using both user credentials and service principal credentials

You can work around by using the subscription name however VSTS breaks as it uses the subscriptionId method to select an azure subscription for azure powershell, ARM tasks etc.

Thanks

Nathan

**Comment by markcowl** [comment]
Fixed in version 1.5.1, which released today to webpi, and will be on the gallery soon.
