### ISSUE TITLE
Set-AzureRmAutomationVariable cmdlet throws error when updating Description

### ISSUE THREAD

**Issue by OliverMartini** [Azure/azure-powershell#2504]
The Set-AzureRmAutomationVariable cmdlet throws the following error when -Description is supplied. If no -Description parameter is supplied, the cmdlet works.

```
Set-AzureRmAutomationVariable -ResourceGroupName resourceGroupName `
>>             -AutomationAccountName automationAccountName `
>>             -Name variableName -Value variabelValue -Encrypted $True `
>>             -Description 'description of variable'
Set-AzureRmAutomationVariable : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Set-AzureRmAutomationVariable -ResourceGroupName resourceGroupName  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzureRmAutomationVariable], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.Automation.Cmdlet.SetAzureAutomationVaria
   ble
```

**Comment by markcowl** [comment]
@jodoglevy Can you take a look?

**Comment by jodoglevy** [comment]
Yes, this is by design. From the cmdlet's docs:
```
SYNTAX
    Set-AzureRMAutomationVariable [-ResourceGroupName] <String> [-AutomationAccountName] <String> [-Name] <String>
    -Encrypted <Boolean> -Value <Object> [<CommonParameters>]

    Set-AzureRMAutomationVariable [-ResourceGroupName] <String> [-AutomationAccountName] <String> [-Name] <String>
    -Description <String> [<CommonParameters>]
```

You can update either the value or description of the variable, but not at the same time.

We designed the cmdlet this way because we want to make sure -Encypted is specified whenever -Value is specified, so that the user consciously thinks about the fact that this value may be stored in plaintext, before any value is sent. But of course -Encrypted is not needed when -Description is specified (and no value for the variable is specified). So in order to make -Encrypted mandatory ONLY when -Value is specified, we used different parameter sets for updating the value and updating the description.
