### ISSUE TITLE
[Doc]: Azure login default subscription question

### ISSUE THREAD

**Issue by JohnMoeLORA** [Azure/azure-powershell#25102]
### Type of issue

Missing information

### Feedback

I was interested to read about the DefaultSubscriptionForLogin parameter for Update-AzConfig in this doc: https://learn.microsoft.com/en-au/powershell/azure/authenticate-interactive?view=azps-12.0.0#login-experience

However, I was wondering whether this applies to the user supplied in credentials (i.e., the "logged on user"), in the current PowerShell session (i.e., saved on the local machine somewhere), or if it's tenant-wide and applies to all new logons?  I ask because while I would like it to default to our production Infrastructure subscription for my region, my colleagues in the Development team or my counterparts in another country would probably prefer another "default".  Can you please add the context this command applies to?  I have a feeling it's the latter, but it would be good to explicitly state that in that case.

**Comment by isra-fel** [comment]
Hi Jone,
As other Az configs, this is a per-OS-user setting, meaning that as long as you login to the operation system as the same user, the setting will still take effect, and it won't be there if you switch user or computer. This is because the configs are stored locally in your AppData directory.
One exception to this is you can set the config at process scope (by `-Scope Process`) so that the setting only lives in your current PowerShell session/process.
Anyways you and your colleagues can definitely set your own default subscriptions without worrying about impacting each other 😄
