### ISSUE TITLE
[Doc]: Conflicting advice about Set-* cmdlet semantics

### ISSUE THREAD

**Issue by sardobi** [Azure/azure-powershell#26678]
### Type of issue

Outdated article

### Feedback

(This is about the engineering docs.)

The docs currently say:

> If your cmdlet is performing a **PATCH** operation (_i.e._, a partial replacement on the server), then the cmdlet should use the verb `Update`.
>
> If your cmdlet is performing a **PUT** operation (_i.e._, a full replacement on the server), the cmdlet should use the verb `Set`.

There are a few issues with this, I think:

First, my team found this a bit vague - it's not clear which of the following meanings is intended:
- "If the cmdlet is issuing a PUT/PATCH request, use `Set`/`Update` respectively"
- "If the cmdlet is using PUT/PATCH _semantics_, use `Set`/`Update` respectively" (but it can use whichever request types you like under the covers)

Second, either way, we're not sure this guidance is correct.
- There are lots of examples of cmdlets where `Set-*` uses PATCH semantics, [e.g. `Az.Storage`](https://learn.microsoft.com/en-gb/powershell/module/az.storage/set-azstorageaccount?view=azps-12.4.0) and [`Az.Compute`](https://learn.microsoft.com/en-gb/powershell/module/az.compute/set-azvm?view=azps-12.4.0).
- Writing a useable `Set-*` cmdlet which obeys PUT semantics is hard.
  - AutoRest doesn't implement `-InputObject` for you, so autogenerated `Set-*` cmdlets do not support piping. Implementing it manually is tedious as it requires a lot of bug-prone boilerplate code.
  - Without piping, `Set-*` with PUT semantics seems like a nightmare for users. They have to explicitly specify every property on their resource using individual parameters, which in many cases can be very impractical.

Based on the above, we suspect the guidance in the docs is outdated. Is this still the recommended semantics for `Set-*`? Is writing `Set-*` cmdlets still recommended at all?

### Page URL

https://github.com/Azure/azure-powershell/blob/b08bc7cb8c20c5302d126dda1ce89967d124b9ce/documentation/development-docs/design-guidelines/cmdlet-best-practices.md#set-vs-update

### Content source URL

https://github.com/Azure/azure-powershell/blob/b08bc7cb8c20c5302d126dda1ce89967d124b9ce/documentation/development-docs/design-guidelines/cmdlet-best-practices.md?plain=1#L36-L38

**Comment by dolauli** [comment]
I believe the docs are still valid, and they are for handcrafted modules.

We have two kinds of modules.

- Handcrafted modules which are based on C# SDK, e.g., Az.Compute, Az.Storage, you may still keep set-* cmdlets
- Autogen modules with autorest.powershell, when using autorest.powershell to generate modules, we do not recommend generating set-* cmdlets because they are difficult to use. Instead, we will generate update-* cmdlets for patch APIs. If there is no patch API available, we can generate an update cmdlet that uses a get->put approach to simulate a partial update on the client side.


Regarding `-InputObject` generated by autorest.powershell, it is only used for piping the path parameter in Azure service, when you use something like `get-* | remove-*`, it only try to get the resource `id` in the pipe in object.
