### ISSUE TITLE
Get-AzureRMResource throwing error for login when it has already being login

### ISSUE THREAD

**Issue by Ajay-MS** [Azure/azure-powershell#2688]
Hello team,
 
I have faced a wired  issue with customer today. Customer has already login to powershell session using SPN.

After login following rm command worked fine.
`Get-AzureRmStorageAccount -Name "<StorageAccountName>" -ResourceGroupName "<ResourceGroupName>"`

But to get azure RM resources is continuously  failing 
`Get-AzureRMResource`

Error command is throwing - 

> Get-AzureRMResource : Run Login-AzureRmAccount to login.
> At C:\Users\valtechnl_admin\Desktop\script.ps1:1 char:20
> + $azureSADetails = (Get-AzureRMResource -ErrorAction Stop) | Where-Obj ...
> +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Tried with Add-AzureRMAccount, Select-AzureRMSubscription but nothing worked for this cmdlet. Can you please help what is wrong there.

AzurePowershell version customer is using 1.3.2

**Comment by markcowl** [comment]
@Ajay-MS Most likely this is caused by multiple versions of Azure PowerShell installed on the machine.  You can find this out with

```Get-Module -ListAvailable```

If azure powershell modules show up anywhere other than in %progranfiles (x86)%\Microsoft SDKs\Azure\PowerShell, then have the customer remove them.

Alternately, installing one of the later powershell miss will automatically clean up any azure powershell modules from the typical downloaded module locations

**Comment by Ajay-MS** [comment]
@markcowl - Thanks for your response . This issue has been been resolved when use install AzurePS using msi instead of install-module.

**Comment by sqlchick** [comment]
Uninstalling, then reinstalling from the [msi download](https://github.com/Azure/azure-powershell/releases) also resolved this issue for me.

**Comment by spottedmahn** [comment]
>Alternately, installing one of the later powershell miss will automatically clean up any azure powershell modules from the typical downloaded module locations

I'm thinking "miss" is a typo and should be "powershell msi's"?

I had to use the msi install to fix my issue.  Using install-module did not work for me either.
