### ISSUE TITLE
Semver error while saving/installing on macOS

### ISSUE THREAD

**Issue by tstringer** [Azure/azure-powershell#2813]
It appears as though attempting to install (or even save) the azure modules (`Azure` and `AzureRM`) result in the following on my machine:

<img width="729" alt="screen shot 2016-08-21 at 11 51 51 am" src="https://cloud.githubusercontent.com/assets/1445483/17838231/ea367c0a-6795-11e6-8882-f4e00e349074.png">

Not matter what I do, this seems to be the result.  And it looks like it's a hard-stop error, as letting this screen "sit" for hours makes no progress.

**Comment by kilasuit** [comment]
@tstringer There is an open issue about this on the PowerShell Repo - see https://github.com/PowerShell/PowerShell/issues/1874

**Comment by kilasuit** [comment]
Essentially this isnt an AzureRM issue but an issue with the Find-Module command not currently being able to work with Semantic Versions - although there are supposed fixes in that linked issue there are currently only a few AzureRM modules that will work on PSCore due to a current building of them for the Full .NET Framework.

@markcowl - I haven't seen a timeline for the whole of the AzureRM modules to target .NET Core. Do you have any possible timeframes that can be shared?

**Comment by markcowl** [comment]
@kilasuit We don't have a complete timeline, but you can expect to see issues for this  to be posted here in the next week or so.  We ened to move our issues for this from the private repo now that the linux version is public. Issues will be tagged with the 'CoreCLR' Label.

Meanwhile, we used the generic cmdlets to start with, because these enable almost all scenarios for all resource types (albeit less conveniently than the typed cmdlets)

**Comment by markcowl** [comment]
### Description

File issues for additional module adds to PowerShell for Linux and add to milestones as appropriate, so custoemrs can track them coming online.  The first additional module should be Webapps.

### Cost: 1

**Comment by tstringer** [comment]
@markcowl any update on this?  Thanks in advance! 👍 😄

**Comment by markcowl** [comment]
@tstringer @kilasuit You can follow the progress on this in this PR:  #3908 This is planned for release late this month.

Closing as this is tracked in a more specific issue here: #3746
