### ISSUE TITLE
Trace logging filtering options should support the ability to filter on error level

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-powershell#2908]
The tracing adapter and interceptors should support the ability to log minimally for informational purposes, but log full error responses from the server when they are encountered. This is especially useful for long running operations that send many requests (such as uploading/downloading a large file).

Additionally, we should ensure support of piping this output to a file so that it doesn't flood the current powershell window executing the command (which I believe should already be supported).

**Comment by markcowl** [comment]
### Description
What we should actually support is limiting the serialization of request and response bodies so that the important parts of messages are captured in the log, but the log is not overwhelmed by large streaming responses.  We should impleme this as follows:

- For requests and resonses that have a length attribute, if the length < 5 k, printig the entire message into the stream
- For requests and responses with no loength, or a length > 5k, print only <request/response content redacted> into the log

### Cost: 2

**Comment by begoldsm** [comment]
@markcowl I think it might be good to somehow be able to give the option to not even include request/response content (even if less than 5k), especially if the client author knows it isn't particularly useful for tracing.
For example, if we have a customer uploading a lot of 4kb files, the interesting thing to trace isn't the content of those files, but the request/response headers and error response bodies (if any). This might make this over complex for the first iteration, but something to think about to help further tune/reduce logging noise.
