### ISSUE TITLE
Error deploying template with key vault reference when key vault is in different subscription

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-powershell#2939]
I am trying to use `New-AzureRmResourceGroupDeployment` to deploy a template to a resource group where some of the template parameters are key vault references.  I have enabled `enabledForTemplateDeployment` on the key vault, but when I attempt to deploy my template/parameter file I get the below error.  The key vault is in a different subscription than the resource group I am deploying to, but the user named in the error message below can successfully read the key vault secrets in question using `Get-AzureKeyVaultSecret`.  Is this expected?  Can it be fixed?  Thanks!

```
New-AzureRmResourceGroupDeployment : The client 'xxxxx@domain.com' with object id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
does not have permission to perform action 'MICROSOFT.KEYVAULT/VAULTS/DEPLOY/ACTION'
on the specified KeyVault resource '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/Provisioning-Dev/providers/Microsoft.KeyVault/vaults/kv-dev'.
Please see https://aka.ms/arm-keyvault for usage details.
```

template:

```
{
   "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
   "contentVersion": "1.0.0.0",
   "parameters": {
       "p1": {
           "type": "securestring"
       }
   },
   "variables": { },
   "resources": [ ]
}
```

parameters:

```
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "p1": {
            "reference": {
                "keyVault": {
                    "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/Provisioning-Dev/providers/Microsoft.KeyVault/vaults/kv-dev"
                },
                "secretName": "secret-test"
            }
        }
    }
}
```

**Comment by gregjhogan** [comment]
I found the permission referenced, but the description seems to indicate it is specifically for virtual machines (see below).  Is the description wrong (and I really should need this permission) or is the permission checking wrong (they key vault already has ```enabledForTemplateDeployment ``` set to true and I can read the secrets with my user).  Thanks!

```ps1
Get-AzureRMProviderOperation Microsoft.KeyVault/vaults/deploy/action
WARNING: The output object type of this cmdlet will be modified in a future release.


Operation         : Microsoft.KeyVault/vaults/deploy/action
OperationName     : Use Vault for Virtual Machines
ProviderNamespace : Microsoft Key Vault
ResourceName      : Key Vault
Description       : Enables access to secrets in a key vault when deploying a virtual machine
```

**Comment by ironicLemon** [comment]
I had the same error when using a service principal for deployment. The error was not actually to do with the key vault permissions they were actually fine. The issue was my deployment user did not have a RmRoleAssignment on the resource group that contained the key vault.

So using:
New-AzureRmRoleAssignment -RoleDefinitionName Contributor `
                          -ObjectId $objectId  `
                          -Scope /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/Provisioning-Dev

$object id is 
The client 'xxxxx@domain.com' with object id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'

When I made that change the deployment worked like a charm

**Comment by gregjhogan** [comment]
The contributor role includes the permission MICROSOFT.KEYVAULT/VAULTS/DEPLOY/ACTION so you did in fact give your user the permission that the error message mentions.  I ended up creating a custom role with just that one permission and assigning it to the service principle on the resource group with the key vault to fix the issue.

I am still curious if it is correct that this permission is needed and the description is wrong or if this permission shouldn't be needed for my scenario (not deploying a VM).  None of the ARM template documentation talks about needing this permission.

**Comment by markcowl** [comment]
@sumedhbarde-msft @pomortaz can you take a look and advise the customer on necessary permissiosn for template deployment using KeyVault

**Comment by gregjhogan** [comment]
I did figure out what permissions are currently necessary, but the description of the permission doesn't line up with what I am doing (see previous comment).  This issue can be closed because while the RBAC permissions are either incorrect or confusing (and not well documented), it does work.  Thanks!

**Comment by JohanLander** [comment]
Hi in your RM group you need to create a new Role  in Access control (IAM) and your user as a  Key Vault Contributor. Then it will work fine

**Comment by gregjhogan** [comment]
My question is if the key vault has enabledForTemplateDeployment set to true and the user performing the deployment can read the secrets (because it is in an access policy) what is this extra RBAC permission for and why does the description mention virtual machines?

We are trusting these resources specifically with sensitive data. It seems important to understand the permissions and how they work, but there doesn't seem to be any explanation for the purpose of the MICROSOFT.KEYVAULT/VAULTS/DEPLOY/ACTION  permission is in this scenario.

**Comment by pomortaz** [comment]
@seanbamsft can you please help clarify?

**Comment by seanbamsft** [comment]
The description is out of date, but Microsoft.KeyVault/vaults/deploy/action is the permission a user needs to have in order to deploy a VM or an ARM template that reference secrets in a vault.

In both of those scenarios, the user specifies the resource ID of a vault that contains secrets they want to use for a deployment (either a cert for a VM or a secret to be substituted in a template). There needs to be some mechanism that ensures the user cannot just specify the resource ID of some vault that they don't own. We could have said that the user must have Microsoft.KeyVault/vaults/write permission on a vault in order to reference it in a deployment. But that would have meant that only users who can actually modify the vault would be able to do deployments. So instead we check that the user has Microsoft.KeyVault/vaults/deploy/action. That way the vault owner can assign the deployment permission to someone without making them an owner of the vault.

**Comment by gregjhogan** [comment]
@seanbamsft thanks for the info!  I though a user/service principal deploying an ARM template also needed to be included in an access policy with read permission.  Is this not true?  If it is true why is inclusion in an access policy needed in addition to the Microsoft.KeyVault/vaults/deploy/action permission?  Thanks!

**Comment by rbitia** [comment]
Hi - I'm creating a storage account and I'm getting this error: Deployment failed. The resource identifier of the KeyVault parameter 'storageaccountkey' is invalid. Please specify the value following 'subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.KeyVault/vaults/{vaultName}' format. See https://aka.ms/arm-keyvault for usage details.

I set myself as an owner in my RG through the portal but it still doesn't work. Is there another solution?

**Comment by aviade** [comment]
You get "client 'xxxxx@domain.com' with object id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
does not have permission to perform action 'MICROSOFT.KEYVAULT/VAULTS/DEPLOY/ACTION' when the Service Fabric cluster is deployed to a Subscription that is different then the KeyVault (specified in the ARM template) subscription.

**Comment by ohadschn** [comment]
1. @seanbamsft - I second @gregjhogan's question, why is this permission needed if KeyVaults already have their own access policies? Is it do prevent DoS on the KeyVault or something like that?
1. Creating a custom role as @gregjhogan is really the only true answer here - but that's a bit of a chore - why not add a built-in role for this super-common need (reference KV secrets in ARM / VM)?

**Comment by seanbamsft** [comment]
@ohadschn The user does not need to be in the access policy for the vault. In the ARM template scenario, the call to Key Vault is being made using ARM's identity, not the user's identity. It's as if you had put ARM's AAD app's object ID in the access policy with permission to get secrets. But since ARM uses the same identity for all customers, there needs to be a mechanism to ensure you can't ask ARM to retrieve secrets from another customer's vault. That mechanism is the Microsoft.KeyVault/vaults/deploy/action ARM RBAC permission.

I'll need to take a look at whether it makes sense to add a built-in role. One concern I have is that built-in roles are required by policy to contain additional permissions that might not be desirable (in particular, Microsoft.Resources/deployments/* and Microsoft.Insights/alertRules/*). For simple scenarios, Key Vault Contributor works (or the generic Contributor/Owner roles). If a new built-in role had additional permissions that you didn't desire, you'd be back to making a custom role anyway.

**Comment by ohadschn** [comment]
Looks like this is all documented: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-keyvault-parameter

**Comment by staal-it** [comment]
I'm trying to use a secret in an ARM template deployed from Azure DevOps but keer getting the following error:
"The service does not have access to '/subscriptions/<sub>/resourcegroups/<group>/providers/microsoft.keyvault/vaults/<vaultName>' Key Vault. Please make sure that you have granted necessary permissions to the service to perform the request operation."

I managed to assign the role mentioned above. The docs @ohadschn is pointing to states something about Managed Applications. Is this the case in terms of Azure DevOps? It states: 

When using a Key Vault with the template for a Managed Application, you must grant access to the Appliance Resource Provider service principal. For more information, see Access Key Vault secret when deploying Azure Managed Applications.

However, I can't find the 'Appliance Resource Provider'-principle mentioned above.

When I use the 'Azure Key Vault'-task I'm able to download the secrets.

**Comment by jasonmv** [comment]
I'm encountering this issue when trying to deploy a template and the Key Vault is in a different subscription. If I deploy within the same description it works without issue.

**Comment by dingmeng-xue** [comment]
@jasonmv , did you set correct permission? If your case is different from above, please create a new issue and provide debug information.

We will close this discussion if there is not further activity.

**Comment by dingmeng-xue** [comment]
@jasonmv , please try again referencing https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/key-vault-parameter?tabs=azure-powershell. If you still have the problem, please contact us and provide detailed information.

**Comment by acraft-bt** [comment]
> I'm was trying to use a Keyvault secret in an ARM template deploying a Microsoft.Web/certificate from Azure DevOps but kept getting the following error: "The service does not have access to '/subscriptions//resourcegroups//providers/microsoft.keyvault/vaults/' Key Vault. Please make sure that you have granted necessary permissions to the service to perform the request operation."
> 
> Besides the above you then also need to grant access to the Microsoft.Web provider using the following: `Set-AzureRmKeyVaultAccessPolicy -VaultName keyvault-bhany3pt7zg6k -ServicePrincipalName abfa0a7c-a6b6-4736-8310-5855508787cd -PermissionsToSecrets get`
> 
> Source: https://azurecto.com/azure-resource-manager-certificates-from-keyvault/

this did the trick!! thanks so much. heads up, you can also do this through the azure portal

![image](https://github.com/Azure/azure-powershell/assets/143546934/a393ac6f-72c3-4636-a869-91b5273798bf)

I feel like the docs should be updated to include this
