### ISSUE TITLE
Azure Automation - Get-AzureRmResourceGroup : Run Login-AzureRmAccount to login.

### ISSUE THREAD

**Issue by jimlane** [Azure/azure-powershell#2960]
The AzureRM.profile and AzureRM.resources modules are added to new automation accounts automatically, but the included versions are 1.10. If you add additional ARM modules to your account (e.g. AzureRM.HDInsight) these will be of the latest version and will conflict. The fix is to add the latest versions of AzureRM.profile and AzureRM.resources to your automation account as well.

**Comment by markcowl** [comment]
@jimlane Yes, this is the case.  The newer versions of those modules use direct, exact  module depednencies, so this should now be easier.  This will be the experience you have every right to expect when this issue is resolved: #2392 

SInce this is not mitigated and since the underlying issue is a duplictae, closing in favor of the duplicated issue.
