### ISSUE TITLE
Add an option to control PromptBehavior in Add-AzureRmAccount

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3091]
### Description

Logging in always displays the username/password login dialog, because we are set to always prompt on login attempts.  Add an option for setting 'Auto' or 'No" prompt behavior so users will use the currently logged in credentials only.

**Comment by markcowl** [comment]
This scenario is covered by persistence

**Comment by sagawater** [comment]
@markcowl Would it be better to change PromptBehavior from Always to SelectAccount or have a way to control it via a SwitchParameter ? We have multiple accounts in our organization and we find ourselves typing our credentials several times a day. I don't see any impact of doing that change since SelectAccount seems to display the same page as Always option when there is no accounts in the current session.
