### ISSUE TITLE
platyPS documentation issues:

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-powershell#3155]
1. folder name in tools is incorrect (should be platyPSHelp not platyPS)
2. Installation does not mention the need to globally install platyPS (Install-Module platyPS)
3. Missing instructions on how to define which service to run help for (the service parameter) with an example (at this point I can't actually figure out how to do it).
4. There needs to be an assumptions/prereqs section indicating that it expects your help to exist in a specific path (under a help folder) and that your service naming convention must adhere to a specific naming convention. For example, if you are in resource manager it should be: $Service\Commands.$Service\help. This holds true for the full path specification as well.

**Comment by cormacpayne** [comment]
@begoldsm Hey Ben, let me try and clear up a few of these issues:

1. Do you mean it should be "platyPS not platyPSHelp"? Currently there is a folder named ["platyPSHelp"](https://github.com/Azure/azure-powershell/tree/dev/tools/platyPSHelp) in the tools folder. The folder should be called "platyPSHelp" because it contains the cmdlets and cmdlet help for the platyPSHelp module I wrote specific for partner teams to generate their help.

2. Though the documentation [does mention that you should install platyPS](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyps-help.md#description), I think that it needs to be more visible for teams using the tool. There's nowhere outside the [psd1 file](https://github.com/Azure/azure-powershell/blob/dev/tools/platyPSHelp/platyPSHelp.psd1#L54) and the snippet I previously linked that says you need to install platyPS first.

3. I generated [help for each of the cmdlets](https://github.com/Azure/azure-powershell/tree/dev/tools/platyPSHelp/help) that includes an example on how to run each cmdlet with the possible scenarios that could be presented. [Here](https://github.com/Azure/azure-powershell/blob/dev/tools/platyPSHelp/help/New-ServiceMarkdownHelp.md#examples) is an example generating the help for Profile, Storage, and TrafficManager (which requires the path be passed through). Is there anything else you think that I should include?

4. Same response to point 3, but I definitely can include more documentation on these paths. The examples say what the resulting paths will be, but I believe I can be more explicit about what paths are required and what their format should be. Any other suggestions?

Let me know if you have any other concerns or comments. Thanks for the feedback!

**Comment by begoldsm** [comment]
Responses!
1. I think it just needs to say that to import it the path is platyPSHelp and not platyPS (it just says platyPS in the document right now, which isn't a valid folder).
3/4. I think it would be good to make it explicit what the assumptions are for generation and validation. For example, the ADL help is not in the expected folder format and so cannot use platyPS at all as is (unless I am missing something?).

**Comment by cormacpayne** [comment]
Fix in PR https://github.com/Azure/azure-powershell/pull/3166
