### ISSUE TITLE
New-AzureProfile throws error when used with a ServicePrincipal

### ISSUE THREAD

**Issue by chrisrpatterson** [Azure/azure-powershell#332]
I created a Service Principal in my Azure directory based on the instructions found here http://blog.davidebbo.com/2014/12/azure-service-principal.html.  I am able to make this Service Principal just fine when using the Add-AzureAccount.  However, if I use New-AzureProfile I get an error AADSTS70001 stating the application with the identifier was not found.

**Comment by stankovski** [comment]
@chrisrpatterson can you please provide us with cmdlet parameters?

**Comment by bmoore-msft** [comment]
I'm able to repro using the following:

$secpasswd = ConvertTo-SecureString $pw -AsPlainText -Force
$creds = New-Object System.Management.Automation.PSCredential ($uid, $secpasswd)
$q = New-AzureProfile -SubscriptionId $subId -Tenant $tenant -ServicePrincipal -Credential $creds

**Comment by markcowl** [comment]
@chrisrpatterson yes, this is a known issue.  If you perform the above steps and then run an additional
```
'Add-AzureAccount -Credentials $creds -Profile $q
```

This should work around the issue.  The underlying problem is that the token cache used when creating the profile is the default (disk) token cache, which is not propagated to commands performed on the profile.
