### ISSUE TITLE
AzureStack: Wrong error message for Get-AzureRmVm

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#3521]
### Cmdlet(s)
Get-AzureRmVm
### PowerShell Version
5

### Module Version
AzureRm 3.4.0

### OS Version
BuildVersion                   10.0.14393.576

### Description
In AzureStack Environment, after logging in to the stack environment, if "Get-AzureRmVm" is run, it should give a friendly error message such as “Import modules consistent to azure stack” . Instead, it gives "Get-AzureRmVM : Run Login-AzureRmAccount to login."

### Script/Steps for Reproduction
Script used to add stack env and authenticate:
     
       Import-Module ~\AzureStack-Tools-master\Connect\AzureStack.Connect.psm1
       Add-AzureStackAzureRmEnvironment -AadTenant "msazurestack.onmicrosoft.com"
 
       Login-AzureRmAccount -TenantId "msazurestack.onmicrosoft.com" -EnvironmentName AzureStack 
       Get-AzureRmVM 

![image](https://cloud.githubusercontent.com/assets/21109279/23038209/0ffe6922-f43e-11e6-8bbe-626fbe9714e3.png)

**Comment by viananth** [comment]
@markcowl : Mark, this was pointed out by Mark Russinovich at a demo.

**Comment by bganapa** [comment]
The issue here is the use of TenantName instead of TenantID, but the confusing part, the command Get-AzureRMVM works after issuing a Get-AzureRMSubscription or Get-AzureRMResourceGroup cmdlet.. It means that Get-AzureRMSubscription is able to brab the token with TenantName and updates the cache and the subsequent Get-AzureRMVM finds the token in the cache.

There must be something unique in the way Get-AzureRMSubscription grabs the token that differs from Get-AzureRMVM

**Comment by markcowl** [comment]
@viananth @bganapa I think we have resolved this as version mismatch, please reopen with specific details, inclusing the debug traces, if you think this is somethign else.
