### ISSUE TITLE
New-AzureRmRoleAssignment gives not authorized exception. But does execute. (executed as Service Principal)

### ISSUE THREAD

**Issue by pascalnaber** [Azure/azure-powershell#3550]
### Cmdlet(s)
New-AzureRmRoleAssignment

the following permissions are added to the service principall:

Windows Azure Active Directory 6 application permissions - 6 delegated permissions (not able to select them all, only where Requires Admin=Yes)
Microsoft Graph - 20 application permissions - 20 delegated permissions (also not able to select them all)

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
Executing New-AzureRmRoleAssignment -RoleDefinitionName "Contributor" -ServicePrincipalName "123456-8494-4813-9282-7877878" -Debug 

results in an exception from which you can draw the conclusion that the statement has not executed.
But it has. The RoleAssignment is added.

### Debug Output
Body:
{
  "odata.error": {
    "code": "Authentication_Unauthorized",
    "message": {
      "lang": "en",
      "value": "Access denied to the specified API version."
    },
    "requestId": "ddf26afd-20f0-4f5c-a3d4-cf768eb91ccc",
    "date": "2017-02-26T17:12:26"
  }
}

New-AzureRmRoleAssignment : Exception of type 'Microsoft.Rest.Azure.CloudException' 
was thrown.
At line:1 char:1
+ New-AzureRmRoleAssignment -RoleDefinitionName "Contributor" -ServiceP ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleAssignment], CloudExce 
   ption
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignm 
   entCommand

### Script/Steps for Reproduction
**Execute as normal user**
Get-AzureRmRoleAssignment -ServicePrincipalName "123456-8494-4813-9282-7877878" -Debug

Result: no RoleAssignments

**Execute as Service Principal:**
Executing New-AzureRmRoleAssignment -RoleDefinitionName "Contributor" -ServicePrincipalName "123456-8494-4813-9282-7877878" -Debug

Result: exception

**Execute as normal user**
Get-AzureRmRoleAssignment -ServicePrincipalName "123456-8494-4813-9282-7877878" -Debug

Result: 1 RoleAssignments

**Comment by markcowl** [comment]
There are likely two issues at play here.  The first is this issue: #3407.  This is dues to be fixed when a new graph service rolls out in a few weeks.  The second is that your application needs to be authorized to use the graph api.

Note that, if you have the graph object id for the given object, you can bypass this issue by using the object id directly.  You may be able to work around this issue by getting the graph object id for the SPNs and Users in the role assignment, and simply using the object id instead of the friendly name.

Closing as a duplicate for now, please track progress in the duplicate issue.
