### ISSUE TITLE
Installed version number different from release 3.6.0

### ISSUE THREAD

**Issue by tohling** [Azure/azure-powershell#3574]
### Cmdlet(s)
All Azure PowerShell cmdlets

### PowerShell Version
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

### Module Version
3.6.0

### OS Version
Major  Minor  Build  Revision
-----  -----  -----  --------
6      3      9600   16406

### Description
I downloaded the latest release at
https://github.com/Azure/azure-powershell/releases/tag/v3.6.0-February2017

After installation, I noticed that the Version that was installed was 3.5.0.

Is this a typo or is the uploaded MSI at the link above incorrect?

### Debug Output
PS D:\Users\> (gmo -listavailable | where-object {$_.name -eq 'Azure'}) | select version, name, author, powershellversion |format-list

Version           : **3.5.0**
Name              : Azure
Author            : Microsoft Corporation
PowerShellVersion : 3.0

### Script/Steps for Reproduction
1. Download azure-powershell.3.6.0.msi from https://github.com/Azure/azure-powershell/releases/tag/v3.6.0-February2017

2, Run azure-powershell.3.6.0.msi 

3. Restart machine.

4. In PowerShell console, run the following,

(gmo -listavailable | where-object {$_.name -eq 'Azure'}) | select version, name, author, powershellversion |format-list

**Comment by cormacpayne** [comment]
@tohling Hey Ling, the `Azure` module is separate from the `AzureRM` module - the `Azure` module contains the RDFE cmdlets, where `AzureRM` contains the ARM cmdlets.

This is correct because these two versions are independent of each other - in the latest release, the `Azure` module is version 3.5.0, where the `AzureRM` module is version 3.6.0.

Let me know if you have any other questions!
