### ISSUE TITLE
Get-AzureRmSubscription should return "enabled" subscriptions only, by default.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#3680]
### Cmdlet(s)
Get-AzureRmSubscription.

### PowerShell Version
3.7.0.

### Module Version
AzureRM.profile at 2.5.0.

### OS Version
Windows 10.0.15063.0.

### Description
We should add a flag (e.g., `-All` or `-Full`) that lists "disabled" accounts along with "enabled" accounts, but the default should only list "enabled" accounts.

**Comment by markcowl** [comment]
What about 'warned' accounts?  What is the rationale for us redacting information by default, rather than allowing the user to filter? It is really, really easy for a user to do somethign liks this:

```Get-AzureRmSubscription | Where {$_.Status -eq "enabled"}```

Note that we already limit the subscriptions that a user can select to those that are 'enabled' or 'warned'.  Also, can you please share the source material / but associated with thsi request?  I wonder if this is a question about logins more than a question about listing subscriptions.

Offhand I'd say this is a breaking change, so it should wait until the May release.

**Comment by markcowl** [comment]
If we decide that we want to do this, we should let customers know ASAP, and then make the change in the next release.

**Comment by twitchax** [comment]
Makes sense.  Azure CLI 2.0 will likely display a warning.

https://github.com/Azure/azure-cli/issues/2645

**Comment by TiloGit** [comment]
fyi, now this get you only enabled one: (**state** instead of status)

`Get-AzureRmSubscription | Where {$_.State -eq "Enabled"}`
