### ISSUE TITLE
Azure PowerShell Improvement Discussion

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#3692]
This issue is meant to evaluate community needs and wishes.  Please comment with suggestions and upvote (thumbs up) comments which we should pay special attention to.

**Comment by AlexanderTroup** [comment]
It would be good to get parity on the Mac version of powershell.  I have a lot of trouble using the cmdlets on mac, and I'm trying to make platform agnostic deployment scripts.

**Comment by cparker4486** [comment]
I'd like to be able to import/export whole zones with the import being idempotent.

I want to be able to maintain a zone file and just import it any time I need to make a change.

`PS> MyZone_com.dns | Import-AzureRmDnsZone -Zone $zone` would be nice.

**Comment by jtuliani** [comment]
Good feedback, thank you. I'll track on our backlog.

**Comment by pixelicous** [comment]
It would be good if we can specify -nowait command on removing resources and other scripts.

I have an azure automation runbook that removes resource groups, everytime i run it, i have to wait through the whole process, paying for those minutes, instead of the provider doing the work while i do not wait

**Comment by cap273** [comment]
Since updating to Azure PowerShell 4.3.0, every Azure PowerShell cmdlet is returning "WARNING: System.ArgumentNullException: Value cannot be null." Further details in MSDN forum post:
https://social.msdn.microsoft.com/Forums/en-US/767c392d-d6a5-4ca9-870d-56c6c0de0ccd/azure-powershell-430-every-cmdlet-returning-warning-systemargumentnullexception-value-cannot?forum=azurescripting

**Comment by codegagan** [comment]
Can this be installed on Linux (Ubuntu) ?

**Comment by jschmitter** [comment]
I'm interested in an azuresdk/azure-powershell docker image with PowerShell 5.x.x  Is there any ETA on when that will be made available?

[Looks like 4.4.0 is the latest](https://hub.docker.com/r/azuresdk/azure-powershell/tags/)
