### ISSUE TITLE
Use Azure Batch with account key only without login

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-powershell#3749]
### Cmdlet(s)
Get-AzureRmBatchAccountKeys

And in extension:
New-AzureBatchJob
New-AzureBatchTask
...

### PowerShell Version
5

### Module Version
3.8

### OS Version
10.0.14393.953

### Description
It is not possible to use the Azure Batch cmdlets just with an account name and key. Instead `Get-AzureRmBatchAccountKeys` has to be invoked which requires that there is an active login session.

To me this doesn't make sense at all, because:
1. Libraries in other languages support that usecase.
2. For other Azure services like Storage it is actually possible, like with `New-AzureStorageContext` which accepts an account name and key without needing a login.

Note that another user also asked about this on [StackOverflow](http://stackoverflow.com/questions/39289638/how-to-list-azure-batch-pools-from-powershell-using-the-account-key).

**Comment by cormacpayne** [comment]
@matthchr Hey Matt, would you mind taking a look at this issue?

**Comment by matthchr** [comment]
@cormacpayne - I've actually thought about this some before. It's doable but there are a few issues.

1. We colocate the data-plane and management-plane operations in the same powershell module, and while it is true that you could do all of the dataplane operations without having an active login session, you can't do any management plane operations since they don't support sharedkey. I'm not sure that it'd be immediately obvious what you could/couldn't use sharedkey with (but I guess you could just look at what takes the `-BatchContext` parameter).
2. As a service (and I think as Azure as a whole) we are moving away from funky one-off authentication mechanisms (i.e. shared key) towards AAD. The Batch dataplane actually supports AAD now in addition to shared key, and in other places such as the portal and the CLI we use AAD auth for both the data plane and the management plane operations and we don't use shared key at all.

So this basically comes down to: Yes, we can definitely do this, but does it make sense to do given the broader direction of things?

@cormacpayne - I assume most other (management only) powershell modules only accept AAD auth, right? We could change Batch to be like that as well, which might make more sense from a consistency standpoint...

**Comment by cormacpayne** [comment]
@matthchr thanks for this information. Let me assign this back to our team for discussion during our next triage.

**Comment by matthchr** [comment]
For some more context, the whole `Get-AzureRmBatchAccountKeys` thing to use the dataplane commandlets isn't even required anymore, you can just use AAD for dataplane through powershell even today. So we have support for sharedkey but it doesn't really "get you much" (mostly just there for legacy reasons).

You can see the changelog note for AAD auth in Batch [here](https://github.com/Azure/azure-powershell/blob/preview/ChangeLog.md#2017118---version-500).

**Comment by matthchr** [comment]
Given the discussion above and the fact that this has been open for 2 years I think I am going to close it for now.
