### ISSUE TITLE
Add-AzureRmAutoscaleSetting

### ISSUE THREAD

**Issue by ronbok** [Azure/azure-powershell#3774]
v3.6

Add-AzureRmAutoscaleSetting -Location $AzureRegion -Name "AutoScale" -ResourceGroup $AzureRGName -TargetResourceId $VMScaleSet.Id -AutoscaleProfiles $VMSSProfileCfg

Why can we not create more than one VMSS rule, on separate scale sets, with the same name?  This will fail if you have two VMSS instances and name the rule "AutoScale" the same name.

**Comment by ronbok** [comment]
Additionally why are these rules not deleted when you delete a scale set?  They hang around and the prevent you from using the same name.

**Comment by singhkays** [comment]
Sorry @sphibbs, I don't own this area. Adding @gatneil & @gbowerman since this seems related to VMSS.

**Comment by gatneil** [comment]
You can't have two autoscale settings of the same name in the same resource group because an autoscaleSetting is a resource just like any other: it must be unique per its type within the resource group.

And the reason they don't get deleted when the target resource is deleted is similar: it's its own separate resource. Some folks would want the settings deleted along with the target resource, while others would find it confusing since it's exposed as a separate resource; plus, resource groups are intended to allow you to group resources with the same lifecycle, so could you delete the resource group instead of just the scale set?

Hope this helps! :)

**Comment by ronbok** [comment]
This is the standard Microsoft mantra and talking out of both sides of their mouth.  First there's an 800 limit in the number of RG's per subscription.  Then the mantra is to limit the number of subscriptions.  Then there's the management and naming of all of these RGs from an RBAC perspective in an automated fashion.  Most clients end up with simple RGs like 'Development','Test', 'QA', 'Production' for a given project, so deleting an RG here to clean up an autoscale setting is insanity.  Instead it necessitates that the PowerShell code has to check for the existence of the autoscale rule first prior to creation and either delete the old rule or create a new one with another name in support of the scale set.

**Comment by ronbok** [comment]
My point being...RGs are MORE about RBAC than they are about Life Cycle of the resources within them.

**Comment by gatneil** [comment]
So, folks can always choose to use resource groups in whatever way they see fit, but their use as a lifecycle management tool is an explicit benefit and design decision (see number 1 in the list of important factors to consider when defining your resource group): https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview#resource-groups. This is probably one of the reasons we allow 800 RGs per sub; that's quite a lot! :). But I do see your point; RGs are both about RBAC and lifecycle management, so if you set up RGs thinking about one, you might not have the most flexibility on the other; is it possible to have a lot of RGs, each of which is configured with RBAC rules based on whether the RG is meant for dev/test/qa/prod?

**Comment by shahabhijeet** [comment]
@ronbok hope this clarifies. Closing it.
