### ISSUE TITLE
Create common code and pattern for handling many pages of list data.  Use Get-AzureRmAdApplication as one of the examples

### ISSUE THREAD

**Issue by munsora** [Azure/azure-powershell#3928]
### Cmdlet(s)
Get-AzureRmADApplication
### PowerShell Version
5.1.14409.1005
### Module Version
AzureRM.Resources  3.7.0
### OS Version
10.0.14409.1005
### Description
Calling commandlet wide open (without any parameters) returns exactly and only 100 objects.  Documentation specifies "If no parameter is provided, it fetches all applications under the tenant".
### Script/Steps for Reproduction
Execute Get-AzureRmADApplication > known/desired application not in objects returned
Execute Get-AzureRmADApplication | Where { $_.DispllayName -like "*KnownName*" > known/desired application object not returned
Execute Get-AzureRmADApplication -DisplayNameStartsWith "KnownName" > known/desired application object is returned
Execute (Get-AzureRmADApplication).Count > 100

**Comment by cormacpayne** [comment]
@munsora [the cmdlet does not appear to do any paging](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.Resources/Models.ActiveDirectory/ActiveDirectoryClient.cs#L694), so it is going to return only the first page of applications. We are looking to implement [`SupportsPaging`](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.Resources/Models.ActiveDirectory/ActiveDirectoryClient.cs#L694) for cmdlets (that are applicable) in the future so that the users can iterate over the pages that are returned, rather than receiving just the first page or every single page at once.

**Comment by maddieclayton** [comment]
Closing as duplicate
