### ISSUE TITLE
Get-AzureResourceGroup tags property

### ISSUE THREAD

**Issue by DexterPOSH** [Azure/azure-powershell#397]
Get-AzureResourceGroup cmdlet returns PSResourceGroup with property Tags which are the Key-Value pairs , but the object's tag property returns the key of the tags as literal 'Name' and 'Value'. This is counter intuitive in my opinion.

For Example - added a tag Environment (Key)--> LAB (Value) to my Resource Group and would expect Tag to contain Environment as the key in the hashtable returned. 

**Current Result**
PS> $ResourceGroups = Get-AzureResourceGroup | Where tags
PS>$ResourceGroups[0].tags

Name                           Value
----                           -----
**Value**                          LAB
**Name**                           Environment
**Value**                          TestValue
**Name**                           TestKey

----

**Expected Result**

PS> $ResourceGroups = Get-AzureResourceGroup | Where tags
PS>$ResourceGroups[0].tags

Name                           Value
----                           -----
**Environment**                          LAB
**TeskKey**                           TestValue

**Comment by ravbhatnagar** [comment]
Unfortunately, currently the way the tag API is implemented is that it supports tagging resources with one value (ex - Lab) or two values (ex - Environment = Lab). We will look into how we can provide some better representation on top of it.

**Comment by ravbhatnagar** [comment]
#726

**Comment by ravbhatnagar** [comment]
We have a PR ready for fixing the usability of tags. This will be addressed as part of that. Since it was a breaking change we have postponed it to June release and added a deprecation message to state about the coming changes.

**Comment by ravbhatnagar** [comment]
Since this turned out to be a change impacting a lot of cmdlets from different teams, we are pushing this out by a month. The reason is to fix this across the board for all Azure cmdlets and give some warning about the upcoming change to customers of all those different cmdlets. The warning we added in added the last release was only to a subset of these cmdlets. 

So in the June release, all the cmdlets using this param will show this warning and then we will actually change it in the July release.

**Comment by ravbhatnagar** [comment]
Fixed in Aug Release
