### ISSUE TITLE
Publish-AzureWebsiteProject throwing Cannot retrieve the dynamic parameters for the cmdlet error

### ISSUE THREAD

**Issue by DreamingDevs** [Azure/azure-powershell#398]
I installed Microsoft Azure PowerShell – May 2015 release downloaded from here - http://azure.microsoft.com/en-us/downloads/

I created a AzureWebsite - **New-AzureWebsite -Location "East US" -Name "abcpqr"**

When i tried to publish a Visual Studio 2013 ASP.Net MVC 4 Project using - 
**PS C:\WebForlder> Publish-AzureWebsiteProject -ProjectFile SampleWeb.csproj -Configuration Debug -Name abcpqr**

I am getting following error - 
```
Publish-AzureWebsiteProject : Cannot retrieve the dynamic parameters for the cmdlet. Object reference not set to an instance of an object.
At line:1 char:1
+ Publish-AzureWebsiteProject -ProjectFile SampleWeb.csproj -Configuration De ...
 + CategoryInfo          : InvalidArgument: (:) [Publish-AzureWebsiteProject], ParameterBindingException
 + FullyQualifiedErrorId : GetDynamicParametersException,Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject
```

how can I resolve this error? I tried different combinations with the same CSPROJ and Publish-AzureWebsiteProject, but no luck.

**Comment by LeviBotelho** [comment]
+1

**Comment by terrymandin** [comment]
+1

**Comment by jasonmitchell** [comment]
I've got this same error in the November 2015 release.  I found that the error only happens when the ConnectionString parameter has not been specified so giving a ConnectionString hash table may be a workaround for now.

The exception is thrown in the getter of the ```WebsiteBaseCmdlet.WebsitesClient``` property when it is called in ```PublishAzureWebsiteProject.GetDynamicParameters()```.  This is because ```AzureSMCmdlet.Profile``` is null when this method is called.  The Profile does not appear to be set until ```BeginProcessing()``` has been called which, according to [MSDN](https://msdn.microsoft.com/en-gb/library/ms714429(v=vs.85).aspx), is after dynamic parameters are bound.
