### ISSUE TITLE
"Environmentname" parameter is missing in "Add-AzureRmAccount" from v4.0

### ISSUE THREAD

**Issue by ciisuke** [Azure/azure-powershell#3985]
This cause template deployment from Visual Studio 2017 not functional.  It looks like VS2017 use "Environmentname" parameter for choosing deployment target.

**Comment by markcowl** [comment]
@ciisuke Yes, this change is documented here: https://github.com/Azure/azure-powershell/blob/preview/documentation/release-notes/migration-guide.4.0.0.md#add-azurermaccount-breaking-changes 

Keeping this alive, as we will likely add a parameter alias in the next release.

**Comment by sphibbs** [comment]
You have a few options to work around the issue until a fix comes out in our June 2017 Release. 
1) Right click on Deploy-AzureResourceGroup.ps1 in your solution. Open with PowerShell ISE. You can now run the script. You will need to login using either Login-AzureRmAccount or Add-AzureRmAccount.
2) Roll back to a previous version of Azure PowerShell. 
   -First Remove AzurePowerShell 4.0
      - If you installed via WebPi or MSI remove via Add Remove Programs
      - If you installed from the PowerShell gallery, delete all azure folders in C:\Program 
         Files\WindowsPowerShell\Modules.
   -Install a previous version of Azure PowerShell from the gallery with the following PowerShell cmd
        Install-Module AzureRm -RequiredVersion 3.8

**Comment by ciisuke** [comment]
Thanks. I'll use Azure PowerShell v3.8 till next version is out.

**Comment by ajklotz** [comment]
I have PowerShell v5.1.14393.953 and the AzureRm.profile version is 3.0.0 (As shown from **Get-Module -ListAvailable AzureRm.profile**) and I'm having errors performing VSTS tasks that use AzCopy to copy files to Azure resources. 

I don't understand how the versioning is working here. I guess the source code for the cmdlet has changed but the version of the AzureRM.profile module is not incrementing as development occurs. I see other modules of the AzureRm module set to version 4.0.0.

**Comment by sphibbs** [comment]
Each modules versions following semantic versioning. Not all modules update each release, so they versions won't change in that caes. AzureRM is the roll up module and will bump major versions if any of the modules installed with it have a breaking change.  The last version of AzureRm.Profile was 2.8.0, with the breaking change release the version bumped up to 3.0. We understand how this can be confusing. 

Due to customer feedback we have decided to release an update. I expect it to be out in the next couple days. 

Deleting the folders is nuclear. We see issues with Uninstall-Module with nested modules like AzureRM. Deleting the folders is a sure fire way to remove. 

Yes, you could write a Function Add-AzureRmAccount using -EnvironmentName.

**Comment by ajklotz** [comment]
@sphibbs Thanks for the quick feedback! I appreciate your time.

**Comment by ErikvanMaanen** [comment]
@ciisuke and for all people using VSTS, a workaround for now would be to modify the cached version of the cmdlet's on the agents.

The following PS command can do so:  (assuming agents on disks F,G,and H.)

#('F:\','G:\','H:\')|%{SL $_;gci -re \*Agent*\_Work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\*\InitializeFunctions.ps1}|%{$_.fullname;sc $_.fullname -Force ((gc $_.fullname).Replace('-EnvironmentName $environmentName','-Environment $environmentName'))}

**Comment by markcowl** [comment]
This is a solution, but I would worry that it might be fragile over time.  There should be a version out that fixes this issue within a day or two, btw.
