### ISSUE TITLE
Get-AzureRmSqlServer 'ServerName' parameter and property should be called 'Name'

### ISSUE THREAD

**Issue by SiloReed** [Azure/azure-powershell#4093]
### Cmdlet(s)
Get-AzureRmSqlServer

### PowerShell Version
PSVersion                      5.1.15063.296 
### Module Version
AzureRM.Sql 3.0.0 
### OS Version
BuildVersion                   10.0.15063.296

### Description
Get-AzureRmSqlServer's ServerName parameter and property should be called Name to be consistent with other cmdlets such as Get-AzureRmAnalysisServicesServer and Get-AzureRMVM
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Get-AzureRmSqlServer -ResourceGroupName rg-ODSTest -Name azrodstst01 
fails with:
Get-AzureRmSqlServer : A parameter cannot be found that matches parameter name 'Name'.

**Comment by cormacpayne** [comment]
@akromm Hey Adam, would you mind taking a look at this issue?

**Comment by akromm** [comment]
We could add an Alias for the parameter name. 

For the property name (I assume you are referring to the property on the server object that is returned) we have it as "ServerName" so that piping the output of one cmdlet into another works.

eg: 
Get-AzureRmResourceGroup | Get-AzureRmSqlServer | New-AzureRmSqlDatabase ...
will create a new database in every server in every resource group in your subscription.

**Comment by jaredmoo** [comment]
Thanks for the suggestion @SiloReed . We will investigate and address this soon, but we have some other higher priority fixes for SQL cmdlets that we are working on first. Cheers

**Comment by akromm** [comment]
Resolved with #4110
