### ISSUE TITLE
Add-AzureAccount is slow

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#418]
Now that accounts (as opposed to mgmt certs) is pretty much a requirement to work with Azure Powershell, I've notived that add-azureaccount is incredibly slow. running "measure-command {add-azureaccount}" and typing my username/password as soon as I'm able to it still takes the cmdlet a full 64 seconds to complete. I have around 10 subscriptions that I have admin rights to. The logon mechanism needs to be a lot faster than it is today. (get-azuresubscription is also unbearably slow)

**Comment by hovsepm** [comment]
@trondhindenes,

Could you add debug log as well? You can do it by first executing 
```
$DebugPreference = "Continue"
``` 
and then calling Add-AzureAccount. That will help us understand your scenario. 

At the same time you if you know which tenants you will be using use -Tenant parameter of the cmdlet narrow down server communication to only that tenant.

**Comment by trondhindenes** [comment]
I'd rather not send the debug log openly as it contains subscription ids
and some user accounts. Is there anywhere I can send it to you privately?

The "tenant" parameter is a good tip, I'll be using that when I can.

**Comment by markcowl** [comment]
@trondhindenes If you have many subscriptions in different tenants, the intention is to use the -tenant parameter to select only the tenant that you nedd to use when logging in - the reason is that powershell must acquire a token against each tenant before it can list subscriptions in that tenant.  You will notice this in the portal as well - you need to select a different tenant in order to view subscriptions in any but your default tenant.

If you are still seeing issues with the -tenant parameter, we will need additional info to debug.  Please respond and we'll find a secure mechanism to transmit your log data.
