### ISSUE TITLE
Set-AzureSubscription should accept pipeline objects

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#429]
This used to work:
Get-AzureSubscription -Current | set-AzureSubscription etc, however it doesn't anymore. Please re-add pipline support to the set-azuresubscription cmdlet.

**Comment by stankovski** [comment]
@trondhindenes thank you for filing this. We can repro the issue.

**Comment by markcowl** [comment]
@trondhindenes This is schedule for the late March release

**Comment by markcowl** [comment]
### Root Cause
Mismatch in output properties in Get-AzureSubscription and input parameters for Set-AzureSUbscription

### Proposed Solution
- Add an alias to each Parameter to support tne new output object properties for Get-AzureSubscription
- Add a mocked scenario test to verify the functionality

### Cost (Work Units): 2

**Comment by hovsepm** [comment]
Fixed in dev branch, will be available in June release
