### ISSUE TITLE
Azure Runtime Error

### ISSUE THREAD

**Issue by HeroSpha** [Azure/azure-powershell#4333]
Im working on an app, i want to create database in azure. First of all i get the database and copy it to another server inside a pool. I can get the database successful, but when i create the database i get an error *Long running operation failed with status 'Failed'*. When i debugged the issue, the error comes Microsoft.Rest.ClientRuntime.azure im using version 3.38

**Comment by cormacpayne** [comment]
@HeroSpha the description you provided sounds like you are using the Azure SDK for .NET instead of Azure PowerShell. If so, please close this issue and open a new one in the [Azure SDK for .NET repository](https://github.com/Azure/azure-sdk-for-net).

If this is an issue you are having with Azure PowerShell, please provide the script that you are running.

**Comment by HeroSpha** [comment]
Yes, sorry for my mistake the issue have been resolved..
