### ISSUE TITLE
Not possible to set multiple rights with Add-AzureRmIotHubKey

### ISSUE THREAD

**Issue by pihai** [Azure/azure-powershell#4350]
### Cmdlet(s)
Add-AzureRmIotHubKey

### PowerShell Version
5.1.14393.0

### Module Version
2.2.1

### OS Version
10.0.14393.0

### Description
I can't create a new IoT-Hub key with multiple rights. Additionally existing keys get messed up too.
Azure Region: West Europe
Tier: F1

### Script/Steps for Reproduction

The default keys of a new IoT Hub look like this:

![iot-hub](https://user-images.githubusercontent.com/1460563/28452187-b2593788-6df1-11e7-9b4b-b2f9d6c3b958.png)

Then I wanted to add a new key with "RegistryRead" and "ServiceConnect" right with the following command:

```
$r = [Microsoft.Azure.Commands.Management.IotHub.Models.PSAccessRights] "RegistryRead, ServiceConnect"
Add-AzureRmIotHubKey -ResourceGroupName "xxx" -Name "xxx" -KeyName "foo" -Rights $r
```

The command finishes successfully and results in the following keys:

![iot-hub-after](https://user-images.githubusercontent.com/1460563/28452252-146c331c-6df2-11e7-98bc-528e354df814.png)

The key "foo" does only have one right and the "iothubowner" key has changed.

**Comment by cormacpayne** [comment]
@rkmanda Hey Roopesh, would you mind taking a look at this issue?

**Comment by rkmanda** [comment]
@chieftn who is looking into this

**Comment by sokhals** [comment]
Hey,

I have also been facing the same issue when trying to assign the rights.

Thanks!

**Comment by cormacpayne** [comment]
@rkmanda @chieftn any update on this issue?

**Comment by rkmanda** [comment]
@Rick Kessler<mailto:rkessler@microsoft.com> / @Ilie Luican<mailto:iliel@microsoft.com> can you please take a look?

**Comment by rkmanda** [comment]
Sapan, can you please have a look?

Thank you,
Ilie.

________________________________
From: Roopesh Manda
Sent: Thursday, July 5, 2018 5:49:50 PM
To: Rick Kessler; Ilie Luican
Cc: Mention; Azure/azure-powershell; Azure/azure-powershell
Subject: RE: [Azure/azure-powershell] Not possible to set multiple rights with Add-AzureRmIotHubKey (#4350)

@Rick Kessler<mailto:rkessler@microsoft.com> / @Ilie Luican<mailto:iliel@microsoft.com> can you please take a look?

**Comment by rkmanda** [comment]
This issue relates back to newtonsoft -- here is my analysis from last summer:

1.  The command functions by taking user input and mapping it to SDK types.
2.  The command utilizes Newtonsoft's serialization / deserialization capabilities to convert listed access rights to enum type AccessRights types (using IoTHubUtils).
3.  AccessRights uses a StringEnumConverter to map string enumerations to the right value.
4.  V6.0.x of Newtonsoft has a bug wherein these values are not properly respected upon deserialization.
5.  The conversion subsequently yields the incorrect AccessRights enumeration.

This issue has been resolved in later versions of Newtonsoft.  But it appears the entire module uses 6.0.8.  Are there any plans to make this update, 6.0.8 is four major revisions (and over three years) out of date.  The only other workaround would be to manually reformat the AccessRights to reflect the current value.

This issue is only impacting the PowerShell module.  We have verificed that the CLI does not have this issue.




I suspect we are still in dll hell with this issue.


Rick Kessler
rkessler@microsoft.com | 703-899-4401 | @rkessler

________________________________

**Comment by mguirao** [comment]
Hey, 
Do you have an update for this issue ?
I'm using module 3.1.2 and this is still the case.

**Comment by jlian** [comment]
We will need to look into if this is still occurring with the new Az PowerShell commands

**Comment by jlian** [comment]
https://msazure.visualstudio.com/One/_workitems/edit/4979335 Target Nov
