### ISSUE TITLE
Update Jenkins job to build on-schedule, share build artifacts

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4439]
### Description

- [x] Verify Jenkins CI job runs tests appropriately
- [x] ~~Update On-dmenad build to build and run all tests~~
- [x] Set up weekly schedule for runs
- [x] ~~(if time) Update Jenkins CI sign job to build latest (default), stack, or all~~

### Cost: 2

**Comment by MiYanni** [comment]
@markcowl Is this task outdated? It seems that you added the Stack building logic to the `build.proj` in September. Since then, it looks like the PowerShell job on Jenkins has been building the Stack.sln during every build. What is the ask here? Since `/p:Scope` is not specified when the build is ran, it defaults to 'all', which includes Stack.

**Comment by markcowl** [comment]
Complete
