### ISSUE TITLE
Register-AzureRmAutomationDscNode - No Progress Info when it apply the DSC configuration in backend

### ISSUE THREAD

**Issue by pankajads** [Azure/azure-powershell#4481]
### Cmdlet(s)
Register-AzureRmAutomationDscNode
### PowerShell Version
5.1

### OS Version
10.0.14393.1480

### Description
When I run Register-AzureRmAutomationDscNode, It register the node and execute dsc configuration. For example, If my configuration takes 30 min to apply, it won't show the dsc config apply progress until it completes.
There are some cmdlets available but can execute them to see report once above command gets completed.
I am looking for continuous real time progress status  when DSC gets apply to azure VM. Think from end user perspective who doesn't know azure and has given pipeline in jenkins (or any other tool) to run to build Infra for their respective application. So these type of users would be able to see the progress at high level what happening rather than waiting for 10-30 min to DSC to finish.
I know we could see progress if I apply dsc in push mode or in ansible. 
Looking for progress info in Register-AzureRmAutomationDscNode cmdlet.

Posted query in MSDN forum - https://social.msdn.microsoft.com/Forums/en-US/3070c8bc-fabe-406d-afc1-f6f5bae30684/azure-automation-dsc-how-i-could-see-detailed-log-of-dsc-progress-when-appying-dsc-configuration?forum=azureautomation

### Debug Output
NA

### Script/Steps for Reproduction
may run above cmdlet and won't see any progress. Should have option to see logging what happening in backend instead of waiting. Imagine if DSC take 20-30 min to finish.

**Comment by cormacpayne** [comment]
@vrdmr Hey Varad, would you mind taking a look at this issue?

**Comment by pankajads** [comment]
Any update on this? I would be happy to contribute if some one guide me.

**Comment by arcotek-ltd** [comment]
This is certainly something that is needed. We need to know exactly what is going on. My configuration takes ~4 hours to complete because it's restoring a large database, installing VisualStudio etc.

If one uses a template ([such as this, written by @mgreenegit](https://github.com/Azure/azure-quickstart-templates/blob/d663d5eb0245d72da0eee766a81bc3650ed53da1/101-automation-configuration/nested/provisionConfiguration.json)) to on board a VM, there is no sign of it in Azure Automation > DSC Nodes, even though the extension has provisioned successfully.

You also need to look at the DSC logging in Azure. It's virtually non-existent. What there is, only tells half the story, like messages that don't tell one where the error actually is. For compilations in Automation Accounts the only way to get any verbose output is to use Write-Warning in a configuration / resource (but that only picks up compilation errors). For example, compilation failed. The only output is:
```
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot bind argument to parameter 'DiskConfigArray' because it is null.
```
This is an **exception** but under "Monitoring" there are no errors and "All Logs" just shows the warnings. Apart from the warnings I've added in place of verbose output, the others are all:
```
The 'Microsoft.PowerShell.Management' module was not imported because 
the 'Microsoft.PowerShell.Management' snap-in was already imported.
``` 
I know! But how do I stop it. `Import-DscResource` has no `-ErrorAction` parameter.

Output example (No errors and "All Logs" has no `Write-Verbose` entries):
![alt text](http://blog.thingsgeeky.co.uk/wp-content/uploads/2018/03/AzureDSCoutput.png "Azure DSC Output")




 
Where is the GIT repo for DSC. The only thing I've ever been able to find is the linux DSC extension. Where's the Windows one "Microsoft.Powershell.DSC" and for that matter, Azure DSC resources. The only thing we can raise issues against is Azure-PowerShell.

**Comment by mbreakey3** [comment]
Register-AzureRmAutomationDscNode (or Register-AzAutomationDscNode as it's now called) is meant to just register the node with the automation pull server. To get the status of the applied configuration you should use Get-AzAutomationDscNode
