### ISSUE TITLE
Azure credentials Error in Azure PS Module 3.5 and above

### ISSUE THREAD

**Issue by zaidmohd** [Azure/azure-powershell#4581]
### Cmdlet(s)
Publish-AzureWebsiteProject

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
PSVersion                      5.1.15063.502

### Module Version
Azure Module Version 3.5 and above

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
Windows 10 or 2012 R2

### Description
I am looking for guidance if anyone faced similar issue of Azure authentication failing with Azure Module version 3.4. 

We have a script which is used to Publish Web Packages to Azure websites, it is doing this through ASM command Publish-AzureWebsiteProject. The script works fine with Azure module version 3.4, but not with any version above this.

Error:
Publish-AzureWebsiteProject : Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials.

At C:\DigitalPlatform-CI-v5\2017.06.28.09\Application\Modules\Microsoft.Mdp.Deploy.Common.psm1:299 char:5
+ ...             Publish-AzureWebsiteProject -Name $webSiteName -Package $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject

Below workaround works, but it uses AzurePublishSettingsFile

1.	Check the azure account using “get-azureaccount”
2.	Remove all the account “remove-azureaccount -name <accountname>
3.	Login to Azure in the default browser and select the correct subscription and run the get the azure publish setting file using command - Get-AzurePublishSettingsFile 
4.	Import the downloaded Azurepublishsetting file using command– Import-AzurePublishSettingsFile
5.	Verify the account using command - get-azureaccount 
6.	Run the deployment script and when it asks for credential, do not provide anything and just close the credentials window

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Publish-AzureWebsiteProject -Name $webSiteName -Package $package -Slot $slotName -ErrorAction Stop

**Comment by markcowl** [comment]
@zaidmohd can you provide a debug log, per the instructiosn above?  This will help in debugging the issue

**Comment by ck-prabhakercirium** [comment]
Hi, I'm getting the same error as well. 
I am trying to publish an Azure Website using the "Publish-AzureWebsiteProject" command, and this seems to work only if I use first Import the PublishSettings file. 
If I want to publish by trying to select a Subscription, it fails with the error mentioned in this log.

Here is the output that I got:
PS D:\AwareProvisioner\Aware.DemoPlatform\SimulateProvisioner\bin\Debug> Publish-AzureWebsiteProject -Name $WebSiteName -Package $PackagePath -Debug 
DEBUG: 17:24:37 - PublishAzureWebsiteProject begin processing with ParameterSet 'Package'.
DEBUG: 17:24:39 - using account id 'ck@pratdevilhotmail.onmicrosoft.com'...
VERBOSE: [Start]    Publishing package C:\DemoPlatform\PackageStore\14c763c3-97eb-46d3-bd26-f7bd36e80fe1\1.0.3\WebPortal.zip
DEBUG: [Common.Authentication]: Authenticating using Account: 'ck@pratdevilhotmail.onmicrosoft.com', environment: 'AzureCloud', tenant: 'e77da93f-c8fd-41ea-9afe-7bd2efc6c41a'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'e77da93f-c8fd-41ea-9afe-7bd2efc6c41a', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-
227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/e77da93f-c8fd-41ea-9afe-7bd2efc6c41a/', CorrelationId: '00000000-0000-0000-0000
-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'e77da93f-c8fd-41ea-9afe-7bd2efc6c41a', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a
258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/20/2017 11:54:41: d476d316-bd75-492b-9a81-5e6ba1be120a - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/e77da93f-c8fd-41ea-9afe-7bd2efc6c41a/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (0 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 09/20/2017 11:54:41: d476d316-bd75-492b-9a81-5e6ba1be120a - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/20/2017 11:54:41: d476d316-bd75-492b-9a81-5e6ba1be120a - TokenCache: No matching token was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 09/20/2017 11:54:41:  - WindowsFormsWebAuthenticationDialogBase: Navigating to 'https://login.microsoftonline.com/e77da93f-c8fd-41ea-9afe-7bd2efc6c41a/oauth2/authorize?resource=https:/
/management.core.windows.net/&client_id=1950a258-227b-4e31-a9cf-717495945fc2&response_type=code&haschrome=1&redirect_uri=urn:ietf:wg:oauth:2.0:oob&login_hint=ck@pratdevilhotmail.onmicrosoft.c
om&client-request-id=d476d316-bd75-492b-9a81-5e6ba1be120a&prompt=attempt_none&x-client-SKU=.NET&x-client-Ver=2.28.3.860&x-client-CPU=x64&x-client-OS=Microsoft Windows NT 6.3.9600.0&site_id=50
1358&display=popup'.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 : 
DEBUG: 09/20/2017 11:54:42: d476d316-bd75-492b-9a81-5e6ba1be120a - <RunAsync>d__0: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: user_interaction_required: One of two conditi
ons was encountered: 1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, because user interaction was required. 2. An error occurred during a silent web auth
entication that prevented the http authentication flow from completing in a short enough time frame
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.PreTokenRequest()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
	ErrorCode: user_interaction_required

DEBUG: [Common.Authentication]: Received exception User Interaction is required to authenticate this user. Please authenticate using the log in dialog. In PowerShell, execute Login-AzureRMAcc
ount for Azure Resource Manager cmdlets or Add-AzureAccount for service management cmdlets., while authenticating.
VERBOSE: [Fail]     Publishing package C:\DemoPlatform\PackageStore\14c763c3-97eb-46d3-bd26-f7bd36e80fe1\1.0.3\WebPortal.zip
Publish-AzureWebsiteProject : Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials.
At line:1 char:1
+ Publish-AzureWebsiteProject -Name $WebSiteName -Package $PackagePath  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject
 
DEBUG: 17:24:51 - PublishAzureWebsiteProject end processing.
DEBUG: 17:24:51 - PublishAzureWebsiteProject end processing.

**Comment by zaidmohd** [comment]
Adding Nisha


________________________________

**Comment by markcowl** [comment]
@ck-prabhakercirium Publish-AzureWebsiteProject is an RDFE cmdlet, you must login using Add-AzureAccount (not Add-AzureRmAccount) to be authenticated to use this cmdlet.

@zaidmohd Closing because there is no debuyg log for the original issue.  If you can get a debug trace for this, please reopen.

**Comment by zaidmohd** [comment]
Gentle reminder
Regards,
Nisha
