### ISSUE TITLE
New-AzureRmNetworkSecurityRuleConfig is incredibly slow

### ISSUE THREAD

**Issue by lesterw1** [Azure/azure-powershell#4720]
### Cmdlet(s)
New-AzureRmNetworkSecurityRuleConfig

### PowerShell Version
5.1.14409.1012

### Module Version
AzureRM.Network 4.4.0

### OS Version
10.0.14409.1012

### Description
This cmdlet is incredibly slow... over 2 seconds to create a single instance.  Try it yourself: 
Measure-Command { $r = New-AzureRmNetworkSecurityRuleConfig -Name "Test" } .
It is MUCH faster to generate your own object instance and then fill in the property values. For example:

$ruleConfig = New-Object Microsoft.Azure.Commands.Network.Models.PSSecurityRule
$ruleConfig.Name = "Rule Name"
$ruleConfig.Direction = "Outbound"
$ruleConfig.SourceAddressPrefix = [System.Collections.Generic.List`1[System.String]] "10.1.0.0/16,172.16.1.0/24".Split(",")
# and so on for the other property values

### Debug Output
ps1> Measure-Command { $r = New-AzureRmNetworkSecurityRuleConfig -Name "Test" -Debug } 
DEBUG: 16:49:11 - NewAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet 'SetByResource'.
DEBUG: 16:49:12 - using account id 'wateles@msci.com'...
DEBUG: AzureQoSEvent: CommandName - New-AzureRmNetworkSecurityRuleConfig; IsSuccess - True; Duration - 00:00:03.5134688; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 16:49:15 - NewAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 16:49:15 - NewAzureNetworkSecurityRuleConfigCommand end processing.

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 80
Ticks             : 40807791
TotalDays         : 4.72312395833333E-05
TotalHours        : 0.00113354975
TotalMinutes      : 0.068012985
TotalSeconds      : 4.0807791
TotalMilliseconds : 4080.7791

### Script/Steps for Reproduction
$r = New-AzureRmNetworkSecurityRuleConfig -Name "Test"

**Comment by cormacpayne** [comment]
@lesterw1 thanks for opening this issue! Taking a look at this cmdlet, it looks like it takes a few milliseconds to actually create the object and write it to the output stream (which is equivalent to what you mentioned above about directly creating the object and populating the properties), so the issue lies somewhere in the steps before the `ExecuteCmdlet` method is run. One thing I noticed was that the static `AutoMapper` used by Network cmdlets is instantiated whenever a cmdlet is run, so this might cause some delay. I currently have a [pull request](https://github.com/Azure/azure-powershell/pull/4679) out to update how `AutoMapper` is being used throughout modules, which should help reduce this delay - testing locally with this branch, I'm consistently getting 300-600ms execution time for the cmdlet.

I've added the `Investigate` label so our team can return to this at a later time and see if there's anything else we can do to reduce the execution time on cmdlets of this type. Please let me know if you have any questions (or find any other cmdlets with a similar problem!)

**Comment by cormacpayne** [comment]
CC: @DeepakRajendranMsft

**Comment by cormacpayne** [comment]
The fix for this has been merged and will be available in the November release of Azure PowerShell (version 5.0.0 - set to release November 8th)

**Comment by cormacpayne** [comment]
@lesterw1 Hey Lester, this should be resolved in [Azure PowerShell 5.0.0](https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-November2017).

Closing this issue since it is resolved. Please feel free to re-open this issue if you are still seeing this problem.
