### ISSUE TITLE
Get-AzureRoleSize names (Small, Medium, Large)

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#476]
Get-AzureRoleSize still reports Standard_A vms as small, medium and large. This should be changed to the correct size identifier, such as Standard_A1 and so forth. The arm template api does not accept "Small", "Medium", "Large", and currently there's no way (as far as I know) to get the correct identifier of the role size.

**Comment by singhkay** [comment]
@trondhindenes This has been fixed in v2 stack. Get-AzureVMSize is the cmdlet to use for v2 resources. It'll return the correct set of names expected by the v2 API 

`
PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-AzureVMSize westus | Select Name

Name         
----         
Standard_A0  
Standard_A1  
Standard_A2  
Standard_A3  
Standard_A5  
`
