### ISSUE TITLE
Query : Is Unplanned Failover equivalent to Plannned Failover For Vmware To Azure Scenario

### ISSUE THREAD

**Issue by shubhamgupta514** [Azure/azure-powershell#4950]
HI,

I am having a query that when I try to initiate the planned failover with the help of powershell cmdlets . It's throwing an error like Planned failover is not supported for InMageAzureV2 provider.

But Unplanned cmdlet is working fine.My concern is that whether we are getting a zero data loss privilege in unplanned failover for Vmware to Azure or not?

**Comment by markcowl** [comment]
@viverm Can you answer thsi customer queriuy about the new functionality?

**Comment by shubhamgupta514** [comment]
@markcowl @viverm please help me with the query

**Comment by bsiva** [comment]
@shubhamgupta514 - Zero data loss is not implicitly guaranteed with Unplanned failover. The way to achieve zero data loss, in the event of a planned migration is to declare the maintenance window to perform the migration operation, take the application down on the primary site meaning users can no longer connect to the applicatio, wait for a later recovery point to be generated and then perform the migration by initiating a failover.

**Comment by shubhamgupta514** [comment]
@bsiva - what I want to understand that in Hyper-V scenario, We have Explicit planned failover option  while  in vmware scenario we don't have that option. 

Application downtime is required in both scenarios. 
So,  How ASR is providing zero data loss in vmware scenario without Explicit planned failover option?

**Comment by bsiva** [comment]
@shubhamgupta514 : the difference between the Hyper-V scenario and the VMware scenario is that the Hyper-V to Azure scenario uses a host based replication stack, whereas the VMware to Azure scenario uses a guest based replication stack. On the guest based replication stack there is no way to guarantee that every last change is replicated before the VM goes down, because network connectivity is required on the VM to be able to replicate changes and network connectivity will go down as part of the shutdown process and writes to disk may still happen post this. We handle this by keeping track of the writes that have happened after the network stack on the VM has gone offline in persistent storage on the VM. These changes are replicated when the VM comes back up and the network stack comes online again.

That is the reason why there is no Planned failover option in the Guest based replication stack. So there is no implicit guarantee of zero data loss on shutdown. However, you can achieve what is effectively 0 data loss at an app level by following the procedure I outlined above. I am assuming this is a migration scenario?

**Comment by shubhamgupta514** [comment]
@Bharat Yes you are right this is a migration scenario

**Comment by shubhamgupta514** [comment]
@bsiva you are right this is a migration scenario

**Comment by shubhamgupta514** [comment]
@bsiva 

Correct me if I am wrong?

what  I am able to understand from your response , In host based replication - incremental snapshots of source server (original server) are used.
and in guest based replication , incremental data changes are stored on the source server queue folder  in persistent storage and then same is applied back to the target vm (in Azure) persistent storage.
'
So how the process server is taking part in all this ?

Could you please clarify me below lines as well : 
"We handle this by keeping track of the writes that have happened after the network stack on the VM has gone offline in persistent storage on the VM. These changes are replicated when the VM comes back up and the network stack comes online again."

 So when you say "the VM comes back up " , you are referring to the source VM or Target VM ?

**Comment by cormacpayne** [comment]
@viverm @bsiva ping on the questions above

**Comment by bsiva** [comment]
@shubhamgupta514 - dont think your summary is accurate. At a high-level, in host based replication the agent is on the Hypervisor host that hosts the VM that is being replicated, whereas in guest based replication the agent is on the VM that is being replicated.

Process server provides additional functionality such as caching/compression etc., as we dont want to burden the guest with the extra processing. In the host based stack this functionality is subsumed on the host.

Please review these documentation links for more information:-
https://docs.microsoft.com/en-us/azure/site-recovery/vmware-azure-architecture
https://docs.microsoft.com/en-us/azure/site-recovery/vmware-azure-common-questions

https://docs.microsoft.com/en-us/azure/site-recovery/hyper-v-azure-architecture

**Comment by viverm** [comment]
@shubhamgupta514  any update on this?

**Comment by Rajeswari-Mamilla** [comment]
Closing the issue as explanation as relevant documents are shared by bsiva. Please reopen the issue in case of any follow-up questions
