### ISSUE TITLE
Update telemetry to capture missing data and implement needed changes

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4965]
### Description

Insights telemetry is not capturing the following data, despite having fields:

- ExceptionType
- ExceptionStackTarce
- InnerExceptionType (shouls contain a list of inner exception types)

We also should add the following data
- InvocationName from MyInvocation (this will have the command actually used)
- ParameteSetName

Verify that the values are sent end-to-end, and are robust over failures (telemetry code should not throw)

### Cost: 4

**Comment by praries880** [comment]
Talked to @twitchax, We don't want invocationname since users could be using a user defined aliasa and that could have uniquely identifying information in there.

[ExceptionType and stack trace](https://github.com/Azure/azure-powershell/blob/2af05ef7a6f271cc8e8fb416d97ea34f79bb8009/src/Common/Commands.Common/MetricHelper.cs#L227) already exist.

**Comment by praries880** [comment]
Update, we are going to support "invocationname"..
