### ISSUE TITLE
Remove-AzureResourceLock cmdlet is invalid

### ISSUE THREAD

**Issue by retk** [Azure/azure-powershell#516]
# Environment
* Windows 10 Preview 10130
* PowerShell 5.0 (5.0.10130.0)
* AzureResourceManager 0.9.3

# Problem

The Remove-AzureResourceLock cmdlet does not support the -LockName parameter or any other parameter that allows me to specify locks.
For example:

```
PS C:\> Get-AzureResourceLock | Remove-AzureResourceLock
Remove-AzureResourceLock : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:25
+ Get-AzureResourceLock | Remove-AzureResourceLock
+                         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{Name=noMoreDe...f; Properties=}:PSObject) [Remove-AzureResourceLock], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.RemoveAzureResourceLockCmdlet
```
```
PS C:\> Remove-AzureResourceLock -LockName noMoreDelete
Remove-AzureResourceLock : A parameter cannot be found that matches parameter name 'LockName'.
```

# Expected Result

The  Remove-AzureResourceLock  command should support LockName parameter and/or the lock as PSObject.

Regards,
 Attila Ersek
 Technical Evangelist

**Comment by markcowl** [comment]
@retk Thank you for the report, assigning to the appropriate team for investigation

**Comment by vivsriaus** [comment]
@retk  This is fixed in the latest powershell. Can you please retry?

PS C:\> Get-AzureResourceLock | Remove-AzureResourceLock

Confirm
Are you sure you want to delete the following lock:
/subscriptions/38b598fc-e57a-423f-b2e7-dc0ddb631f1f/resourceGroups/testSite/providers/Microsoft.Web/sites/vivsriaus4231
23/providers/Microsoft.Authorization/locks/test2
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
