### ISSUE TITLE
Use getAssetName or Get-Location in Redis Cache tests

### ISSUE THREAD

**Issue by SiddharthChatrolaMs** [Azure/azure-powershell#5321]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@SiddharthChatrolaMs has this issue been addressed?

**Comment by MECHANDR** [comment]
Planning to close this issue due to lack of repro steps. 
@maddieclayton ,@bsiegel, Let me know if you have the repro steps.

**Comment by cormacpayne** [comment]
@MECHANDR Hey there, I'm no longer a part of the Azure PowerShell team, but I can give some insight as to what this issue is about: in the RedisCache tests, the location value is hard-coded (_e.g._, [here](https://github.com/Azure/azure-powershell/blob/master/src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.ps1#L10)), which can cause issues if another user recording these tests does not have permissions to create a RedisCache resource in the given location. The recommended pattern is to use the common `Get-Location` function (_e.g._, [this CognitiveServices test](https://github.com/Azure/azure-powershell/blob/f0c250fcb2c2ed0e6b1b6f38e5edc58b9aeb354c/src/CognitiveServices/CognitiveServices.Test/ScenarioTests/CognitiveServicesAccountTests.ps1#L30)), which allows you to specify the namespace of the resource that you'll be creating, and a preferred location, and if the user has permissions to create the resource in the given location, it will be used, otherwise the first location available for the user will be used.

**Comment by MECHANDR** [comment]
Issue fixed as part of PR #10510. Closing this issue.
