### ISSUE TITLE
StorageAccountTests.ps1: Get-ProviderLocation_Stage used for non-normal location 'eastus2(stage)'

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5337]
If you are trying to run the scenario tests in StorageAccountTests.ps1, some of the tests use `Get-ProviderLocation_Stage` from the Common.ps1. This always returns 'eastus2(stage)'. I was testing this using the test `Test-NewAzureStorageAccount`. However, the location 'eastus2(stage)' seems to be some kind of test location. Our 'Azure SDK Infrastructure' subscription has access to this location, but other subscriptions do not. Additionally, I attempted to use 'westus' via `Get-ProviderLocation`, and this failed too, stating "Supplied location westus is not valid." I have no idea how. Here is the error shown when using 'eastus2(stage)':

> The provided location 'eastus2(stage)' is not available for resource type 'Microsoft.Storage/storageAccounts'. List of available regions for the resource type is 'eastus,eastus2,westus,westeurope,eastasia,southeastasia,japaneast,japanwest,northcentralus,southcentralus,centralus,northeurope,brazilsouth,australiaeast,australiasoutheast,southindia,centralindia,westindia,canadaeast,canadacentral,westus2,westcentralus,uksouth,ukwest,koreacentral,koreasouth'.

So, it is beyond me why 'westus' does not work as it is included in that list. So, please allow the tests to run without using 'eastus2(stage)' as it isn't a commonly available location.

**Comment by blueww** [comment]
Hi MiYanni,

Since Feature team would like to release the Powershell for some new feature as soon as the feature release, so the new feature might not available on product tenants, but only on stage when we develop the feature for PowerShell some times. In this case, we can only record the test on Stage when send the PR, since the feature still not available in product tenants.

Currently I don't have a way to avoid using stage in Unit test. Do you have any idea for it?
But now, you can change all "Get-ProviderLocation_Stage" to "Get-ProviderLocation", I have tested, it works fine.

Besides that, for "Supplied location westus is not valid.", this is because the test case use Type “Standard_ZRS” which is not available with "-kind StorageV2" now on both stage and westus (it do available on stage before). I have tried change the case to use type as 'Standard_LRS'， and it works fine. Following is the code.

```
function Test-NewAzureStorageAccount
{
    # Setup
    $rgname = Get-StorageManagementTestResourceName;

    try
    {
        # Test
        $stoname = 'sto' + $rgname;
        $stotype = 'Standard_LRS';
		$kind = 'StorageV2'

        $loc = Get-ProviderLocation ResourceManagement;
        New-AzureRmResourceGroup -Name $rgname -Location $loc;

        $loc = Get-ProviderLocation ResourceManagement;
        New-AzureRmStorageAccount -ResourceGroupName $rgname -Name $stoname -Location $loc -Type $stotype -Kind $kind;
        
		$sto = Get-AzureRmStorageAccount -ResourceGroupName $rgname  -Name $stoname;
		$stotype = 'StandardLRS';
        Assert-AreEqual $sto.StorageAccountName $stoname;
        Assert-AreEqual $sto.Sku.Name $stotype;
        Assert-AreEqual $sto.Location $loc;
        Assert-AreEqual $sto.Kind $kind;
        
        Retry-IfException { Remove-AzureRmStorageAccount -Force -ResourceGroupName $rgname -Name $stoname; }
    }
    finally
    {
        # Cleanup
        Clean-ResourceGroup $rgname
    }
}
```

**Comment by MiYanni** [comment]
@blueww Maybe we should modify the error message in that instance to say something that is a bit more descriptive. For example, "Supplied location westus is not valid for the given type Standard_ZRS" so that someone knows why westus can't be used, since we also tell them westus is a valid storageAccount location. If it was confusing for me, it would be confusing for someone else.

For the session tests, I'm going to simply leave that test not being ran live. 6 months (or more) from now, we're going to want more things running live on our nightly test execution. By then, we'd probably have a way to mark a test like this as 'NotLive' so it wouldn't be ran live nightly, since the feature isn't publicly available.

**Comment by blueww** [comment]
@MiYanni 
The error message is reported from server, not from Powershell, we don't parse error message generally. If the error message really need change, we should write a mail to SRP team to suggest the change.

Besides that, all storage SRP feature should be public now. So we can change all all "Get-ProviderLocation_Stage" (and "Get-ProviderLocation_Canary") to "Get-ProviderLocation", I have tested, it works fine. (except one -asjob issue which discussed in a mail, which you are also in.)

**Comment by MiYanni** [comment]
@blueww 
When you are going through and removing the Encryption parameters, you'll need to update the tests to no longer test those parameters. At that time, can you also update the tests to no longer use Canary and Staged locations?

**Comment by blueww** [comment]
If the new feature available publicly,  when I develop removing the Encryption parameters, I will make it not use Canary and Staged locations, else, we might will need to use them, since the feature not available on all public tenants, so only can record it on specific tenants.

**Comment by MiYanni** [comment]
Sounds great. I'd suggest... if there are features that only exist in Canary or Staged locations (and you have a way to check to see that those features exist), I'd suggest checking a standard location for that feature. Then, in the future, when that feature is on standard locations, the test will work by using standard locations. So, if that check fails (a standard location doesn't have that feature), then make it fall back to a Canary or Standard location. That will future-proof the tests so they work with Canary or Staged locations until those features are released.

**Comment by blueww** [comment]
@MiYanni 
I don't quite understand you suggestion.
For storage SRP, there's no standard way to check if a feature exist on a server until run the case and see it failed (might also need to parse the error message to make sure it failed since the feature not exist.)
Do you have a sample for check the feature exist and failover location? If so, I can have a look and see if it can applied to storage SRP.

**Comment by MiYanni** [comment]
I have a branch that fixes these tests. See https://github.com/Azure/azure-powershell/issues/5243#issuecomment-362464537
Once the PR is accepted, I will close this issue and #5243
