### ISSUE TITLE
Key Vault reference blocking creation of Key Vault

### ISSUE THREAD

**Issue by EwanNoble** [Azure/azure-powershell#5433]
### Cmdlet(s)
New-AzureRmResourceGroupDeployment

### PowerShell Version
5.1.16299.98

### Module Version
5.2.0

### OS Version
10.0.16299.98

### Description
Attempting to create a Key Vault, it's Key Vault Secrets and use these secrets in SQL Server deployments for the admin password. The Key Vault secret reference is being resolved before the Key Vault has been created, despite dependencies being set.

### Debug Output
```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-request-id               : b6507e8a-b4f5-4bb6-8c34-c70066dac50f
x-ms-correlation-request-id   : b6507e8a-b4f5-4bb6-8c34-c70066dac50f
x-ms-routing-request-id       : UKWEST:20180202T225647Z:b6507e8a-b4f5-4bb6-8c34-c70066dac50f
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Fri, 02 Feb 2018 22:56:47 GMT

Body:
{
  "error": {
    "code": "KeyVaultParameterReferenceNotFound",
    "message": "The specified KeyVault '/subscriptions/[subscriptionid]/resourceGroups/TestRG1/providers/Microsoft.KeyVault/vaults/KeyVaultetw3lrseox63e' could not be found. Please see
https://aka.ms/arm-keyvault for usage details."
  }
}
```

### Script/Steps for Reproduction
Gist here: https://gist.github.com/EwanNoble/5c551b0f1f501aa7c576f2e76a6ad70b

Example usage:
New-AzureRmResourceGroup -Name "TestRG1" -Location "West Europe"
New-AzureRmResourceGroup -Name "TestRG2" -Location "West Europe"
New-AzureRmResourceGroupDeployment -ResourceGroupName "TestRG1" -TemplateUri "https://gist.githubusercontent.com/EwanNoble/5c551b0f1f501aa7c576f2e76a6ad70b/raw/6c42ee917d67479292fa2b05312f608ca772faf7/azuredeploy.json" -TemplateBaseUrl "https://gist.githubusercontent.com/EwanNoble/5c551b0f1f501aa7c576f2e76a6ad70b/raw/6c42ee917d67479292fa2b05312f608ca772faf7" -OtherResourceGroupName "TestRG2"

**Comment by maddieclayton** [comment]
@RandalliLama Can you take a look at this issue?

**Comment by gr4per** [comment]
Suffering from exact same issue...

**Comment by RandalliLama** [comment]
@seanbamsft @dragav Can either of you help with this?

**Comment by dragav** [comment]
It seems that the vault uri is missing the subscription id in this fragment:
"keyVault": {
       "id": "[resourceId(parameters('SharedKeyVaultResourceGroupName'), 'Microsoft.KeyVault/vaults', parameters('SharedKeyVaultName'))]"
                            },

Here is an example (from https://aka.ms/arm-keyvault):
"keyVault": {
                "id": "[resourceId(subscription().subscriptionId,  parameters('vaultResourceGroup'), 'Microsoft.KeyVault/vaults', parameters('vaultName'))]"
              },

**Comment by seanbamsft** [comment]
The resourceId() call is fine as it will use the current subscription ID. The issue here is that PowerShell calls the /validate API on ARM to validate the template prior to submitting the deployment. ARM attempts to validate the linked template, including the Key Vault reference. I do not see any way to skip this validation from PowerShell.

I used Fiddler to skip the /validate call and just create the deployment (removed /validate and changed it from a POST to a PUT). That worked once I fixed two other issues with the template: the vault needs "accessPolicies": [] in its properties and the password for SQL needs to meet some minimum complexity requirements.

**Comment by bmoore-msft** [comment]
@EwanNoble @gr4per - the way you can do this is by nesting both deployments.  In the KV deployment you provide an output of the resourceId and then reference that in the SQL deployment.  That will short-circuit the validation call...

That said, I'm interesting in learning more about your scenario...  The KeyVault feature was meant to help avoid putting secrets into the source code.  When you setup a vault, the secrets are passed in - and in that case you may as well just use them on the SQL resource as well, rather than the KV reference.  I realize that's a simplification but still interested in your scenario to see if there's more we need to consider.

**Comment by gr4per** [comment]
Nesting the deployments worked for me.
My scenario is about post installation custom scripts that download stuff from private github repos, so the github key is in the vault in my case to ensure scaling the vm set later each new vm deployment has access to the secret.

**Comment by bmoore-msft** [comment]
@gr4per - thx... so in your case you're adding the key to the vault in the same deployment where the VM will consume it?

**Comment by bmoore-msft** [comment]
makes sense, but in that case, why not just pass the key through the template?  (you can email me if you want to take it off line bmoore at microsoft)

**Comment by maddieclayton** [comment]
From the conversation, it seems that this issue has been resolved.  If not, please let me know and I will reopen the issue.
