### ISSUE TITLE
Ad Hoc Validation for AzureRM.Kubernetes module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5492]
### Description

- [x] Validate live CRUD scenarios for AzureRM.Kubrnetes module - sync up with David on a simple Kubernetes app for test (or use the scenairo test app)
- [x] File bugs or fix issues as appropriate
- [x] Determine whether we should release this milestone

### Cost: 2

**Comment by maddieclayton** [comment]
## New-AzureRmKubernetes
- ```New-AzureRmKubernetes -ResourceGroupName maddie1 -Name kub```
   - If ResourceGroup uses an invalid Location, it will throw an error.  I think it should just choose a location.
- ```New-AzureRmKubernetes -ResourceGroupName maddie1 -Name kub``` (fails for unrelated reason)
```New-AzureRmKubernetes -ResourceGroupName maddie1 -Name kub -Location 'East US'```
   - Error: Service principal clientID: 29254fce-3a53-49dc-bc36-5e8d0e560631 not found in Active Directory tenant 72f988bf-86f1-41af-91ab-2d7cd011db47, Please see https://aka.ms/acs-sp-help for more details.  I think this is because the service principal is created in the previous (failing) command, and the following command does not handle that it already exists.  Changing the name of the Kubernetes fixes the issue.

**Comment by maddieclayton** [comment]
Released here: https://www.powershellgallery.com/packages/AzureRM.Aks/0.0.1-preview
