### ISSUE TITLE
Fix Output, Parameters, and Piping for KeyVault cmdlets

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5496]
### Description
Work with KeyVault team to update KeyVault cmdlets to make the following changes.  In this release, we want to identify proposed cmdlet changes, present these to the KeyVautl team, and make the changes ourselves, or in coordination with them.

We want to normalize the cmdlets in the following ways.
- [ ] Correctly specify output type
- [ ] Enumerate collections
- [ ] Take piepline input as appropriate
  - [ ] Get-AzureRmKeyVault | Get-AzureKeyVaultSecret
  - [ ] Get-AzureKeyVaultSecret | Get-AzureKeyVaultSecret
- [ ] Accept pipeline input using object parameter set
- [ ] Accept pipeline input using resourceid parameter set (control plane only)
- [ ] Accept multiple instances as well as single instances for parameters that specify a resource.

Additionally we need to:
- [ ] Ensure all cmdlets are covered by tests
- [ ] Ensure all tests are passing with the new changes and skipped tests are fixed and rerecorded
- [ ] All documentation is updated and all examples/help messages are updated or fixed

**Comment by maddieclayton** [comment]
Proposed changes here: https://github.com/maddieclayton/azure-powershell/wiki/KeyVault-Improvements

**Comment by maddieclayton** [comment]
## Breaking Changes

### General
- **Make nullable parameters not nullable**
- **Figure out which cmdlets are asynchronous, add asjob, and update in the breaking change release**.
- **Remove ConfirmImpact (possibly add shouldcontinue in its place)**
- **Remove ValueFromPipelineByPropertyName where necessary to enable piping**

### Add-AzureKeyVaultCertificate
- **Change from asynchronous operation to synchronous, and change output to KeyVaultCertificate?**
- **Make policy mandatory as cmdlet fails without it.**

### Add-AzureKeyVaultCertificateContact
- **Change the output to just the contact rather than all contacts?**

### Add-AzureKeyVaultKey
- **Remove the Tags alias or ValueFromPipeline tag**
- **Add piping for Get-AzureRmResource | Add-AzureKeyVaultKey**

### Get-AzureKeyVaultCertificate
- **Remove ValueFromPipelineByPropertyName on Name to enable ResourceId parameter set**
- **Add piping for Get-AzureRmResource | Get-AzureKeyVaultCertificate**

### Get-AzureKeyVaultCertificateIssuer
- **Remove ValueFromPipelineByPropertyName on Name to enable ResourceId parameter set**
- **Add piping for Get-AzureRmResource | Get-AzureKeyVaultCertificateIssuer**

### Get-AzureKeyVaultKey
- **Remove ValueFromPipelineByPropertyName on Name to enable ResourceId parameter set**
- **Add piping for Get-AzureRmResource | Get-AzureKeyVaultKey**

### New-AzureRmKeyVault
- **Add AsJob and make call synchronous**

### Remove-AzureRmKeyVault
- **Remove ValueFromPipelineByPropertyName on ResourceGroupName to enable ResourceId parameter set**
- **Add piping for Get-AzureRmResource | Remove-AzureRmKeyVault**

### Remove-AzureRmKeyVaultAccessPolicy
- **Remove ValueFromPipelineByPropertyName on ResourceGroupName to enable ResourceId parameter set**
- **Add piping for Get-AzureRmResource | Remove-AzureRmKeyVaultAccessPolicy**

### Remove-AzureKeyVaultCertificate
- **Remove ConfirmImpact = High and possibly add shouldcontinue prompt**

### Remove-AzureKeyVaultCertificateContact
- **Remove ValueFromPipelineByPropertyName on EmailAddress to enable InputObject parameter set**
- **Add piping for Get-AzureKeyVaultCertificateContact | Remove-AzureRmKeyVaultAccessPolicy**

### Remove-AzureKeyVaultCertificateOperation
- **Remove ValueFromPipelineByPropertyName**
- **Add piping scenarios: Get-AzureKeyVaultCertificateOperation | Remove-AzureKeyVaultCertificateOperation**

### Remove-AzureKeyVaultSecret
- **Remove ValueFromPipelineByPropertyName**

### Remove-AzureKeyVaultKey
- **Remove ValueFromPipelineByPropertyName**

### Restore-AzureKeyVaultKey
- **Remove ValueFromPipelineByPropertyName**
- **Add piping for Get-AzureRmResource**

### Restore-AzureKeyVaultSecret
- **Remove ValueFromPipelineByPropertyName**
- **Add piping for Get-AzureRmResource**

### Set-AzureRmKeyVaultAccessPolicy
- Remove "all" from validateset

### Set-AzureKeyVaultCertificateIssuer
- **Remove unnecessary parameters from parameter sets**

### Set-AzureKeyVaultCertificatePolicy
- **Remove unnecessary parameters from parameter sets**

### Set-AzureKeyVaultSecretAttribute
- **Delete, make Set-AzureKeyVaultSecret have -SecureValue as optional**

### Undow-AzureKeyVaultCertificateRemove
- Change type to PSType

**Comment by maddieclayton** [comment]
All related issues merged into KV preview. Closing.
