### ISSUE TITLE
New-AzureAutomationModule and Set-AzureAutomationModule: Inconsistent parameter name

### ISSUE THREAD

**Issue by SherifTalaat** [Azure/azure-powershell#553]
Consistency is one of the important words we use to describe PowerShell. And it's very important to keep it everywhere in every module and cmdlet.

The New-AzureAutomationModule cmdlet has -ContentLink <Uri> parameter while the Set-AzureAutomationModule cmdlet has -ContentLinkUri <Uri> parameter. The parameters are the same but names are different. It will be great to keep the same across whether -ContentLink or -ContentLinkUri.

Also, I've noticed -ContentLink (or -ContentLinkUri) accepts only URL not UNC path and  we MUST upload the module file to a publicly accessible location (Azure Blog or FTP) in order to import it using Azure PowerShell. Although if you are uploading it using Azure portal, you can simply select the file from the local machine. It will be great if you allow the same for Azure PowerShell too.

Regards,
Sherif Talaat
PowerShell MVP

**Comment by markcowl** [comment]
@SherifTalaat Thank you for the report assigning to the automation team for investigation

**Comment by jodoglevy** [comment]
Thanks @SherifTalaat, filed an internal bug on -ContentLink/ContentLinkUri for our team.

The standard of the file having to be at an accessible URL, not UNC path, is standard for Azure ARM PowerShell. Also, the URL does not have to be public to everyone, for example you can pass a SasLink on an Azure Blob Storage blob that is not public, so that only Azure Automation can access it.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
