### ISSUE TITLE
Slow Resources tests in playback mode

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5564]
These are slow in playback:
- `Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagedApplicationTests.TestManagedApplicationCRUD`
- `Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceTests.TestMoveAResourceTest`

![image](https://user-images.githubusercontent.com/17788297/36320841-7ebb0e50-12fc-11e8-9d18-e32661ad0200.png)

## Goals
- [ ] Figure out why they are slow
- [ ] Make them not slow

**Comment by cormacpayne** [comment]
Looks like the issue is in the following while-loop:

https://github.com/Azure/azure-powershell/blob/2b6c7a526fe54caa4f021d493523b6419b925603/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Components/LongRunningOperationHelper.cs#L87-L100

Specifically, the `Task.Delay` call here:

https://github.com/Azure/azure-powershell/blob/2b6c7a526fe54caa4f021d493523b6419b925603/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Components/LongRunningOperationHelper.cs#L98
