### ISSUE TITLE
New-AzureRmVMSS shouldn't use magic constants

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-powershell#5657]
### Description

In several places we use magic constants in our New-AzureRmVmss code. In particular,
- currently, a size of a port range is a # of instances multiplied by 2.
- offset for inbound NAT frontend ports is 1000.

TODO: confirm with Compute team what the values has to be.

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by sergey-shandar** [comment]
@gatneil could you help with this? Currently, we use the magic constants in VMSS and they are based on our experience instead of explanations from the Compute team.

**Comment by gatneil** [comment]
@sergey-shandar 

The port range is multiplied by 2 due to overprovisioning: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-design-overview#overprovisioning. If overprovisioning is off, then the larger port range is unnecessary (unless the customer scales out later, in which case the port range has to be large enough to hold all the new VMs, plus the overprovisioned VMs during the scale-out).

What is the offset of 1,000 for NAT ports referring to?
