### ISSUE TITLE
Confused about how to install (and update)

### ISSUE THREAD

**Issue by farzadmf** [Azure/azure-powershell#5680]
Hi,

I have a general question that's been bugging me for a long time.

First time I installed Azure PowerShell, I used Web Platform Installer, but since I didn't use that application for anything else, I decided to download the MSI installer directly from here.

At this point, when I ran the command `Get-Module AzureRM -ListAvailable`, nothing was returned but `Get-Module AzureRM* -ListAvailable` listed a whole bunch of sub modules.

But I want to be able to update to the latest version easily through command line, so I ran the command mentioned in the *Releases* section here:

```
Install-Module -Name AzureRM -Repository PSGallery -Force
```

Now, when I do `Get-Module AzureRM -ListAvailable`, I see this

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.4.1      AzureRM
```

Should `ExportedCommands` be empty? Also, when I run `Import-Module AzureRM`, I get a bunch of `Error in TypeData`, complaining that "a member is already present"

Can you please let me know how I can make sure I have the proper module installed, and I can easily update to the latest version using the command line?

Thanks in advance

**Comment by cormacpayne** [comment]
@farzadmf Hey Farzad, there are two ways to install the Azure PowerShell cmdlets:

- Via `.msi` -- this can be either from the Web Platform Installer or from the installer we attach as a part of each release
    - Modules installed via the `.msi` are _currently_ placed in `C:\Program Files (x86)\Microsoft SDKs\Azure`
    - Since the `.msi` acts as a "roll-up installer", there is no `AzureRM` module installed -- each module is installed on their own
- Via PowerShell Gallery
    - Modules installed from the gallery are placed in `C:\Program Files\WindowsPowerShell\Modules`
    - `AzureRM` is considered a "roll-up module" since it defines the versions of modules that should be installed rather than containing any cmdlets itself (which is why you see no cmdlets above in the `ExportedCommands` field)

Due to the _current_ different installation paths of the above methods, it is possible to have two sets of Azure PowerShell commands sitting on your box. In the very near future, we plan on changing on the `.msi` is constructed and it will behave as if the modules were installed from the PowerShell Gallery.

For now, my recommendation would be to uninstall the modules you have from any `.msi` or installer -- you can remove them by going to Control Panel > Programs > Programs and Features and uninstalling Microsoft Azure PowerShell. Once uninstalled, you can install and update the `AzureRM` roll-up module from the command line, as mentioned in the release notes.

```powershell
# Install the latest Azure PowerShell modules
Install-Module -Name AzureRM -Repository PSGallery -Force

# Update to the latest Azure PowerShell modules
Update-Module -Name AzureRM
```

Please let us know if you have any additional questions or comments!

**Comment by farzadmf** [comment]
Thank you so much @cormacpayne for the detailed explanation; I will try to follow your suggestions, and I think it will be fine :)
