### ISSUE TITLE
Tag azure powershell modules with the supported api-versions

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#5684]
Also add the supported api-versions part of the release notes if possible.

This would be helpful for azure stack and sovereign clouds as they are typically a version behind

**Comment by MiYanni** [comment]
@twitchax Do we want to do anything...

**Comment by sphibbs** [comment]
For Stack users they will need to use the bootstrapper, no need to 'find' the supported api version. 

For other clouds that have been a version behind since the begging of time, we haven't heard customer issues here. If we do we can figure out a way to bubble up this info. 

@twitchax is in the room and approves this text / action
