### ISSUE TITLE
Output types are not clearly documented

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-powershell#5777]
### Description
First of all, I like the way that all AzureRM commands are documented and come with examples out of the box. This makes it easy to get started and you do not need to be an expert to use them.

However, the only problem I have at the moment is that some/all documented outputs are simply types. This is fine for built-in types but if they are custom types it is hard to know what to expect from them.
These types should be documented somewhere as well so we can either read it in the same page or click through to get more details.

An example of this is [New-AzureRmServiceBusKey](https://docs.microsoft.com/en-us/powershell/module/azurerm.servicebus/new-azurermservicebuskey?view=azurermps-5.5.0) where the output only mentions the following:

> Microsoft.Azure.Commands.ServiceBus.Models.PSListKeysAttributes

This without any link to a payload description.

### Script/Steps for Reproduction
Not Applicable

### Module Version
Not Applicable

### Environment Data
Not Applicable

### Debug Output
Not Applicable

**Comment by cormacpayne** [comment]
@tomkerkhove Hey Tom, thanks for the feedback and the suggestion ☺️ 

This is something that has been discussed internally and with the docs team a couple of times before. For this scenario to be enabled, we need proper XML documentation for all model types we're using in Azure PowerShell, which would take a good amount of time to do manually. We are looking into ways that we can pull the proper information from a service team's [REST API spec](https://github.com/Azure/azure-rest-api-specs) to generate the type and property documentation in Azure PowerShell. Once that work has been completed, we can then hand the documentation off to the docs team and they can do the work necessary to get it on https://docs.microsoft.com with all other reference documentation.

I'm going to move this issue into our backlog so that we can take a look at this after Build (early May) and see where our team prioritizes this work.

**Comment by cormacpayne** [comment]
@tomkerkhove Hey Tom, as an update, we are working with the docs team to get this information bubbled up on https://docs.microsoft.com in our reference docs, but @twitchax will be able to provide more information (and possibly a soft ETA) on when this will be available.

**Comment by twitchax** [comment]
FYI for @dend. :)

**Comment by dend** [comment]
This is coming soon™

**Comment by maddieclayton** [comment]
This is now available!  Thanks to the docs team for getting this working!
