### ISSUE TITLE
New-AzureRMResourceGroup clears Tags on execution

### ISSUE THREAD

**Issue by brwilkinson** [Azure/azure-powershell#5894]
### Description

Running New-AzureRMResourceGroup clears the tags if the resource group already exists

I can't see this being the expected behavior ?

### Script/Steps for Reproduction

```powershell
PS PS:\> New-AzureRmResourceGroup -Name foo10 -Location eastus2 -Tag @{owner='mrfoo'}


ResourceGroupName : foo10
Location          : eastus2
ProvisioningState : Succeeded
Tags              :
                    Name   Value
                    =====  =====
                    owner  mrfoo

ResourceId        : /subscriptions/b8f402aa-20f7-4888-b45c-3cf086dad9c3/resourceGroups/foo10


PS PS:\> New-AzureRmResourceGroup -Name foo10 -Location eastus2

Confirm
Provided resource group already exists. Are you sure you want to update it?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y


ResourceGroupName : foo10
Location          : eastus2
ProvisioningState : Succeeded
Tags              :
ResourceId        : /subscriptions/b8f402aa-20f7-4888-b45c-3cf086dad9c3/resourceGroups/foo10
```
**Note: The Tags are now blank.**

### Module Version

```powershell
get-module azurerm -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.6.0      AzureRM
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17133.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17133.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```

```

**Comment by markcowl** [comment]
@brwilkinson Is the ask that the cmdlet simply throws when the resource group already exists?  Other than not throwing for existence, I would expect that a PUT request to an existing resource would replace all properties with the properties provided.

**Comment by markcowl** [comment]
@cormacpayne We should make sure we have a consistent experience for New-* cmdlets

**Comment by brwilkinson** [comment]
Well this one is interesting, since the resource group is a container.

All of the resources in the resource group don't get deleted /removed if it already exists. 

So I guess a consistent behavior might be expected with the tags. 

Tags is the only other parameter that is set on the Cmdlet. Perhaps it should be removed...

**Comment by cormacpayne** [comment]
@brwilkinson Hey Ben, I believe this behavior is expected and desired; running `New-AzureRmResourceGroup` with the properties (name and location) of a resource group that already exists will prompt the user for confirmation of their action. At this point, the only thing that is being updated are the tags of the resource group. If they should stay the same as the resources in the group (as mentioned in a previous comment), then it seems there's no value in running this cmdlet with the properties of an existing resource group (since it will do nothing). There is the case where you'd want to update the tags of an existing resource group, in which case I would recommend using the `Set-AzureRmResourceGroup` cmdlet as it doesn't prompt for extra confirmation.

Please let me know if you have any questions or concerns with this approach 😀

**Comment by brwilkinson** [comment]
@cormacpayne no that is not a correct assumption. Every automation/template resource group deployment script will include this command prior to new-azurermresourcegroupdeployment Cmdlet. You are not accounting for those scripts, where the RG already exists.

**Comment by brwilkinson** [comment]
Please reopen & fix this issue.
