### ISSUE TITLE
Feedback - Add Relevant Methods to the Azure Objects

### ISSUE THREAD

**Issue by newguyneal** [Azure/azure-powershell#6021]
Have Azure SDK objects be able to pass reference to themselves into relevant CMDlets.

for example:

$VM = Get-AzureRMVM -ResourceGroupName "myresourcegroup" -Name "myvm"

$VM.Stop()

$VM.Start()

$VM.Update()

etc...

in addition to:
$VM = Get-AzureRMVM -ResourceGroupName "myresourcegroup" -Name "myvm"

$VM | Start-AzureRMVM

$VM | Stop-AzureRMVM

$VM | Update-AzureRMVM

etc...

PowerShell Objects have properties and methods

**Comment by maddieclayton** [comment]
@newguyneal Thanks for the feature request! We require all new cmdlets to have the ability to pipe either the object or the output of Get-AzureRmResource into cmdlets (using two new parameter sets that accept either an InputObject or a ResourceId).  We are working on implementing these parameter sets into existing cmdlets, but with the number of cmdlets currently in AzureRM, it will take a while for these parameter sets to be implemented.  We are tracking the issue here: https://github.com/Azure/azure-powershell/issues/5901, so I will close this issue and link it from the existing issue.  Please let us know if there are certain cmdlets that we should prioritize (for example, VM cmdlets).

**Comment by newguyneal** [comment]
@maddieclayton  I don't think the linked issue and what I was asking is the same as that issue. The linked issue is creating a base class for all resources to inherit from and gaining the ability to pipe whatever azure resource you want because they stem from the same parent class. I am talking about adding relevant self referencing methods to specific Azure resources so that you do not have to pipeline them and it is handled by the azure object itself.

**Comment by maddieclayton** [comment]
@newguyneal Is this requested feature for the SDK or for PowerShell?
