### ISSUE TITLE
Issue with Get-AzureRmSqlDatabase Remove-AzureRmSqlDatabase New-AzureRmSqlDatabaseCopy

### ISSUE THREAD

**Issue by dalibormesaric** [Azure/azure-powershell#6122]
### Description

During our release in VSTS we temporary create another database that goes with our slot swapping strategy. To run azure powershell commands we use "Run Inline Azure Powershell" (https://marketplace.visualstudio.com/items?itemName=petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Build-InlinePowershell).

Early in the release process we have the following step:
1. Check if COPY database already exists - if so delete it
	Get-AzureRmSqlDatabase -ResourceGroupName $ResourceGroupName -ServerName $SqlServerName -DatabaseName $databaseCopyName
	Remove-AzureRmSqlDatabase -ResourceGroupName $ResourceGroupName `
          -ServerName $SqlServerName `
          -DatabaseName $databaseCopyName `
          -Force
2. Create COPY database
	New-AzureRmSqlDatabaseCopy -ResourceGroupName rg-resourcegroupname `
     -ServerName sql-servername `
     -Tags @{key="value"} `
     -DatabaseName sqldb-databasename `
     -CopyResourceGroupName rg-resourcegroupname `
     -CopyServerName sql-servername `
     -CopyDatabaseName sqldb-databasename-copy

Later in the release process we delete the COPY database:
1. Check if COPY database already exists - if so delete it
	Get-AzureRmSqlDatabase -ResourceGroupName $ResourceGroupName -ServerName $SqlServerName -DatabaseName $databaseCopyName
	Remove-AzureRmSqlDatabase -ResourceGroupName $ResourceGroupName `
          -ServerName $SqlServerName `
          -DatabaseName $databaseCopyName `
          -Force

After the release is done, COPY database is removed from resource group resources, but still visible under sql server resource

On the next release we get the following errors:

The Resource 'Microsoft.Sql/servers/sql-servername/databases/sqldb-databasename-copy' under resource group 'rg-resourcegroupname' was not found.
45138: The destination database name 'sqldb-databasename-copy' already exists on the server 'sql-servername'.

The first error is from Get-AzureRmSqlDatabase and the second from New-AzureRmSqlDatabaseCopy.

Redeploy works without those errors.

The COPY database is found if I try to get that resource locally through powershell and run Get-AzureRmSqlDatabase, but it is not visible in https://resources.azure.com/

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.7.0      AzureRM
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@jaredmoo @akromm hey guys, would you mind taking a look at this issue when you get the chance?

**Comment by dalibormesaric** [comment]
ping @jaredmoo @akromm

**Comment by jaredmoo** [comment]
This looks like an issue where Azure Resource Manager (the frontend for Azure management API's) has cached that the database does not exist (you cannot see it directly using `Get-AzureRmSqlDatabase -DatabaseName foo`, but you can see it if you list all databases in the server using `Get-AzureRmSqlDatabase`. As a result, `Remove-AzureRmSqlDatabase` does nothing (it thinks the database is already deleted). When you try to create the copy again, the attempt to create the database automatically repopulates the ARM cache, but the copy actually fails with the 'already exists' message that you saw. Now that the ARM cache is repopulated, everything works fine.

We have been working to avoid these cache inconsistencies from happening. However there is a trick to repairing this yourself, which is to do a HTTP PUT request that repopulates the ARM cache but does not actually change the state of the database. The easiest way to do this in PowerShell is:

 1. Run `Get-AzureRmSqlDatabase` to get the list of all databases in the server (this call does not go through the cache, which is why the database is still visible), 
 2. Filter on client side using `where` to find that database
 3. Pipe it into `New-AzureRmSqlDatabase`

Then you can delete the database and it will be actually deleted.

I understand that this additional complexity in your script is probably annoying :) the good news is that the upcoming 6.1.0 release uses a new version of the database API which should be much less likely to hit this issue.

**Comment by dalibormesaric** [comment]
Before the first release step I described there was no COPY database in the resources, but then I saw these timestamps:

From VSTS release log:
2018-05-23T10:53:36.5803689Z Checking if database exists ...
2018-05-23T10:53:37.5934282Z Copying database ...
2018-05-23T10:53:40.1697156Z ##[error]45138: The destination database name 'sqldb-databasename-copy' already exists on the server 'sql-servername'.
2018-05-23T10:53:40.5337661Z ##[section]Finishing: Copy database

And when I ran Get-AzureRmSqlDatabase -ResourceGroupName rg-resourcegroupname -ServerName sql-servername -DatabaseName sqldb-databasename-copy:
ResourceGroupName             : rg-resourcegroupname
ServerName                    : sql-servername 
DatabaseName                  : sqldb-databasename-copy
CreationDate                  : 2018-05-23 10:54:35

Notice CreationDate. It looks like it was created with the New-AzureRmSqlDatabaseCopy, but one minute after the script failed saying that the database already exists.

That copy database is only partially created (contains only 3 tables), so I would say that the database copy starts fine, but fails later.

**Comment by dalibormesaric** [comment]
Possibly related #5630 or https://social.msdn.microsoft.com/Forums/lync/en-US/fdc93d4c-c907-4635-9a25-48cb9494e813/the-destination-database-name-copyofxxxxxxxxxx-already-exists-on-the-server-xxxxxxxx?forum=ssdsgetstarted

**Comment by dalibormesaric** [comment]
ping @jaredmoo @akromm (hope that it is ok if I ping you if there is no response within a week :))

**Comment by akromm** [comment]
@dalibormesaric  We will take a look at our sever side logs and see if we can determine what is happening.

**Comment by jimoha** [comment]
@dalibormesaric Adam raised the issue to our team as we handle geo-replication of databases. Would it be possible for you to create a support ticket with information about the server and database names, and a timestamp of when the issue was observed so that we can investigate. 
Additionally if you have a repro that is less that 7 days old, it would help as the logs are significantly easier to access for this timeframe.

**Comment by dalibormesaric** [comment]
Thanks @jimoha ! Support request ID is 118053118293243.

**Comment by dalibormesaric** [comment]
The issue was gone after we updated to azure powershell 6.1.1.

**Comment by jaredmoo** [comment]
Cool, thanks for confirmation :)
