### ISSUE TITLE
New-AzureDnsZone is missing -Overwrite parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#619]
The `New-AzureDnsZone` command is lacking the `-Overwrite` parameter that the other Azure DNS commands have. Please ensure that this parameter is added.

For an explanation of Azure DNS eTags and the `-Overwrite` parameter, see the following documentation: https://azure.microsoft.com/en-us/documentation/articles/dns-getstarted-create-dnszone/

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
@pcgeek86 Thanks for the feedback, Trevor, assigning to the network team to investigate.

**Comment by pcgeek86** [comment]
Had a Yammer conversation with @jtuliani and we are resolving there. I'll file a new bug for `Remove-AzureDnsZone` needing a `-Force` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by jtuliani** [comment]
Closing this item.  Based on discussion with Trevor on Yammer, I think we've agreed that we shouldn't add '-Overwrite' to New-AzureDnsZone, since it risks giving a false impression that the resulting zone would be identical to a genuinely new zone (it wouldn't, pre-existing record sets would still be there).
