### ISSUE TITLE
see still open issue #6214

### ISSUE THREAD

**Issue by whiggs** [Azure/azure-powershell#6373]
The response to this issue I submitted indicates to me that the person responding either did not correctly read the code or does not know how the azurerm module loads profiles and is not in any way shape or form satisfactory.

**Comment by kilasuit** [comment]
#6214 is still open and therefore there is no need to open an additional issue for this and therefore this issue should be closed

**Comment by cormacpayne** [comment]
@whiggs Hey William, @kilasuit is correct, since there is already an open issue tracking the status of this module loading issue, we should keep the discussion and investigation within https://github.com/Azure/azure-powershell/issues/6214 and close this issue in favor of it. Our team will respond to that issue within the next day 😀
