### ISSUE TITLE
Look into GetLocation issues in Compute tests on Netstandard builds

### ISSUE THREAD

**Issue by praries880** [Azure/azure-powershell#6436]
Opening this WRT PR #6394 

Comments from @hyonholee 
`

https://github.com/Azure/azure-powershell/pull/6394

Not that I disabled some tests in NETSTANDARD mode.

These tests pass in NET45 mode, but failing in the check-in testing for NETSTANDARD mode.

I checked the logs and it looks like Get-Location is not working correctly for NETSTANDARD.

These tests call the following command during the tests.

     Get-Location "Microsoft.Compute" "virtualMachines" "East US"

This calls Get-Location in Common.ps1 script in the following location.

https://github.com/Azure/azure-powershell/blob/e78e977fe0b41df3768215a47ca8054cfbd61b10/src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/Common.ps1#L583

After the above command, Get-Location returns “West US” even though “East US” is given as a default parameter.

The same command returns “East US” for NET45 mode, so these tests are failing only for NETSTANDARD mode.

I suspect Get-AzureRmResourceProvider in AzureRM.Resources.Netcore.ps1 might not work properly, because, in NETSTANDARD, it looks like it is calling Get-AzureRmResourceProvider from the following script file.

https://github.com/Azure/azure-powershell/blob/e78e977fe0b41df3768215a47ca8054cfbd61b10/src/ResourceManager/Compute/Commands.Compute.Test/AzureRM.Resources.Netcore.ps1#L33

Could you investigate why these tests are failing only in NETSTANDARD mode?
`

**Comment by MiYanni** [comment]
@praries880 @hyonholee I ran into this issue when converting test projects to NetCore. It is because you have your test recordings using a very old version of the Resources SDK. In my notes:
> AzureRM.Compute: 2/3 of the tests are skipped because of Resources->ResourceManager update and Storage update, need re-recorded

So, I implemented a workaround without recording all the tests. That's what that `Commands.Compute.Test/AzureRM.Resources.Netcore.ps1` file is. It allows **most** of the tests to run with the current recordings in NetCore, and the non-NetCore file allows **all** the tests to run in desktop. 

## To Fix
If you want this issue fixed, you need to update your version of the Resources SDK to use our [common Resources SDK](https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/Common/Commands.ResourceManager.Common), delete the Commands.Compute.Test/AzureRM.Resources.Netcore.ps1` and Commands.Compute.Test/AzureRM.Resources.ps1`, and re-record **all the tests**.

**Comment by MiYanni** [comment]
The changes for this issue have been merged.
