### ISSUE TITLE
Comment on the pace of development of the .Net core cmdlets

### ISSUE THREAD

**Issue by yobyot** [Azure/azure-powershell#6652]
I just wanted to let the dev team know that it feels like the Core Azure cmdlets are falling further behind the pace of the development of Desktop cmdlets.

We had a whole-year wait for an update before February, 18 for the Core cmdlets as compared to the near-impossible-to-keep-up-with cadence of Desktop cmdlet releases. And while things have picked up in 2018, the schedule appears to vary.

In case this makes any difference to the product roadmap, here're two items to consider:
* The AWS PowerShell cmdlets are always complete and current. AWS releases Core cmdlets whenever it updates its API. I find it ironic that PowerShell Core is a second-class citizen in Azure but not in AWS.
* If PowerShell Core is to ever be a replacement for Desktop, those of us who use Azure need a complete implementation.

Thanks.

![image](https://user-images.githubusercontent.com/14332263/42654285-1feae3f2-85e6-11e8-9dfe-40b3c0a78ceb.png)

**Comment by cormacpayne** [comment]
@yobyot Hey Alex, thanks for filing this issue. Let me address individual parts of your comment:

> I just wanted to let the dev team know that it feels like the Core Azure cmdlets are falling further behind the pace of the development of Desktop cmdlets.

Currently, the `AzureRM` (desktop) module is our main product and the one that we release every two weeks to the PowerShell Gallery. By the end of this month, we are looking to publish `AzureRM.Netcore` (.NET Core) to the PowerShell Gallery within a day of `AzureRM` going out and it should be picked up by Cloud Shell around the same time (since they are now shipping with `AzureRM.Netcore`). By the middle of September, we plan to shift the focus to a new module, `Az`, which will target .NET Standard, and will become our main product, replacing `AzureRM`. This will then be the module that we ship every two weeks and maintain as it will be able to work for both desktop and .NET Core. So look for the development of the .NET Core (and later .NET Standard) modules pick up over the next couple of months 😀

> We had a whole-year wait for an update before February, 18 for the Core cmdlets as compared to the near-impossible-to-keep-up-with cadence of Desktop cmdlet releases.

I'm confused by the "near-impossible-to-keep-up-with cadence of Desktop cmdlet releases" part of this sentence -- would you mind elaborating on this? Starting at the beginning of this year, we implemented a system of publishing `AzureRM` every two weeks, and you can see this pattern in the publish dates of `AzureRM` on the PowerShell Gallery (ignoring hot fixes and special releases, such as //Build in May). We also outline the next three releases of `AzureRM` in our [milestones page](https://github.com/Azure/azure-powershell/milestones), which outlines the timelines around these releases, including the day the package will be publicly available. If there's a way that we can be more clear about our shipping dates, please let us know.

>In case this makes any difference to the product roadmap, here're two items to consider:
> - The AWS PowerShell cmdlets are always complete and current. AWS releases Core cmdlets whenever it updates its API. I find it ironic that PowerShell Core is a second-class citizen in Azure but not in AWS.
> - If PowerShell Core is to ever be a replacement for Desktop, those of us who use Azure need a complete implementation.

This was mentioned above, but just to reiterate, our plan is for the .NET Standard (`Az`) module to become our main product starting in mid-September, which will be compatible with desktop and .NET Core. This will be the product that we ship on the two week cadence and will be up to date with all of the latest changes in our cmdlets.

Please let us know if you have any other questions or comments!
