### ISSUE TITLE
Storage Policy Permissions do not appear to be documented

### ISSUE THREAD

**Issue by MattAllison** [Azure/azure-powershell#6679]
### Description

Various commands to deal with Storage Policy objects (New-AzureStorageContainerStoredAccessPolicy) have a -Permission parameter that takes a string value.

The possible values contained within the string do not appear to be documented anywhere other than a brief example of "(rwd)".

### Script/Steps for Reproduction

```powershell

get-help New-AzureStorageContainerStoredAccessPolicy -Parameter Permission

```

### Module Version

Issue occurs in all versions

**Comment by blueww** [comment]
@MattAllison 
Actually, the allowed permission value are doc in SAS documentation as following :
https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas
https://docs.microsoft.com/en-us/rest/api/storageservices/Constructing-an-Account-SAS?redirectedfrom=MSDN

PowerShell is aligned with the SAS documentation. We don't doc the allowed value in Powershell doc since the value can change with new Azure storage feature added.

Let me know if you have more comments and suggestion for this.

**Comment by blueww** [comment]
@MattAllison 

Do you still have any other questions or comments for this?
I will close this issue as not receive comment from you for 10 days.
Feel free to reopen it if you have further questions or comments.
