### ISSUE TITLE
Remove-AzureStorageDirectory :: Missing a -Force parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#69]
The `Remove-AzureStorageDirectory` command is missing a `-Force` parameter. If the directory is not empty, then an exception is thrown.

* Azure PowerShell module version 0.8.12
* WMF / PowerShell 5.0 November 2014 Preview

> Remove-AzureStorageDirectory : The remote server returned an error: (409) Conflict. HTTP Status Code: 409 - HTTP Error Message: The specified directory is not empty.

![image](https://cloud.githubusercontent.com/assets/466713/5582210/55841362-902b-11e4-8cde-43c21538d162.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
@pcgeek86 Still not there  adding a task to enforce this through static analysis for appropriate cmdlet verbs

**Comment by markcowl** [comment]
@blueww Can you take a look?  If it is possible to delete a directory that contains files as Trevor describes,, then either we should swallow this exception and delete the directory, or we should provide a Force parameter (and prompt with SHoudlContinue)  if an exception like this is caught.

**Comment by blueww** [comment]
Only empty File directory can be deleted, or server will report 409 error as above.
So it’s not necessary to add -Force to Remove-azurestorageDirectory as only empty dir can be deleted.

See 
https://msdn.microsoft.com/en-us/library/azure/dn690119.aspx
```
Error code			HTTP status code	User message 
DirectoryNotEmpty	Conflict (409)		The specified directory is not empty.
```

**Comment by pcgeek86** [comment]
@markcowl I think we need some user experience training.

**Comment by markcowl** [comment]
@blueww If the user specified -Froce, how hard would it be to list and delete the files in the directory after a ShouldContinue prompt, and *then* delete the directory?  This is the behavior I would expect from this (and similar) cmdlets

**Comment by blueww** [comment]
Actually, as the file directory tree might be big, and the cmdlet might run a lot of time, we need carefully design the behavior, such as:
1.	How to show the progress of the deleting, since it might run a lot of time, and we don’t know how many files/dirs Left.
2.	Since it might run long time, how to handle it if there are still files uploading to the dir/subdir when deleting
3.	If some single file/dir delete request fail or file/dir list fail, how to handle it, just fail and exist?

So the cost to make the cmdlet works good with the -Force will not be low.
And the test cost of the change will also increase, since we need to make sure the code can handle big file tree.

It might be better to provide a script for recursively delete file/dir in a Dir, so user can debug and edit it per their requirement . I have write a draft. 

```
function RemoveFileDir ([Microsoft.WindowsAzure.Storage.File.CloudFileDirectory]$dir)
{
    $filelist = Get-AzureStorageFile -Directory $dir
    foreach ($f in $filelist)
    {
        if ($f.GetType().Name -eq "CloudFileDirectory")
        {
            RemoveFileDir($f)
        }
        else
        {
            Remove-AzureStorageFile -File $f
        }
    }
    Remove-AzureStorageDirectory -Directory $dir
} 

```
Besides that, I see there’s a talk in Java for same issue, and Java also don’t support delete none-empty directory. https://github.com/Azure/azure-storage-java/issues/53 
Do you know any azure tools support to delete none-empty file directory? Then we can reference how they handle it.
Thanks!

**Comment by blueww** [comment]
There are no more comments for this and we have give the script to resolve the issue, so close it.

**Comment by nshampur** [comment]
IMO the command needs a -Recurse option. Don't make folks write a routine to achieve something as simple as this.

**Comment by juchom** [comment]
I just hit the same issue, I really think there is something to do here.

**Comment by kunalchandratre1** [comment]
Here is full source code and step by step guide for using recursion to delete the file storage directory and its contents - https://sanganakauthority.blogspot.com/2019/07/delete-azure-file-storage-directory-and.html
