### ISSUE TITLE
Use force/confirm correctly

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#718]
Several of the Azure cmdlets allow the use of `ConfirmPreference` (f.ex `-confirm:$false`) without this parameter having any effect. An example is 
`Get-AzureSubscription -SubscriptionId <id> | Remove-AzureSubscription -Confirm:$false` (still prompts to confirm)

This is a CLEAR violation of the Powershell design guidelines. Please update the cmdlets to properly support ConfirmPreference and related parameters.

**Comment by devigned** [comment]
Agreed. We are going to resolve this.

**Comment by pcgeek86** [comment]
@trondhindenes @devigned  

+1, here is a link to PowerShell design guidelines. Please distribute to Azure PowerShell team, and all related Microsoft buddies. Recommended reading.

https://technet.microsoft.com/en-us/library/ms714657(v=vs.85).aspx

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by trondhindenes** [comment]
Any updates on this?

**Comment by markcowl** [comment]
@trondhindenes @pcgeek86 Finally circling back on this and related issues.  Do you guys have a preference on how we would roll this out?  We could change a few services at a time, or we could make the change wholesale for all ARM cmdlets.  My thought is that inconsistency would be more confusing, and one break is preferable.  What do you guys think about this?

BTW - the historical reasons for this are exactly what you would expect - we decided to buck the guidance so we could provide a single parameter for avoiding prompts, because we were skewing in favor of users who were not familiar with PowerShell but needed a WIndows command line for Azure. Scripting has become so important now, though, that we are rethinking these instances of non-compliance, and we will address the inexperienced users with additional documentation.

**Comment by kilasuit** [comment]
You need to make use of the underlying PowerShell Language and do this on all ARM cmdlets at once.

Else you may as well be writing python.

Also regards to the users not familar to PowerShell the CommonParameters are simple enough to understand and in my opinion this **should** never of made the light to released functionality.

**Comment by kilasuit** [comment]
Also see #475 for this issue

**Comment by markcowl** [comment]
Fixed
