### ISSUE TITLE
Start-CopyAzureStorageBlob does not update the Metadata

### ISSUE THREAD

**Issue by DrEight** [Azure/azure-powershell#7268]
Step to reproduce the problem:
1) write a file with metadata to a blob
2) copy the file with Start-CopyAzureStorageBlob  to a destination Blob
3) update the file and the metadata in source
4) overwrite the file with Start-CopyAzureStorageBlob -force
5) the metadata in destination blob stays with the original value, but the file is overwritten 

So the result is that you have in the destination blob the new file with the old metadata

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by blueww** [comment]
@DrEight 

Powershell blob Copy is actually server side blob copy. Powershell only send the copy request to server, and server will do the real copy. So the current behavior is from server.

I see there's already a bug for it, please wait for the server bug fix and deployed to product.

And since this is not a powershell code bug, and can't be fixed in Powershell code, do you mind if I close the issue first？

**Comment by DrEight** [comment]
This bug caused us a lot of problems during a migration. The migration is done and so I don't care anymore.
I reported so you can fix it and I hope others will not have the same troubles we had.

**Comment by blueww** [comment]
@DrEight 
Thanks for reporting this! Will use the issue to track the fixing.

**Comment by blueww** [comment]
This is already fixed in the last release: https://github.com/Azure/azure-powershell/releases/tag/v6.10.0-October2018 
Please check and feel free to inform us if you need more assitance.
