### ISSUE TITLE
Can't upload blob with SAS

### ISSUE THREAD

**Issue by alvipeo** [Azure/azure-powershell#7283]
I'm leaving a link to my SO question because apparently no one knows how to do it. And to me it doesn't make sense as I'm sure it's possible with REST API.

[SO question](https://stackoverflow.com/q/52338480/2896495)

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by alvipeo** [comment]
Thank you! This is extremely important for scenarios with VSTS or external system/customer uploading something.

**Comment by blueww** [comment]
@alvipeo 
There are 2 issues:
1. Please use the latest Azure Powershell from https://github.com/Azure/azure-powershell/releases (currently is 6.9.0)
2. If you need upload blob with SAS without Read permission, please add -Force to Set-AzureStorageBlobContent cmdlets. This is because by default we will check if the dest blob exist (need read permission), and remind user weather to overwrite if dest blob exist.

**Comment by alvipeo** [comment]
Sorry, how do I install this latest version?

**Comment by blueww** [comment]
@alvipeo 
Per https://github.com/Azure/azure-powershell/releases : 

To install AzureRM from the PowerShell Gallery, run the following command:
`Install-Module -Name AzureRM -Repository PSGallery -Force`
To update from an older version of AzureRM, run the following command:
`Update-Module -Name AzureRM`

**Comment by blueww** [comment]
@alvipeo 
If your issue is resolved?
I will close the issue now, as not see more request from you.
Feel free to contact us if you need more assistant from us.
