### ISSUE TITLE
 Get-AzureWebsite returns error "An error occurred while sending the request."

### ISSUE THREAD

**Issue by imeya** [Azure/azure-powershell#7498]
When I execute this cmdlet `get-AzureWebsite`, an error occurs: An error occurred while sending the request.

Because I have two subscriptions, I thought maybe it's due to that it can not find the correct subscription. Then I used the `Select-AzureSubscription -SubscriptionName` , but another error occurs for the select cmdlet: The subscription name Azure CXP Community Internal Consumption doesn't exist.

I don't know why. The 2 subscriptions can be fetched using  `Get-AzureRmSubscription`.

The screenshot is as below:
![get-azurewebsite-2](https://user-images.githubusercontent.com/25738099/46641169-b1078280-cba2-11e8-9235-661efe284a0f.JPG)

**Comment by cormacpayne** [comment]
@imeya it looks like you're mixing cmdlets from the `AzureRM` (ARM calls) and `Azure` (RDFE calls) modules -- you should do one of the following to make the cmdlet calls consistent:

(1) If you're working in RDFE, change the first call to `Get-AzureSubscription` to get all RDFE subscriptions rather than ARM

(2) If you're working in ARM, change the `Select-AzureSubscription` call to `Select-AzureRmSubscription` and the `Get-AzureWebsite` call to `Get-AzureRmWebApp`
