### ISSUE TITLE
webapp: Mark RDFE commands deprecated with the next release

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-powershell#7668]
AppService team is deprecating old apis https://blogs.msdn.microsoft.com/appserviceteam/2018/03/12/deprecating-service-management-apis-support-for-azure-app-services/
& customers should use the AzureRM* equivalent commands see https://docs.microsoft.com/en-us/powershell/module/azurerm.websites/?view=azurermps-6.11.0#app_service

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by eyccli** [comment]
Hi, I have a question since I am facing the same issue. Is there an equivalent command to"Publish-AzureWebsiteProject" ? I do not see anything that supports that in the new ARM commands.

**Comment by mrsanjaysharma2** [comment]
I don't see an update to my Build/Release Task list in TFS 2015 (Still seeing Azure Web App Deployment). And since Azure Web Deployment is using deprecated cmdlets my releases are failing with "Downlevel error message", Is there an equivalent to this task for my agent on TFS 2015 that can be used.
![forgithub](https://user-images.githubusercontent.com/40750473/50208905-7129fc00-0398-11e9-9969-a7eb2fd23b39.png)
