### ISSUE TITLE
The new -Mode parameter on New-AzureResourceGroupDeployment has no documentation

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#767]
# Problem

The new `-Mode` parameter for the `New-AzureResourceGroupDeployment` command, in Azure PowerShell 0.9.7 in Azure Resource Manager (ARM) "mode" does not have any documentation. The parameter supports auto-completion values of `Complete` and `Incremental`, but there is no *definition* of what these values mean.

![2015-08-18 11_23_33-new notification](https://cloud.githubusercontent.com/assets/466713/9337294/c2154f02-459b-11e5-91ec-c980d25ca6d5.png)

![image](https://cloud.githubusercontent.com/assets/466713/9337317/e820ed50-459b-11e5-8644-52e2efe326d8.png)

# Expected Result

The `-Mode` parameter for the `New-AzureResourceGroupDeployment` command should have documentation that instructs the end user on how to properly utilize it.

I would fill this out myself, and submit a Pull Request (PR), but I'm not part of the Azure engineering team, and do not have any intrinsic knowledge on how this parameter is intended to work. 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by jeffbry** [comment]
Details are in the REST spec: https://msdn.microsoft.com/en-us/library/azure/dn790564.aspx

**Comment by pcgeek86** [comment]
@jeffbry Hi Jeff, if you're not familiar with the concept of built-in help in PowerShell commands / modules, you can check out the reference documentation here: https://technet.microsoft.com/en-us/library/dd878343(v=vs.85).aspx.

This bug pertains to the missing built-in PowerShell help in the `-Mode` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ravbhatnagar** [comment]
Lets fix this!

**Comment by jeffpatton1971** [comment]
Hey, just found this issue as I was looking for mildly more complete documentation of what this parameter mean outside of the cmdlet documentation

https://msdn.microsoft.com/en-us/library/mt679003.aspx

Neat, that you guys added it to the website, could you at least flesh it out. And to +1 @pcgeek86 could we also please add the parameters that the cmdlet accepts into the in-line help?

It really seems that lately. and I know that @pcgeek86 will agree as will ANYONE else who has been working in powershell since monad. Lately it seems that the azure folks have decided to just thumb their noses at what has for all intents and purposes become the standard for powershell. 

missing in-line help

displaying the properties like storageprofile, but when outputting data outputting a json string that is storageprofiletext which...don't get me started again.

I think we should all get together and figure out what's really going on.

**Comment by ravbhatnagar** [comment]
Fixed - 3/3 release
