### ISSUE TITLE
Send messages to Azure Storage Queue via start-job in PowerShell

### ISSUE THREAD

**Issue by imeya** [Azure/azure-powershell#7746]
I want to send messages to azure storage queue using start-job, but always get the $queue parameter is null error, code like below:

```
$queue = Get-AzureStorageQueue -Name 'itemsqueue' -Context $context
1..10 | % {
    $msgContent = new-object -TypeName Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage -ArgumentList "this is messgage $_";
    Start-Job { $queue.CloudQueue.AddMessage($msgContent) }

}
```

Get-Job | Receive-Job

I also tried add -ArgumentList after the start-job, but it throws the error "string does not have the method AddMessage"

**Comment by maddieclayton** [comment]
@blueww Can you take a look at this question?

@imeya We suggest that, wherever possible, you use PowerShell cmdlets in your script rather than the underlying .NET SDK calls, as PowerShell cmdlets are guaranteed not to break outside of breaking change releases, but .NET SDK calls can have breaking changes.

**Comment by blueww** [comment]
@imeya 
I can repro the issue. 
But since this issue not really caused by the storage cmdlet, but seems related with the usage of Start-Job, I still don't find a way tp resolve it.

The Add message to Queue is a sync operation and generally should be fast, why you need run it in a job? Could you just run it without Start-Job?
