### ISSUE TITLE
New-AzureRmVMConfig - allow temp storage letter to be configured

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-powershell#7804]
When configuring Azure VMs, the temporary storage (disk) uses D by default (a poor choice IMO).

The current workaround is to reassign the temporary drive to a different letter AFTER the VM is provisioned  (see: [https://github.com/MicrosoftDocs/azure-docs/issues/18477#issuecomment-437514214)](https://github.com/MicrosoftDocs/azure-docs/issues/18477#issuecomment-437514214)

The New-AzureRmVMConfig cmdlet should allow a parameter such as -TempDriveLetter which accepts a drive letter to be used for the temporary disk and would save time for those of us trying to lift and shift systems to Azure, as THE MAJORITY of existing systems use D for data drives and is also (highly-likely) to be referenced in any scripts used to maintain such systems.

Thanks in advance.

**Comment by maddieclayton** [comment]
@nibhat @koralski @savyasachisamal Can you take a look at this feature request?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.

**Comment by bdcoder2** [comment]
Please keep this case OPEN -- as far as I know, we (still) cannot configure the temp drive letter when configuring a VM via powershell.   The ability to select the temp drive letter at configuration is very much needed to ease the transition to Azure.

**Comment by Drewm3** [comment]
@bdcoder2 , we did implement the functionality to maintain the drive letter of the temp disk a few years ago. This resolved the majority of the customer's issues with the original implementation. We had considered allowing the customer to provide a drive letter at the time of provisioning, but this approach is much more challenging because some VM sizes such as Lv2 now have multiple disks, and you can resize instances from one size to another which will cause disks to add/remove. With multiple disks this is a non-trivial update to be made, and we want to avoid adding functionality that only works for some VM sizes if we can.

**Comment by bdcoder2** [comment]
@drewm3, Sorry - I must still be missing something as the documentation for   still does not show any switch that allows a drive letter to be selected at the time of VM creation, i.e.:

[https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermvmconfig?view=azurermps-6.13.0](https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermvmconfig?view=azurermps-6.13.0)

Back in November, of 2018, I asked this same question -- see: [https://github.com/MicrosoftDocs/azure-docs/issues/18477#issuecomment-437514214](https://github.com/MicrosoftDocs/azure-docs/issues/18477#issuecomment-437514214), which also has a reference to this case.

If I did miss something, please close the issue; but before doing so, can you provide a link to the PowerShell commandlet that allows us to configure a VM with say "Z" as the temp drive?

Thanks again.

**Comment by Drewm3** [comment]
@bdcoder2, the drive letter is not selected by Azure code. The drive letter is being selected by Windows which uses the first available drive letter after A:\ and B:\ when it is presented with a volume that is presented to it when it contains a file system, such as NTFS, which it understands. So in this case, what I believe you are requesting is for Azure to add specific code to change the drive letter *after* Windows selected the drive letter. 

Is this the correct understanding of your request? If yes, then I would like to move to tracking this request in our Azure UserVoice feedback system. This will allow us to get a broader view of how many customers would like this same feature so that we can invest our development resources in a way that provide the most benefit to the most customers.

**Comment by bdcoder2** [comment]
@Drewm3 - Thanks.  I really do not know when (or by what method) the temp drive letter is selected.  The base issue was that the following cmdlet:

`New-AzureRmVMConfig`

Does not (as far as I know) offer any switch that allows us to configure the temp drive letter, regardless of what underlying system allocates it.   So, when the above command is used to create/configure a VM, (going by what you describe), "D" is selected as the temp drive.   We then must jump through several hoops (described in my previous posts) to re-assign the temp drive.

I have also read about issues that even if we change the temp drive letter (after the VM is created) and then later try to resize the VM, the temp drive defaults back to "D" -- which, again, would be  disastrous when all you are doing is changing the VM size.

So, I guess, yes, if moving this request to the "Azure UserVoice feedback system" will get us one step closer to being able to specify what letter is used as the temp drive when a VM is created or resized, then I say do the voodoo you need to do!

Thanks again!

**Comment by Wan-Ling-Chen** [comment]
It seems that this request is raised from time to time , yet it will not be solved after years. I encounter the same bottleneck which cause operation effort and time for my time sensitive task after provisioning again and again.
