### ISSUE TITLE
Get-AzureStorageBlob behaves strangely when the blob name contains special chars like []

### ISSUE THREAD

**Issue by imeya** [Azure/azure-powershell#7848]
When use the following code:
```
$name = "test/new11_22[1].jpg"
$blob = Get-AzureStorageBlob -Container $container.Name -Context $context -Blob $name -ErrorAction Stop 
```

But the $blob is null, and no error occurs.

if I rename the blob without [1], then $blob is not null and I can see the blob.

So why it returns null when the blob name has [] characters? and no error occurs?

And something strange is that, if I just remove  the -Blob, use the below code:
`$blob = Get-AzureStorageBlob -Container $container.Name -Context $context
`
I can see all blobs listed even the one which name contains []  characters.

**Comment by blueww** [comment]
@imeya 

In the help of Get-AzureStorageBlob, you can see the -Blob parameter support wildchar search.
https://docs.microsoft.com/en-us/powershell/module/azure.storage/get-azurestorageblob?view=azurermps-6.12.0

> Specifies a name or name pattern, which can be used for a wildcard search. If no blob name is specified, the cmdlet lists all the blobs in the specified container. If a value is specified for this parameter, the cmdlet lists all blobs with names that match this parameter.

For the blob name `"test/new11_22[1].jpg"`, `[1]` will be taken as a set include only one element `1` (e.g. [0-9] means one number)
So the blob name matchs the pattern `"test/new11_22[1].jpg"`, should be `"test/new11_221.jpg"`

For you issue, you can try one of following 2 options:

1. use -Prefix instead of -Blob, as prefix don't support wild char. Anyway, this will also get other blob start with the blob name, like `test/new11_22[1].jpgab`

```powershell
PS C:\WINDOWS\system32> Get-AzureStorageBlob -Container $containerName -Context $ctx -prefix test/new11_22[1].jpg

   Container Uri: https://***.blob.core.windows.net/***

Name                 BlobType  Length          ContentType                    LastModified         AccessTier SnapshotTime         IsDeleted 
----                 --------  ------          -----------                    ------------         ---------- ------------         --------- 
test/new11_22[1].jpg BlockBlob 2097152         application/octet-stream       2018-11-16 07:29:19Z                                 False 
```

2. get blob with "test/new11_22?1?.jpg", `?` matches single char. Anyway, this will also get other blob start match the pattern, like `test/new11_22111.jpg`

```powershell
Get-AzureStorageBlob -Container $containerName -Context $ctx -Blob test/new11_22?1?.jpg

   Container Uri: https://azcopyperf1.blob.core.windows.net/weitest2

Name                 BlobType  Length          ContentType                    LastModified         AccessTier SnapshotTime         IsDeleted 
----                 --------  ------          -----------                    ------------         ---------- ------------         --------- 
test/new11_22[1].jpg BlockBlob 2097152         application/octet-stream       2018-11-16 07:29:19Z                                 False  
```

**Comment by maddieclayton** [comment]
Closing as question was answered. Please reopen if you have further questions.
