### ISSUE TITLE
connect-azurermaccount vs connect-azaccount: What have you done?!?!?

### ISSUE THREAD

**Issue by whiggs** [Azure/azure-powershell#7896]
### Description

I recently started using the az powershell module in lieu of the azurerm powershell module that I was accustomed to, since the az powershell module is meant to replace the azurerm powershell module.  However, run into a big problem right off the bat when using this module when trying to connect to azure.  When using the azurerm powershell module, I can simply pass the appropriate function's "Credential" parameter a credential object (just like you can with the azure command line tool):
![easy](https://i.imgur.com/S9lgoXz.png)
However, when I try to authenticate to azure using the new az powershell module, apparently the credentials by themselves are not good enough.  Now it is requiring more information, like the items indicated below:
![crap](https://i.imgur.com/iCi6Fup.png)
To make things even more difficult, due to the fact that the help content for the functions is non-existent, making the process of figuring out what constitutes valid input for a particular parameter a frustrating, trial and error process (the below help content is returned when "get-help connect-azaccount -full" is run **after the help content has been updated on the machine and is unacceptably lacking**):
```powershell
@{CommonParameters=True; WorkflowCommonParameters=False; details=; Syntax=; parameters=; inputTypes=; returnValues=; aliases=Add-AzAccount
Login-AzAccount
; remarks=None; PSSnapIn=; alertSet=; description=; examples=; Synopsis=
Connect-AzAccount [-Environment <string>] [-Tenant <string>] [-Subscription <string>] [-ContextName <string>] [-SkipContextPopulation] [-Force] [-Scope <ContextModificationScope>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Connect-AzAccount -Credential <pscredential> -ServicePrincipal -Tenant <string> [-Environment <string>] [-Subscription <string>] [-ContextName <string>] [-SkipContextPopulation] [-Force] [-Scope <ContextModificationScope>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Connect-AzAccount -CertificateThumbprint <string> -ApplicationId <string> -Tenant <string> [-Environment <string>] [-ServicePrincipal] [-Subscription <string>] [-ContextName <string>] [-SkipContextPopulation] [-Force] [-Scope <ContextModificationScope>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Connect-AzAccount -AccessToken <string> -AccountId <string> [-Environment <string>] [-Tenant <string>] [-GraphAccessToken <string>] [-KeyVaultAccessToken <string>] [-Subscription <string>] [-ContextName <string>] [-SkipValidation] [-SkipContextPopulation] [-Force] [-Scope <ContextModificationScope>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Connect-AzAccount -Identity [-Environment <string>] [-Tenant <string>] [-AccountId <string>] [-ManagedServicePort <int>] [-ManagedServiceHostName <string>] [-ManagedServiceSecret <securestring>] [-Subscription <string>] [-ContextName <string>] [-SkipContextPopulation] [-Force] [-Scope <ContextModificationScope>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
; ModuleName=Az.Profile; nonTerminatingErrors=; xmlns:command=http://schemas.microsoft.com/maml/dev/command/2004/10; xmlns:dev=http://schemas.microsoft.com/maml/dev/2004/10; xmlns:maml=http://schemas.microsoft.com/maml/2004/10; Name=Connect-AzAccount; Category=Cmdlet; Component=; Role=; Functionality=}
```
So, I am requesting two things:

1. Allow users to connect to azure with the az powershell module using only the credential parameter, which is currently possible in both the azure command line tool and the azurerm module.
2. Actually create the help content for the modules functions.

### Script/Steps for Reproduction

```powershell
$cred = New-Object System.Management.Automation.PSCredential -ArgumentList "username", (ConvertTo-SecureString "Password" -Force -AsPlainText)
Connect-azaccount -credential $cred
```

### Module Version

Version 0.6.1

### Environment Data

```powershell

PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.17134.407                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.17134.407                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                                        

```

### Debug Output

Not applicable

**Comment by cormacpayne** [comment]
@whiggs Hey William, thanks for providing this information. Regarding your first request with the `-Credential` parameter, we currently have an [existing issue](https://github.com/Azure/azure-powershell/issues/7430) open that we are using to track discussions surrounding this missing scenario in the `Az` module, as well as any future plans or progress made. A quick summary on why the U/P scenario through the `-Credential` parameter was removed in `Az` (more information outlined in the previously mentioned issue): Azure PowerShell uses ADAL for authentication to Azure, and to move from .NET Framework to .NET Standard, we needed to move from version 2.x.x to 3.x.x, and this version does not support U/P on .NET Standard [due to security reasons](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-with-username-and-password#using-username-and-password-is-not-recommended). As a result, we have no way to authenticate users with U/P using the underlying ADAL calls that we were previously using in `AzureRM`. We are working with the ADAL team to bring back the U/P scenario for CSP users as they have no way to create and use service principals for authentication; other users _could_ use U/P for authentication if it is brought back, but we _strongly_ advise using service principal authentication instead of U/P. Feel free to take a look at the issue previously linked as it has a ton of information surrounding this topic, has great discussions with other users, and tracks the status of U/P coming back in `Az` in time for GA on 2018-12-18.

Regarding your second request with the help content for our modules, the content that you are getting back from `Get-Help Connect-AzAccount -Full` is interesting; are you only seeing the parameter sets with, what looks to be, metadata before and after? When I run the same command in both PS 5.1 and PS Core with `Az.Profile` freshly installed, I see the expected help content that we have for `Az` commands: Name, syntax, parameters, inputs/outputs. While we currently are supporting the `AzureRM` module and the (preview) `Az` module, the reference documentation that's found on https://docs.microsoft.com/en-us/powershell/azure/ will be pointing at the `AzureRM` cmdlets, but once we GA the `Az` module on 2018-12-18, these reference docs will flip to the `Az` cmdlets, and the content you see when running `Get-Help` will be up-to-date, just like it currently is in `AzureRM`.

Please let me know if you have any questions or concerns about the comments made above.
