### ISSUE TITLE
0.9.7 ARM :: Rename -DatabaseName parameter to -Name on *SqlDatabase commands

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#819]
It's redundant to have `AzureSqlDatabase` as the command's noun, and also offer the `-DatabaseName` parameter. It should simply be `-Name`.

If you want to avoid breaking scripts:
1. Rename the parameter to `-Name`
2. Add a parameter alias for `-DatabaseName` to `-Name` parameter.

![image](https://cloud.githubusercontent.com/assets/466713/9583130/c8918244-4fc6-11e5-96be-15e63c04cb2d.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
@akromm thoughts on this one?

**Comment by akromm** [comment]
We use DatabaseName as the parameter name to help with piping the output of one command to the input of another command. We will take renaming and adding an alias into consideration.

**Comment by pcgeek86** [comment]
@akromm That should only break if you're doing pipelining by property name. I'd recommend doing pipelining without using property names `[Parameter(ValueFromPipeline = $true)]' so that you support pipelining by object type, not by property name.

This should be covered by the Azure PowerShell guidelines, per https://github.com/Azure/azure-powershell/issues/1557

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
@pcgeek86 @akromm Pipelining by value is, in general not appropriate for our scenario - we do not want to create assembly version dependencies between the output of one cmdlet and the input of another, especially when the cmdlets come from different assemblies.  In this case, using a property Alias as you suggest so that both the piping and direct cmdlet execution scenarios are supported without creating type dependencies is a better option.

**Comment by akromm** [comment]
#4110

**Comment by akromm** [comment]
resolved with #4110
