### ISSUE TITLE
can't login u/p with connect-azaccount

### ISSUE THREAD

**Issue by SRE93** [Azure/azure-powershell#8279]
Hey there, I tried different things to log into azureRM with the new Az Module, using Connect-AzAccount. Is it a bug or feature? ;)
Please assist:

`PS C:\> $cred = Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
PS C:\> Connect-AzAccount -Credential $cred

cmdlet Connect-AzAccount at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ServicePrincipal:

#didn't worked

PS C:\> Connect-AzAccount -Credential $cred -ServicePrincipal

cmdlet Connect-AzAccount at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Tenant:

#didn't worked

PS C:\> Connect-AzAccount -Credential $cred -ServicePrincipal -Tenant TENANTID
WARNING: The provided service principal secret will be included in the 'AzureRmContext.json' file found in the user
profile. Please ensure that this directory has appropriate protections.
Connect-AzAccount : AADSTS700016: Application with identifier 'USER' was not found in the directory
'TENANTID'. This can happen if the application has not been installed by the administrator
of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong
tenant
Trace ID: 8d88fb3f-be62-4ce1-a110-f798008d2200
Correlation ID: 2f0c1b7f-9ac2-4469-bb52-a44b506765d8
Timestamp: 2019-01-10 13:02:36Z
At line:1 char:1
+ Connect-AzAccount -Credential $cred -ServicePrincipal -Tenant 7b23ea3 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], AdalServiceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

#didn't worked

**Comment by SRE93** [comment]
already submitted here as well: https://github.com/Azure/azure-docs-powershell/issues/910

**Comment by cormacpayne** [comment]
@SRE93 Hey Sandro, U/P support is currently not available in the `Az` module, but we plan on supporting this scenario for Windows PowerShell 5.1 only in an upcoming release. We are currently tracking this work in the following issue: https://github.com/Azure/azure-powershell/issues/7430

Some notable comments from the above issue:
- [More information on why U/P is not currently supported](https://github.com/Azure/azure-powershell/issues/7430#issuecomment-426480499)
- [Brief information on CSP users](https://github.com/Azure/azure-powershell/issues/7430#issuecomment-438868338)
- [Adding this functionality for Windows PowerShell 5.1](https://github.com/Azure/azure-powershell/issues/7430#issuecomment-446726280)

I'm going to close this issue in favor of the one linked above since that is where we're currently tracking discussions and the status of the work for this functionality. Please let me know if this comment doesn't address your issue and I will be happy to re-open this issue for further discussion, and feel free to comment on the linked issue if there are additional comments you'd like to make on the subject outside of this issue.

**Comment by lakhviruppal** [comment]
I have same issue recently. Is there any fix available for it.

Thank you 
Lakhvir
