### ISSUE TITLE
How do I import a certificate from one KeyVault to another?

### ISSUE THREAD

**Issue by wisconsinsara** [Azure/azure-powershell#8468]
Is there a way to import a KeyVault certificate from another KeyVault? I prefer to use PowerShell.

**Comment by maddieclayton** [comment]
You should be able to backup the certificate using Backup-AzKeyVaultCertificate: https://docs.microsoft.com/en-us/powershell/module/az.keyvault/Backup-AzKeyVaultCertificate?view=azps-1.2.0, then restore the certificate to a different keyvault using Restore-AzKeyVaultCertificate: https://docs.microsoft.com/en-us/powershell/module/az.keyvault/restore-azkeyvaultcertificate?view=azps-1.2.0.  Please let me know if this does not work for you and I will reopen this issue.

**Comment by thecherrytree** [comment]
Does this work for PFX certificates? What happens if you run this command on an agent? Does it download to a local path on an agent? Right now, I am using the import-azkeyvaultcertificate with unexpected behavior when trying to use the certificate collection or certificate string parameters, so this seems like it might be a promising option. I've just opened this ticket given that I believe my issue might also be documentation related, but it could also be a bug:
https://github.com/Azure/azure-powershell/issues/9485
