### ISSUE TITLE
[Static Analysis] Misleading description in the BreakingChangeIssues.csv file.

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-powershell#8507]
### Description

The description in the [BreakingChangeIssues.csv](https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell/10672/artifact/artifacts/BreakingChangeIssues.csv/*view*/) file claims:
> The parameter set 'StorageAccountSubscriptionIdSet' for cmdlet 'Set-AzSqlDatabaseAuditing' has been removed

But in fact, the ['StorageAccountSubscriptionIdSet'](https://github.com/Azure/azure-powershell/pull/8489/files#diff-fd4316eef4e061fcd4989d162bced838L25) parameter set was not removed.

**Comment by cormacpayne** [comment]
@vladimir-shcherbakov because of all the variables that go into defining a parameter set (parameters, ordering, mandatory vs. optional, etc.), it is difficult to come up with a message that accurately depicts the changes of a parameter set in all cases. The message says the set has been removed, which isn't true in the sense that there still exists a parameter set called `StorageAccountSubscriptionIdSet`, but that doesn't necessarily mean that we are able to map that parameter set to any of the new parameter sets. In this case, the `-StorageAccountSubscriptionId` parameter within that parameter set was changed from optional to mandatory, so the breaking change tool is looking for a parameter set that meets all of the criteria given from the old set. In this case, users can find that the `DefaultParameterSet` and `StorageAccountSubscriptionIdSet` sets will cover any and all possible combinations of parameters that a user in the old `StorageAccountSubscriptionIdSet` would've used, but the breaking change tool isn't (currently) capable of seeing that these combinations can be covered by multiple sets, rather than just one, so it throws saying the set has been removed. I think a better message would say that the set has changed and cannot be mapped to a new set, and to take a look at the specific changes. In this case, since the changes are false-positives when it comes to the breaking change tool, we can have the user suppress the exception and get by these exceptions.
