### ISSUE TITLE
[Test Framework] Providing a KeyValuePair while recording and accessing it in playback

### ISSUE THREAD

**Issue by ankushbindlish2** [Azure/azure-powershell#8543]
### Description

We are unable to Record/Playback without keeping a cache of generated guids.

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by markcowl** [comment]
@ankushbindlish2 There are two options for this based on existing mechanisms in the test recorder:

(1) You can use HttpMockServer.GetAssetGuid(testname) this works similarly to GetAssetName().  In record mode it generates a new GUID and stores it in the recording in the order it was requested. In playback mode, it pops the next value from the stack and returns it as a GUID.   I think this should be sufficient for your scenario, as you can simply call this once for each guid value you need, and assign the results to your variables appropriately.  The downside is that anytime you changed the ordering of calls to this fucntion in your test, you would need to re-record.  This seems OK, as the only time you generally would do this is if you were editing the test and would re-record anyway.

(2) You can use HttpMockServer.GetVariable to save any arbitrary string key/Value pair in the test recording.  The call either ignores the value and returns the stored value (in playback mode) or stores and returns the provided value (in record mode).  This is slightly less elegant to use, but is robust over changes in the order fo calls that don't otherwise require a re-recording.
