### ISSUE TITLE
Make -Name parameter of Get-AzResource a positional parameter

### ISSUE THREAD

**Issue by aydeisen** [Azure/azure-powershell#8625]
## Description of the new feature
Is it possible to make the `Name` parameter in `Get-AzResource` a positional parameter?  I know it's such a minor thing, but when I'm working quickly, it's frustrating when the cmdlet fails just because I forgot to specify the parameter.

## Proposed implementation details (optional)
Make the `Name` parameter a positional parameter

**Comment by cormacpayne** [comment]
@aydeisen thanks for opening this feature request -- I can understand where the frustration is coming from (I've hit this issue a few times myself 😁), unfortunately, in PowerShell, it is an anti-pattern to have a positional parameter that is optional. In this specific case of `Get-AzResource`, we have a couple of things that could be the first positional parameter, such as `-Name`, `-ResourceGroupName`, `-ResourceId`, etc., so other users _could be_ expecting to provide those values, rather than for specifically the `-Name` parameter, when running `Get-AzResource "some_string"`. This kind of ambiguity is why we enforce that new cmdlets only have positional parameters that are mandatory. Please let me know if you have any other questions or concerns!
