### ISSUE TITLE
New-AzureRMResourceGroupDeployment: Parameters from parameter object AND parameter file

### ISSUE THREAD

**Issue by DianeHadley** [Azure/azure-powershell#8631]
As far as I can tell, parameters can only be defined by using -TemplateParameterFile OR -TemplateParameterObject (not both). I think it would be a helpful feature to be able to use both options. If this is not added as a feature, I think it would be helpful to add a more specific error message when a user tries to use both flags. The current error is just the generic "Parameter set cannot be resolved". The proposed error message would be something like "Cannot specify both a template parameter file and a template parameter object".

**Comment by cormacpayne** [comment]
@DianeHadley Hey Diane, thanks for filing this issue. It should be the case that the parameters are in sets that are mutually exclusive and that PowerShell will give a meaningful message if a user were to somehow provide both of those values together. Usually don't like to rely on custom error messages when it comes to providing parameters together, since PowerShell should handle that with properly designed parameter sets, so we'll take a look and make sure the cmdlets with these template parameters are better handled.

**Comment by cormacpayne** [comment]
@DianeHadley Hey Diane, I just double-checked, and it appears that the sets for this cmdlet (and other `*-AzResourceGroupDeployment` cmdlets) are modeled properly, and that the following exception when providing two of `-TemplateParameterFile`, `-TemplateParameterObject` and `-TemplateParameterUri` in the same command call is correct:

```
Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

In PowerShell, when working from the command line (rather than writing a script), having the parameter sets modeled in this way allow for a user to provide the value for one parameter, and when they tab through other parameters available to them, they won't be able to see any of the other values in separate sets (since PowerShell is able to scope down which set the user may be in). This is a little different when writing a script since the user doesn't necessarily get this piece of functionality, so the error seen above is the correct behavior from PowerShell to allow the user to ensure that the combinations of parameters they are providing are all available in a single parameter set (which they can check by referring to the cmdlet's documentation).

As for whether or not the above parameters should be provided together, I think the current behavior (with the parameters being in individual sets) provides a better experience for user as, I personally believe, allowing for multiple representations of the parameter (and template) to be provided in the same set can cause confusion, especially around how the values will be "merged together". I think that it's easier for users to put all of their information into one of the presented parameter forms rather than having to worry about how the different forms will interact with each together and merge together. If you have any additional ideas or insight around this topic, please feel free to post a response and we can discuss this some more (I think it would be a good idea to have this feature implemented, but I want to make sure that it's implemented in a fashion that isn't confusing to users).
