### ISSUE TITLE
Uninstall-AzureRM

### ISSUE THREAD

**Issue by Mitch-P97** [Azure/azure-powershell#8648]
Shouldn't it be Uninstall-Module AzureRM?  And requires elevated privileges.

**Comment by cormacpayne** [comment]
@Mitch-P97 Hey Mitch, the reason that you cannot run `Uninstall-Module -Name AzureRM` (or `Uninstall-Module -Name Az`) is due to the fact that these modules have dependencies (`RequiredModules`) on the individual service modules that we ship. From the documentation for [`Uninstall-Module`](https://docs.microsoft.com/en-us/powershell/module/powershellget/uninstall-module):

_You cannot uninstall a module if it has other modules as dependencies._

As a result, there was no simple way to uninstall every `AzureRM` module from the command line, so we introduced the `Uninstall-AzureRM` cmdlet to allow for an easy way to remove the `AzureRM` module and all of its dependencies.

Please let me know if you have any questions!
