### ISSUE TITLE
0.9.7 ARM :: New-AzureRedisCache -Size parameter design problem

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#868]
Since its inception, PowerShell has had special identifiers `KB`, `MB`, `GB`, et al. to make it easy for IT admins to do number calculations in their PowerShell scripts.

The `New-AzureRedisCache` command creates ambiguity, because the `-Size` parameter accepts values such as `250MB`, `2.5GB`, and so on, which conflict with the PowerShell identifiers.

![image](https://cloud.githubusercontent.com/assets/466713/9706275/07aed1b2-549e-11e5-85e9-c73c6dde912f.png)

This design should be corrected, to avoid conflicts with the built-in PowerShell identifiers.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by stankovski** [comment]
@SiddharthChatrolaMs please address

**Comment by SiddharthChatrolaMs** [comment]
Size of redis cache can be: C0, C1, C2, C3, C4, C5, C6, 250MB, 1GB, 2.5GB, 6GB, 13GB, 26GB, 53GB
What should we use instead of MB, GB?

**Comment by pcgeek86** [comment]
I'd suggest using something that doesn't conflict with PowerShell commands. For example:

250 MB, 1 GB

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by cormacpayne** [comment]
The cmdlet `New-AzureRedisCache` no longer exists, but `New-AzureRmRedisCache` does, and has the same sizes mentioned above in the validate set for the `Size` parameter. I am going to close this issue due to a lack of activity; @pcgeek86 please let me know if this should be re-opened and we will contact the corresponding team to take a look.
