### ISSUE TITLE
Cannot verify the Microsoft .NET Framework version 4.5.2 because it is not included in the list of permitted versions

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-powershell#8695]
## Description

I'm authoring a script that would programmatically connect to AzureRM using AccountId and AccessToken (of an AAD app), load necessary modules, and perform some ARM and KV operations. On this line:

```powershell
Import-Module AzureRM.KeyVault -Scope Local -Force -MinimumVersion 5.2.1 -Verbose
```

I'm getting this verbose message I try to decipher:

>VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureRM.KeyVault\5.2.1\AzureRM.KeyVault.psd1'.
**VERBOSE: Cannot verify the Microsoft .NET Framework version 4.5.2 because it is not included in the list of permitted versions.**

What does it mean?

**Comment by maddieclayton** [comment]
@abatishchev Please attempt a repro on Az and let us know if you continue to see this issue.

**Comment by abatishchev** [comment]
Will do!

**Comment by markcowl** [comment]
Closing for lack of comment.  Please reopen if you see this issue in Az

**Comment by mattduguid** [comment]
We too have just started seeing this error in the Azure pipelines for an "Azure Powershell" task "v3", we are not in a position yet to update our scripts to support az or change the task to "v4 (preview)", can we fix or suppress this for time being?

VERBOSE: Populating RepositorySourceLocation property for module AzureRM.KeyVault.
VERBOSE: Loading module from path 'C:\Modules\azurerm_6.***.0\AzureRM.KeyVault\5.1.1\AzureRM.KeyVault.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module AzureRM.KeyVault.
VERBOSE: Loading module from path 'C:\Program 
VERBOSE: Files\WindowsPowerShell\Modules\AzureRM.KeyVault\2.1.0\.\Microsoft.Azure.Commands.KeyVault.dll'.
VERBOSE: Loading module from path 'C:\Program 
Files\WindowsPowerShell\Modules\AzureRM.KeyVault\2.1.0\AzureRM.KeyVault.psm1'.
Rename secret '***-******' to '******' and copy from keyvault '***' to keyvault '***'
VERBOSE: Cannot verify the Microsoft .NET Framework v***ion 4.5.2 because it is not included in the list of permitted v***ions.

etc...
