### ISSUE TITLE
Az Module Crashes Powershell ISE

### ISSUE THREAD

**Issue by lukeuhren** [Azure/azure-powershell#8697]
Az Module causes Powershell to become unresponsive and crash.... I posted a question to it here https://social.technet.microsoft.com/Forums/windowsserver/en-US/f80d6936-06a5-4c2b-88e0-60979ae6a7cd/azure-az-powershell-module-crashes-powershellunresponsive?forum=winserverpowershell#f80d6936-06a5-4c2b-88e0-60979ae6a7cd as well with full details on issue. It appears others have the same issue. Could this be looked into and possibly fixed? That is if someone at Microsoft can replicate it.

**Comment by cormacpayne** [comment]
@joeyaiello Hey Joey, would you mind commenting on the above about VS Code usage?

**Comment by lukeuhren** [comment]
I'd say just close this off.... I'm just going to start using Visual Studio Code with Powershell extension and retire ISE from my work dev tools.

**Comment by superfliege** [comment]
Hello @cormacpayne 

Sorry for reopen the topic.

The Powershell ISE hangs constantly. This disturb our daily work.
I have already seen this incident by many colleagues of mine.

This happens in the following cases:
- Using the AzureRM module
- Using the Az module
- Especially when using the GUI Login from Connect-Az or Connect-AzureRm

If these things are not used, other scripts will run perfectly. The ISE does not freeze.

I think it's a shame not every colleague wants to work with visual code. Visual code is also slightly overloaded for system administrations. (In my view).

Is the Powershell ISE no longer supported from Microsoft?

Is there a workaround or can I hope for an improvement here?

Otherwise, we will probably all have to switch to Visual Code. 
I hope for an clear statement, so our team can plan the to improve the daily work.

Thanks for your work and your answer.

**Comment by mattpurnell** [comment]
Definitely makes ISE unworkable with Azure..!
