### ISSUE TITLE
Authentication Loop while trying to connect to AzAccount module

### ISSUE THREAD

**Issue by v-gonzaron** [Azure/azure-powershell#8701]
[ps-debug.txt](https://github.com/Azure/azure-powershell/files/2933525/ps-debug.txt)

### Description
I've remove my PowerShell AzureRM module and upgraged & installed the Azure Az Module.

There are 2 TWO issues:
1: when issing a Connect-AzAccount command I'm getting prompted with the username and password dialog instead of the device login diaglog

2: when I attempt to use my crednetials that are used against the subscript I get in an endless loop of 'your account as been locked' when my account credientals are both correct and my account is not locked. Again, my account credentials are correct and my account is _not_ locked.

## Steps to reproduce

```powershell
*Open PS as Admin

*Run command   connect-AzAccount

*Credentials pop up shows

*give the user Credentials

*Enter User password

*he gets prompt he had been sent a txt code to his email 

*he gets the code & enters the code to the pop up.

*The following error shows after entering the code
```

## Environment data

```
Attached File
```

## Module versions

```powershell

```Attached file

## Debug output

<!-- Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block -->

```
Attached File
```

## Error output

![asking for mfa](https://user-images.githubusercontent.com/48263530/53843871-79daa900-3f69-11e9-9e20-92becd7535df.JPG)

<!-- Please run Resolve-AzureRmError and paste the output in the below code block -->

```

```
[ps-debug.txt](https://github.com/Azure/azure-powershell/files/2933529/ps-debug.txt)

**Comment by cormacpayne** [comment]
@v-gonzaron 

(1) If you would like to skip the interactive login and use device code flow, you can provide the `-UseDeviceAuthentication` parameter to enable this login behavior

(2) The dialog prompt that you're seeing is determined by your STS, so you will need to contact your AD domain administrator as this message is coming from their end rather than Azure.

**Comment by v-gonzaron** [comment]
He has the Device authentication enabled, and he actually gets the authentication SMS.
However, after he inputs that txt the authentication loops and never logs in.

Does the parameter you provided me Enable that feature? or disables it?

**Comment by cormacpayne** [comment]
If you're using Windows PowerShell (PowerShell 5.1) and run `Connect-AzAccount` and are prompted to provide credentials in a window that pops up, you can run `Connect-AzAccount -UseDeviceAuthentication` to use device code flow to authenticate. Providing this additional parameter will notify the user of the code they must use in `https://microsoft.com/devicelogin` to authenticate.

**Comment by v-gonzaron** [comment]
In this case the user is NOT using the -usedeviceauthentication parameter. However the Code for auth is still getting to his phone. Then He gets the error shown on the screenshot, and loops into an auth failure untill completely errors out.

So, we checked all over Azure AD, and no MFA is been implemented or enabled. There is no MFA enforcement at all coming from Azure AD, so it has to be from somewhere else, but we do not know where it comes from.

**Comment by markcowl** [comment]
The dialog you are displaying, and processing it are determined by your local STS (thus the log for your domain that appears in the dialg - it is actually a browser window on a dialog presented by your STS.

It is most likely that the issue is with this dialog, or an incompatibility between your default browser settings and this dialog.  Your domain Administrator is the one who should eb able to help you with this login issue.

In the interim, following the -UseDeviceAuthenticationCode pathway allows you to choose a browser and follows a different authentication path that may help you work around this until the problem with the STS-presented login dialog is fixed.

**Comment by v-gonzaron** [comment]
The parameter -UseDeviceAuthenticationCode   has solved the login problem.
However, now the customer is asking where can he find the STS at the On premise, since he does not seem to have activated anything.

where can I get to know if the STS is active or any logs to obtain data?

**Comment by markcowl** [comment]
@v-gonzaron The latest version os Az has some additional traces which may help AD folks to pinpoint the STS issue.

Turning on $DebugPreference=”Continue” before logging in will print out all the traces from the AD authentication library, which should show communication with the STS.  Once we have this, AD folks ought to be able to help with diagnosing the STS issue.

**Comment by ZachEdwards7** [comment]
> @v-gonzaron The latest version os Az has some additional traces which may help AD folks to pinpoint the STS issue.
> 
> Turning on $DebugPreference=”Continue” before logging in will print out all the traces from the AD authentication library, which should show communication with the STS. Once we have this, AD folks ought to be able to help with diagnosing the STS issue.

@markcowl this happens when the user is member of multiple tenants and the user object is disabled in one of those tenants... please reference IcM #165458224 for a better understanding

**Comment by bradcstevens** [comment]
> > @v-gonzaron The latest version os Az has some additional traces which may help AD folks to pinpoint the STS issue.
> > Turning on $DebugPreference=”Continue” before logging in will print out all the traces from the AD authentication library, which should show communication with the STS. Once we have this, AD folks ought to be able to help with diagnosing the STS issue.
> 
> @markcowl this happens when the user is member of multiple tenants and the user object is disabled in one of those tenants... please reference IcM #165458224 for a better understanding

Is there any way to force the removal of the user object that is disabled in one of those tenants? I am currently dealing with the login loop mentioned here due to my user object being disabled in a customer tenant. It's completely blocking my ability to login with my credentials via Az PowerShell even for purposes unrelated to the tenant my object is disabled in....
