### ISSUE TITLE
Service Bus Module - Get-AzServiceBusNamespace without Resource Group parameter

### ISSUE THREAD

**Issue by droessmj** [Azure/azure-powershell#9131]
## Description of the new feature
Get-AzServiceBusNamespace by -Name or -Namespace name only.

## Proposed implementation details (optional)
Holistic fix, update ServiceBusManagementClient to support said operation and port to Az Powershell. Hacky fix, do a list Service Bus resources and return the resource by name. 

## Use Case 
[Service Bus Namespaces are unique across Azure](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-create-namespace-portal)

> To begin using Service Bus messaging entities in Azure, you must first create a namespace with a name that is unique across Azure. A namespace provides a scoping container for addressing Service Bus resources within your application.>

If they are unique, why can they not be retrieved by Name only similarly to Key Vaults and Storage Accounts?

**Comment by niander** [comment]
@MiYanni Hey, do you know if such capability is going to be available in the generated cmdlets?

**Comment by MiYanni** [comment]
@droessmj This is because the ServiceBus API doesn't expose that type of REST call. The best you can do is list *all* the namespaces for a given subscription, and filter it (`Where-Object`) afterwards. So, that should work currently for you. While this is a valid use case, if the ServiceBus service itself doesn't expose this functionality, there's nothing we can do from the PowerShell side of things. You can [see a preview](https://github.com/Azure/azure-powershell/blob/generation/src/ServiceBus/docs/latest-2019-04-30/Get-AzServiceBusNamespace.md#syntax) of what the syntax is for the upcoming generated cmdlet.

@v-Ajnava @sazeesha @dsouzaarun Any additional comments on this?

**Comment by droessmj** [comment]
thanks for the follow up, @MiYanni. I ended up with exactly what you're saying above (i.e. `Where-Object`) in my scripts. I started to write the "missing" functionality myself, and ran into the API limitation also. I left this open to see if I had missed anything, but at this point it's more or less confirmed working to current spec. Thanks for your time.

**Comment by MiYanni** [comment]
@droessmj If you have any other suggestions like this, we can always consider adding them into the new generated cmdlets. These cmdlets will be more consistent with all services and expose anything available in the APIs for those services. But, we do have the ability to add custom cmdlets/functionality, so suggestions would be awesome. Thanks!
