### ISSUE TITLE
[Redis Cache] rdb-storage-connection-string should be a securestring

### ISSUE THREAD

**Issue by twoqubits** [Azure/azure-powershell#9217]
Currently, the **_rdb-storage-connection-string_** property of redisConfiguration is a clear-text string.  A securestring should be used to avoid compromise of the storage account key.

https://docs.microsoft.com/en-us/powershell/module/az.rediscache/set-azrediscache?view=azps-2.0.0
https://github.com/Azure/azure-quickstart-templates/tree/master/201-redis-premium-persistence

**Comment by MiYanni** [comment]
@SiddharthChatrolaMs Can you determine if using a SecureString makes sense for this configuration property since it includes secret information?

**Comment by SiddharthChatrolaMs** [comment]
@MiYanni You mean take it out of the dictionary and make it an object of type secure string? can we make it secure string inside configuration dictionary? Do we need a service/api change to achieve this?

**Comment by MiYanni** [comment]
@SiddharthChatrolaMs Hashtable is a `IDictionary<string, object>`, so it is just a collection of anything. What @twoqubits is suggesting is that `rdb-storage-connection-string` is provided as type `SecureString`. Then, in your cmdlet code, you convert the SecureString to a string to send it to your service. We have [extension methods for SecureString](https://github.com/Azure/azure-powershell-common/blob/master/src/Common/Extensions/SecureStringExtensions.cs). I was asking you if this is appropriate, since your service just takes un-encryption connection strings anyway. So, making it a SecureString doesn't actually add any security.

**Comment by SiddharthChatrolaMs** [comment]
Just making it Secure String in CMDLET and then converting underneath doesn't add any value or security. ARM should be sending payload as encrypted so we should be fine.

**Comment by SiddharthChatrolaMs** [comment]
Connection from local machine to ARM should be on HTTPS so that is encrypted as well

**Comment by MECHANDR** [comment]
@MiYanni Can we close this issue? Based on the previous responses converting connection string to be a securestring isnt helping, and connection from local machine to ARM is HTTPS only.

**Comment by MiYanni** [comment]
@MECHANDR I'm no longer on the Azure PowerShell team. It is up to the Redis Cache team to decide if they want to close the issue as they own their cmdlets.
