### ISSUE TITLE
[Question] Granting access to our own REST APIs for ARM/Az module

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-powershell#9235]
## Description of the new feature

Hello colleagues, we have a few REST-based APIs which use AAD for auth. These APIs are a part of some internal automation process. On the other hand we also use ARM module, and Az module in future, to manage and automate azure components. In order to call both in the same script we need to login twice, first time to Azure through AAD for ARM/Az module and second time to Azure through AAD, most of the time with the same creds, to call our APIs. 

The question here is, how can we:

1. Grant access to ARM/Az module to call our APIs, so we dont need to login twice
2. Extract cached tokens from ARM/Az module to reuse them for our API calls. As i know it is possible to do with ARM module, but seems like tis approach does not work for Az. At least it did not work in azure shell

Thanks

**Comment by MiYanni** [comment]
@eosfor It is insecure to provide the token directly. We would like to provide functionality to reuse our access. However, we do not see implementing this in the short term. We were going to expose this via `Invoke-AzRestMethod`. You can see the issue for that here: https://github.com/Azure/azure-powershell/issues/3806

**Comment by eosfor** [comment]
hello @MiYanni ,

Thanks for your comment. That is great, and i'm looking forward to see it in action. However, the question is about something opposite. What if i need to grant access to my in-house APIs for Az/ARM module?

**Comment by MiYanni** [comment]
@eosfor This will be significantly easier to achieve in our upcoming AutoRest generated cmdlets. That design allows you to do what you want with the HTTP pipeline. If you wanted to do this currently, I believe you'd have to implement (by hand) your own SDK client. In the generated cmdlets, there is no dependence on the SDK clients at all, so that work would be throwaway. Currently, services would on-board into our REST API specs pipeline, and get an SDK generated that would work with our current cmdlets.
