### ISSUE TITLE
Document permissions required for New-AzADApplication?

### ISSUE THREAD

**Issue by jeking3** [Azure/azure-powershell#9266]
## Description of the new feature

There are multiple permissions required to allow a Service Principal (application) the ability to create and manage other applications.  There is no documentation on New-AzADApplication that would explain what permissions are required, and I haven't been able to figure them out yet.

The best information source I found so far is https://github.com/Azure/azure-powershell/issues/3215 and even that seems incomplete.

**Comment by markcowl** [comment]
The permissions required of users to create an application are described here:
https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles

The permissions of Service Principals are described here:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-permissions-and-consent

Usually you need to be in the administraotr role to assign permissions in AD Graph to other users and principals.

For service principals used in authentication automation, you want 'application permissions', not 'delegated permissions'.  Generally you need to be able to read, write, and list users in order to manipulate AD objects.

For most purposes in ARM, you care only about RBAC role assignments,

@dcaro I think we should take a look at the existing documentatoion - it should be *obvious* how to set up a service principal, instead it takes some documentation hunting and guesswork

**Comment by jeking3** [comment]
I'm still confused between what a Service Principal and an Application is... but anyway, the following permissions allowed me to execute the API call when authenticating as an administrative application that I set up, and now I can create other applications:

![image](https://user-images.githubusercontent.com/11771245/58123143-32170580-7bd9-11e9-9113-4e0f8b44245a.png)

Sorry the image is a bit larger here because I have a 3840px screen resolution.

**Comment by dcaro** [comment]
@jeking3 does this article helps your understanding of Applications and Service Principals? 
https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals

**Comment by jeking3** [comment]
Based on that information and what I see in the Azure portal, it looks like an Azure Active Directory App Registration is both an Application and a Service Principal, since the App Registration has both an Application ID and a Tenant ID, and the Tenant ID would only be associated with the application through a Service Principal.  Correct?

**Comment by MiYanni** [comment]
@jeking3 Yes, that is correct.

**Comment by jeking3** [comment]
@MiYanni not sure why you closed this, since the issue in the title of the issue is still outstanding.
