### ISSUE TITLE
Add support to install cert to particular service fabric node type

### ISSUE THREAD

**Issue by lovelangy** [Azure/azure-powershell#9520]
in Service Fabric, we use [Add-AzServiceFabricApplicationCertificate](https://docs.microsoft.com/en-us/powershell/module/az.servicefabric/Add-azServiceFabricApplicationCertificate?view=azps-2.3.2) to install cert to cluster

> Use Add-AzServiceFabricApplicationCertificate to install a certificate to **all nodes** in the cluster. You can specify a certificate you already have or have the system generate a new one for you, and upload it to a new or existing Azure key vault.

However, it installs to all the node type.  

In production, we normally have front end node type/ and backend node type.   we only want to install SSL cert to front end node. 

Can you please add a new parameter  '[-NodeType<String>]' to this command?

**Comment by cormacpayne** [comment]
@juhacket Hey Justin, would you mind taking a look at this issue?

**Comment by a-santamaria** [comment]
@lovelangy, we are going to deprecate this cmdlet as it's misleading since it doesn't make any changes in the cluster side, it only adds the cert to all vmss and compute already has support for this. Please use [Add-AzVmssSecret](https://docs.microsoft.com/en-us/powershell/module/az.compute/add-azvmsssecret?view=azps-2.4.0)
