### ISSUE TITLE
Right procedure to perform updates?

### ISSUE THREAD

**Issue by Lumute** [Azure/azure-powershell#9666]
Every release being published [link](https://github.com/Azure/azure-powershell/releases) says the way to upgrade is to run "Update-Module -Name Az"

The official installation document [link](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps#update-the-azure-powershell-module) says that using Update-Module will not do it correctly and instead you need to do a forced re-install but this may leave old versions installed...

Which one is right? what is the correct way to update? Did you guys fix the Update-Module mechanism to work properly?

**Comment by markcowl** [comment]
@Lumute We don't own `Update-Module`, that is the PowerShell Team.  The repo for the PowerShellGte moduel is here: https://github.com/PowerShell/PowerShellGet

Update-Module in fact updates the module correctly, but does not have any optiosn for removing olde rversions.  If you want to remove older versions, then removing and re-installign is a better option.

It is currently planned to have a set of cmdlets to manage your Azure PowerShell so that you could properly update and remove old versions.  If there was an update / auto-update mechanism, would you use it?

**Comment by Lumute** [comment]
Thanks Mark, so if I understand correctly both of the methods suggested (Update-Module or Install-Module with -Force) will install the new version correctly but may leave older versions installed? 

And the solution if you want to make sure older versions are removed is to first Uninstall the older version using the Uninstall-AllModules script from the gallery and then install the new version?

Yes, an update / auto-update mechanism would be really useful and would definitely use it.

**Comment by markcowl** [comment]
@Lumute Yes, that or a similar script.  For interactive use, actually opening the directory and deleting the module folders is the fastest and best option.

**Comment by markcowl** [comment]
#8595 is the current issue that tracks the new capability.  Closing thsi and linking it to the new feature issue.
