### ISSUE TITLE
Untrusted repository  You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet.  Are you sure you want to install the modules from 'PSGallery'? [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"):

### ISSUE THREAD

**Issue by willyam3469** [Azure/azure-powershell#9687]
## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by cormacpayne** [comment]
@willyam3469 Hey there, I'm going to assume that this issue is about the prompt that is popped when installing a module from the PowerShell Gallery -- the PowerShell Gallery is set as an "untrusted repository" by default to prevent users from installing _any_ module or script from this open gallery without first verifying that they are sure they want to install the given module or script; this applies even for Microsoft-developed modules, such as `Az`. To bypass this prompt _in the cases that you're confident the module or script you're installing is safe_, you can provide the `-Force` parameter:

```powershell
Install-Module -Name Az -Repository PSGallery -Force
```

You can also set the `PSGallery` repository to "trusted" to avoid this prompt altogether, but it's advised to keep the repository as it is.

**Comment by cveld** [comment]
It would be great that you could trust publishers. I.e. I don't want to trust all packages from PSGallery but only those from Microsoft by default.

**Comment by dayadam** [comment]
Why aren't all packages trusted? Isn't this a basic Microsoft module? https://learn.microsoft.com/en-us/powershell/module/?view=azps-10.1.0

**Comment by cormacpayne** [comment]
@dayadam @cveld Hey folks, I've been off the Azure PowerShell team for a few years now, but my understanding is that for features related to installing modules, you'd want to file an issue against the [`PowerShellGet` module](https://github.com/PowerShell/PSResourceGet) (which houses the `Install-Module` cmdlet). I just took a quick look and couldn't find any issues relating to "trust X author" in the repository, so it may be something that's worth filing an issue for and seeing what kind of traction you receive.

**Comment by Bruno-Lazarini** [comment]
Hey everyone, Im trying to understand too. It is strange that Microsoft Learning suggests installing even tho it have some security issues. I am going to ask some Microsoft consultant to know if we're safe and then I bring it here for you.
I suggest you to do the same.

Regards

**Comment by lll000111** [comment]
Why is this closed, nothing has changed.
I too just got very confused why Microsoft recommends I install something from an "untrusted repository".

**Comment by jvmap** [comment]
> Why is this closed, nothing has changed. I too just got very confused why Microsoft recommends I install something from an "untrusted repository".

I agree, this is terrible security design. "Untrusted repository" should not be an expected warning when installing an official package from an official repository. You basically force/train everyone to ignore this warning, because even the official modules are expected to be untrusted, "this is fine". The supply chain is wide open to attack by design.

This issue should never have been closed. Users need a way to distinguish between trusted and untrusted publishers.
