### ISSUE TITLE
Generation for Azure BlockChain Service

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9884]
## Description

Generate and customize modules for the Azure BlockChain service

- [x] Generate, build, and examine API surface
- [x] Ensure that all POST operations use only expanded variants
- [x] Ensure that New/Set/Update cmdlets use only expanded variants
- [x] Change Cmdlet, Parameter, and property names for consistency and clarity
- [ ] Write CRUD tests for top-level resources
- [x] Hold a cmdlet design review using the updated generated help files
- [x] Implement requested configurations and customizatiosn from review
- [ ] Add to Az preview release

**Comment by dolauli** [comment]
@markcowl @erich-wang 
The first four items are covered in PR #9909. And customization for new cmdlets are not covered yet since the business logic is not quite clear.
BTW, There is one question that is related to the parameter SubscriptionId, which is required in the restful API call, but probably should be optional in azure-powershell (Default "SubscriptionId" could be retrieved from the context after login.).

**Comment by dolauli** [comment]
The zip file attached contains the blockchain help files for review. 
[latest-2019-04-30-blockchain-helpfiles-for-review.zip](https://github.com/Azure/azure-powershell/files/3554144/latest-2019-04-30-blockchain-helpfiles-for-review.zip)

**Comment by dolauli** [comment]
@cormacpayne

**Comment by dolauli** [comment]
Suggest moving the issue to next sprint since the PR is still in review.
